Repository DevExpress/devextreme-demos, pull requests merged in 2020-12, with the labels that each got.

#427 Fix linter for local run
  .eslintignore
  utils/interactive/repos-helper.js
Labels: 20_2

#428 Fix linter for local run
  .eslintignore
  utils/interactive/repos-helper.js
Labels: 21_1, cherry-pick

#431 add-demo now updates Modules section if files copied from existing demo (#422)
  utils/interactive/add-demo.js
  utils/interactive/menu-meta-utils.js
Labels: 20_2, cherry-pick

#412 Fix mvc/netcore scripts
  package.json
  utils/internal/prepare-mvc.js
  utils/internal/prepare-netcore.js
  utils/shared/fs-utils.js
Labels: 20_2

#437 DataGrid - add jsZip library to old cellCustomization export demo
  JSDemos/Demos/DataGrid/ExcelCellCustomization/AngularJS/index.html
  JSDemos/Demos/DataGrid/ExcelCellCustomization/Knockout/index.html
  JSDemos/Demos/DataGrid/ExcelCellCustomization/jQuery/index.html
Labels: 21_1

#438 DataGrid - add jsZip library to old cellCustomization export demo
  JSDemos/Demos/DataGrid/ExcelCellCustomization/AngularJS/index.html
  JSDemos/Demos/DataGrid/ExcelCellCustomization/Knockout/index.html
  JSDemos/Demos/DataGrid/ExcelCellCustomization/jQuery/index.html
Labels: 20_2, cherry-pick

#436 Fix mvc/netcore scripts
  package.json
  utils/internal/prepare-mvc.js
  utils/internal/prepare-netcore.js
  utils/shared/fs-utils.js
Labels: 21_1, cherry-pick

#439 Fix comment
  utils/shared/fs-utils.js
Labels: 20_2

#441 DevExtreme.AspNet.Data update utility
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Web.config
  MVCDemos/packages.config
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  package.json
  utils/internal/update-aspnet-data.js
Labels: 20_2

#432 Using "instance" instead of "data" to get the instance of a widget (cherry pick #381)
  JSDemos/Demos/NumberBox/Overview/jQuery/index.js
  JSDemos/Demos/TextBox/Overview/jQuery/index.js
  MVCDemos/Views/DataGrid/MultipleRecordSelectionAPI.cshtml
  NetCoreDemos/Views/DataGrid/MultipleRecordSelectionAPI.cshtml
Labels: 21_1, cherry-pick

#442 Add unit tests
  .github/workflows/unit_tests.yml
  jest.config.js
  package.json
  tests/shared/fs-utils.test.js
Labels: 21_1

#443 Add unit tests
  .github/workflows/unit_tests.yml
  jest.config.js
  package.json
  tests/shared/fs-utils.test.js
Labels: 20_2, cherry-pick

#448 File Management - Update description links to the azure-file-system.js file
  JSDemos/Demos/FileManager/AzureClientBinding/description.md
  JSDemos/Demos/FileUploader/AzureDirectUploading/description.md
  NetCoreDemos/wwwroot/Descr/FileManager/AzureClientBinding.md
Labels: 20_2, cherry-pick

#447 File Management - Update description links to the azure-file-system.js file
  JSDemos/Demos/FileManager/AzureClientBinding/description.md
  JSDemos/Demos/FileUploader/AzureDirectUploading/description.md
  NetCoreDemos/wwwroot/Descr/FileManager/AzureClientBinding.md
Labels: 21_1

#450 strips demo. Apply suggestions after review
  JSDemos/Demos/Charts/Strips/Angular/app/app.component.html
  JSDemos/Demos/Charts/Strips/Angular/app/app.component.ts
  JSDemos/Demos/Charts/Strips/Vue/App.vue
Labels: 20_2

#451 strips demo. Apply suggestions after review
  JSDemos/Demos/Charts/Strips/Angular/app/app.component.html
  JSDemos/Demos/Charts/Strips/Angular/app/app.component.ts
  JSDemos/Demos/Charts/Strips/Vue/App.vue
Labels: 21_1, cherry-pick

#456 Fix localization in configs for react/vue approaches
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.js
Labels: 21_1

#457 Fix localization in configs for react/vue approaches
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.js
Labels: 20_2, cherry-pick

#462 DataGrid/FilterBuilder: Remove Globalize from demos
  JSDemos/Demos/DataGrid/CellCustomization/AngularJS/index.html
  JSDemos/Demos/DataGrid/CellCustomization/AngularJS/index.js
  JSDemos/Demos/DataGrid/CellCustomization/Knockout/index.html
  JSDemos/Demos/DataGrid/CellCustomization/Knockout/index.js
  JSDemos/Demos/DataGrid/CellCustomization/React/DiffCell.js
  JSDemos/Demos/DataGrid/CellCustomization/Vue/DiffCell.vue
  JSDemos/Demos/DataGrid/CellCustomization/jQuery/index.html
  JSDemos/Demos/DataGrid/CellCustomization/jQuery/index.js
  JSDemos/Demos/DataGrid/GridSummaries/AngularJS/index.html
  JSDemos/Demos/DataGrid/GridSummaries/AngularJS/index.js
  JSDemos/Demos/DataGrid/GridSummaries/Knockout/index.html
  JSDemos/Demos/DataGrid/GridSummaries/Knockout/index.js
  JSDemos/Demos/DataGrid/GridSummaries/React/App.js
  JSDemos/Demos/DataGrid/GridSummaries/Vue/App.vue
  JSDemos/Demos/DataGrid/GridSummaries/jQuery/index.html
  JSDemos/Demos/DataGrid/GridSummaries/jQuery/index.js
  JSDemos/Demos/DataGrid/Overview/AngularJS/index.html
  JSDemos/Demos/DataGrid/Overview/jQuery/index.html
  JSDemos/Demos/DataGrid/Row3RdPartyEngineTemplate/jQuery/index.html
  JSDemos/Demos/DataGrid/RowTemplate/AngularJS/index.html
  JSDemos/Demos/DataGrid/RowTemplate/Knockout/index.html
  JSDemos/Demos/DataGrid/RowTemplate/Knockout/index.js
  JSDemos/Demos/DataGrid/RowTemplate/jQuery/index.html
  JSDemos/Demos/FilterBuilder/Customization/jQuery/index.html
  JSDemos/Demos/FilterBuilder/WithList/jQuery/index.html
  JSDemos/Demos/FilterBuilder/WithList/jQuery/index.js
Labels: 20_2, cherry-pick

#461 DataGrid/FilterBuilder: Remove Globalize from demos
  JSDemos/Demos/DataGrid/CellCustomization/AngularJS/index.html
  JSDemos/Demos/DataGrid/CellCustomization/AngularJS/index.js
  JSDemos/Demos/DataGrid/CellCustomization/Knockout/index.html
  JSDemos/Demos/DataGrid/CellCustomization/Knockout/index.js
  JSDemos/Demos/DataGrid/CellCustomization/React/DiffCell.js
  JSDemos/Demos/DataGrid/CellCustomization/Vue/DiffCell.vue
  JSDemos/Demos/DataGrid/CellCustomization/jQuery/index.html
  JSDemos/Demos/DataGrid/CellCustomization/jQuery/index.js
  JSDemos/Demos/DataGrid/GridSummaries/AngularJS/index.html
  JSDemos/Demos/DataGrid/GridSummaries/AngularJS/index.js
  JSDemos/Demos/DataGrid/GridSummaries/Knockout/index.html
  JSDemos/Demos/DataGrid/GridSummaries/Knockout/index.js
  JSDemos/Demos/DataGrid/GridSummaries/React/App.js
  JSDemos/Demos/DataGrid/GridSummaries/Vue/App.vue
  JSDemos/Demos/DataGrid/GridSummaries/jQuery/index.html
  JSDemos/Demos/DataGrid/GridSummaries/jQuery/index.js
  JSDemos/Demos/DataGrid/Overview/AngularJS/index.html
  JSDemos/Demos/DataGrid/Overview/jQuery/index.html
  JSDemos/Demos/DataGrid/Row3RdPartyEngineTemplate/jQuery/index.html
  JSDemos/Demos/DataGrid/RowTemplate/AngularJS/index.html
  JSDemos/Demos/DataGrid/RowTemplate/Knockout/index.html
  JSDemos/Demos/DataGrid/RowTemplate/Knockout/index.js
  JSDemos/Demos/DataGrid/RowTemplate/jQuery/index.html
  JSDemos/Demos/FilterBuilder/Customization/jQuery/index.html
  JSDemos/Demos/FilterBuilder/WithList/jQuery/index.html
  JSDemos/Demos/FilterBuilder/WithList/jQuery/index.js
Labels: 21_1

#473 dxScheduler - add specific FF css rule for CellTemplates demo
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/CellTemplates/React/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/Vue/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Scheduler/CellTemplates.css
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/CellTemplates.css
Labels: 20_2

#474 dxScheduler - add specific FF css rule for CellTemplates demo
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/CellTemplates/React/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/Vue/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Scheduler/CellTemplates.css
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/CellTemplates.css
Labels: 21_1, cherry-pick

#476 Cherry Pick 21_1: Refactor master-detail demos ( #475)
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/detail-view.component.css
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/detail-view.component.html
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/detail-view.component.ts
  JSDemos/Demos/DataGrid/MasterDetailAPI/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/MasterDetailView/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/MasterDetailView/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/MasterDetailView/Angular/app/detail-grid.component.css
  JSDemos/Demos/DataGrid/MasterDetailView/Angular/app/detail-grid.component.html
  JSDemos/Demos/DataGrid/MasterDetailView/Angular/app/detail-grid.component.ts
  JSDemos/Demos/DataGrid/WebAPIService/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/WebAPIService/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/WebAPIService/Angular/app/detail-grid.component.css
  JSDemos/Demos/DataGrid/WebAPIService/Angular/app/detail-grid.component.html
  JSDemos/Demos/DataGrid/WebAPIService/Angular/app/detail-grid.component.ts
Labels: 21_1, cherry-pick

#477 Fix screenshot testing
  JSDemos/Demos/DataGrid/MasterDetailAPI/Angular/app/app.component.html
Labels: 21_1

#478 CP: Master-Detail API - Fix screenshot testing (#477)
  JSDemos/Demos/DataGrid/MasterDetailAPI/Angular/app/app.component.html
Labels: 20_2, cherry-pick

#481 SelectBox - Search and editing demo
  JSDemos/Demos/SelectBox/SearchAndEditing/Angular/app/app.component.html
  JSDemos/Demos/SelectBox/SearchAndEditing/Angular/app/app.component.ts
  JSDemos/Demos/SelectBox/SearchAndEditing/AngularJS/index.js
  JSDemos/Demos/SelectBox/SearchAndEditing/React/App.js
  JSDemos/Demos/SelectBox/SearchAndEditing/Vue/App.vue
  JSDemos/Demos/SelectBox/SearchAndEditing/jQuery/index.js
Labels: 20_2

#486 Improve the SelectBox - Search and editing demo in JS frameworks (#481)
  JSDemos/Demos/SelectBox/SearchAndEditing/Angular/app/app.component.html
  JSDemos/Demos/SelectBox/SearchAndEditing/Angular/app/app.component.ts
  JSDemos/Demos/SelectBox/SearchAndEditing/AngularJS/index.js
  JSDemos/Demos/SelectBox/SearchAndEditing/React/App.js
  JSDemos/Demos/SelectBox/SearchAndEditing/Vue/App.vue
  JSDemos/Demos/SelectBox/SearchAndEditing/jQuery/index.js
Labels: 21_1, cherry-pick

#483 dxScheduler - update recurrence exception in recurrence demo and use form.updateDate in demo
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/ContextMenuIntegration/AngularJS/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/jQuery/data.js
  JSDemos/Demos/Scheduler/CustomTemplates/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/CustomTemplates/AngularJS/index.js
  JSDemos/Demos/Scheduler/CustomTemplates/React/App.js
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/App.vue
  JSDemos/Demos/Scheduler/CustomTemplates/jQuery/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/RecurringAppointments/AngularJS/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Knockout/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/React/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Vue/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/jQuery/data.js
  MVCDemos/Models/SampleData/RecurringAppointments.cs
  MVCDemos/Views/Scheduler/CustomTemplates.cshtml
  NetCoreDemos/Models/SampleData/RecurringAppointments.cs
  NetCoreDemos/Views/Scheduler/CustomTemplates.cshtml
Labels: 21_1, cherry-pick

#482 dxScheduler - update recurrence exception in recurrence demo and use form.updateDate in demo
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/ContextMenuIntegration/AngularJS/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/jQuery/data.js
  JSDemos/Demos/Scheduler/CustomTemplates/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/CustomTemplates/AngularJS/index.js
  JSDemos/Demos/Scheduler/CustomTemplates/React/App.js
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/App.vue
  JSDemos/Demos/Scheduler/CustomTemplates/jQuery/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/RecurringAppointments/AngularJS/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Knockout/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/React/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Vue/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/jQuery/data.js
  MVCDemos/Models/SampleData/RecurringAppointments.cs
  MVCDemos/Views/Scheduler/CustomTemplates.cshtml
  NetCoreDemos/Models/SampleData/RecurringAppointments.cs
  NetCoreDemos/Views/Scheduler/CustomTemplates.cshtml
Labels: 20_2

#490 Add tests for fs-util module (#469)
  jest.config.js
  package.json
  tests/shared/fs-utils.test.js
  utils/shared/fs-utils.js
  utils/tests/.eslintrc.js
  utils/tests/shared/fs-utils.test.js
Labels: 20_2, cherry-pick

#494 Fix versions
  package.json
Labels: 21_1

#489 SelectBox - Add valueExpr in the Search and editing demos
  JSDemos/Demos/SelectBox/SearchAndEditing/Angular/app/app.component.html
  JSDemos/Demos/SelectBox/SearchAndEditing/jQuery/index.js
  MVCDemos/Views/SelectBox/SearchAndEditing.cshtml
  NetCoreDemos/Views/SelectBox/SearchAndEditing.cshtml
Labels: 20_2

#495 SelectBox - Add valueExpr in the Search and editing demos (#489)
  JSDemos/Demos/SelectBox/SearchAndEditing/Angular/app/app.component.html
  JSDemos/Demos/SelectBox/SearchAndEditing/jQuery/index.js
  MVCDemos/Views/SelectBox/SearchAndEditing.cshtml
  NetCoreDemos/Views/SelectBox/SearchAndEditing.cshtml
Labels: 21_1, cherry-pick

#497 DataGrid - Fix Batch Update Request demo in ASP.NET Core approach (T960161)
  NetCoreDemos/Controllers/ApiControllers/DataGridBatchUpdateWebApiController.cs
Labels: 20_2, cherry-pick

#496 DataGrid - Fix Batch Update Request demo in ASP.NET Core approach (T960161)
  NetCoreDemos/Controllers/ApiControllers/DataGridBatchUpdateWebApiController.cs
Labels: 21_1
