Repository DevExpress/devextreme-demos, pull requests merged in 2020-11, with the labels that each got.

#332 dxScheduler - replace dates in recurrence demo
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/ContextMenuIntegration/AngularJS/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/jQuery/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/RecurringAppointments/AngularJS/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Knockout/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/React/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Vue/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/jQuery/data.js
Labels: 20_2

#330 Fix warning in the "HtmlEditor > Mentions" demo (T944741)
  JSDemos/Demos/HtmlEditor/Mentions/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/Mentions/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/Mentions/React/App.js
  JSDemos/Demos/HtmlEditor/Mentions/Vue/App.vue
  JSDemos/Demos/HtmlEditor/Mentions/jQuery/index.html
  MVCDemos/Views/HtmlEditor/Mentions.cshtml
  NetCoreDemos/Views/HtmlEditor/Mentions.cshtml
Labels: 20_2

#329 Fix warning in the "Editors > Right-to-Left Support" demo (T944728)
  JSDemos/Demos/Common/EditorsRightToLeftSupport/React/App.js
Labels: 20_2

#339 Bump version in NetCore demos
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
Labels: 20_2

#341 Run linters in parallel
  package.json
Labels: 20_2

#346 File Uploader - Fix custom dropzone jquery ie demo
  JSDemos/Demos/FileUploader/CustomDropzone/jQuery/index.js
  MVCDemos/Views/FileUploader/CustomDropzone.cshtml
  NetCoreDemos/Views/FileUploader/CustomDropzone.cshtml
Labels: 20_2

#347 DataGrid/TreeList: Fix demos for IE
  JSDemos/Demos/DataGrid/BatchUpdateRequest/jQuery/index.js
  JSDemos/Demos/DataGrid/EditStateManagement/jQuery/index.js
  JSDemos/Demos/TreeList/FocusedRow/jQuery/index.js
Labels: 20_2

#350 Fix Scheduler Timezones demo in IE
  JSDemos/Demos/Scheduler/TimeZonesSupport/AngularJS/index.js
  JSDemos/Demos/Scheduler/TimeZonesSupport/jQuery/index.js
  MVCDemos/Views/Scheduler/TimeZonesSupport.cshtml
  NetCoreDemos/Views/Scheduler/TimeZonesSupport.cshtml
Labels: 20_2

#357 Globalize reducing from demos
  JSDemos/Demos/Charts/Doughnut/AngularJS/index.html
  JSDemos/Demos/Charts/Doughnut/AngularJS/index.js
  JSDemos/Demos/Charts/Doughnut/Knockout/index.html
  JSDemos/Demos/Charts/Doughnut/Knockout/index.js
  JSDemos/Demos/Charts/Doughnut/jQuery/index.html
  JSDemos/Demos/Charts/Doughnut/jQuery/index.js
  JSDemos/Demos/Charts/DoughnutWithCustomLabelInCenter/jQuery/index.html
  JSDemos/Demos/Charts/DoughnutWithCustomLabelInCenter/jQuery/index.js
  JSDemos/Demos/Charts/SignalRService/AngularJS/index.html
  JSDemos/Demos/Charts/SignalRService/AngularJS/index.js
  JSDemos/Demos/Charts/SignalRService/jQuery/index.html
  JSDemos/Demos/Charts/SignalRService/jQuery/index.js
  JSDemos/Demos/RangeSelector/DiscreteScale/AngularJS/index.html
  JSDemos/Demos/RangeSelector/DiscreteScale/AngularJS/index.js
  JSDemos/Demos/RangeSelector/DiscreteScale/Knockout/index.html
  JSDemos/Demos/RangeSelector/DiscreteScale/Knockout/index.js
  JSDemos/Demos/RangeSelector/DiscreteScale/jQuery/index.html
  JSDemos/Demos/RangeSelector/DiscreteScale/jQuery/index.js
  JSDemos/Demos/VectorMap/Overview/Angular/app/app.component.css
  JSDemos/Demos/VectorMap/Overview/AngularJS/index.html
  JSDemos/Demos/VectorMap/Overview/AngularJS/index.js
  JSDemos/Demos/VectorMap/Overview/Knockout/index.html
  JSDemos/Demos/VectorMap/Overview/Knockout/index.js
  JSDemos/Demos/VectorMap/Overview/jQuery/index.html
  JSDemos/Demos/VectorMap/Overview/jQuery/index.js
  JSDemos/Demos/VectorMap/TooltipHTMLSupport/Angular/app/app.component.css
  JSDemos/Demos/VectorMap/TooltipHTMLSupport/AngularJS/index.html
  JSDemos/Demos/VectorMap/TooltipHTMLSupport/AngularJS/index.js
  JSDemos/Demos/VectorMap/TooltipHTMLSupport/Knockout/index.html
  JSDemos/Demos/VectorMap/TooltipHTMLSupport/Knockout/index.js
  JSDemos/Demos/VectorMap/TooltipHTMLSupport/jQuery/index.html
  JSDemos/Demos/VectorMap/TooltipHTMLSupport/jQuery/index.js
Labels: 20_2

#359 DataGrid: Fix Command Column Customization demo for Vue approach
  JSDemos/Demos/DataGrid/CommandColumnCustomization/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/CommandColumnCustomization/React/App.js
  JSDemos/Demos/DataGrid/CommandColumnCustomization/Vue/App.vue
Labels: 20_2

#365 File Uploader - Refactor and update custom drop zone demo
  JSDemos/Demos/FileUploader/CustomDropzone/Angular/app/app.component.html
  JSDemos/Demos/FileUploader/CustomDropzone/Angular/app/app.component.ts
  JSDemos/Demos/FileUploader/CustomDropzone/React/App.js
  JSDemos/Demos/FileUploader/CustomDropzone/Vue/App.vue
  JSDemos/Demos/FileUploader/CustomDropzone/description.md
  JSDemos/menuMeta.json
Labels: 20_2

#363 DataGrid Custom editors demo: Use svg instead of png to fix icons bluring in the lookup
  JSDemos/Demos/DataGrid/CustomEditors/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/CustomEditors/AngularJS/index.html
  JSDemos/Demos/DataGrid/CustomEditors/React/App.js
  JSDemos/Demos/DataGrid/CustomEditors/Vue/App.vue
  JSDemos/Demos/DataGrid/CustomEditors/jQuery/index.js
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Angular/config.js
  JSDemos/images/icons/status-1.png
  JSDemos/images/icons/status-1.svg
  JSDemos/images/icons/status-2.png
  JSDemos/images/icons/status-2.svg
  JSDemos/images/icons/status-3.png
  JSDemos/images/icons/status-3.svg
  JSDemos/images/icons/status-4.png
  JSDemos/images/icons/status-4.svg
  JSDemos/images/icons/status-5.png
  JSDemos/images/icons/status-5.svg
  MVCDemos/Views/DataGrid/CustomEditors.cshtml
  NetCoreDemos/Views/DataGrid/CustomEditors.cshtml
Labels: 20_2

#369 Fix build on farm after icons rename
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Angular/config.js
  MVCDemos/DevExtreme.MVC.Demos.csproj
Labels: 20_2

#367 Use "apiKey" option instead of "key" in the Map demos
  JSDemos/Demos/Map/ProvidersAndTypes/Angular/app/app.component.html
  JSDemos/Demos/Map/ProvidersAndTypes/Angular/app/app.component.ts
  JSDemos/Demos/Map/ProvidersAndTypes/AngularJS/index.js
  JSDemos/Demos/Map/ProvidersAndTypes/Knockout/index.js
  JSDemos/Demos/Map/ProvidersAndTypes/React/App.js
  JSDemos/Demos/Map/ProvidersAndTypes/Vue/App.vue
  JSDemos/Demos/Map/ProvidersAndTypes/jQuery/index.js
  MVCDemos/Views/Map/ProvidersAndTypes.cshtml
  NetCoreDemos/Views/Map/ProvidersAndTypes.cshtml
Labels: 20_2

#371 Add status icons for MVC and NETCore
  MVCDemos/Content/images/icons/status-1.png
  MVCDemos/Content/images/icons/status-1.svg
  MVCDemos/Content/images/icons/status-2.png
  MVCDemos/Content/images/icons/status-2.svg
  MVCDemos/Content/images/icons/status-3.png
  MVCDemos/Content/images/icons/status-3.svg
  MVCDemos/Content/images/icons/status-4.png
  MVCDemos/Content/images/icons/status-4.svg
  MVCDemos/Content/images/icons/status-5.png
  MVCDemos/Content/images/icons/status-5.svg
  NetCoreDemos/wwwroot/images/icons/status-1.png
  NetCoreDemos/wwwroot/images/icons/status-1.svg
  NetCoreDemos/wwwroot/images/icons/status-2.png
  NetCoreDemos/wwwroot/images/icons/status-2.svg
  NetCoreDemos/wwwroot/images/icons/status-3.png
  NetCoreDemos/wwwroot/images/icons/status-3.svg
  NetCoreDemos/wwwroot/images/icons/status-4.png
  NetCoreDemos/wwwroot/images/icons/status-4.svg
  NetCoreDemos/wwwroot/images/icons/status-5.png
  NetCoreDemos/wwwroot/images/icons/status-5.svg
Labels: 20_2

#368 TreeView - fix DnD Demo (T948114)
  MVCDemos/Views/TreeView/DragAndDropHierarchicalDataStructure.cshtml
  MVCDemos/Views/TreeView/DragAndDropPlainDataStructure.cshtml
  NetCoreDemos/Views/TreeView/DragAndDropHierarchicalDataStructure.cshtml
  NetCoreDemos/Views/TreeView/DragAndDropPlainDataStructure.cshtml
Labels: 20_2

#377 DataGrid - Removes redundant summary
  JSDemos/Demos/DataGrid/RemoteGrouping/AngularJS/index.js
Labels: 20_2

#379 DataGrid - Removes redundant summary #377
  JSDemos/Demos/DataGrid/RemoteGrouping/AngularJS/index.js
Labels: 21_1, cherry-pick

#370 TreeList: Fix TreeList React Web API Service demo
  JSDemos/Demos/TreeList/WebAPIService/React/App.js
Labels: 20_2

#375 Rename files
  .eslintignore
  package.json
  utils/interactive/add-demo.js
  utils/interactive/edit-demo.js
  utils/interactive/launch-demo.js
  utils/interactive/link-repos.js
  utils/interactive/menu-meta-utils.js
  utils/interactive/prompts-questions.js
  utils/interactive/repos-helper.js
  utils/internal/create-config.js
  utils/internal/prepare-common.js
  utils/internal/prepare-mvc.js
  utils/internal/prepare-netcore.js
  utils/shared/child-process-utils.js
  utils/shared/fs-utils.js
  utils/templates/Angular/app/app.component.html
  utils/templates/Angular/app/app.component.ts
  utils/templates/Angular/app/app.service.ts
  utils/templates/Angular/index.html
  utils/templates/AngularJS/AngularJSIndex.html
  utils/templates/AngularJS/AngularJSIndex.js
  utils/templates/AngularJS/data.js
  utils/templates/AngularJS/index.html
  utils/templates/AngularJS/index.js
  utils/templates/Knockout/KnockoutIndex.html
  utils/templates/Knockout/KnockoutIndex.js
  utils/templates/Knockout/data.js
  utils/templates/Knockout/index.html
  utils/templates/Knockout/index.js
  utils/templates/React/App.js
  utils/templates/React/data.js
  utils/templates/React/index.html
  utils/templates/React/index.js
  utils/templates/Vue/App.vue
  utils/templates/Vue/data.js
  utils/templates/Vue/index.html
  utils/templates/Vue/index.js
  utils/templates/jQuery/data.js
  utils/templates/jQuery/index.html
  utils/templates/jQuery/index.js
Labels: 20_2

#383 Linter for utils folder and renames
  .eslintignore
  .eslintrc.js
  package.json
  utils/.eslintrc.js
  utils/add-demo.js
  utils/cp_utils.js
  utils/edit-demo.js
  utils/interactive/add-demo.js
  utils/interactive/edit-demo.js
  utils/interactive/launch-demo.js
  utils/interactive/link-repos.js
  utils/interactive/menu-meta-utils.js
  utils/interactive/prompts-questions.js
  utils/interactive/repos-helper.js
  utils/internal/create-config.js
  utils/internal/prepare-common.js
  utils/internal/prepare-mvc.js
  utils/internal/prepare-netcore.js
  utils/launch-demo.js
  utils/link-repos.js
  utils/prepare-common.js
  utils/prepare-mvc.js
  utils/prepare-netcore.js
  utils/repos_helper.js
  utils/shared/child-process-utils.js
  utils/shared/fs-utils.js
  utils/templates/Angular/app/app.component.html
  utils/templates/Angular/app/app.component.ts
  utils/templates/Angular/app/app.service.ts
  utils/templates/Angular/index.html
  utils/templates/AngularJS/AngularJSIndex.html
  utils/templates/AngularJS/AngularJSIndex.js
  utils/templates/AngularJS/data.js
  utils/templates/AngularJS/index.html
  utils/templates/AngularJS/index.js
  utils/templates/Knockout/KnockoutIndex.html
  utils/templates/Knockout/KnockoutIndex.js
  utils/templates/Knockout/data.js
  utils/templates/Knockout/index.html
  utils/templates/Knockout/index.js
  utils/templates/React/App.js
  utils/templates/React/data.js
  utils/templates/React/index.html
  utils/templates/React/index.js
  utils/templates/Vue/App.vue
  utils/templates/Vue/data.js
  utils/templates/Vue/index.html
  utils/templates/Vue/index.js
  utils/templates/jQuery/data.js
  utils/templates/jQuery/index.html
  utils/templates/jQuery/index.js
Labels: 21_1, cherry-pick

#380 Demos updating
  JSDemos/Demos/Charts/AxisLabelsTemplates/React/App.js
  JSDemos/Demos/Charts/PieWithAnnotations/React/App.js
  JSDemos/Demos/Charts/Strips/Angular/app/app.component.html
  JSDemos/Demos/Charts/Strips/React/App.js
  JSDemos/Demos/Charts/Strips/Vue/App.vue
  JSDemos/Demos/Charts/Strips/jQuery/index.js
  MVCDemos/Views/Charts/Strips.cshtml
  NetCoreDemos/Views/Charts/Strips.cshtml
Labels: 20_2

#386 dxChart - Fix custom aggregation function (T948359)
  JSDemos/Demos/Charts/PointsAggregation/Angular/app/app.component.ts
  JSDemos/Demos/Charts/PointsAggregation/AngularJS/index.js
  JSDemos/Demos/Charts/PointsAggregation/React/App.js
  JSDemos/Demos/Charts/PointsAggregation/Vue/App.vue
  JSDemos/Demos/Charts/PointsAggregation/jQuery/index.js
  JSDemos/Demos/Charts/SignalRService/Angular/app/app.component.ts
  JSDemos/Demos/Charts/SignalRService/AngularJS/index.js
  JSDemos/Demos/Charts/SignalRService/React/App.js
  JSDemos/Demos/Charts/SignalRService/Vue/App.vue
  JSDemos/Demos/Charts/SignalRService/jQuery/index.js
  MVCDemos/Views/Charts/PointsAggregation.cshtml
  MVCDemos/Views/Charts/SignalRService.cshtml
  NetCoreDemos/Views/Charts/PointsAggregation.cshtml
  NetCoreDemos/Views/Charts/SignalRService.cshtml
Labels: 21_1

#381 Using "instance" instead of "data" to get the instance of a widget
  JSDemos/Demos/NumberBox/Overview/jQuery/index.js
  JSDemos/Demos/TextBox/Overview/jQuery/index.js
  MVCDemos/Views/DataGrid/MultipleRecordSelectionAPI.cshtml
  NetCoreDemos/Views/DataGrid/MultipleRecordSelectionAPI.cshtml
Labels: 20_2

#382 Update linter
  .eslintrc.js
  JSDemos/Demos/DataGrid/CustomSummaries/React/App.js
  JSDemos/Demos/DataGrid/DnDBetweenGrids/Vue/Grid.vue
  JSDemos/Demos/DataGrid/ExcelCellCustomization/React/App.js
  JSDemos/Demos/DataGrid/ExcelJS/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/DataGrid/FocusedRow/React/App.js
  JSDemos/Demos/DataGrid/GroupSummaries/React/App.js
  JSDemos/Demos/DataGrid/RealTimeUpdates/React/App.js
  JSDemos/Demos/FileUploader/Validation/React/App.js
  JSDemos/Demos/HtmlEditor/Mentions/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Angular/config.js
  JSDemos/Demos/TreeList/FocusedRow/React/App.js
  JSDemos/Demos/VectorMap/AreaWithLabelsAndTwoLegends/React/App.js
  package.json
  utils/.eslintrc.js
Labels: 20_2

#389 Update linter (#382)
  .eslintrc.js
  JSDemos/Demos/DataGrid/CustomSummaries/React/App.js
  JSDemos/Demos/DataGrid/DnDBetweenGrids/Vue/Grid.vue
  JSDemos/Demos/DataGrid/ExcelCellCustomization/React/App.js
  JSDemos/Demos/DataGrid/ExcelJS/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/DataGrid/FocusedRow/React/App.js
  JSDemos/Demos/DataGrid/GroupSummaries/React/App.js
  JSDemos/Demos/DataGrid/RealTimeUpdates/React/App.js
  JSDemos/Demos/FileUploader/Validation/React/App.js
  JSDemos/Demos/HtmlEditor/Mentions/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Angular/config.js
  JSDemos/Demos/TreeList/FocusedRow/React/App.js
  JSDemos/Demos/VectorMap/AreaWithLabelsAndTwoLegends/React/App.js
  package.json
  utils/.eslintrc.js
Labels: 21_1, cherry-pick

#391 Fix DataGrid and TreeList React demos (XXX prop -> defaultXXX prop)
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/React/App.js
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/React/OrderHistory.js
  JSDemos/Demos/DataGrid/CellCustomization/React/App.js
  JSDemos/Demos/DataGrid/CustomEditors/React/App.js
  JSDemos/Demos/DataGrid/CustomEditors/React/EmployeeDropDownBoxComponent.js
  JSDemos/Demos/DataGrid/FocusedRow/React/App.js
  JSDemos/Demos/DataGrid/GridAdaptabilityOverview/React/App.js
  JSDemos/Demos/DataGrid/KeyboardNavigation/React/App.js
  JSDemos/Demos/DataGrid/RealTimeUpdates/React/App.js
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/React/App.js
  JSDemos/Demos/DataGrid/RightToLeftSupport/React/App.js
  JSDemos/Demos/TreeList/KeyboardNavigation/React/App.js
Labels: 21_1, cherry-pick

#384 Fix DataGrid and TreeList React demos (XXX prop -> defaultXXX prop)
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/React/App.js
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/React/OrderHistory.js
  JSDemos/Demos/DataGrid/CellCustomization/React/App.js
  JSDemos/Demos/DataGrid/CustomEditors/React/App.js
  JSDemos/Demos/DataGrid/CustomEditors/React/EmployeeDropDownBoxComponent.js
  JSDemos/Demos/DataGrid/FocusedRow/React/App.js
  JSDemos/Demos/DataGrid/GridAdaptabilityOverview/React/App.js
  JSDemos/Demos/DataGrid/KeyboardNavigation/React/App.js
  JSDemos/Demos/DataGrid/RealTimeUpdates/React/App.js
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/React/App.js
  JSDemos/Demos/DataGrid/RightToLeftSupport/React/App.js
  JSDemos/Demos/TreeList/KeyboardNavigation/React/App.js
Labels: 20_2

#390 TreeList: Fix React Web API Service demo
  JSDemos/Demos/TreeList/WebAPIService/React/App.js
Labels: 21_1, cherry-pick

#393 DataGrid Export to PDF - FIX: Error on Export to PDF demo when copied to CodePen (T949821)
  .eslintrc.js
  JSDemos/Demos/DataGrid/ExportToPDF/jQuery/index.html
  JSDemos/Demos/DataGrid/ExportToPDF/jQuery/index.js
Labels: 21_1

#395 DataGrid Export to PDF - FIX: Error on Export to PDF demo when copied to CodePen (T949821)
  .eslintrc.js
  JSDemos/Demos/DataGrid/ExportToPDF/jQuery/index.html
  JSDemos/Demos/DataGrid/ExportToPDF/jQuery/index.js
Labels: 20_2, cherry-pick

#397 Fix charts and localization demo
  JSDemos/Demos/Charts/Strips/Angular/index.html
  JSDemos/Demos/Charts/Strips/React/index.html
  JSDemos/Demos/Charts/Strips/Vue/index.html
  JSDemos/Demos/Charts/Strips/jQuery/index.html
  JSDemos/Demos/Localization/UsingGlobalize/Knockout/index.js
Labels: 20_2

#399 Remove old upload service in FileUploader demos
  JSDemos/Demos/FileUploader/CustomDropzone/Angular/app/app.component.html
  JSDemos/Demos/FileUploader/CustomDropzone/React/App.js
  JSDemos/Demos/FileUploader/CustomDropzone/Vue/App.vue
  JSDemos/Demos/FileUploader/CustomDropzone/jQuery/index.js
  JSDemos/Demos/FileUploader/FileUploading/Angular/app/app.component.html
  JSDemos/Demos/FileUploader/FileUploading/AngularJS/index.js
  JSDemos/Demos/FileUploader/FileUploading/Knockout/index.js
  JSDemos/Demos/FileUploader/FileUploading/React/App.js
  JSDemos/Demos/FileUploader/FileUploading/Vue/App.vue
  JSDemos/Demos/FileUploader/FileUploading/jQuery/index.js
  JSDemos/Demos/FileUploader/Validation/Angular/app/app.component.html
  JSDemos/Demos/FileUploader/Validation/AngularJS/index.js
  JSDemos/Demos/FileUploader/Validation/React/App.js
  JSDemos/Demos/FileUploader/Validation/Vue/App.vue
  JSDemos/Demos/FileUploader/Validation/jQuery/index.js
Labels: 21_1

#400 Remove old upload service in FileUploader demos
  JSDemos/Demos/FileUploader/CustomDropzone/Angular/app/app.component.html
  JSDemos/Demos/FileUploader/CustomDropzone/React/App.js
  JSDemos/Demos/FileUploader/CustomDropzone/Vue/App.vue
  JSDemos/Demos/FileUploader/CustomDropzone/jQuery/index.js
  JSDemos/Demos/FileUploader/FileUploading/Angular/app/app.component.html
  JSDemos/Demos/FileUploader/FileUploading/AngularJS/index.js
  JSDemos/Demos/FileUploader/FileUploading/Knockout/index.js
  JSDemos/Demos/FileUploader/FileUploading/React/App.js
  JSDemos/Demos/FileUploader/FileUploading/Vue/App.vue
  JSDemos/Demos/FileUploader/FileUploading/jQuery/index.js
  JSDemos/Demos/FileUploader/Validation/Angular/app/app.component.html
  JSDemos/Demos/FileUploader/Validation/AngularJS/index.js
  JSDemos/Demos/FileUploader/Validation/React/App.js
  JSDemos/Demos/FileUploader/Validation/Vue/App.vue
  JSDemos/Demos/FileUploader/Validation/jQuery/index.js
Labels: 20_2

#405 File Uploader - Fix demo links and descriptions
  JSDemos/Demos/FileUploader/AzureDirectUploading/description.md
  JSDemos/Demos/FileUploader/ChunkUploading/description.md
  JSDemos/Demos/FileUploader/Validation/description.md
  MVCDemos/Content/Descr/FileUploader/ChunkUploading.md
  MVCDemos/Content/Descr/FileUploader/Validation.md
  NetCoreDemos/wwwroot/Descr/FileUploader/ChunkUploading.md
  NetCoreDemos/wwwroot/Descr/FileUploader/Validation.md
Labels: 20_2

#406 File Uploader - Fix demo links and descriptions
  JSDemos/Demos/FileUploader/AzureDirectUploading/description.md
  JSDemos/Demos/FileUploader/ChunkUploading/description.md
  JSDemos/Demos/FileUploader/Validation/description.md
  MVCDemos/Content/Descr/FileUploader/ChunkUploading.md
  MVCDemos/Content/Descr/FileUploader/Validation.md
  NetCoreDemos/wwwroot/Descr/FileUploader/ChunkUploading.md
  NetCoreDemos/wwwroot/Descr/FileUploader/Validation.md
Labels: 21_1, cherry-pick

#407 Support any origin for FileГploading/Upload service
  NetCoreDemos/Controllers/FileUploaderController.cs
Labels: 21_1

#408 Support any origin for FileГploading/Upload service
  NetCoreDemos/Controllers/FileUploaderController.cs
Labels: 20_2

#409 DataGrid Export to PDF - FIX: Uncaught TypeError: Cannot read property 'jsPDF' of undefined
  JSDemos/Demos/DataGrid/ExportToPDF/jQuery/index.html
Labels: 20_2

#410 DataGrid Export to PDF - FIX: Uncaught TypeError: Cannot read property 'jsPDF' of undefined
  JSDemos/Demos/DataGrid/ExportToPDF/jQuery/index.html
Labels: 21_1, cherry-pick

#411 Fix css in Overview Scheduler demo
  JSDemos/Demos/Scheduler/Overview/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/Overview/AngularJS/styles.css
  JSDemos/Demos/Scheduler/Overview/React/styles.css
  JSDemos/Demos/Scheduler/Overview/Vue/App.vue
  JSDemos/Demos/Scheduler/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Scheduler/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/Overview.css
Labels: 21_1

#416 dxScheduler - add recurrenceRule expression for server-side demos
  NetCoreDemos/Views/Scheduler/SignalRService.cshtml
  NetCoreDemos/Views/Scheduler/WebAPIService.cshtml
Labels: 21_1, cherry-pick

#420 List - It is not possible to drag & drop an item from one control to another in a certain scenario(T941682)
  JSDemos/Demos/List/ItemDragging/Angular/app/app.component.css
  JSDemos/Demos/List/ItemDragging/React/styles.css
  JSDemos/Demos/List/ItemDragging/Vue/App.vue
  JSDemos/Demos/List/ItemDragging/jQuery/styles.css
  MVCDemos/Content/DemosStyles/List/ItemDragging.css
  NetCoreDemos/wwwroot/css/DemosStyles/List/ItemDragging.css
Labels: 20_2

#421 List - It is not possible to drag & drop an item from one control to another in a certain scenario(T941682)
  JSDemos/Demos/List/ItemDragging/Angular/app/app.component.css
  JSDemos/Demos/List/ItemDragging/React/styles.css
  JSDemos/Demos/List/ItemDragging/Vue/App.vue
  JSDemos/Demos/List/ItemDragging/jQuery/styles.css
  MVCDemos/Content/DemosStyles/List/ItemDragging.css
  NetCoreDemos/wwwroot/css/DemosStyles/List/ItemDragging.css
Labels: 21_1, cherry-pick

#423 Hide Strips demo
  JSDemos/menuMeta.json
Labels: 20_2

#424 Revert "Hide Strips demo (#423)"
  JSDemos/menuMeta.json
Labels: 20_2

#425 Fix vue linter warnings
  JSDemos/Demos/Charts/CustomAnnotations/Vue/AnnotationTemplate.vue
  JSDemos/Demos/Map/ProvidersAndTypes/Vue/App.vue
  JSDemos/Demos/ScrollView/Overview/Vue/App.vue
  JSDemos/Demos/TreeView/DragAndDropHierarchicalDataStructure/Vue/App.vue
  JSDemos/Demos/TreeView/DragAndDropPlainDataStructure/Vue/App.vue
  JSDemos/Demos/VectorMap/CustomAnnotations/Vue/AnnotationTemplate.vue
Labels: 21_1

#426 Fix vue warnings
  JSDemos/Demos/Charts/CustomAnnotations/Vue/AnnotationTemplate.vue
  JSDemos/Demos/Map/ProvidersAndTypes/Vue/App.vue
  JSDemos/Demos/ScrollView/Overview/Vue/App.vue
  JSDemos/Demos/TreeView/DragAndDropHierarchicalDataStructure/Vue/App.vue
  JSDemos/Demos/TreeView/DragAndDropPlainDataStructure/Vue/App.vue
  JSDemos/Demos/VectorMap/CustomAnnotations/Vue/AnnotationTemplate.vue
Labels: 20_2, cherry-pick
