Repository DevExpress/devextreme-demos, pull requests merged in 2021-03, with the labels that each got.

#630 Remove config (generate it instead)
  .gitignore
  gulpfile.js/copy-mercurial-asp-files.js
  gulpfile.js/js.js
  repository.config.json
  utils/interactive/repos-helper.js
  utils/shared/config-helper.js
  utils/tests/shared/config-helper.test.js
Labels: 20_2, cherry-pick

#629 Remove config (generate it instead)
  .gitignore
  gulpfile.js/copy-mercurial-asp-files.js
  gulpfile.js/js.js
  repository.config.json
  utils/interactive/repos-helper.js
  utils/shared/config-helper.js
  utils/tests/shared/config-helper.test.js
Labels: 21_1

#636 dxScheduler - disable current time indicator in recurrence and menu integration demos
  JSDemos/Demos/Scheduler/ContextMenuIntegration/AngularJS/index.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/App.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/App.vue
  JSDemos/Demos/Scheduler/ContextMenuIntegration/jQuery/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/RecurringAppointments/AngularJS/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Knockout/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/React/App.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Vue/App.vue
  JSDemos/Demos/Scheduler/RecurringAppointments/jQuery/index.js
  MVCDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  MVCDemos/Views/Scheduler/RecurringAppointments.cshtml
  NetCoreDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  NetCoreDemos/Views/Scheduler/RecurringAppointments.cshtml
Labels: 21_1

#637 dxScheduler - disable current time indicator in recurrence and menu integration demos
  JSDemos/Demos/Scheduler/ContextMenuIntegration/AngularJS/index.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/App.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/App.vue
  JSDemos/Demos/Scheduler/ContextMenuIntegration/jQuery/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/RecurringAppointments/AngularJS/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Knockout/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/React/App.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Vue/App.vue
  JSDemos/Demos/Scheduler/RecurringAppointments/jQuery/index.js
  MVCDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  MVCDemos/Views/Scheduler/RecurringAppointments.cshtml
  NetCoreDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  NetCoreDemos/Views/Scheduler/RecurringAppointments.cshtml
Labels: 20_2, cherry-pick

#638 Fix config reading
  utils/shared/config-helper.js
  utils/tests/shared/config-helper.test.js
Labels: 21_1

#639 Fix config reading (#638)
  utils/shared/config-helper.js
  utils/tests/shared/config-helper.test.js
Labels: 20_2, cherry-pick

#643 dxScheduler - fix dates in demos with month view
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/ContextMenuIntegration/AngularJS/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/AngularJS/index.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/App.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/App.vue
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/jQuery/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/jQuery/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/RecurringAppointments/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/RecurringAppointments/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/RecurringAppointments/AngularJS/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/AngularJS/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Knockout/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Knockout/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/React/App.js
  JSDemos/Demos/Scheduler/RecurringAppointments/React/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Vue/App.vue
  JSDemos/Demos/Scheduler/RecurringAppointments/Vue/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/jQuery/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/jQuery/index.js
  MVCDemos/Models/SampleData/RecurringAppointments.cs
  MVCDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  MVCDemos/Views/Scheduler/RecurringAppointments.cshtml
  NetCoreDemos/Models/SampleData/RecurringAppointments.cs
  NetCoreDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  NetCoreDemos/Views/Scheduler/RecurringAppointments.cshtml
Labels: 20_2

#648 dxScheduler - fix dates in demos with month view (#643)
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/ContextMenuIntegration/AngularJS/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/AngularJS/index.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/App.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/App.vue
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/jQuery/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/jQuery/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/RecurringAppointments/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/RecurringAppointments/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/RecurringAppointments/AngularJS/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/AngularJS/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Knockout/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Knockout/index.js
  JSDemos/Demos/Scheduler/RecurringAppointments/React/App.js
  JSDemos/Demos/Scheduler/RecurringAppointments/React/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/Vue/App.vue
  JSDemos/Demos/Scheduler/RecurringAppointments/Vue/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/jQuery/data.js
  JSDemos/Demos/Scheduler/RecurringAppointments/jQuery/index.js
  MVCDemos/Models/SampleData/RecurringAppointments.cs
  MVCDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  MVCDemos/Views/Scheduler/RecurringAppointments.cshtml
  NetCoreDemos/Models/SampleData/RecurringAppointments.cs
  NetCoreDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  NetCoreDemos/Views/Scheduler/RecurringAppointments.cshtml
Labels: 21_1, cherry-pick

#649 Fix vulnerable regex
  MVCDemos/Models/DataGrid/EmployeeValidation.cs
  MVCDemos/ViewModels/EditorsViewModel.cs
  NetCoreDemos/Models/DataGrid/EmployeeValidation.cs
  NetCoreDemos/ViewModels/EditorsViewModel.cs
Labels: 21_1

#650 Fix vulnerable regex
  MVCDemos/Models/DataGrid/EmployeeValidation.cs
  MVCDemos/ViewModels/EditorsViewModel.cs
  NetCoreDemos/Models/DataGrid/EmployeeValidation.cs
  NetCoreDemos/ViewModels/EditorsViewModel.cs
Labels: 20_2, cherry-pick

#651 Rename HTML Editor toolbar item properties to name and acceptedValues
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/OutputFormats/Knockout/index.js
  JSDemos/Demos/HtmlEditor/OutputFormats/React/App.js
  JSDemos/Demos/HtmlEditor/OutputFormats/Vue/App.vue
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/index.js
  JSDemos/Demos/HtmlEditor/Overview/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/Overview/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/Overview/Knockout/index.js
  JSDemos/Demos/HtmlEditor/Overview/React/App.js
  JSDemos/Demos/HtmlEditor/Overview/Vue/App.vue
  JSDemos/Demos/HtmlEditor/Overview/jQuery/index.js
  JSDemos/Demos/HtmlEditor/Tables/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/Tables/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/Tables/React/App.js
  JSDemos/Demos/HtmlEditor/Tables/Vue/App.vue
  JSDemos/Demos/HtmlEditor/Tables/jQuery/index.js
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/Knockout/index.js
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/React/App.js
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/Vue/App.vue
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/jQuery/index.js
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  MVCDemos/Views/HtmlEditor/Overview.cshtml
  MVCDemos/Views/HtmlEditor/Tables.cshtml
  MVCDemos/Views/HtmlEditor/ToolbarCustomization.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/Overview.cshtml
  NetCoreDemos/Views/HtmlEditor/Tables.cshtml
  NetCoreDemos/Views/HtmlEditor/ToolbarCustomization.cshtml
Labels: 21_1

#653 dxScheduler - add expressions for recurrence to Web API demo
  JSDemos/Demos/Scheduler/WebAPIService/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/WebAPIService/AngularJS/index.js
  JSDemos/Demos/Scheduler/WebAPIService/Knockout/index.js
  JSDemos/Demos/Scheduler/WebAPIService/React/App.js
  JSDemos/Demos/Scheduler/WebAPIService/Vue/App.vue
  JSDemos/Demos/Scheduler/WebAPIService/jQuery/index.js
  MVCDemos/Views/Scheduler/WebAPIService.cshtml
  NetCoreDemos/Views/Scheduler/WebAPIService.cshtml
Labels: 21_1

#654 dxScheduler - add expressions for recurrence to Web API demo
  JSDemos/Demos/Scheduler/WebAPIService/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/WebAPIService/AngularJS/index.js
  JSDemos/Demos/Scheduler/WebAPIService/Knockout/index.js
  JSDemos/Demos/Scheduler/WebAPIService/React/App.js
  JSDemos/Demos/Scheduler/WebAPIService/Vue/App.vue
  JSDemos/Demos/Scheduler/WebAPIService/jQuery/index.js
  MVCDemos/Views/Scheduler/WebAPIService.cshtml
  NetCoreDemos/Views/Scheduler/WebAPIService.cshtml
Labels: 20_2, cherry-pick

#663 DataGrid Cell Editing Demo: remove keyExpr
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/React/App.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Vue/App.vue
Labels: 21_1

#662 DataGrid Cell Editing Demo: remove keyExpr
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/React/App.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Vue/App.vue
Labels: 20_2

#669 Scheduler - Fix - View types should be correct in MVC/.NetCore virtual scrolling demo
  MVCDemos/Views/Scheduler/VirtualScrolling.cshtml
  NetCoreDemos/Views/Scheduler/VirtualScrolling.cshtml
Labels: 21_1

#670 Scheduler - Fix - View types should be correct in MVC/.NetCore virtual scrolling demo
  MVCDemos/Views/Scheduler/VirtualScrolling.cshtml
  NetCoreDemos/Views/Scheduler/VirtualScrolling.cshtml
Labels: 20_2

#668 TreeList: Fix Node Drag & Drop demo for Vue approach
  JSDemos/Demos/TreeList/LocalReordering/Vue/App.vue
Labels: 21_1, cherry-pick

#667 TreeList: Fix Node Drag & Drop demo for Vue approach
  JSDemos/Demos/TreeList/LocalReordering/Vue/App.vue
Labels: 20_2

#675 Scheduler - Update demos on virtual scrolling
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Angular/index.html
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/React/data.js
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/React/index.html
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/React/index.js
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/React/styles.css
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Vue/data.js
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Vue/index.html
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Vue/index.js
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Vue/styles.css
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/description.md
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/jQuery/data.js
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/jQuery/index.html
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/jQuery/index.js
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/jQuery/styles.css
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Angular/index.html
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/React/data.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/React/index.html
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/React/index.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Vue/data.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Vue/index.html
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Vue/index.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/description.md
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/jQuery/data.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/jQuery/index.html
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/jQuery/index.js
  JSDemos/menuMeta.json
Labels: 21_1

#693 Scheduler - Remove width from the horizontal Virtual Scrolling demo
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/jQuery/index.js
  JSDemos/menuMeta.json
Labels: 21_1

#673 DataGrid.Pdf - Upgrade jsPDF and AutoTable plugin versions
  JSDemos/Demos/DataGrid/ExportToPDF/jQuery/index.html
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.js
  MVCDemos/Views/DataGrid/ExportToPDF.cshtml
  NetCoreDemos/Views/DataGrid/ExportToPDF.cshtml
  package.json
Labels: 20_2

#686 DataGrid.Pdf - Upgrade jsPDF and AutoTable plugin versions
  JSDemos/Demos/DataGrid/ExportToPDF/jQuery/index.html
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.js
  MVCDemos/Views/DataGrid/ExportToPDF.cshtml
  NetCoreDemos/Views/DataGrid/ExportToPDF.cshtml
  package.json
Labels: 21_1, cherry-pick

#697 Replace "devextreme-generator" dependency by "@devextreme/vdom"
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.js
  package.json
Labels: 21_1

#703 Scheduler - Virtual scrolling demo - Add Month view
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/jQuery/index.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/jQuery/index.js
Labels: 21_1
