Repository DevExpress/devextreme-demos, pull requests merged in 2021-07, with the labels that each got.

#1038 exceljs.export: update file-saver lib
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.js
  package.json
Labels: 21_2

#1040 exceljs.export: fix file-saver package name
  JSDemos/Demos/DataGrid/ExcelJS/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJS/React/App.js
  JSDemos/Demos/DataGrid/ExcelJS/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSExportImages/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSExportImages/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSExportImages/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSExportMultipleGrids/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSExportMultipleGrids/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSExportMultipleGrids/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSOverview/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSOverview/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSOverview/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJSOverview/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Vue/App.vue
Labels: 21_2

#1002 TreeView Load Data on Demand: rewrite
  JSDemos/Demos/TreeView/LoadDataOnDemand/description.md
  JSDemos/menuMeta.json
Labels: 21_1

#1041 TreeView Load Data on Demand: rewrite (#1002)
  JSDemos/Demos/TreeView/LoadDataOnDemand/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#1045 exceljs.export: add comment for file-saver-es
  JSDemos/Demos/DataGrid/ExcelJS/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJS/React/App.js
  JSDemos/Demos/DataGrid/ExcelJS/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSExportImages/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSExportImages/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSExportImages/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSExportMultipleGrids/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSExportMultipleGrids/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSExportMultipleGrids/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSOverview/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSOverview/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSOverview/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJSOverview/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Vue/App.vue
Labels: 21_2

#1043 Update Scheduler-WebAPIService etalon
  testing/etalons/Scheduler-WebAPIService.png
Labels: 21_2

#1048 Scheduler - Remove extra method from the Angular time zones demo
  JSDemos/Demos/Scheduler/TimeZonesSupport/Angular/app/app.component.ts
Labels: 20_2

#980 Rewrite Scheduler ContextMenu integration Demo whithout using e.component
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/App.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/MenuItems.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/App.vue
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/MenuItems.js
Labels: 21_2

#1049 treelist - fixes lookup config in editing demos for Angular
  JSDemos/Demos/TreeList/FormEditing/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/PopupEditing/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/RowEditing/Angular/app/app.component.ts
Labels: 21_2

#1050 treelist - fixes lookup config in editing demos for Angular (#1049)
  JSDemos/Demos/TreeList/FormEditing/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/PopupEditing/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/RowEditing/Angular/app/app.component.ts
Labels: 21_1, cherry-pick

#1055 Change credit to wikipedia/kaggle in some demos
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#1056 Change credit to wikipedia/kaggle in some demos
  JSDemos/menuMeta.json
Labels: 20_2, cherry-pick

#1054 Change credit to wikipedia/kaggle in some demos
  JSDemos/menuMeta.json
Labels: 21_2

#1057 List Demos small updates
  JSDemos/Demos/List/ItemDragging/Angular/app/app.component.html
  JSDemos/Demos/List/ItemDragging/React/App.js
  JSDemos/Demos/List/ItemDragging/Vue/App.vue
  JSDemos/Demos/List/ItemDragging/jQuery/index.js
  JSDemos/Demos/List/ItemTemplate/Angular/app/app.component.html
  JSDemos/Demos/List/ListEditingAndAPI/Angular/app/app.component.css
  JSDemos/Demos/List/ListEditingAndAPI/Angular/app/app.component.html
  JSDemos/Demos/List/ListEditingAndAPI/Angular/app/app.component.ts
  JSDemos/Demos/List/ListEditingAndAPI/AngularJS/index.html
  JSDemos/Demos/List/ListEditingAndAPI/AngularJS/index.js
  JSDemos/Demos/List/ListEditingAndAPI/AngularJS/styles.css
  JSDemos/Demos/List/ListEditingAndAPI/Knockout/index.html
  JSDemos/Demos/List/ListEditingAndAPI/Knockout/index.js
  JSDemos/Demos/List/ListEditingAndAPI/Knockout/styles.css
  JSDemos/Demos/List/ListEditingAndAPI/React/App.js
  JSDemos/Demos/List/ListEditingAndAPI/React/styles.css
  JSDemos/Demos/List/ListEditingAndAPI/Vue/App.vue
  JSDemos/Demos/List/ListEditingAndAPI/jQuery/index.html
  JSDemos/Demos/List/ListEditingAndAPI/jQuery/index.js
  JSDemos/Demos/List/ListEditingAndAPI/jQuery/styles.css
  JSDemos/Demos/List/ListWithSearchBar/Angular/app/app.component.html
  JSDemos/Demos/List/ListWithSearchBar/AngularJS/index.js
  JSDemos/Demos/List/ListWithSearchBar/Knockout/index.js
  JSDemos/Demos/List/ListWithSearchBar/React/App.js
  JSDemos/Demos/List/ListWithSearchBar/Vue/App.vue
  JSDemos/Demos/List/ListWithSearchBar/jQuery/index.js
  JSDemos/Demos/List/WebAPI/Angular/app/app.component.ts
  JSDemos/Demos/List/WebAPI/React/App.js
  JSDemos/Demos/List/WebAPI/Vue/App.vue
  JSDemos/Demos/List/WebAPI/jQuery/index.js
  MVCDemos/Content/DemosStyles/List/ListEditingAndAPI.css
  MVCDemos/Views/List/ListEditingAndAPI.cshtml
  MVCDemos/Views/List/ListWithSearchBar.cshtml
  MVCDemos/Views/List/WebApi.cshtml
  NetCoreDemos/Views/List/ListEditingAndAPI.cshtml
  NetCoreDemos/Views/List/ListWithSearchBar.cshtml
  NetCoreDemos/Views/List/WebApi.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/List/ListEditingAndAPI.css
Labels: 20_2

#1058 List Demos small updates
  JSDemos/Demos/List/ItemDragging/Angular/app/app.component.html
  JSDemos/Demos/List/ItemDragging/React/App.js
  JSDemos/Demos/List/ItemDragging/Vue/App.vue
  JSDemos/Demos/List/ItemDragging/jQuery/index.js
  JSDemos/Demos/List/ItemTemplate/Angular/app/app.component.html
  JSDemos/Demos/List/ListEditingAndAPI/Angular/app/app.component.css
  JSDemos/Demos/List/ListEditingAndAPI/Angular/app/app.component.html
  JSDemos/Demos/List/ListEditingAndAPI/Angular/app/app.component.ts
  JSDemos/Demos/List/ListEditingAndAPI/AngularJS/index.html
  JSDemos/Demos/List/ListEditingAndAPI/AngularJS/index.js
  JSDemos/Demos/List/ListEditingAndAPI/AngularJS/styles.css
  JSDemos/Demos/List/ListEditingAndAPI/Knockout/index.html
  JSDemos/Demos/List/ListEditingAndAPI/Knockout/index.js
  JSDemos/Demos/List/ListEditingAndAPI/Knockout/styles.css
  JSDemos/Demos/List/ListEditingAndAPI/React/App.js
  JSDemos/Demos/List/ListEditingAndAPI/React/styles.css
  JSDemos/Demos/List/ListEditingAndAPI/Vue/App.vue
  JSDemos/Demos/List/ListEditingAndAPI/jQuery/index.html
  JSDemos/Demos/List/ListEditingAndAPI/jQuery/index.js
  JSDemos/Demos/List/ListEditingAndAPI/jQuery/styles.css
  JSDemos/Demos/List/ListWithSearchBar/Angular/app/app.component.html
  JSDemos/Demos/List/ListWithSearchBar/AngularJS/index.js
  JSDemos/Demos/List/ListWithSearchBar/Knockout/index.js
  JSDemos/Demos/List/ListWithSearchBar/React/App.js
  JSDemos/Demos/List/ListWithSearchBar/Vue/App.vue
  JSDemos/Demos/List/ListWithSearchBar/jQuery/index.js
  JSDemos/Demos/List/WebAPI/Angular/app/app.component.ts
  JSDemos/Demos/List/WebAPI/React/App.js
  JSDemos/Demos/List/WebAPI/Vue/App.vue
  JSDemos/Demos/List/WebAPI/jQuery/index.js
  MVCDemos/Content/DemosStyles/List/ListEditingAndAPI.css
  MVCDemos/Views/List/ListEditingAndAPI.cshtml
  MVCDemos/Views/List/ListWithSearchBar.cshtml
  MVCDemos/Views/List/WebApi.cshtml
  NetCoreDemos/Views/List/ListEditingAndAPI.cshtml
  NetCoreDemos/Views/List/ListWithSearchBar.cshtml
  NetCoreDemos/Views/List/WebApi.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/List/ListEditingAndAPI.css
Labels: 21_1, cherry-pick

#1059 List Demos small updates
  JSDemos/Demos/List/ItemDragging/Angular/app/app.component.html
  JSDemos/Demos/List/ItemDragging/React/App.js
  JSDemos/Demos/List/ItemDragging/Vue/App.vue
  JSDemos/Demos/List/ItemDragging/jQuery/index.js
  JSDemos/Demos/List/ItemTemplate/Angular/app/app.component.html
  JSDemos/Demos/List/ListEditingAndAPI/Angular/app/app.component.css
  JSDemos/Demos/List/ListEditingAndAPI/Angular/app/app.component.html
  JSDemos/Demos/List/ListEditingAndAPI/Angular/app/app.component.ts
  JSDemos/Demos/List/ListEditingAndAPI/AngularJS/index.html
  JSDemos/Demos/List/ListEditingAndAPI/AngularJS/index.js
  JSDemos/Demos/List/ListEditingAndAPI/AngularJS/styles.css
  JSDemos/Demos/List/ListEditingAndAPI/Knockout/index.html
  JSDemos/Demos/List/ListEditingAndAPI/Knockout/index.js
  JSDemos/Demos/List/ListEditingAndAPI/Knockout/styles.css
  JSDemos/Demos/List/ListEditingAndAPI/React/App.js
  JSDemos/Demos/List/ListEditingAndAPI/React/styles.css
  JSDemos/Demos/List/ListEditingAndAPI/Vue/App.vue
  JSDemos/Demos/List/ListEditingAndAPI/jQuery/index.html
  JSDemos/Demos/List/ListEditingAndAPI/jQuery/index.js
  JSDemos/Demos/List/ListEditingAndAPI/jQuery/styles.css
  JSDemos/Demos/List/ListWithSearchBar/Angular/app/app.component.html
  JSDemos/Demos/List/ListWithSearchBar/AngularJS/index.js
  JSDemos/Demos/List/ListWithSearchBar/Knockout/index.js
  JSDemos/Demos/List/ListWithSearchBar/React/App.js
  JSDemos/Demos/List/ListWithSearchBar/Vue/App.vue
  JSDemos/Demos/List/ListWithSearchBar/jQuery/index.js
  JSDemos/Demos/List/WebAPI/Angular/app/app.component.ts
  JSDemos/Demos/List/WebAPI/React/App.js
  JSDemos/Demos/List/WebAPI/Vue/App.vue
  JSDemos/Demos/List/WebAPI/jQuery/index.js
  MVCDemos/Content/DemosStyles/List/ListEditingAndAPI.css
  MVCDemos/Views/List/ListEditingAndAPI.cshtml
  MVCDemos/Views/List/ListWithSearchBar.cshtml
  MVCDemos/Views/List/WebApi.cshtml
  NetCoreDemos/Views/List/ListEditingAndAPI.cshtml
  NetCoreDemos/Views/List/ListWithSearchBar.cshtml
  NetCoreDemos/Views/List/WebApi.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/List/ListEditingAndAPI.css
  testing/etalons/List-ListEditingAndAPI.png
Labels: 21_2

#1063 dxScheduler - remove unnecessary config from Group Orientation demo
  JSDemos/Demos/Scheduler/GroupOrientation/React/App.js
Labels: 21_2

#1014 TreeView with Search Bar: rewrite
  JSDemos/Demos/TreeView/TreeViewWithSearchBar/description.md
  JSDemos/menuMeta.json
Labels: 21_1

#1065 TreeView with Search Bar: rewrite (#1014)
  JSDemos/Demos/TreeView/TreeViewWithSearchBar/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#1069 Fix type casting in stackedbar demo for MVC approach
  NetCoreDemos/Views/Charts/StackedBar.cshtml
Labels: 21_2

#1071 Fix type casting in stackedbar demo for MVC approach
  MVCDemos/Views/Charts/StackedBar.cshtml
Labels: 21_2

#1073 Scheduler - CurrentTimeIndicator demo - Increase timeout in test code before screenshot
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/test-code.js
Labels: 21_2

#1074 update data for stepline demo
  JSDemos/Demos/Charts/StepLine/Angular/app/app.service.ts
  JSDemos/Demos/Charts/StepLine/AngularJS/data.js
  JSDemos/Demos/Charts/StepLine/Knockout/data.js
  JSDemos/Demos/Charts/StepLine/React/data.js
  JSDemos/Demos/Charts/StepLine/Vue/data.js
  JSDemos/Demos/Charts/StepLine/jQuery/data.js
  testing/etalons/Charts-StepLine.png
Labels: 21_2

#1077 Fix object literals in DataGrid Filtering Vue demo
  JSDemos/Demos/DataGrid/Filtering/Vue/App.vue
Labels: 21_1, cherry-pick

#1078 Fix object literals in DataGrid Filtering Vue demo
  JSDemos/Demos/DataGrid/Filtering/Vue/App.vue
Labels: 21_2

#1080 dxScheduler - Implement server-side demos for DND
  MVCDemos/Content/DemosStyles/Scheduler/CustomDragAndDrop.css
  MVCDemos/Controllers/SchedulerController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/SampleData/DragAndDropAppointments.cs
  MVCDemos/Views/Scheduler/CustomDragAndDrop.cshtml
  NetCoreDemos/Controllers/SchedulerController.cs
  NetCoreDemos/Models/SampleData/DragAndDropAppointments.cs
  NetCoreDemos/Views/Scheduler/CustomDragAndDrop.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/CustomDragAndDrop.css
Labels: 21_2

#1075 TreeList: Fix reordering to first position of another parent (T1014312)
  JSDemos/Demos/TreeList/LocalReordering/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/LocalReordering/React/App.js
  JSDemos/Demos/TreeList/LocalReordering/Vue/App.vue
  JSDemos/Demos/TreeList/LocalReordering/jQuery/index.js
  MVCDemos/Views/TreeList/LocalReordering.cshtml
  NetCoreDemos/Views/TreeList/LocalReordering.cshtml
Labels: 21_1, cherry-pick

#1076 TreeList: Fix reordering to first position of another parent (T1014312)
  JSDemos/Demos/TreeList/LocalReordering/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/LocalReordering/React/App.js
  JSDemos/Demos/TreeList/LocalReordering/Vue/App.vue
  JSDemos/Demos/TreeList/LocalReordering/jQuery/index.js
  MVCDemos/Views/TreeList/LocalReordering.cshtml
  NetCoreDemos/Views/TreeList/LocalReordering.cshtml
Labels: 21_2

#1082 dxScheduler - Add AllDayExpr option in serve-side demos for DND
  MVCDemos/Views/Scheduler/CustomDragAndDrop.cshtml
  NetCoreDemos/Views/Scheduler/CustomDragAndDrop.cshtml
Labels: 21_2

#1085 dxScheduler - Replace screenshots for scheduler with new toolbar
  testing/etalons/Scheduler-Adaptability.png
  testing/etalons/Scheduler-Agenda.png
  testing/etalons/Scheduler-BasicViews.png
  testing/etalons/Scheduler-CellTemplates.png
  testing/etalons/Scheduler-ContextMenuIntegration.png
  testing/etalons/Scheduler-CurrentTimeIndicator.png
  testing/etalons/Scheduler-CustomDragAndDrop.png
  testing/etalons/Scheduler-CustomTemplates.png
  testing/etalons/Scheduler-CustomizeIndividualViews.png
  testing/etalons/Scheduler-Editing.png
  testing/etalons/Scheduler-GoogleCalendarIntegration.png
  testing/etalons/Scheduler-GroupByDate.png
  testing/etalons/Scheduler-GroupOrientation.png
  testing/etalons/Scheduler-IncreaseViewDuration.png
  testing/etalons/Scheduler-LimitAppointmentCountPerCell.png
  testing/etalons/Scheduler-Overview.png
  testing/etalons/Scheduler-RecurringAppointments.png
  testing/etalons/Scheduler-Resources.png
  testing/etalons/Scheduler-SignalRService.png
  testing/etalons/Scheduler-SimpleArray.png
  testing/etalons/Scheduler-TimeZonesSupport.png
  testing/etalons/Scheduler-Timelines.png
  testing/etalons/Scheduler-VirtualScrolling.png
  testing/etalons/Scheduler-WebAPIService.png
  testing/widgets/ scheduler/etalons/scheduler_contextMenu_cell_click.png
  testing/widgets/ scheduler/etalons/scheduler_contextMenu_click.png
  testing/widgets/ scheduler/etalons/scheduler_contextMenu_header_click.png
  testing/widgets/ scheduler/etalons/scheduler_contextMenu_init.png
Labels: 21_2

#1086 dxScheduler - Rewrite angular demo for virtual scrolling using nested
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/VirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/App.vue
Labels: 21_1, cherry-pick

#1083 dxScheduler - Rewrite angular demo for virtual scrolling using nested
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/VirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/App.vue
Labels: 21_2

#1084 Add metadata testing
  JSDemos/menuMeta.json
  utils/tests/test-menu-meta.test.js
Labels: 21_2

#1087 Add metadata testing (#1084)
  JSDemos/menuMeta.json
  utils/tests/test-menu-meta.test.js
Labels: 21_1, cherry-pick

#1089 TreeList: Fix LocalReodering vue demo after T1014312
  JSDemos/Demos/TreeList/LocalReordering/Vue/App.vue
Labels: 21_2

#1088 TreeList: Fix LocalReodering vue demo after T1014312
  JSDemos/Demos/TreeList/LocalReordering/Vue/App.vue
Labels: 21_1, cherry-pick

#1092 dxScheduler - Fix dates for overview demo
  JSDemos/Demos/Scheduler/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/Overview/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Overview/AngularJS/data.js
  JSDemos/Demos/Scheduler/Overview/AngularJS/index.js
  JSDemos/Demos/Scheduler/Overview/React/App.js
  JSDemos/Demos/Scheduler/Overview/React/data.js
  JSDemos/Demos/Scheduler/Overview/Vue/App.vue
  JSDemos/Demos/Scheduler/Overview/Vue/data.js
  JSDemos/Demos/Scheduler/Overview/jQuery/data.js
  JSDemos/Demos/Scheduler/Overview/jQuery/index.js
  MVCDemos/Models/SampleData/Workouts.cs
  MVCDemos/Views/Scheduler/Overview.cshtml
  NetCoreDemos/Models/SampleData/Workouts.cs
  NetCoreDemos/Views/Scheduler/Overview.cshtml
  testing/etalons/Scheduler-Overview.png
Labels: 21_2

#1093 dxScheduler - Fix dates for overview demo
  JSDemos/Demos/Scheduler/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/Overview/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Overview/AngularJS/data.js
  JSDemos/Demos/Scheduler/Overview/AngularJS/index.js
  JSDemos/Demos/Scheduler/Overview/React/App.js
  JSDemos/Demos/Scheduler/Overview/React/data.js
  JSDemos/Demos/Scheduler/Overview/Vue/App.vue
  JSDemos/Demos/Scheduler/Overview/Vue/data.js
  JSDemos/Demos/Scheduler/Overview/jQuery/data.js
  JSDemos/Demos/Scheduler/Overview/jQuery/index.js
  MVCDemos/Models/SampleData/Workouts.cs
  MVCDemos/Views/Scheduler/Overview.cshtml
  NetCoreDemos/Models/SampleData/Workouts.cs
  NetCoreDemos/Views/Scheduler/Overview.cshtml
Labels: 21_1, cherry-pick

#1094 dxScheduler - Fix dates for overview demo
  JSDemos/Demos/Scheduler/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/Overview/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Overview/AngularJS/data.js
  JSDemos/Demos/Scheduler/Overview/AngularJS/index.js
  JSDemos/Demos/Scheduler/Overview/React/App.js
  JSDemos/Demos/Scheduler/Overview/React/data.js
  JSDemos/Demos/Scheduler/Overview/Vue/App.vue
  JSDemos/Demos/Scheduler/Overview/Vue/data.js
  JSDemos/Demos/Scheduler/Overview/jQuery/data.js
  JSDemos/Demos/Scheduler/Overview/jQuery/index.js
  MVCDemos/Models/SampleData/Workouts.cs
  MVCDemos/Views/Scheduler/Overview.cshtml
  NetCoreDemos/Models/SampleData/Workouts.cs
  NetCoreDemos/Views/Scheduler/Overview.cshtml
Labels: 20_2, cherry-pick

#1095 Fix React test: Scheduler-CurrentTimeIndicator
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/test-code.js
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/visualtestrc.json
Labels: 21_2

#1097 Scheduler - Disabled Dates: Update the description
  JSDemos/Demos/Scheduler/CellTemplates/description.md
Labels: 21_1

#1098 Scheduler - Disabled Dates: Update the description
  JSDemos/Demos/Scheduler/CellTemplates/description.md
Labels: 21_2, cherry-pick

#1091 HtmlEditor demos - use bindings instead of adding content directly to markup (T1003792)
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.component.ts
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.service.ts
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/data.js
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/data.js
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/index.js
  JSDemos/Demos/HtmlEditor/Overview/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/Overview/Angular/app/app.component.ts
  JSDemos/Demos/HtmlEditor/Overview/Angular/app/app.service.ts
  JSDemos/Demos/HtmlEditor/Overview/AngularJS/data.js
  JSDemos/Demos/HtmlEditor/Overview/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/Overview/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/Overview/jQuery/data.js
  JSDemos/Demos/HtmlEditor/Overview/jQuery/index.html
  JSDemos/Demos/HtmlEditor/Overview/jQuery/index.js
  JSDemos/Demos/HtmlEditor/Tables/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/Tables/Angular/app/app.component.ts
  JSDemos/Demos/HtmlEditor/Tables/Angular/app/app.service.ts
  JSDemos/Demos/HtmlEditor/Tables/AngularJS/data.js
  JSDemos/Demos/HtmlEditor/Tables/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/Tables/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/Tables/AngularJS/styles.css
  JSDemos/Demos/HtmlEditor/Tables/jQuery/data.js
  JSDemos/Demos/HtmlEditor/Tables/jQuery/index.html
  JSDemos/Demos/HtmlEditor/Tables/jQuery/index.js
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/Angular/app/app.component.ts
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/Angular/app/app.service.ts
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/AngularJS/data.js
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/jQuery/data.js
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/jQuery/index.html
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/jQuery/index.js
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  MVCDemos/Views/HtmlEditor/Overview.cshtml
  MVCDemos/Views/HtmlEditor/Tables.cshtml
  MVCDemos/Views/HtmlEditor/ToolbarCustomization.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/Overview.cshtml
  NetCoreDemos/Views/HtmlEditor/Tables.cshtml
  NetCoreDemos/Views/HtmlEditor/ToolbarCustomization.cshtml
Labels: 21_1

#1103 HtmlEditor demos - use bindings instead of adding content directly to markup (T1003792)
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.component.ts
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.service.ts
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/data.js
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/data.js
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/index.js
  JSDemos/Demos/HtmlEditor/Overview/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/Overview/Angular/app/app.component.ts
  JSDemos/Demos/HtmlEditor/Overview/Angular/app/app.service.ts
  JSDemos/Demos/HtmlEditor/Overview/AngularJS/data.js
  JSDemos/Demos/HtmlEditor/Overview/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/Overview/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/Overview/jQuery/data.js
  JSDemos/Demos/HtmlEditor/Overview/jQuery/index.html
  JSDemos/Demos/HtmlEditor/Overview/jQuery/index.js
  JSDemos/Demos/HtmlEditor/Tables/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/Tables/Angular/app/app.component.ts
  JSDemos/Demos/HtmlEditor/Tables/Angular/app/app.service.ts
  JSDemos/Demos/HtmlEditor/Tables/AngularJS/data.js
  JSDemos/Demos/HtmlEditor/Tables/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/Tables/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/Tables/AngularJS/styles.css
  JSDemos/Demos/HtmlEditor/Tables/jQuery/data.js
  JSDemos/Demos/HtmlEditor/Tables/jQuery/index.html
  JSDemos/Demos/HtmlEditor/Tables/jQuery/index.js
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/Angular/app/app.component.ts
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/Angular/app/app.service.ts
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/AngularJS/data.js
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/jQuery/data.js
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/jQuery/index.html
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/jQuery/index.js
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  MVCDemos/Views/HtmlEditor/Overview.cshtml
  MVCDemos/Views/HtmlEditor/Tables.cshtml
  MVCDemos/Views/HtmlEditor/ToolbarCustomization.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/Overview.cshtml
  NetCoreDemos/Views/HtmlEditor/Tables.cshtml
  NetCoreDemos/Views/HtmlEditor/ToolbarCustomization.cshtml
Labels: 21_2, cherry-pick

#1104 TagBox: fix issue with Tag Count Limitation Angular Demo (T1017708)
  JSDemos/Demos/TagBox/TagCountLimitation/Angular/app/app.component.html
  JSDemos/Demos/TagBox/TagCountLimitation/Angular/app/app.component.ts
Labels: 21_1, cherry-pick

#1105 TagBox: fix issue with Tag Count Limitation Angular Demo (T1017708)
  JSDemos/Demos/TagBox/TagCountLimitation/Angular/app/app.component.html
  JSDemos/Demos/TagBox/TagCountLimitation/Angular/app/app.component.ts
Labels: 20_2, cherry-pick
