Repository DevExpress/devextreme-demos, pull requests merged in 2021-06, with the labels that each got.

#942 dxScheduler - refactor resources and agenda demos
  .eslintrc.js
  JSDemos/Demos/Scheduler/Agenda/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/Agenda/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/Agenda/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Agenda/AngularJS/data.js
  JSDemos/Demos/Scheduler/Agenda/AngularJS/index.js
  JSDemos/Demos/Scheduler/Agenda/React/App.js
  JSDemos/Demos/Scheduler/Agenda/React/data.js
  JSDemos/Demos/Scheduler/Agenda/Vue/App.vue
  JSDemos/Demos/Scheduler/Agenda/Vue/data.js
  JSDemos/Demos/Scheduler/Agenda/jQuery/data.js
  JSDemos/Demos/Scheduler/Agenda/jQuery/index.js
  JSDemos/Demos/Scheduler/Resources/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/Resources/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/Resources/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Resources/AngularJS/data.js
  JSDemos/Demos/Scheduler/Resources/AngularJS/index.js
  JSDemos/Demos/Scheduler/Resources/Knockout/data.js
  JSDemos/Demos/Scheduler/Resources/Knockout/index.js
  JSDemos/Demos/Scheduler/Resources/React/App.js
  JSDemos/Demos/Scheduler/Resources/React/data.js
  JSDemos/Demos/Scheduler/Resources/Vue/App.vue
  JSDemos/Demos/Scheduler/Resources/Vue/data.js
  JSDemos/Demos/Scheduler/Resources/jQuery/data.js
  JSDemos/Demos/Scheduler/Resources/jQuery/index.js
  MVCDemos/Controllers/SchedulerController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/AppointmentWithResources.cs
  MVCDemos/Models/AssigneeResource.cs
  MVCDemos/Models/SampleData/AgendaTasks.cs
  MVCDemos/Models/SampleData/AppointmentsWithResources.cs
  MVCDemos/Models/SampleData/AssigneeResources.cs
  MVCDemos/ViewModels/SchedulerResourcesViewModel.cs
  MVCDemos/Views/Scheduler/Agenda.cshtml
  MVCDemos/Views/Scheduler/Resources.cshtml
  NetCoreDemos/Controllers/SchedulerController.cs
  NetCoreDemos/Models/AppointmentWithResources.cs
  NetCoreDemos/Models/AssigneeResource.cs
  NetCoreDemos/Models/SampleData/AgendaTasks.cs
  NetCoreDemos/Models/SampleData/AppointmentsWithResources.cs
  NetCoreDemos/Models/SampleData/AssigneeResources.cs
  NetCoreDemos/ViewModels/SchedulerResourcesViewModel.cs
  NetCoreDemos/Views/Scheduler/Agenda.cshtml
  NetCoreDemos/Views/Scheduler/Resources.cshtml
Labels: 21_2, cherry-pick

#943 DataGrid - fix button order in CellEditing demo in MVC and netcore
  MVCDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  NetCoreDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
Labels: 21_1

#947 Fix lint issues
  .github/workflows/CI.yml
  MVCDemos/Views/Gantt/ExportToPDF.cshtml
  MVCDemos/Views/Popup/Overview.cshtml
  NetCoreDemos/Controllers/RemoteValidationController.cs
  NetCoreDemos/Views/Gantt/ExportToPDF.cshtml
  NetCoreDemos/Views/Popup/Overview.cshtml
  package.json
Labels: 21_1

#951 Fix linter issues
  .github/workflows/CI.yml
  MVCDemos/Views/Popup/Overview.cshtml
  NetCoreDemos/Controllers/RemoteValidationController.cs
  NetCoreDemos/Views/Popup/Overview.cshtml
  package.json
Labels: 21_2, cherry-pick

#945 dxScheduler - fix currentDate for SimpleArray demo
  MVCDemos/Views/Scheduler/SimpleArray.cshtml
  NetCoreDemos/Views/Scheduler/SimpleArray.cshtml
Labels: 21_2

#952 dxScheduler - fix imports in menuMeta.json
  JSDemos/menuMeta.json
Labels: 21_1

#954 dxScheduler - fix imports in menuMeta.json
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#897 Scheduler Custom Templates: rewrite
  JSDemos/Demos/Scheduler/CustomTemplates/description.md
  JSDemos/menuMeta.json
Labels: 20_2

#959 Scheduler - Screenshot tester should wait appointments to appear from both schedulers in Signal-R demo
  JSDemos/Demos/Scheduler/SignalRService/test-code.js
Labels: 21_2

#961 Scheduler Custom Templates: rewrite
  JSDemos/Demos/Scheduler/CustomTemplates/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#960 Scheduler Custom Templates: rewrite
  JSDemos/Demos/Scheduler/CustomTemplates/description.md
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#957 TreeList Filter Row: replace quotes with <i></i>
  JSDemos/Demos/TreeList/UsingFilterRow/description.md
Labels: 21_2, cherry-pick

#956 TreeList Filter Row: replace quotes with <i></i>
  JSDemos/Demos/TreeList/UsingFilterRow/description.md
Labels: 21_1, cherry-pick

#955 TreeList Filter Row: replace quotes with <i></i>
  JSDemos/Demos/TreeList/UsingFilterRow/description.md
Labels: 20_2

#877 Scheduler Grouping: rewrite
  JSDemos/Demos/Scheduler/GroupOrientation/description.md
  JSDemos/menuMeta.json
Labels: 20_2

#962 Scheduler Grouping: rewrite (#877)
  JSDemos/Demos/Scheduler/GroupOrientation/description.md
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#963 Scheduler Grouping: rewrite (#877)
  JSDemos/Demos/Scheduler/GroupOrientation/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#872 Scheduler Resources demo: rewrite
  JSDemos/Demos/Scheduler/Resources/description.md
  JSDemos/menuMeta.json
Labels: 20_2

#964 Scheduler Resources demo: rewrite (#872)
  JSDemos/Demos/Scheduler/Resources/description.md
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#965 Scheduler Resources demo: rewrite
  JSDemos/Demos/Scheduler/Resources/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#953 DataGrid - fix IE for CellEditing Demo
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/jQuery/index.js
Labels: 21_1

#948 Fix underscore package version
  package.json
Labels: 21_1

#912 Scheduler Customize Individual Views: rewrite
  JSDemos/Demos/Scheduler/CustomizeIndividualViews/description.md
Labels: 21_1

#967 Scheduler Customize Individual Views: rewrite
  JSDemos/Demos/Scheduler/CustomizeIndividualViews/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#958 Fix linter issues
  .github/workflows/CI.yml
  MVCDemos/Views/Popup/Overview.cshtml
  NetCoreDemos/Controllers/RemoteValidationController.cs
  NetCoreDemos/Views/Popup/Overview.cshtml
  package.json
Labels: 20_2

#969 Master-detail Angular demos - Added folders for custom components
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/detail-view/detail-view.component.css
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/detail-view/detail-view.component.html
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/detail-view/detail-view.component.ts
  JSDemos/Demos/DataGrid/MasterDetailView/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/MasterDetailView/Angular/app/detail-grid/detail-grid.component.css
  JSDemos/Demos/DataGrid/MasterDetailView/Angular/app/detail-grid/detail-grid.component.html
  JSDemos/Demos/DataGrid/MasterDetailView/Angular/app/detail-grid/detail-grid.component.ts
  JSDemos/Demos/DataGrid/WebAPIService/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/WebAPIService/Angular/app/detail-grid/detail-grid.component.css
  JSDemos/Demos/DataGrid/WebAPIService/Angular/app/detail-grid/detail-grid.component.html
  JSDemos/Demos/DataGrid/WebAPIService/Angular/app/detail-grid/detail-grid.component.ts
Labels: 21_2, cherry-pick

#973 fix MVC Validation demo iframe run (T1004392)
  MVCDemos/Global.asax.cs
Labels: 21_1

#974 fix MVC Validation demo iframe run (T1004392)
  MVCDemos/Global.asax.cs
Labels: 21_2, cherry-pick

#976 Update vDom package
  package.json
Labels: 21_1

#975 Update vDom package
  package.json
Labels: 21_2

#981 workflow-improvements
  README.md
  package.json
  utils/interactive/launch-demo.js
Labels: 21_2

#935 TreeView Hierarchical Data Structure: rewrite
  JSDemos/Demos/TreeView/HierarchicalDataStructure/description.md
  JSDemos/menuMeta.json
Labels: 21_1

#983 TreeView Hierarchical Data Structure: rewrite (#935)
  JSDemos/Demos/TreeView/HierarchicalDataStructure/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#984 dxScheduler - remove globalize from 'custom template' demo
  JSDemos/Demos/Scheduler/CustomTemplates/React/AppointmentTooltip.js
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/AppointmentTooltipTemplate.vue
Labels: 21_1

#985 dxScheduler - remove globalize from 'custom template' demo
  JSDemos/Demos/Scheduler/CustomTemplates/React/AppointmentTooltip.js
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/AppointmentTooltipTemplate.vue
Labels: 21_2, cherry-pick

#978 TreeList - Row "data" property is missing (T1004318)
  JSDemos/Demos/TreeList/LocalReordering/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/LocalReordering/React/App.js
  JSDemos/Demos/TreeList/LocalReordering/Vue/App.vue
  JSDemos/Demos/TreeList/LocalReordering/jQuery/index.js
  MVCDemos/Views/TreeList/LocalReordering.cshtml
  NetCoreDemos/Views/TreeList/LocalReordering.cshtml
Labels: 21_1

#979 TreeList - Row "data" property is missing (T1004318)
  JSDemos/Demos/TreeList/LocalReordering/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/LocalReordering/React/App.js
  JSDemos/Demos/TreeList/LocalReordering/Vue/App.vue
  JSDemos/Demos/TreeList/LocalReordering/jQuery/index.js
  MVCDemos/Views/TreeList/LocalReordering.cshtml
  NetCoreDemos/Views/TreeList/LocalReordering.cshtml
Labels: 21_2, cherry-pick

#987 TreeView Plain Data Structure: rewrite (#970)
  JSDemos/Demos/TreeView/FlatDataStructure/description.md
Labels: 21_2, cherry-pick

#878 Scheduler Group by Date: rewrite
  JSDemos/Demos/Scheduler/GroupByDate/description.md
  JSDemos/menuMeta.json
Labels: 20_2

#994 Fix DialogsAndNotifications testcafe tests (jQuery)
  JSDemos/Demos/Common/DialogsAndNotificationsOverview/jQuery/index.js
Labels: 21_1

#971 Fix underscore package version
  package.json
Labels: 21_2, cherry-pick

#995 temp: run workflow every hour
  .github/workflows/testcafe_tests.yml
Labels: 21_2

#993 Scheduler Group by Date: rewrite (#878)
  JSDemos/Demos/Scheduler/GroupByDate/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#992 Scheduler Group by Date: rewrite (#878)
  JSDemos/Demos/Scheduler/GroupByDate/description.md
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#996 Fix unstable tests for SignalR demos
  JSDemos/Demos/Charts/SignalRService/test-code.js
  JSDemos/Demos/DataGrid/SignalRService/test-code.js
Labels: 21_2

#1003 TreeList: Fix LoadOnDemand screenshot tests for mvc core
  JSDemos/Demos/TreeList/LoadDataOnDemand/test-code.js
Labels: 21_2

#1005 Fix visualRange updating. Load on demand chart demo
  JSDemos/Demos/Charts/LoadDataOnDemand/Angular/app/app.component.ts
Labels: 21_2

#1006 Fix visualRange updating. Load on demand chart demo
  JSDemos/Demos/Charts/LoadDataOnDemand/Angular/app/app.component.ts
Labels: 20_2, cherry-pick

#1007 Fix visualRange updating. Load on demand chart demo
  JSDemos/Demos/Charts/LoadDataOnDemand/Angular/app/app.component.ts
Labels: 21_1, cherry-pick

#1009 Update vDom package
  package.json
Labels: 21_2

#1011 Fix diplsay demos in MVC project
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/Shared/_DocumentDomain.cshtml
  MVCDemos/Views/Shared/_Layout.cshtml
Labels: 21_1

#999 dxScheduler - init target property in dxMenu
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/ContextMenuIntegration/AngularJS/index.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/App.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/App.vue
  JSDemos/Demos/Scheduler/ContextMenuIntegration/jQuery/index.js
  MVCDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  NetCoreDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  testing/widgets/ scheduler/contextMenuIntegration.test.js
  testing/widgets/ scheduler/etalons/scheduler_contextMenu_cell_click.png
  testing/widgets/ scheduler/etalons/scheduler_contextMenu_click.png
  testing/widgets/ scheduler/etalons/scheduler_contextMenu_header_click.png
  testing/widgets/ scheduler/etalons/scheduler_contextMenu_init.png
Labels: 21_2

#1012 dxScheduler - init target property in dxMenu
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/ContextMenuIntegration/AngularJS/index.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/App.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/App.vue
  JSDemos/Demos/Scheduler/ContextMenuIntegration/jQuery/index.js
  MVCDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  NetCoreDemos/Views/Scheduler/ContextMenuIntegration.cshtml
Labels: 21_1, cherry-pick

#988 TreeView Virtual Mode: rewrite
  JSDemos/Demos/TreeView/VirtualMode/description.md
  JSDemos/menuMeta.json
Labels: 21_1

#1015 DropDownBox multiple selection: Fix event handlers for the Angular demo (T1007700)
  JSDemos/Demos/DropDownBox/MultipleSelection/Angular/app/app.component.html
  JSDemos/Demos/DropDownBox/MultipleSelection/Angular/app/app.component.ts
Labels: 21_2

#1017 DropDownBox multiple selection: Fix event handlers for the Angular demo (T1007700)
  JSDemos/Demos/DropDownBox/MultipleSelection/Angular/app/app.component.html
  JSDemos/Demos/DropDownBox/MultipleSelection/Angular/app/app.component.ts
Labels: 21_1, cherry-pick

#1016 TreeView Virtual Mode: rewrite (#988)
  JSDemos/Demos/TreeView/VirtualMode/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#1010 treelist - fixes rootValue for angular (#1008)
  JSDemos/Demos/TreeList/LocalReordering/Angular/app/app.component.html
Labels: 21_2, cherry-pick

#1008 treelist - fixes rootValue for angular
  JSDemos/Demos/TreeList/LocalReordering/Angular/app/app.component.html
Labels: 21_1

#1023 RangeSelector: Fix LogarithmicScale screenshot tests for non-jquery approaches
  JSDemos/Demos/RangeSelector/LogarithmicScale/test-code.js
  testing/etalons/RangeSelector-LogarithmicScale.png
Labels: 21_2

#997 run workflow every hour on weekend only
  .github/workflows/testcafe_tests.yml
Labels: 21_2

#998 PivotGrid: Update Field Chooser demo descriptions
  JSDemos/Demos/PivotGrid/IntegratedFieldChooser/description.md
  JSDemos/Demos/PivotGrid/StandaloneFieldChooser/description.md
  JSDemos/menuMeta.json
Labels: 21_1

#1028 PivotGrid: Update Field Chooser demo descriptions (#998)
  JSDemos/Demos/PivotGrid/IntegratedFieldChooser/description.md
  JSDemos/Demos/PivotGrid/StandaloneFieldChooser/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#1000 Fix DialogsAndNotifications testcafe tests (jQuery)
  JSDemos/Demos/Common/DialogsAndNotificationsOverview/jQuery/index.js
Labels: 21_2, cherry-pick

#1020 TreeView - Add equals search mode to the Treeview with searchbar demo
  JSDemos/Demos/TreeView/TreeViewWithSearchBar/Angular/app/app.component.html
  JSDemos/Demos/TreeView/TreeViewWithSearchBar/AngularJS/index.js
  JSDemos/Demos/TreeView/TreeViewWithSearchBar/React/App.js
  JSDemos/Demos/TreeView/TreeViewWithSearchBar/Vue/App.vue
  JSDemos/Demos/TreeView/TreeViewWithSearchBar/jQuery/index.js
  MVCDemos/Views/TreeView/TreeViewWithSearchBar.cshtml
  NetCoreDemos/Views/TreeView/TreeViewWithSearchBar.cshtml
Labels: 21_2

#1024 DataGrid — add keyExpr to Overview demo
  JSDemos/Demos/DataGrid/Overview/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/Overview/AngularJS/index.js
  JSDemos/Demos/DataGrid/Overview/React/App.js
  JSDemos/Demos/DataGrid/Overview/Vue/App.vue
  JSDemos/Demos/DataGrid/Overview/jQuery/index.js
  MVCDemos/Views/DataGrid/Overview.cshtml
  NetCoreDemos/Views/DataGrid/Overview.cshtml
Labels: 21_1

#1025 DataGrid — add keyExpr to Overview demo
  JSDemos/Demos/DataGrid/Overview/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/Overview/AngularJS/index.js
  JSDemos/Demos/DataGrid/Overview/React/App.js
  JSDemos/Demos/DataGrid/Overview/Vue/App.vue
  JSDemos/Demos/DataGrid/Overview/jQuery/index.js
  MVCDemos/Views/DataGrid/Overview.cshtml
  NetCoreDemos/Views/DataGrid/Overview.cshtml
Labels: 21_2, cherry-pick

#1026 DataGrid — fix typos in MultipleRecordSelectionAPI demo
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/AngularJS/index.js
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/jQuery/index.html
Labels: 21_1

#1027 DataGrid — fix typos in MultipleRecordSelectionAPI demo
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/AngularJS/index.js
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/jQuery/index.html
Labels: 21_2, cherry-pick

#1034 Fix turndown version
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
Labels: 20_2

#1033 Fix turndown version
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
Labels: 21_1

#1032 Fix turndown version
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
Labels: 21_2

#1035 MVC: Fix set devexpress domain
  MVCDemos/Views/Shared/_DocumentDomain.cshtml
Labels: 21_1

#1037 Fix DialogsAndNotifications/Overview demo
  JSDemos/Demos/Common/DialogsAndNotificationsOverview/jQuery/index.js
Labels: 21_1

#1036 MVC: Fix display demos in MVC project
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/Shared/_DocumentDomain.cshtml
  MVCDemos/Views/Shared/_Layout.cshtml
Labels: 21_2, cherry-pick
