Repository DevExpress/devextreme-demos, pull requests merged in 2021-01, with the labels that each got.

#502 DataGrid - Fix MvcAdditionalFiles for Batch Update Request demo (T960161)
  JSDemos/menuMeta.json
  NetCoreDemos/Controllers/ApiControllers/DataGridWebApiController.cs
Labels: 21_1

#503 DataGrid - Fix MvcAdditionalFiles for Batch Update Request demo (T960161)
  JSDemos/menuMeta.json
  NetCoreDemos/Controllers/ApiControllers/DataGridWebApiController.cs
Labels: 20_2, cherry-pick

#509 dxScheduler - use new Date() in Disable dates demo
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/CellTemplates/React/App.js
  JSDemos/Demos/Scheduler/CellTemplates/React/data.js
  JSDemos/Demos/Scheduler/CellTemplates/Vue/App.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/data.js
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/data.js
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/index.js
  MVCDemos/Models/Appointment.cs
  MVCDemos/Models/SampleData/AppointmentsWorkHours.cs
  MVCDemos/Views/Scheduler/CellTemplates.cshtml
  NetCoreDemos/Models/Appointment.cs
  NetCoreDemos/Models/SampleData/AppointmentsWorkHours.cs
  NetCoreDemos/Views/Scheduler/CellTemplates.cshtml
Labels: 20_2

#510 dxScheduler - use new Date() in Disable dates demo
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/CellTemplates/React/App.js
  JSDemos/Demos/Scheduler/CellTemplates/React/data.js
  JSDemos/Demos/Scheduler/CellTemplates/Vue/App.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/data.js
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/data.js
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/index.js
  MVCDemos/Models/Appointment.cs
  MVCDemos/Models/SampleData/AppointmentsWorkHours.cs
  MVCDemos/Views/Scheduler/CellTemplates.cshtml
  NetCoreDemos/Models/Appointment.cs
  NetCoreDemos/Models/SampleData/AppointmentsWorkHours.cs
  NetCoreDemos/Views/Scheduler/CellTemplates.cshtml
Labels: 21_1, cherry-pick

#511 Replace object literals with outside objects in React DataGrid editing demos
  JSDemos/Demos/DataGrid/FormEditing/React/App.js
  JSDemos/Demos/DataGrid/PopupEditing/React/App.js
Labels: 21_1

#513 Form - fix Validation demo (T962487)
  JSDemos/Demos/Form/Validation/AngularJS/index.js
  JSDemos/Demos/Form/Validation/Knockout/index.js
  JSDemos/Demos/Form/Validation/React/App.js
  JSDemos/Demos/Form/Validation/Vue/App.vue
  JSDemos/Demos/Form/Validation/jQuery/index.js
Labels: 20_2

#514 Form - fix Validation demo (T962487)
  JSDemos/Demos/Form/Validation/AngularJS/index.js
  JSDemos/Demos/Form/Validation/Knockout/index.js
  JSDemos/Demos/Form/Validation/React/App.js
  JSDemos/Demos/Form/Validation/Vue/App.vue
  JSDemos/Demos/Form/Validation/jQuery/index.js
Labels: 21_1, cherry-pick

#512 20_2 Replace object literals with outside objects in React DataGrid editing demos (#511)
  JSDemos/Demos/DataGrid/FormEditing/React/App.js
  JSDemos/Demos/DataGrid/PopupEditing/React/App.js
Labels: 20_2, cherry-pick

#515 Repair the "DataGrid - Overview" demo
  JSDemos/Demos/DataGrid/Overview/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/Overview/AngularJS/index.js
  JSDemos/Demos/DataGrid/Overview/React/App.js
  JSDemos/Demos/DataGrid/Overview/Vue/App.vue
  JSDemos/Demos/DataGrid/Overview/jQuery/index.js
  MVCDemos/Views/DataGrid/Overview.cshtml
  NetCoreDemos/Views/DataGrid/Overview.cshtml
Labels: 21_1

#516 Repair the "DataGrid - Overview" demo (#515)
  JSDemos/Demos/DataGrid/Overview/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/Overview/AngularJS/index.js
  JSDemos/Demos/DataGrid/Overview/React/App.js
  JSDemos/Demos/DataGrid/Overview/Vue/App.vue
  JSDemos/Demos/DataGrid/Overview/jQuery/index.js
  MVCDemos/Views/DataGrid/Overview.cshtml
  NetCoreDemos/Views/DataGrid/Overview.cshtml
Labels: 20_2, cherry-pick

#525 Add tests for child-precess-utils module
  utils/tests/shared/child-process-utils.test.js
Labels: 21_1

#526 Add tests for child-precess-utils module (#525)
  utils/tests/shared/child-process-utils.test.js
Labels: 20_2, cherry-pick

#532 Add survey page example
  JSDemos/Demos/HtmlEditor/SurveyExample/description.md
  JSDemos/menuMeta.json
Labels: 20_2

#536 dxScheduler - fix disable dates demo in IE 11
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/CellTemplates/React/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/Vue/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/index.js
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Scheduler/CellTemplates.css
  MVCDemos/Views/Scheduler/CellTemplates.cshtml
  NetCoreDemos/Views/Scheduler/CellTemplates.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/CellTemplates.css
Labels: 21_1

#537 dxScheduler - fix disable dates demo in IE 11
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/CellTemplates/React/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/Vue/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/index.js
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Scheduler/CellTemplates.css
  MVCDemos/Views/Scheduler/CellTemplates.cshtml
  NetCoreDemos/Views/Scheduler/CellTemplates.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/CellTemplates.css
Labels: 20_2, cherry-pick

#543 Improve 'Resolved Axis Label Overlapping' demo
  JSDemos/Demos/Charts/AxisLabelsOverlapping/Angular/app/app.component.css
  JSDemos/Demos/Charts/AxisLabelsOverlapping/AngularJS/styles.css
  JSDemos/Demos/Charts/AxisLabelsOverlapping/Knockout/styles.css
  JSDemos/Demos/Charts/AxisLabelsOverlapping/React/styles.css
  JSDemos/Demos/Charts/AxisLabelsOverlapping/Vue/App.vue
  JSDemos/Demos/Charts/AxisLabelsOverlapping/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Charts/AxisLabelsOverlapping.css
  NetCoreDemos/wwwroot/css/DemosStyles/Charts/AxisLabelsOverlapping.css
Labels: 21_1

#544 Improve 'Resolved Axis Label Overlapping' demo
  JSDemos/Demos/Charts/AxisLabelsOverlapping/Angular/app/app.component.css
  JSDemos/Demos/Charts/AxisLabelsOverlapping/AngularJS/styles.css
  JSDemos/Demos/Charts/AxisLabelsOverlapping/Knockout/styles.css
  JSDemos/Demos/Charts/AxisLabelsOverlapping/React/styles.css
  JSDemos/Demos/Charts/AxisLabelsOverlapping/Vue/App.vue
  JSDemos/Demos/Charts/AxisLabelsOverlapping/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Charts/AxisLabelsOverlapping.css
  NetCoreDemos/wwwroot/css/DemosStyles/Charts/AxisLabelsOverlapping.css
Labels: 20_2, cherry-pick

#547 Master-detail Angular demos - Added folders for custom components
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/detail-view/detail-view.component.css
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/detail-view/detail-view.component.html
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Angular/app/detail-view/detail-view.component.ts
  JSDemos/Demos/DataGrid/MasterDetailView/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/MasterDetailView/Angular/app/detail-grid/detail-grid.component.css
  JSDemos/Demos/DataGrid/MasterDetailView/Angular/app/detail-grid/detail-grid.component.html
  JSDemos/Demos/DataGrid/MasterDetailView/Angular/app/detail-grid/detail-grid.component.ts
  JSDemos/Demos/DataGrid/WebAPIService/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/WebAPIService/Angular/app/detail-grid/detail-grid.component.css
  JSDemos/Demos/DataGrid/WebAPIService/Angular/app/detail-grid/detail-grid.component.html
  JSDemos/Demos/DataGrid/WebAPIService/Angular/app/detail-grid/detail-grid.component.ts
Labels: 20_2

#548 Update spaces in List editing demo
  JSDemos/Demos/List/ListEditingAndAPI/React/App.js
  JSDemos/Demos/List/ListEditingAndAPI/Vue/App.vue
Labels: 21_1

#549 Update spaces in list editing demos
  JSDemos/Demos/List/ListEditingAndAPI/React/App.js
  JSDemos/Demos/List/ListEditingAndAPI/Vue/App.vue
Labels: 20_2, cherry-pick
