Repository DevExpress/devextreme-demos, pull requests merged in 2021-11, with the labels that each got.

#1489 Fix reviewers in renovate config
  renovate.json
Labels: 21_2

#1496 Renovate: assign reviewers even if automerge is true
  renovate.json
Labels: 21_2

#1497 Linter - add 'no `test.only`' rule
  .eslintrc.js
  package-lock.json
  package.json
Labels: 21_2

#1502 Fix Vue test: Map - Providers And Types
  JSDemos/Demos/Map/ProvidersAndTypes/Angular/app/app.component.css
  JSDemos/Demos/Map/ProvidersAndTypes/AngularJS/styles.css
  JSDemos/Demos/Map/ProvidersAndTypes/Knockout/styles.css
  JSDemos/Demos/Map/ProvidersAndTypes/React/App.js
  JSDemos/Demos/Map/ProvidersAndTypes/React/styles.css
  JSDemos/Demos/Map/ProvidersAndTypes/Vue/App.vue
  JSDemos/Demos/Map/ProvidersAndTypes/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Map/ProvidersAndTypes.css
  NetCoreDemos/wwwroot/css/DemosStyles/Map/ProvidersAndTypes.css
  testing/etalons/Map-ProvidersAndTypes.png
Labels: 21_2

#1503 Fix angular version to 12
  JSDemos/configs/Angular/config.js
  package-lock.json
  package.json
Labels: 21_2

#1507 Fix angular version to 12 (#1503)
  JSDemos/configs/Angular/config.js
  package.json
Labels: 21_1, cherry-pick

#1508 Fix angular version to 12 (#1503) (#1507)
  JSDemos/configs/Angular/config.js
  package.json
Labels: 20_2, cherry-pick

#1511 Add `changedFiles` logger
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
  utils/visual-tests/matrix-test-helper.js
Labels: 21_2

#1510 Fix T1042114
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.js
  package-lock.json
  package.json
Labels: 21_2

#1515 Remove comment from config
  JSDemos/configs/Angular/config.js
Labels: 20_2, cherry-pick

#1514 Remove comment from config
  JSDemos/configs/Angular/config.js
Labels: 21_1, cherry-pick

#1513 Remove comment in config
  JSDemos/configs/Angular/config.js
Labels: 21_2

#1516 dxScheduler - fix templates in React (T1041269)
  testing/widgets/scheduler/etalons/scheduler_CellTemplates_selection.png
  testing/widgets/scheduler/etalons/scheduler_overview_selection.png
  testing/widgets/scheduler/templates.test.js
Labels: 21_2

#1518 update versions
  .github/workflows/CI.yml
  .github/workflows/unit_tests.yml
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  package-lock.json
  package.json
  renovate.json
Labels: 22_1

#1532 Update etalon (T1045321)
  testing/etalons/DataGrid-MasterDetailAPI.png
Labels: 21_2

#1534 Update etalon (T1045321) (#1532)
  testing/etalons/DataGrid-MasterDetailAPI.png
Labels: cherry-pick, 22_1

#1537 Bullet Charts: Update Demo description
  JSDemos/Demos/Charts/SimpleBullets/description.md
Labels: 21_2

#1539 Update etalons after update Chrome to 96
  testing/etalons/Accordion-Overview.png
  testing/etalons/Autocomplete-Overview.png
  testing/etalons/Button-Icons.png
  testing/etalons/Charts-AxisCustomPosition.png
  testing/etalons/Charts-LogarithmicVsLinearAxes.png
  testing/etalons/Charts-SpiderWeb.png
  testing/etalons/Common-ActionAndListsOverview.png
  testing/etalons/Common-NavigationOverview.png
  testing/etalons/Common-NavigationRightToLeftSupport.png
  testing/etalons/DataGrid-CRUDOperations.png
  testing/etalons/DataGrid-CellCustomization.png
  testing/etalons/DataGrid-ExcelJS.png
  testing/etalons/Diagram-CustomShapesWithTemplates.png
  testing/etalons/Diagram-CustomShapesWithTemplatesWithEditing.png
  testing/etalons/Diagram-ItemSelection.png
  testing/etalons/DropDownButton-Overview.png
  testing/etalons/FieldSet-Overview.png
  testing/etalons/FileUploader-CustomDropzone.png
  testing/etalons/FileUploader-FileSelection.png
  testing/etalons/FilterBuilder-Customization.png
  testing/etalons/HtmlEditor-OutputFormats.png
  testing/etalons/HtmlEditor-Overview.png
  testing/etalons/HtmlEditor-Tables.png
  testing/etalons/HtmlEditor-ToolbarCustomization.png
  testing/etalons/List-ListSelection.png
  testing/etalons/List-ListWithSearchBar.png
  testing/etalons/LoadIndicator-Overview.png
  testing/etalons/LoadPanel-Overview.png
  testing/etalons/Menu-Overview.png
  testing/etalons/Popup-Scrolling.png
  testing/etalons/RangeSelector-ChartOnBackgroundWithSeriesTemplate.png
  testing/etalons/Scheduler-Agenda.png
  testing/etalons/Scheduler-CustomTemplates.png
  testing/etalons/Scheduler-CustomizeIndividualViews.png
  testing/etalons/Scheduler-GroupByDate.png
  testing/etalons/Scheduler-GroupOrientation.png
  testing/etalons/SelectBox-SearchAndEditing.png
  testing/etalons/Sortable-Kanban.png
  testing/etalons/TabPanel-Overview.png
  testing/etalons/TabPanel-SortableClosableTabs.png
  testing/etalons/Tabs-Overview.png
  testing/etalons/TextArea-Overview.png
  testing/etalons/Tooltip-Overview.png
  testing/etalons/TreeView-ContextMenuIntegration.png
  testing/etalons/TreeView-DragAndDropHierarchicalDataStructure.png
  testing/etalons/TreeView-DragAndDropPlainDataStructure.png
  testing/etalons/TreeView-ItemSelectionAndCustomization.png
  testing/etalons/Validation-Overview.png
  testing/etalons/VectorMap-AreaWithLabelsAndTwoLegends.png
Labels: 21_2

#1530 DataGrid - ToolbarCustomization - fix templates for Vue2
  JSDemos/Demos/DataGrid/ToolbarCustomization/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/ToolbarCustomization/Vue/App.vue
Labels: 22_1

#1531 DataGrid - ToolbarCustomization - fix templates for Vue2
  JSDemos/Demos/DataGrid/ToolbarCustomization/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/ToolbarCustomization/Vue/App.vue
Labels: cherry-pick, 21_2

#1538 Bullet Charts: Update Demo description (#1537)
  JSDemos/Demos/Charts/SimpleBullets/description.md
Labels: cherry-pick, 22_1

#1540 Editors Appearance demo - Fix editors container height
  JSDemos/Demos/Common/EditorAppearanceVariants/Angular/app/app.component.css
  JSDemos/Demos/Common/EditorAppearanceVariants/AngularJS/styles.css
  JSDemos/Demos/Common/EditorAppearanceVariants/React/styles.css
  JSDemos/Demos/Common/EditorAppearanceVariants/Vue/App.vue
  JSDemos/Demos/Common/EditorAppearanceVariants/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Common/EditorAppearanceVariants.css
  NetCoreDemos/wwwroot/css/DemosStyles/Common/EditorAppearanceVariants.css
Labels: 21_2

#1546 GitHub image update
  testing/etalons/Accordion-Overview.png
  testing/etalons/Autocomplete-Overview.png
  testing/etalons/Button-Icons.png
  testing/etalons/Charts-AxisCustomPosition.png
  testing/etalons/Charts-LogarithmicVsLinearAxes.png
  testing/etalons/Charts-SpiderWeb.png
  testing/etalons/Common-ActionAndListsOverview.png
  testing/etalons/Common-NavigationOverview.png
  testing/etalons/Common-NavigationRightToLeftSupport.png
  testing/etalons/DataGrid-CRUDOperations.png
  testing/etalons/DataGrid-CellCustomization.png
  testing/etalons/DataGrid-ExcelJS.png
  testing/etalons/Diagram-CustomShapesWithTemplates.png
  testing/etalons/Diagram-CustomShapesWithTemplatesWithEditing.png
  testing/etalons/Diagram-ItemSelection.png
  testing/etalons/DropDownButton-Overview.png
  testing/etalons/FieldSet-Overview.png
  testing/etalons/FileUploader-CustomDropzone.png
  testing/etalons/FileUploader-FileSelection.png
  testing/etalons/FilterBuilder-Customization.png
  testing/etalons/HtmlEditor-OutputFormats.png
  testing/etalons/HtmlEditor-Overview.png
  testing/etalons/HtmlEditor-Tables.png
  testing/etalons/HtmlEditor-ToolbarCustomization.png
  testing/etalons/List-ListSelection.png
  testing/etalons/List-ListWithSearchBar.png
  testing/etalons/LoadIndicator-Overview.png
  testing/etalons/LoadPanel-Overview.png
  testing/etalons/Menu-Overview.png
  testing/etalons/Popup-Scrolling.png
  testing/etalons/RangeSelector-ChartOnBackgroundWithSeriesTemplate.png
  testing/etalons/Scheduler-Agenda.png
  testing/etalons/Scheduler-CustomTemplates.png
  testing/etalons/Scheduler-CustomizeIndividualViews.png
  testing/etalons/Scheduler-GroupByDate.png
  testing/etalons/Scheduler-GroupOrientation.png
  testing/etalons/SelectBox-SearchAndEditing.png
  testing/etalons/Sortable-Kanban.png
  testing/etalons/TabPanel-Overview.png
  testing/etalons/TabPanel-SortableClosableTabs.png
  testing/etalons/Tabs-Overview.png
  testing/etalons/TextArea-Overview.png
  testing/etalons/Tooltip-Overview.png
  testing/etalons/TreeView-ContextMenuIntegration.png
  testing/etalons/TreeView-DragAndDropHierarchicalDataStructure.png
  testing/etalons/TreeView-DragAndDropPlainDataStructure.png
  testing/etalons/TreeView-ItemSelectionAndCustomization.png
  testing/etalons/Validation-Overview.png
  testing/etalons/VectorMap-AreaWithLabelsAndTwoLegends.png
Labels: 22_1

#1545 Editors Appearance demo - Fix editors container
  JSDemos/Demos/Common/EditorAppearanceVariants/Angular/app/app.component.css
  JSDemos/Demos/Common/EditorAppearanceVariants/AngularJS/styles.css
  JSDemos/Demos/Common/EditorAppearanceVariants/React/styles.css
  JSDemos/Demos/Common/EditorAppearanceVariants/Vue/App.vue
  JSDemos/Demos/Common/EditorAppearanceVariants/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Common/EditorAppearanceVariants.css
  NetCoreDemos/wwwroot/css/DemosStyles/Common/EditorAppearanceVariants.css
Labels: cherry-pick, 22_1

#1544 Popup Overview: deprecate closeOnOutsideClick and publish hideOnOutsideClick
  JSDemos/Demos/Popup/Overview/Angular/description.md
  JSDemos/Demos/Popup/Overview/React/description.md
  JSDemos/Demos/Popup/Overview/Vue/description.md
  JSDemos/Demos/Popup/Overview/description.md
Labels: 22_1
