Repository DevExpress/devextreme-demos, pull requests merged in 2021-10, with the labels that each got.

#1399 Add Getting Started links to root demos
  JSDemos/Demos/Button/PredefinedTypes/description.md
  JSDemos/Demos/ButtonGroup/Overview/description.md
  JSDemos/Demos/DataGrid/Overview/Angular/description.md
  JSDemos/Demos/DataGrid/Overview/React/description.md
  JSDemos/Demos/DataGrid/Overview/Vue/description.md
  JSDemos/Demos/DataGrid/Overview/jQuery/description.md
  JSDemos/Demos/DateBox/Overview/description.md
  JSDemos/Demos/Drawer/LeftOrRightPosition/description.md
  JSDemos/Demos/DropDownButton/Overview/description.md
  JSDemos/Demos/FloatingActionButton/Overview/description.md
  JSDemos/Demos/Form/Overview/description.md
  JSDemos/Demos/HtmlEditor/Overview/description.md
  JSDemos/Demos/List/ListEditingAndAPI/description.md
  JSDemos/Demos/PivotGrid/Overview/Angular/description.md
  JSDemos/Demos/PivotGrid/Overview/React/description.md
  JSDemos/Demos/PivotGrid/Overview/Vue/description.md
  JSDemos/Demos/PivotGrid/Overview/jQuery/description.md
  JSDemos/Demos/Popup/Overview/description.md
  JSDemos/Demos/Scheduler/Overview/Angular/description.md
  JSDemos/Demos/Scheduler/Overview/React/description.md
  JSDemos/Demos/Scheduler/Overview/Vue/description.md
  JSDemos/Demos/Scheduler/Overview/jQuery/description.md
  JSDemos/Demos/SelectBox/Overview/description.md
  JSDemos/Demos/TabPanel/Overview/description.md
  JSDemos/Demos/TagBox/Overview/description.md
  JSDemos/Demos/TreeList/Overview/Angular/description.md
  JSDemos/Demos/TreeList/Overview/React/description.md
  JSDemos/Demos/TreeList/Overview/Vue/description.md
  JSDemos/Demos/TreeList/Overview/jQuery/description.md
  JSDemos/Demos/TreeView/HierarchicalDataStructure/description.md
Labels: 21_2

#1374 DataGrid - addNewRowPosition demo (JQuery)
  JSDemos/Demos/DataGrid/CustomNewRecordPosition/description.md
  JSDemos/Demos/DataGrid/CustomNewRecordPosition/jQuery/data.js
  JSDemos/Demos/DataGrid/CustomNewRecordPosition/jQuery/index.html
  JSDemos/Demos/DataGrid/CustomNewRecordPosition/jQuery/index.js
  JSDemos/Demos/DataGrid/CustomNewRecordPosition/jQuery/styles.css
  JSDemos/menuMeta.json
  testing/etalons/DataGrid-CustomNewRecordPosition.png
  testing/widgets/datagrid/CustomNewRecordPosition.test.js
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_first_added.png
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_insertAfterKey_clicked.png
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_last_added.png
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_pageBottom_added.png
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_pageTop_added.png
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_viewportBottom_added.png
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_viewportTop_added.png
Labels: 21_2

#1408 DataGrid - CustomNewRecordPosition - fix menuMeta
  JSDemos/menuMeta.json
  utils/interactive/menu-meta-utils.js
Labels: 21_2

#1411 datagrid (CommandColumnCustomization) - adds the disabled option
  JSDemos/Demos/DataGrid/CommandColumnCustomization/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/CommandColumnCustomization/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/CommandColumnCustomization/AngularJS/index.js
  JSDemos/Demos/DataGrid/CommandColumnCustomization/React/App.js
  JSDemos/Demos/DataGrid/CommandColumnCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/CommandColumnCustomization/jQuery/index.js
  JSDemos/menuMeta.json
  MVCDemos/Views/DataGrid/CommandColumnCustomization.cshtml
  NetCoreDemos/Views/DataGrid/CommandColumnCustomization.cshtml
  testing/etalons/DataGrid-CommandColumnCustomization.png
Labels: 21_2

#1410 DataGrid and TreeList: update etalons with checkbox
  testing/etalons/DataGrid-CustomSummaries.png
  testing/etalons/DataGrid-DeferredSelection.png
  testing/etalons/TreeList-Overview.png
Labels: 21_2

#1412 DataGrid: Fix unstable test with newRowPosition last
  testing/widgets/datagrid/CustomNewRecordPosition.test.js
Labels: 21_2

#1414 DataGrid: Fix newRowPosition 'last' if scrolling.mode is 'virtual'
  JSDemos/Demos/DataGrid/RowTemplate/Vue/App.vue
  testing/widgets/datagrid/CustomNewRecordPosition.test.js
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_last_added.png
Labels: 21_2

#1419 fix typo in filename
  .gitattributes
Labels: 21_2

#1418 Update etalons for chrome 94.0.4606.71
  testing/etalons/Accordion-Overview.png
  testing/etalons/Autocomplete-Overview.png
  testing/etalons/Button-Icons.png
  testing/etalons/Charts-AxisCustomPosition.png
  testing/etalons/Common-ActionAndListsOverview.png
  testing/etalons/Common-NavigationOverview.png
  testing/etalons/Common-NavigationRightToLeftSupport.png
  testing/etalons/DataGrid-CRUDOperations.png
  testing/etalons/DataGrid-CellCustomization.png
  testing/etalons/DataGrid-ExcelJS.png
  testing/etalons/Diagram-CustomShapesWithTexts.png
  testing/etalons/DropDownButton-Overview.png
  testing/etalons/FieldSet-Overview.png
  testing/etalons/FileUploader-CustomDropzone.png
  testing/etalons/FileUploader-FileSelection.png
  testing/etalons/FilterBuilder-Customization.png
  testing/etalons/Gantt-TaskTemplate.png
  testing/etalons/HtmlEditor-OutputFormats.png
  testing/etalons/HtmlEditor-Overview.png
  testing/etalons/HtmlEditor-Tables.png
  testing/etalons/HtmlEditor-ToolbarCustomization.png
  testing/etalons/List-ListSelection.png
  testing/etalons/List-ListWithSearchBar.png
  testing/etalons/LoadIndicator-Overview.png
  testing/etalons/LoadPanel-Overview.png
  testing/etalons/Menu-Overview.png
  testing/etalons/Popup-Scrolling.png
  testing/etalons/Scheduler-Agenda.png
  testing/etalons/Scheduler-CustomTemplates.png
  testing/etalons/Scheduler-CustomizeIndividualViews.png
  testing/etalons/Scheduler-Editing.png
  testing/etalons/Scheduler-GroupByDate.png
  testing/etalons/Scheduler-GroupOrientation.png
  testing/etalons/Scheduler-Overview.png
  testing/etalons/Scheduler-SimpleArray.png
  testing/etalons/SelectBox-SearchAndEditing.png
  testing/etalons/Sortable-Kanban.png
  testing/etalons/TabPanel-Overview.png
  testing/etalons/TabPanel-SortableClosableTabs.png
  testing/etalons/Tabs-Overview.png
  testing/etalons/TextArea-Overview.png
  testing/etalons/Tooltip-Overview.png
  testing/etalons/TreeView-ContextMenuIntegration.png
  testing/etalons/TreeView-DragAndDropHierarchicalDataStructure.png
  testing/etalons/TreeView-DragAndDropPlainDataStructure.png
  testing/etalons/TreeView-ItemSelectionAndCustomization.png
  testing/etalons/Validation-Overview.png
Labels: 21_2

#1415 DataGrid - CustomNewRecordPosition - minor fixes
  JSDemos/Demos/DataGrid/CustomNewRecordPosition/jQuery/index.html
  JSDemos/Demos/DataGrid/CustomNewRecordPosition/jQuery/index.js
  testing/etalons/DataGrid-CustomNewRecordPosition.png
  testing/widgets/datagrid/CustomNewRecordPosition.test.js
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_first_added.png
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_insertAfterKey_clicked.png
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_last_added.png
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_pageBottom_added.png
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_pageTop_added.png
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_viewportBottom_added.png
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_viewportTop_added.png
Labels: 21_2

#1426 HtmlEditor - update Vue demos
  JSDemos/Demos/HtmlEditor/Overview/Vue/App.vue
  JSDemos/Demos/HtmlEditor/Tables/Vue/App.vue
Labels: 21_2

#1416 DataGrid: Add Custom New Record Position description
  JSDemos/Demos/DataGrid/CustomNewRecordPosition/description.md
Labels: 21_2

#1431 RangeSlider: update etalon after tooltip integration rework
  testing/etalons/RangeSlider-Overview.png
Labels: 21_2

#1442 File Uploader - Fix validation demo in angular approach
  JSDemos/Demos/Charts/ZoomingAndScrollingAPI/React/App.js
  JSDemos/Demos/FileUploader/Validation/Angular/app/app.component.html
Labels: 20_2, cherry-pick

#1440 File Uploader - Fix validation demo in angular approach
  JSDemos/Demos/FileUploader/Validation/Angular/app/app.component.html
Labels: 21_1, cherry-pick

#1444 File Uploader - Fix validation demo in angular approach
  JSDemos/Demos/FileUploader/Validation/Angular/app/app.component.html
Labels: 21_2

#1447 datagrid (CommandColumnCustomization) - updates the Clone button icon and badges
  JSDemos/Demos/DataGrid/CommandColumnCustomization/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/CommandColumnCustomization/AngularJS/index.js
  JSDemos/Demos/DataGrid/CommandColumnCustomization/React/App.js
  JSDemos/Demos/DataGrid/CommandColumnCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/CommandColumnCustomization/jQuery/index.js
  JSDemos/menuMeta.json
  MVCDemos/Views/DataGrid/CommandColumnCustomization.cshtml
  NetCoreDemos/Views/DataGrid/CommandColumnCustomization.cshtml
  testing/etalons/DataGrid-CommandColumnCustomization.png
Labels: 21_2

#1433 TreeList - the Load Data on Demand demo - improve the store implementation in Angular, React, Vue
  JSDemos/Demos/TreeList/LoadDataOnDemand/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/LoadDataOnDemand/React/App.js
  JSDemos/Demos/TreeList/LoadDataOnDemand/Vue/App.vue
Labels: 21_2

#1435 TreeList - the Load Data on Demand demo - improve the store implementation in Angular, React, Vue
  JSDemos/Demos/TreeList/LoadDataOnDemand/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/LoadDataOnDemand/React/App.js
  JSDemos/Demos/TreeList/LoadDataOnDemand/Vue/App.vue
Labels: 20_2, cherry-pick

#1455 Fix charts demos build 20 2
  MVCDemos/Views/Charts/CustomizePointsAndLabels.cshtml
  MVCDemos/Views/Charts/Strips.cshtml
  NetCoreDemos/Views/Charts/CustomizePointsAndLabels.cshtml
  NetCoreDemos/Views/Charts/Strips.cshtml
Labels: 20_2, cherry-pick

#1459 HtmlEditor - use tags for the devextreme-quill package in NetCore and MVC demos
  MVCDemos/Views/HtmlEditor/Mentions.cshtml
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  MVCDemos/Views/HtmlEditor/Overview.cshtml
  MVCDemos/Views/HtmlEditor/Tables.cshtml
  MVCDemos/Views/HtmlEditor/ToolbarCustomization.cshtml
  NetCoreDemos/Views/HtmlEditor/Mentions.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/Overview.cshtml
  NetCoreDemos/Views/HtmlEditor/Tables.cshtml
  NetCoreDemos/Views/HtmlEditor/ToolbarCustomization.cshtml
Labels: 20_2

#1464 Form Demo - Remove unnecessary style
  JSDemos/Demos/Form/CustomizeItem/Angular/app/app.component.css
  JSDemos/Demos/Form/CustomizeItem/AngularJS/styles.css
  JSDemos/Demos/Form/CustomizeItem/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Form/CustomizeItem.css
  NetCoreDemos/wwwroot/css/DemosStyles/Form/CustomizeItem.css
Labels: 21_2

#1449 DataGrid - CustomNewRecordPosition - tests split
  testing/widgets/datagrid/CustomNewRecordPosition.test.js
  testing/widgets/datagrid/etalons/datagrid_CustomNewRecordPosition_last_added.png
Labels: 21_2

#1468 DataGrid: Replace rowTemplate to dataRowTemplate in the Row 3rd Party Engine Template demo
  JSDemos/Demos/DataGrid/Row3RdPartyEngineTemplate/jQuery/index.html
  JSDemos/Demos/DataGrid/Row3RdPartyEngineTemplate/jQuery/index.js
  JSDemos/Demos/DataGrid/Row3RdPartyEngineTemplate/jQuery/styles.css
  testing/etalons/DataGrid-Row3RdPartyEngineTemplate.png
Labels: 21_2

#1491 Editor Appearance Variants demo - Fix tests
  JSDemos/Demos/Common/EditorAppearanceVariants/AngularJS/index.html
  JSDemos/Demos/Common/EditorAppearanceVariants/AngularJS/index.js
  JSDemos/Demos/Common/EditorAppearanceVariants/AngularJS/styles.css
  MVCDemos/Views/Common/EditorAppearanceVariants.cshtml
  NetCoreDemos/Views/Common/EditorAppearanceVariants.cshtml
Labels: 21_2
