Repository DevExpress/devextreme-demos, pull requests merged in 2021-09, with the labels that each got.

#1209 CheckBox restyling: update etalons
  testing/etalons/DataGrid-CellEditingAndEditingAPI.png
  testing/etalons/DataGrid-CustomSummaries.png
  testing/etalons/DataGrid-DeferredSelection.png
  testing/etalons/DataGrid-ExcelJS.png
  testing/etalons/DataGrid-ExcelJSOverview.png
  testing/etalons/DataGrid-ExportToExcel.png
  testing/etalons/DataGrid-MultipleRecordSelectionAPI.png
  testing/etalons/DataGrid-MultipleRecordSelectionModes.png
  testing/etalons/FileManager-AzureClientBinding.png
  testing/etalons/FileManager-AzureServerBinding.png
  testing/etalons/FileManager-BindingToEF.png
  testing/etalons/FileManager-BindingToFileSystem.png
  testing/etalons/FileManager-BindingToHierarchicalStructure.png
  testing/etalons/FileManager-Overview.png
  testing/etalons/FileManager-UICustomization.png
  testing/etalons/PivotGrid-LayoutCustomization.png
Labels: 21_2

#1214 Fix Editors Overview demo for narrow screens
  JSDemos/Demos/Common/EditorsOverview/Angular/app/app.component.css
  JSDemos/Demos/Common/EditorsOverview/AngularJS/styles.css
  JSDemos/Demos/Common/EditorsOverview/Knockout/styles.css
  JSDemos/Demos/Common/EditorsOverview/React/styles.css
  JSDemos/Demos/Common/EditorsOverview/Vue/App.vue
  JSDemos/Demos/Common/EditorsOverview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Common/EditorsOverview.css
  NetCoreDemos/wwwroot/css/DemosStyles/Common/EditorsOverview.css
  testing/etalons/Common-EditorsOverview.png
Labels: 21_2

#1212 Fix Vue test: Scheduler - CurrentTimeIndicator
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/AngularJS/styles.css
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/React/styles.css
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/Vue/App.vue
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/jQuery/styles.css
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/visualtestrc.json
  MVCDemos/Content/DemosStyles/Scheduler/CurrentTimeIndicator.css
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/CurrentTimeIndicator.css
  testing/etalons/Scheduler-CurrentTimeIndicator.png
Labels: 21_2

#1213 Fix Vue test: DataGrid-FocusedRow
  JSDemos/Demos/DataGrid/FocusedRow/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/FocusedRow/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/FocusedRow/AngularJS/index.html
  JSDemos/Demos/DataGrid/FocusedRow/AngularJS/styles.css
  JSDemos/Demos/DataGrid/FocusedRow/React/App.js
  JSDemos/Demos/DataGrid/FocusedRow/React/styles.css
  JSDemos/Demos/DataGrid/FocusedRow/Vue/App.vue
  JSDemos/Demos/DataGrid/FocusedRow/Vue/styles.css
  JSDemos/Demos/DataGrid/FocusedRow/jQuery/index.html
  JSDemos/Demos/DataGrid/FocusedRow/jQuery/styles.css
  JSDemos/Demos/DataGrid/FocusedRow/visualtestrc.json
  MVCDemos/Content/DemosStyles/DataGrid/FocusedRow.css
  MVCDemos/Views/DataGrid/FocusedRow.cshtml
  NetCoreDemos/Views/DataGrid/FocusedRow.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/FocusedRow.css
  testing/etalons/DataGrid-FocusedRow.png
Labels: 21_2

#1215 TreeView-ItemSelectionAndCustomization: fix option layout
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Angular/app/app.component.css
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Angular/app/app.component.html
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/AngularJS/index.html
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/AngularJS/styles.css
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/React/App.js
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/React/styles.css
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Vue/App.vue
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/jQuery/index.html
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/jQuery/styles.css
  MVCDemos/Content/DemosStyles/TreeView/ItemSelectionAndCustomization.css
  MVCDemos/Views/TreeView/ItemSelectionAndCustomization.cshtml
  NetCoreDemos/Views/TreeView/ItemSelectionAndCustomization.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TreeView/ItemSelectionAndCustomization.css
  testing/etalons/TreeView-ItemSelectionAndCustomization.png
Labels: 21_2

#1219 Skip test: PivotGrid-IntegratedFieldChooser
  JSDemos/Demos/PivotGrid/IntegratedFieldChooser/visualtestrc.json
Labels: 21_2

#1216 Fix Vue test: Scheduler-Editing
  JSDemos/Demos/Scheduler/Editing/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/Editing/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/Editing/AngularJS/index.html
  JSDemos/Demos/Scheduler/Editing/AngularJS/styles.css
  JSDemos/Demos/Scheduler/Editing/React/App.js
  JSDemos/Demos/Scheduler/Editing/React/styles.css
  JSDemos/Demos/Scheduler/Editing/Vue/App.vue
  JSDemos/Demos/Scheduler/Editing/jQuery/index.html
  JSDemos/Demos/Scheduler/Editing/jQuery/styles.css
  JSDemos/Demos/Scheduler/Editing/visualtestrc.json
  MVCDemos/Content/DemosStyles/Scheduler/Editing.css
  MVCDemos/Views/Scheduler/Editing.cshtml
  NetCoreDemos/Views/Scheduler/Editing.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/Editing.css
  testing/etalons/Scheduler-Editing.png
Labels: 21_2

#1220 Fix Vue test: LoadPanel-Overview
  JSDemos/Demos/LoadPanel/Overview/Vue/App.vue
  JSDemos/Demos/LoadPanel/Overview/visualtestrc.json
Labels: 21_2

#1223 Fix AngularJS test: Scheduler-CrrentTimeIndicator
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/AngularJS/styles.css
Labels: 21_2

#1225 Fix NetCore test: Pivotgrid-Headerfilter
  NetCoreDemos/Views/PivotGrid/HeaderFilter.cshtml
Labels: 21_2

#1229 Use single eslint config instead of 3 one.
  .eslintignore
  .eslintrc.js
  .react.eslintignore
  .react.eslintrc.json
  .vue.eslintignore
  .vue.eslintrc.json
  package.json
Labels: 21_2

#1228 Fix layout: TreeView-ItemSelectionAndCustomization
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Angular/app/app.component.css
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Angular/app/app.component.html
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/AngularJS/index.html
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/AngularJS/styles.css
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/React/App.js
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/React/styles.css
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Vue/App.vue
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/jQuery/index.html
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/jQuery/styles.css
  MVCDemos/Content/DemosStyles/TreeView/ItemSelectionAndCustomization.css
  MVCDemos/Views/TreeView/ItemSelectionAndCustomization.cshtml
  NetCoreDemos/Views/TreeView/ItemSelectionAndCustomization.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TreeView/ItemSelectionAndCustomization.css
  testing/etalons/TreeView-ItemSelectionAndCustomization.png
Labels: 21_2

#1238 Gantt - Fix screenshot for ChartAppearence demo
  JSDemos/Demos/DataGrid/ExportToPDF/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSOverview/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/React/App.js
  JSDemos/Demos/TabPanel/SortableClosableTabs/React/App.js
  package-lock.json
  testing/etalons/Gantt-ChartAppearance.png
Labels: 21_2

#1234 Turn on eslint:recommended rules for jQuery approach
  .eslintrc.js
  JSDemos/Demos/Button/Icons/jQuery/index.js
  JSDemos/Demos/Charts/ErrorBars/jQuery/index.js
  JSDemos/Demos/Charts/LoadDataOnDemand/jQuery/index.js
  JSDemos/Demos/Charts/LogarithmicVsLinearAxes/jQuery/index.js
  JSDemos/Demos/Charts/Overview/jQuery/index.js
  JSDemos/Demos/Charts/ParetoChart/jQuery/index.js
  JSDemos/Demos/Charts/PointsAggregation/jQuery/index.js
  JSDemos/Demos/Charts/ZoomingAndScrolling/jQuery/index.js
  JSDemos/Demos/ContextMenu/Basics/jQuery/index.js
  JSDemos/Demos/ContextMenu/Templates/jQuery/index.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/jQuery/index.js
  JSDemos/Demos/DataGrid/CustomEditors/jQuery/index.js
  JSDemos/Demos/DataGrid/HorizontalVirtualScrolling/jQuery/data.js
  JSDemos/Demos/DataGrid/MultiRowHeadersBands/jQuery/index.js
  JSDemos/Demos/DataGrid/RowEditingAndEditingEvents/jQuery/index.js
  JSDemos/Demos/Diagram/AdvancedDataBinding/jQuery/index.js
  JSDemos/Demos/Diagram/CustomShapesWithTemplates/jQuery/index.js
  JSDemos/Demos/Diagram/CustomShapesWithTemplatesWithEditing/jQuery/index.js
  JSDemos/Demos/Diagram/ItemSelection/jQuery/index.js
  JSDemos/Demos/DropDownButton/Overview/jQuery/index.js
  JSDemos/Demos/FileUploader/ChunkUploading/jQuery/index.js
  JSDemos/Demos/FilterBuilder/WithList/jQuery/index.js
  JSDemos/Demos/Gallery/ItemTemplate/jQuery/index.js
  JSDemos/Demos/Gantt/ChartAppearance/jQuery/index.js
  JSDemos/Demos/Gantt/TaskTemplate/jQuery/index.js
  JSDemos/Demos/Gauges/AnglesCustomization/jQuery/index.js
  JSDemos/Demos/Gauges/CustomLayoutLinearGauge/jQuery/index.js
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypes/jQuery/index.js
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypes/jQuery/index.js
  JSDemos/Demos/Gauges/GaugeTitleCustomized/jQuery/index.js
  JSDemos/Demos/Gauges/GaugeTooltip/jQuery/index.js
  JSDemos/Demos/Gauges/ScaleCustomTickInterval/jQuery/index.js
  JSDemos/Demos/Gauges/ScaleCustomTickValues/jQuery/index.js
  JSDemos/Demos/Gauges/ScaleLabelFormatting/jQuery/index.js
  JSDemos/Demos/Gauges/ScaleMinorTicks/jQuery/index.js
  JSDemos/Demos/Gauges/SubvalueIndicatorTextFormatting/jQuery/index.js
  JSDemos/Demos/Gauges/ValueIndicatorsAPI/jQuery/index.js
  JSDemos/Demos/Gauges/VariableNumberOfSubvalueIndicators/jQuery/index.js
  JSDemos/Demos/List/ItemTemplate/jQuery/index.js
  JSDemos/Demos/List/ListSelection/jQuery/index.js
  JSDemos/Demos/PivotGrid/HeaderFilter/jQuery/index.js
  JSDemos/Demos/PivotGrid/StandaloneFieldChooser/jQuery/index.js
  JSDemos/Demos/Popup/Overview/jQuery/index.js
  JSDemos/Demos/Popup/Scrolling/jQuery/index.js
  JSDemos/Demos/RadioGroup/Overview/jQuery/data.js
  JSDemos/Demos/Scheduler/GoogleCalendarIntegration/jQuery/index.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/jQuery/index.js
  JSDemos/Demos/Slideout/Overview/jQuery/index.js
  JSDemos/Demos/TabPanel/SortableClosableTabs/jQuery/index.js
  JSDemos/Demos/TreeList/FilterPanel/jQuery/index.js
  JSDemos/Demos/TreeList/MultipleRowSelection/jQuery/index.js
  JSDemos/Demos/TreeList/Overview/jQuery/index.js
  JSDemos/Demos/VectorMap/CustomProjection/jQuery/data.js
Labels: 21_2

#1243 scrollable: add mask for renovated widget spefic
  testing/etalons/Gantt-StripLines_mask.png
Labels: 21_2

#1242 Add eslint:recommended for AngularJS demos
  .eslintrc.js
  JSDemos/Demos/ActionSheet/PopoverMode/AngularJS/index.js
  JSDemos/Demos/Button/Icons/AngularJS/index.js
  JSDemos/Demos/Charts/LoadDataOnDemand/AngularJS/index.js
  JSDemos/Demos/Charts/LogarithmicVsLinearAxes/AngularJS/index.js
  JSDemos/Demos/Charts/Overview/AngularJS/index.js
  JSDemos/Demos/Charts/ParetoChart/AngularJS/index.js
  JSDemos/Demos/Charts/PointsAggregation/AngularJS/index.js
  JSDemos/Demos/Charts/SignalRService/AngularJS/index.js
  JSDemos/Demos/ContextMenu/Basics/AngularJS/index.js
  JSDemos/Demos/ContextMenu/Templates/AngularJS/index.js
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/AngularJS/index.js
  JSDemos/Demos/DataGrid/CustomDataSource/AngularJS/index.js
  JSDemos/Demos/DataGrid/CustomEditors/AngularJS/index.js
  JSDemos/Demos/DataGrid/Filtering/AngularJS/index.js
  JSDemos/Demos/DataGrid/HorizontalVirtualScrolling/AngularJS/data.js
  JSDemos/Demos/DataGrid/MultiRowHeadersBands/AngularJS/index.js
  JSDemos/Demos/DataGrid/RowEditingAndEditingEvents/AngularJS/index.js
  JSDemos/Demos/FileUploader/ChunkUploading/AngularJS/index.js
  JSDemos/Demos/Gantt/ChartAppearance/Vue/App.vue
  JSDemos/Demos/Gauges/ValueIndicatorsAPI/AngularJS/index.js
  JSDemos/Demos/List/ListWithSearchBar/AngularJS/index.js
  JSDemos/Demos/LoadPanel/Overview/AngularJS/index.js
  JSDemos/Demos/Lookup/EventHandling/AngularJS/index.js
  JSDemos/Demos/Lookup/Templates/AngularJS/index.js
  JSDemos/Demos/MultiView/Overview/AngularJS/index.js
  JSDemos/Demos/NumberBox/Overview/AngularJS/index.js
  JSDemos/Demos/PivotGrid/HeaderFilter/AngularJS/index.js
  JSDemos/Demos/PivotGrid/StandaloneFieldChooser/AngularJS/index.js
  JSDemos/Demos/Popover/Overview/AngularJS/index.js
  JSDemos/Demos/Popup/Overview/AngularJS/index.js
  JSDemos/Demos/RadioGroup/Overview/AngularJS/data.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/AngularJS/index.js
  JSDemos/Demos/Scheduler/CustomTemplates/AngularJS/index.js
  JSDemos/Demos/Scheduler/GoogleCalendarIntegration/AngularJS/index.js
  JSDemos/Demos/TabPanel/Overview/AngularJS/index.js
  JSDemos/Demos/TreeList/FilterPanel/AngularJS/index.js
  JSDemos/Demos/TreeList/MultipleRowSelection/AngularJS/index.js
  JSDemos/Demos/TreeList/Overview/AngularJS/index.js
  JSDemos/Demos/TreeView/DragAndDropHierarchicalDataStructure/AngularJS/index.js
  JSDemos/Demos/TreeView/DragAndDropPlainDataStructure/AngularJS/index.js
  JSDemos/Demos/TreeView/TreeViewWithSearchBar/AngularJS/index.js
  JSDemos/Demos/VectorMap/CustomProjection/AngularJS/data.js
Labels: 21_2

#1176 DataGrid - using toolbar options in demos
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/AngularJS/index.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/React/App.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Vue/App.vue
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/jQuery/index.js
  JSDemos/Demos/DataGrid/ExportToPDF/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/ExportToPDF/React/App.js
  JSDemos/Demos/DataGrid/ExportToPDF/Vue/App.vue
  JSDemos/Demos/DataGrid/ExportToPDF/jQuery/index.html
  JSDemos/Demos/DataGrid/ExportToPDF/jQuery/index.js
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/AngularJS/index.html
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/AngularJS/index.js
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/AngularJS/styles.css
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/React/App.js
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/React/styles.css
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Vue/App.vue
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/jQuery/index.html
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/jQuery/index.js
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/jQuery/styles.css
  JSDemos/Demos/DataGrid/ToolbarCustomization/React/App.js
  MVCDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  MVCDemos/Views/DataGrid/ExportToPDF.cshtml
  MVCDemos/Views/DataGrid/MultipleRecordSelectionAPI.cshtml
  NetCoreDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  NetCoreDemos/Views/DataGrid/ExportToPDF.cshtml
  NetCoreDemos/Views/DataGrid/MultipleRecordSelectionAPI.cshtml
  testing/etalons/DataGrid-ExportToPDF.png
  testing/etalons/DataGrid-MultipleRecordSelectionAPI.png
Labels: 21_2

#1244 datagrid - updates badges in demos with toolbar
  JSDemos/menuMeta.json
Labels: 21_2

#1245 Add eslint:recommended rules to Knockout
  .eslintrc.js
  JSDemos/Demos/Button/Icons/Knockout/index.js
  JSDemos/Demos/Charts/Overview/Knockout/index.js
  JSDemos/Demos/Charts/ParetoChart/Knockout/index.js
  JSDemos/Demos/ContextMenu/Basics/Knockout/index.js
  JSDemos/Demos/ContextMenu/Templates/Knockout/index.js
  JSDemos/Demos/DataGrid/ColumnCustomization/Knockout/index.js
  JSDemos/Demos/DataGrid/ColumnsBasedOnADataSource/Knockout/index.js
  JSDemos/Demos/DataGrid/ExportToExcel/Knockout/index.js
  JSDemos/Demos/DataGrid/Filtering/Knockout/index.js
  JSDemos/Demos/DataGrid/FilteringAPI/Knockout/index.js
  JSDemos/Demos/DataGrid/GridAdaptabilityOverview/Knockout/index.js
  JSDemos/Demos/DataGrid/GridColumnsHidingPriority/Knockout/index.js
  JSDemos/Demos/DataGrid/MasterDetailView/Knockout/index.js
  JSDemos/Demos/DataGrid/MultiRowHeadersBands/Knockout/index.js
  JSDemos/Demos/DataGrid/MultipleSorting/Knockout/index.js
  JSDemos/Demos/DataGrid/RowEditingAndEditingEvents/Knockout/index.js
  JSDemos/Demos/DataGrid/RowSelection/Knockout/index.js
  JSDemos/Demos/DataGrid/RowTemplate/Knockout/index.js
  JSDemos/Demos/DataGrid/StatePersistence/Knockout/index.js
  JSDemos/Demos/DataGrid/ToolbarCustomization/Knockout/index.js
  JSDemos/Demos/Gauges/BaseValueForRangeBar/Knockout/index.js
  JSDemos/Demos/Gauges/ScaleCustomTickInterval/Knockout/index.js
  JSDemos/Demos/Gauges/ScaleCustomTickValues/Knockout/index.js
  JSDemos/Demos/List/ItemTemplate/Knockout/index.js
  JSDemos/Demos/List/ListWithSearchBar/Knockout/index.js
  JSDemos/Demos/NumberBox/Overview/Knockout/index.js
  JSDemos/Demos/PivotGrid/VirtualScrolling/Knockout/index.js
  JSDemos/Demos/Popup/Overview/Knockout/index.js
  JSDemos/Demos/RadioGroup/Overview/Knockout/data.js
  JSDemos/Demos/Scheduler/GoogleCalendarIntegration/Knockout/index.js
  JSDemos/Demos/SelectBox/SearchAndEditing/Knockout/index.js
  JSDemos/Demos/Slideout/Overview/Knockout/index.js
  JSDemos/Demos/TreeList/Overview/Knockout/index.js
  JSDemos/Demos/TreeView/VirtualMode/Knockout/index.js
  JSDemos/Demos/VectorMap/CustomProjection/Knockout/data.js
Labels: 21_2

#1246 Gantt - Fix ChartAppearence vue demo on farm
  JSDemos/Demos/Gantt/ChartAppearance/Vue/App.vue
  JSDemos/Demos/Gantt/ChartAppearance/visualtestrc.json
Labels: 21_2

#1239 DataGrid Toolbar Customization - fix selectbox width
  JSDemos/Demos/DataGrid/ToolbarCustomization/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/ToolbarCustomization/AngularJS/index.js
  JSDemos/Demos/DataGrid/ToolbarCustomization/Knockout/index.js
  JSDemos/Demos/DataGrid/ToolbarCustomization/React/App.js
  JSDemos/Demos/DataGrid/ToolbarCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/ToolbarCustomization/jQuery/index.js
  MVCDemos/Views/DataGrid/ToolbarCustomization.cshtml
  NetCoreDemos/Views/DataGrid/ToolbarCustomization.cshtml
  testing/etalons/DataGrid-ToolbarCustomization.png
Labels: 21_2

#1237 Fix React and Vue test: RangeSelector-UseRangeSelectionForFiltering
  JSDemos/Demos/RangeSelector/UseRangeSelectionForFiltering/React/index.html
  JSDemos/Demos/RangeSelector/UseRangeSelectionForFiltering/Vue/index.html
  JSDemos/Demos/RangeSelector/UseRangeSelectionForFiltering/visualtestrc.json
Labels: 21_2

#1252 Fix Vue test: Sortable - Kanban
  JSDemos/Demos/Sortable/Kanban/Vue/index.html
  JSDemos/Demos/Sortable/Kanban/visualtestrc.json
Labels: 21_2

#1248 Fix scheduler demo
  JSDemos/Demos/Scheduler/Adaptability/Vue/App.vue
Labels: 21_2

#1254 fix eslint issues
  JSDemos/Demos/DataGrid/ExportToPDF/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSOverview/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/React/App.js
  JSDemos/Demos/TabPanel/SortableClosableTabs/React/App.js
Labels: 21_1

#1251 Fix Vue test: Map - Routes
  JSDemos/Demos/Map/Routes/Angular/app/app.component.css
  JSDemos/Demos/Map/Routes/AngularJS/styles.css
  JSDemos/Demos/Map/Routes/Knockout/styles.css
  JSDemos/Demos/Map/Routes/React/App.js
  JSDemos/Demos/Map/Routes/React/styles.css
  JSDemos/Demos/Map/Routes/Vue/App.vue
  JSDemos/Demos/Map/Routes/jQuery/styles.css
  JSDemos/Demos/Map/Routes/visualtestrc.json
  MVCDemos/Content/DemosStyles/Map/Routes.css
  NetCoreDemos/wwwroot/css/DemosStyles/Map/Routes.css
  testing/etalons/Map-Routes.png
Labels: 21_2

#1255 Fix Vue test: Gantt-ExportToPDF
  JSDemos/Demos/Gantt/ExportToPDF/Angular/app/app.component.css
  JSDemos/Demos/Gantt/ExportToPDF/React/styles.css
  JSDemos/Demos/Gantt/ExportToPDF/Vue/App.vue
  JSDemos/Demos/Gantt/ExportToPDF/jQuery/styles.css
  JSDemos/Demos/Gantt/ExportToPDF/visualtestrc.json
  MVCDemos/Content/DemosStyles/Gantt/ExportToPDF.css
  NetCoreDemos/wwwroot/css/DemosStyles/Gantt/ExportToPDF.css
  testing/etalons/Gantt-ExportToPDF.png
Labels: 21_2

#1258 Enable 'operator-assignment' eslint rule
  .eslintrc.js
  JSDemos/Demos/Charts/TilingAlgorithms/AngularJS/index.js
  JSDemos/Demos/Charts/TilingAlgorithms/Knockout/index.js
  JSDemos/Demos/Charts/TilingAlgorithms/React/App.js
  JSDemos/Demos/Charts/TilingAlgorithms/Vue/App.vue
  JSDemos/Demos/Charts/TilingAlgorithms/jQuery/index.js
Labels: 21_2

#1260 Enable 'camelcase' eslint rule
  .eslintrc.js
  JSDemos/Demos/DropDownBox/MultipleSelection/React/App.js
  JSDemos/Demos/DropDownBox/SingleSelection/React/App.js
  JSDemos/Demos/Gantt/TaskTemplate/test-code.js
  JSDemos/Demos/Gantt/Validation/test-code.js
Labels: 21_2

#1259 Enable 'no-multi-str' eslint rule
  .eslintrc.js
  JSDemos/Demos/Drawer/LeftOrRightPosition/AngularJS/data.js
  JSDemos/Demos/Drawer/LeftOrRightPosition/jQuery/data.js
  JSDemos/Demos/Drawer/TopOrBottomPosition/AngularJS/data.js
  JSDemos/Demos/Drawer/TopOrBottomPosition/jQuery/data.js
Labels: 21_2

#1261 Enable 'max-classes-per-file' eslint rule
  .eslintrc.js
  JSDemos/Demos/Charts/DrillDown/React/Breadcrumb.js
  JSDemos/Demos/Charts/DrillDown/React/TreeMapBreadcrumbs.js
  JSDemos/Demos/DropDownButton/Overview/React/App.js
  JSDemos/Demos/DropDownButton/Overview/React/ColorIcon.js
Labels: 21_2

#1263 Enable 'no-bitwise' eslint rule
  .eslintrc.js
Labels: 21_2

#1264 Enable 'no-underscore-dangle' eslit rule
  .eslintrc.js
  JSDemos/Demos/DropDownBox/MultipleSelection/React/App.js
  JSDemos/Demos/DropDownBox/SingleSelection/React/App.js
  JSDemos/Demos/Gallery/Overview/test-code.js
  JSDemos/Demos/PivotGrid/ChartIntegration/React/App.js
  JSDemos/Demos/PivotGrid/Overview/React/App.js
Labels: 21_2

#1265 Enable 'no-useless-concat' eslint rule
  .eslintrc.js
  JSDemos/Demos/Autocomplete/Overview/AngularJS/index.js
  JSDemos/Demos/Autocomplete/Overview/Knockout/index.js
  JSDemos/Demos/Autocomplete/Overview/jQuery/index.js
  JSDemos/Demos/Charts/DoughnutWithCustomLabelInCenter/jQuery/index.js
  JSDemos/Demos/Charts/ExportAndPrintingAPI/AngularJS/index.js
  JSDemos/Demos/Charts/ExportAndPrintingAPI/Knockout/index.js
  JSDemos/Demos/Charts/ExportAndPrintingAPI/jQuery/index.js
  JSDemos/Demos/Charts/SimpleBullets/AngularJS/index.js
  JSDemos/Demos/Charts/SimpleBullets/Knockout/index.js
  JSDemos/Demos/Charts/SimpleBullets/jQuery/index.js
  JSDemos/Demos/FileUploader/FileUploading/jQuery/index.js
  JSDemos/Demos/Scheduler/Editing/AngularJS/index.js
  JSDemos/Demos/Scheduler/Editing/Knockout/index.js
  JSDemos/Demos/Scheduler/Editing/jQuery/index.js
Labels: 21_2

#1266 Enable 'guard-for-in' eslint rule
  .eslintrc.js
  JSDemos/Demos/Charts/SignalRService/test-code.js
  JSDemos/Demos/DataGrid/SignalRService/test-code.js
  JSDemos/Demos/Scheduler/SignalRService/signalr-session-id.js
Labels: 21_2

#1270 Enable 'no-restricted-properties' eslint rule
  .eslintrc.js
  JSDemos/Demos/RangeSelector/LogarithmicScale/AngularJS/index.js
  JSDemos/Demos/RangeSelector/LogarithmicScale/Knockout/index.js
  JSDemos/Demos/RangeSelector/LogarithmicScale/React/data.js
  JSDemos/Demos/RangeSelector/LogarithmicScale/Vue/data.js
  JSDemos/Demos/RangeSelector/LogarithmicScale/jQuery/index.js
Labels: 21_2

#1271 Enable 'new-cap' eslint rule
  .eslintrc.js
  JSDemos/Demos/Accordion/Overview/Knockout/index.js
  JSDemos/Demos/Common/EditorsOverview/Knockout/index.js
  JSDemos/Demos/Common/FormsAndMultiPurposeOverview/Knockout/index.js
  JSDemos/Demos/DataGrid/ExportToPDF/React/App.js
  JSDemos/Demos/DataGrid/ExportToPDF/Vue/App.vue
  JSDemos/Demos/DataGrid/ExportToPDF/jQuery/index.js
  JSDemos/Demos/FileUploader/FileUploading/Knockout/index.js
  JSDemos/Demos/LoadPanel/Overview/Knockout/index.js
  JSDemos/Demos/MultiView/Overview/Knockout/index.js
  JSDemos/Demos/Popup/Overview/Knockout/index.js
  JSDemos/Demos/Slideout/Overview/Knockout/index.js
  JSDemos/Demos/TabPanel/Overview/Knockout/index.js
  JSDemos/Demos/Tabs/Overview/Knockout/index.js
  JSDemos/Demos/Validation/Overview/Knockout/index.js
Labels: 21_2

#1272 Enable 'no-useless-constructor' eslint rule
  .eslintrc.js
  JSDemos/Demos/Button/PredefinedTypes/React/App.js
  JSDemos/Demos/ButtonGroup/Overview/React/App.js
  JSDemos/Demos/DataGrid/CollaborativeEditing/React/App.js
  JSDemos/Demos/DataGrid/DnDBetweenGrids/React/App.js
  JSDemos/Demos/Gantt/TaskTemplate/React/App.js
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/React/App.js
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/React/App.js
  JSDemos/Demos/Lookup/Basics/React/App.js
  JSDemos/Demos/Popup/Scrolling/React/App.js
  JSDemos/Demos/TileView/ItemTemplate/React/App.js
Labels: 21_2

#1206 DataGrid - using DropDownButton in export toolbar button
  testing/etalons/DataGrid-ExcelJS.png
  testing/etalons/DataGrid-ExcelJSOverview.png
  testing/etalons/DataGrid-ExportToExcel.png
Labels: 21_2

#1277 Enable 'prefer-spread' eslint rule
  .eslintrc.js
  JSDemos/Demos/DataGrid/Filtering/AngularJS/index.js
  JSDemos/Demos/DataGrid/Filtering/Knockout/index.js
  JSDemos/Demos/DataGrid/Filtering/React/App.js
  JSDemos/Demos/DataGrid/Filtering/Vue/App.vue
  JSDemos/Demos/DataGrid/Filtering/jQuery/index.js
Labels: 21_2

#1276 dxScheduler - replace onContentReady handler on ref in react adaptability demo
  JSDemos/Demos/Scheduler/Adaptability/React/App.js
Labels: 21_2

#1279 Common-NavgationOverview: add _mask
  testing/etalons/Common-NavigationOverview_mask.png
Labels: 21_2

#1273 Fix Vue test: Charts-Palette
  JSDemos/Demos/Charts/Palette/Angular/app/app.component.css
  JSDemos/Demos/Charts/Palette/Angular/app/app.component.html
  JSDemos/Demos/Charts/Palette/AngularJS/index.html
  JSDemos/Demos/Charts/Palette/AngularJS/styles.css
  JSDemos/Demos/Charts/Palette/React/App.js
  JSDemos/Demos/Charts/Palette/React/styles.css
  JSDemos/Demos/Charts/Palette/Vue/App.vue
  JSDemos/Demos/Charts/Palette/jQuery/index.html
  JSDemos/Demos/Charts/Palette/jQuery/styles.css
  JSDemos/Demos/Charts/Palette/visualtestrc.json
  MVCDemos/Content/DemosStyles/Charts/Palette.css
  MVCDemos/Views/Charts/Palette.cshtml
  NetCoreDemos/Views/Charts/Palette.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Charts/Palette.css
  testing/etalons/Charts-Palette.png
Labels: 21_2

#1281 Enable 'prefer-const' eslit rule
  .eslintrc.js
  JSDemos/Demos/Charts/Scatter/AngularJS/index.js
  JSDemos/Demos/Charts/Scatter/Knockout/index.js
  JSDemos/Demos/Charts/Scatter/React/data.js
  JSDemos/Demos/Charts/Scatter/Vue/data.js
  JSDemos/Demos/Charts/Scatter/jQuery/index.js
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/jQuery/index.js
  JSDemos/Demos/Diagram/CustomShapesWithTemplatesWithEditing/jQuery/index.js
  JSDemos/Demos/Slideout/Overview/jQuery/index.js
  JSDemos/Demos/TreeList/FocusedRow/jQuery/index.js
Labels: 21_2

#1262 DataGrid Toolbar Customization: toolbar property instead of onToolbarPreparing
  JSDemos/Demos/DataGrid/ToolbarCustomization/description.md
Labels: 21_2

#1284 Enable 'radix' eslint rule
  .eslintrc.js
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/AngularJS/index.js
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/Knockout/index.js
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/jQuery/index.js
  JSDemos/Demos/DataGrid/Overview/AngularJS/index.js
  JSDemos/Demos/DataGrid/Overview/React/DiscountCell.js
  JSDemos/Demos/DataGrid/Overview/Vue/DiscountCell.vue
Labels: 21_2

#1285 Enable 'no-sequences' eslint rule
  .eslintrc.js
  JSDemos/Demos/Common/DialogsAndNotificationsOverview/AngularJS/index.js
  JSDemos/Demos/Gauges/UpdateCircularGaugeDataAtRuntime/Vue/App.vue
  JSDemos/Demos/Menu/Overview/AngularJS/index.js
  JSDemos/Demos/TreeView/FlatDataStructure/AngularJS/index.js
  JSDemos/Demos/TreeView/HierarchicalDataStructure/AngularJS/index.js
Labels: 21_2

#1293 Enable 'no-multi-assign' eslint rule
  .eslintrc.js
  JSDemos/Demos/Charts/TilingAlgorithms/AngularJS/index.js
  JSDemos/Demos/Charts/TilingAlgorithms/Knockout/index.js
  JSDemos/Demos/Charts/TilingAlgorithms/React/App.js
  JSDemos/Demos/Charts/TilingAlgorithms/Vue/App.vue
  JSDemos/Demos/Charts/TilingAlgorithms/jQuery/index.js
  JSDemos/Demos/DataGrid/CommandColumnCustomization/AngularJS/index.js
  JSDemos/Demos/DataGrid/ToolbarCustomization/React/App.js
  JSDemos/Demos/FileManager/UICustomization/React/App.js
  JSDemos/Demos/FileManager/UICustomization/Vue/App.vue
  JSDemos/Demos/FileManager/UICustomization/jQuery/index.js
  JSDemos/Demos/Scheduler/SignalRService/signalr-session-id.js
Labels: 21_2

#1294 Enable 'no-unused-expressions' eslint rule
  .eslintrc.js
  JSDemos/Demos/Charts/CustomLegendMarkers/jQuery/index.js
  JSDemos/Demos/DataGrid/FocusedRow/AngularJS/index.js
  JSDemos/Demos/Gantt/ChartAppearance/jQuery/index.js
  JSDemos/Demos/TreeList/FocusedRow/AngularJS/index.js
Labels: 21_2

#1295 Enable 'no-shadow' eslint rule
  .eslintrc.js
  JSDemos/Demos/Calendar/Overview/jQuery/index.js
  JSDemos/Demos/Charts/SimpleBullets/React/App.js
  JSDemos/Demos/Common/ActionAndListsOverview/Vue/App.vue
  JSDemos/Demos/DataGrid/ToolbarCustomization/Knockout/index.js
  JSDemos/Demos/DropDownBox/MultipleSelection/AngularJS/index.js
  JSDemos/Demos/DropDownBox/MultipleSelection/Knockout/index.js
  JSDemos/Demos/DropDownBox/MultipleSelection/jQuery/index.js
  JSDemos/Demos/DropDownBox/SingleSelection/AngularJS/index.js
  JSDemos/Demos/DropDownBox/SingleSelection/Knockout/index.js
  JSDemos/Demos/DropDownBox/SingleSelection/jQuery/index.js
  JSDemos/Demos/List/ItemDragging/React/App.js
  JSDemos/Demos/Localization/UsingGlobalize/AngularJS/index.js
  JSDemos/Demos/Localization/UsingGlobalize/Knockout/index.js
  JSDemos/Demos/Localization/UsingGlobalize/jQuery/index.js
  JSDemos/Demos/Localization/UsingIntl/AngularJS/index.js
  JSDemos/Demos/Localization/UsingIntl/Knockout/index.js
  JSDemos/Demos/Localization/UsingIntl/React/App.js
  JSDemos/Demos/Localization/UsingIntl/Vue/App.vue
  JSDemos/Demos/Localization/UsingIntl/jQuery/index.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/App.js
  JSDemos/Demos/Scheduler/CustomDragAndDrop/React/App.js
  JSDemos/Demos/Scheduler/CustomTemplates/React/App.js
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/App.vue
  JSDemos/Demos/Scheduler/TimeZonesSupport/React/App.js
  JSDemos/Demos/Slider/Overview/Knockout/index.js
  JSDemos/Demos/Sortable/Kanban/React/App.js
  JSDemos/Demos/Sortable/Kanban/jQuery/index.js
  JSDemos/Demos/TabPanel/SortableClosableTabs/jQuery/index.js
  JSDemos/Demos/TreeList/LoadDataOnDemand/test-code.js
  JSDemos/Demos/TreeList/LocalReordering/React/App.js
  JSDemos/Demos/TreeList/LocalReordering/Vue/App.vue
  JSDemos/Demos/TreeList/MultipleRowSelection/React/App.js
  JSDemos/Demos/TreeList/MultipleRowSelection/Vue/App.vue
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/jQuery/index.js
  JSDemos/Demos/TreeView/LoadDataOnDemand/test-code.js
Labels: 21_2

#1298 Enable 'no-return-assign' eslint rule
  .eslintrc.js
  JSDemos/Demos/ActionSheet/Basics/test-code.js
  JSDemos/Demos/Charts/ExportCustomMarkup/React/Form.js
  JSDemos/Demos/DataGrid/CommandColumnCustomization/React/data.js
  JSDemos/Demos/DataGrid/CommandColumnCustomization/Vue/data.js
  JSDemos/Demos/DataGrid/Filtering/React/App.js
  JSDemos/Demos/DataGrid/FilteringAPI/React/App.js
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/React/App.js
  JSDemos/Demos/DataGrid/MultipleSorting/React/App.js
  JSDemos/Demos/Drawer/LeftOrRightPosition/Vue/App.vue
  JSDemos/Demos/Drawer/TopOrBottomPosition/Vue/App.vue
  JSDemos/Demos/DropDownBox/MultipleSelection/React/App.js
  JSDemos/Demos/DropDownBox/SingleSelection/React/App.js
  JSDemos/Demos/FloatingActionButton/Overview/React/App.js
  JSDemos/Demos/Form/ColumnsAdaptability/test-code.js
  JSDemos/Demos/LoadIndicator/Overview/test-code.js
  JSDemos/Demos/PivotGrid/ChartIntegration/React/App.js
  JSDemos/Demos/PivotGrid/Overview/React/App.js
  JSDemos/Demos/RangeSelector/UseRangeSelectionForCalculation/test-code.js
  JSDemos/Demos/ScrollView/Overview/test-code.js
Labels: 21_2

#1275 Fix React test: TreeList - LoadDataOnDemand
  JSDemos/Demos/TreeList/LoadDataOnDemand/test-code.js
  JSDemos/Demos/TreeList/LoadDataOnDemand/visualtestrc.json
Labels: 21_2

#1290 Charts-Palette: fix layout
  JSDemos/Demos/Charts/Palette/Angular/app/app.component.css
  JSDemos/Demos/Charts/Palette/AngularJS/styles.css
  JSDemos/Demos/Charts/Palette/React/styles.css
  JSDemos/Demos/Charts/Palette/Vue/App.vue
  JSDemos/Demos/Charts/Palette/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Charts/Palette.css
  NetCoreDemos/wwwroot/css/DemosStyles/Charts/Palette.css
Labels: 21_2

#1291 Fix test: DataGrid-RealTimeUpdates
  JSDemos/Demos/DataGrid/RealTimeUpdates/test-styles.css
  JSDemos/Demos/DataGrid/RealTimeUpdates/visualtestrc.json
  testing/etalons/DataGrid-RealTimeUpdates.png
Labels: 21_2

#1274 Fix React test: Datagrid-SignalRService
  JSDemos/Demos/DataGrid/SignalRService/test-code.js
  JSDemos/Demos/DataGrid/SignalRService/visualtestrc.json
Labels: 21_2

#1300 Enable 'no-throw-literal' eslint rule
  .eslintrc.js
  JSDemos/Demos/Charts/BarSparklines/React/App.js
  JSDemos/Demos/Charts/BarSparklines/Vue/App.vue
  JSDemos/Demos/Charts/ClientSideDataProcessing/React/App.js
  JSDemos/Demos/Charts/ClientSideDataProcessing/Vue/App.vue
  JSDemos/Demos/DataGrid/CustomDataSource/React/App.js
  JSDemos/Demos/DataGrid/CustomDataSource/Vue/App.vue
  JSDemos/Demos/DataGrid/SignalRService/test-code.js
  JSDemos/Demos/Diagram/Adaptability/React/App.js
  JSDemos/Demos/Diagram/Adaptability/Vue/App.vue
  JSDemos/Demos/Diagram/Containers/React/App.js
  JSDemos/Demos/Diagram/Containers/Vue/App.vue
  JSDemos/Demos/Diagram/CustomShapesWithIcons/React/App.js
  JSDemos/Demos/Diagram/CustomShapesWithIcons/Vue/App.vue
  JSDemos/Demos/Diagram/CustomShapesWithTexts/React/App.js
  JSDemos/Demos/Diagram/CustomShapesWithTexts/Vue/App.vue
  JSDemos/Demos/Diagram/Overview/React/App.js
  JSDemos/Demos/Diagram/Overview/Vue/App.vue
  JSDemos/Demos/Diagram/ReadOnly/React/App.js
  JSDemos/Demos/Diagram/ReadOnly/Vue/App.vue
  JSDemos/Demos/Diagram/UICustomization/React/App.js
  JSDemos/Demos/Diagram/UICustomization/Vue/App.vue
  JSDemos/Demos/TreeList/LoadDataOnDemand/React/App.js
  JSDemos/Demos/TreeList/LoadDataOnDemand/Vue/App.vue
  JSDemos/Demos/TreeView/LoadDataOnDemand/React/App.js
  JSDemos/Demos/TreeView/LoadDataOnDemand/Vue/App.vue
Labels: 21_2

#1299 Enable 'default-case' eslint rule
  .eslintrc.js
  JSDemos/Demos/Charts/LogarithmicAxis/AngularJS/index.js
  JSDemos/Demos/Charts/LogarithmicAxis/Knockout/index.js
  JSDemos/Demos/Charts/LogarithmicAxis/React/App.js
  JSDemos/Demos/Charts/LogarithmicAxis/Vue/App.vue
  JSDemos/Demos/Charts/LogarithmicAxis/jQuery/index.js
  JSDemos/Demos/DataGrid/EditStateManagement/Vue/store.js
  JSDemos/Demos/DataGrid/EditStateManagement/jQuery/index.js
  JSDemos/Demos/FileManager/CustomThumbnails/React/App.js
  JSDemos/Demos/FileManager/CustomThumbnails/Vue/App.vue
  JSDemos/Demos/FileManager/CustomThumbnails/jQuery/index.js
  JSDemos/Demos/TreeView/ContextMenuIntegration/AngularJS/index.js
  JSDemos/Demos/TreeView/ContextMenuIntegration/React/App.js
  JSDemos/Demos/TreeView/ContextMenuIntegration/Vue/App.vue
  JSDemos/Demos/TreeView/ContextMenuIntegration/jQuery/index.js
Labels: 21_2

#1297 Enable 'prefer-rest-params' eslint rule
  .eslintrc.js
  JSDemos/Demos/DataGrid/Filtering/AngularJS/index.js
  JSDemos/Demos/DataGrid/Filtering/Knockout/index.js
  JSDemos/Demos/DataGrid/Filtering/React/App.js
  JSDemos/Demos/DataGrid/Filtering/Vue/App.vue
  JSDemos/Demos/DataGrid/Filtering/jQuery/index.js
  JSDemos/Demos/Localization/UsingGlobalize/Knockout/index.js
Labels: 21_2

#1303 Enable 'vars-on-top' eslint rule
  .eslintrc.js
Labels: 21_2

#1305 Enabled import-related eslint rules
  .eslintrc.js
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/Vue/App.vue
  JSDemos/Demos/Localization/UsingGlobalize/React/App.js
  JSDemos/Demos/Localization/UsingGlobalize/Vue/App.vue
  JSDemos/Demos/Localization/UsingIntl/React/App.js
  JSDemos/Demos/Localization/UsingIntl/Vue/App.vue
Labels: 21_2

#1302 Enable 'no-void' eslint rule
  .eslintrc.js
  JSDemos/Demos/DataGrid/MultipleSorting/React/App.js
  JSDemos/Demos/DataGrid/MultipleSorting/Vue/App.vue
  JSDemos/Demos/TreeList/LoadDataOnDemand/test-code.js
Labels: 21_2

#1304 Enable 'import/order' eslint rule
  .eslintrc.js
  JSDemos/Demos/DataGrid/ExportToPDF/React/App.js
  JSDemos/Demos/DataGrid/ExportToPDF/Vue/App.vue
Labels: 21_2

#1268 CheckBox: add example with iconSize
  JSDemos/Demos/CheckBox/Overview/Angular/app/app.component.html
  JSDemos/Demos/CheckBox/Overview/Angular/app/app.component.ts
  JSDemos/Demos/CheckBox/Overview/React/App.js
  JSDemos/Demos/CheckBox/Overview/Vue/App.vue
  JSDemos/Demos/CheckBox/Overview/jQuery/index.html
  JSDemos/Demos/CheckBox/Overview/jQuery/index.js
  MVCDemos/Views/CheckBox/Overview.cshtml
  NetCoreDemos/Views/CheckBox/Overview.cshtml
  testing/etalons/CheckBox-Overview.png
Labels: 21_2

#1310 Text comparison improvements; Test-specific settings; Visualtestrc autocompletion
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
  JSDemos/Demos/Button/Icons/visualtestrc.json
  JSDemos/Demos/Charts/PieWithResolvedLabelOverlapping/visualtestrc.json
  JSDemos/Demos/Common/StylingMode/visualtestrc.json
  JSDemos/Demos/DataGrid/DeferredSelection/visualtestrc.json
  JSDemos/Demos/Gantt/ChartAppearance/visualtestrc.json
  JSDemos/Demos/Gantt/ContextMenu/visualtestrc.json
  JSDemos/Demos/Gantt/TaskTemplate/visualtestrc.json
  JSDemos/Demos/Gantt/Validation/visualtestrc.json
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypes/visualtestrc.json
  JSDemos/Demos/PivotGrid/IntegratedFieldChooser/visualtestrc.json
  JSDemos/Demos/PivotGrid/LayoutCustomization/visualtestrc.json
  JSDemos/Demos/PivotGrid/Overview/visualtestrc.json
  JSDemos/Demos/ScrollView/Overview/visualtestrc.json
  JSDemos/Demos/TreeList/FilterModes/visualtestrc.json
  JSDemos/Demos/TreeList/Overview/visualtestrc.json
  package-lock.json
  package.json
  testing/common.test.js
  testing/visualtestrc-schema.json
  utils/tests/testcafe-helpers/matrix-test-helper.test.js
Labels: 21_2

#1315 dxScheduler - remove line-height rule in agenda
  testing/etalons/Scheduler-Agenda.png
Labels: 21_2

#1308 Fix Vue test: Button-Icons
  JSDemos/Demos/Button/Icons/Angular/app/app.component.css
  JSDemos/Demos/Button/Icons/Angular/app/app.component.html
  JSDemos/Demos/Button/Icons/AngularJS/index.html
  JSDemos/Demos/Button/Icons/AngularJS/styles.css
  JSDemos/Demos/Button/Icons/Knockout/index.html
  JSDemos/Demos/Button/Icons/Knockout/styles.css
  JSDemos/Demos/Button/Icons/React/App.js
  JSDemos/Demos/Button/Icons/React/styles.css
  JSDemos/Demos/Button/Icons/Vue/App.vue
  JSDemos/Demos/Button/Icons/jQuery/index.html
  JSDemos/Demos/Button/Icons/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Button/Icons.css
  MVCDemos/Views/Button/Icons.cshtml
  NetCoreDemos/Views/Button/Icons.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Button/Icons.css
  testing/etalons/Button-Icons.png
Labels: 21_2

#1278 Fix Vue test: Common-StylingMode
  JSDemos/Demos/Common/StylingMode/Angular/app/app.component.css
  JSDemos/Demos/Common/StylingMode/Angular/app/app.component.html
  JSDemos/Demos/Common/StylingMode/AngularJS/index.html
  JSDemos/Demos/Common/StylingMode/AngularJS/styles.css
  JSDemos/Demos/Common/StylingMode/React/App.js
  JSDemos/Demos/Common/StylingMode/React/styles.css
  JSDemos/Demos/Common/StylingMode/Vue/App.vue
  JSDemos/Demos/Common/StylingMode/jQuery/index.html
  JSDemos/Demos/Common/StylingMode/jQuery/styles.css
  JSDemos/Demos/Common/StylingMode/visualtestrc.json
  MVCDemos/Content/DemosStyles/Common/StylingMode.css
  MVCDemos/Views/Common/StylingMode.cshtml
  NetCoreDemos/Views/Common/StylingMode.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Common/StylingMode.css
  testing/etalons/Common-StylingMode.png
Labels: 21_2

#1316 Use devextreme-screenshot-comparer@2.0.6
  package-lock.json
  package.json
Labels: 21_2

#1318 Get rid of extra ignore at visualtestrc.json
  JSDemos/Demos/DataGrid/DeferredSelection/visualtestrc.json
  JSDemos/Demos/Gantt/ChartAppearance/visualtestrc.json
  JSDemos/Demos/Gantt/ContextMenu/visualtestrc.json
  JSDemos/Demos/Gantt/Validation/visualtestrc.json
  JSDemos/Demos/PivotGrid/IntegratedFieldChooser/visualtestrc.json
  JSDemos/Demos/PivotGrid/LayoutCustomization/visualtestrc.json
  JSDemos/Demos/PivotGrid/Overview/visualtestrc.json
  JSDemos/Demos/TreeList/FilterModes/visualtestrc.json
  JSDemos/Demos/TreeList/Overview/visualtestrc.json
Labels: 21_2

#1319 Fix React test: Treelist-FilterModes
  JSDemos/Demos/TreeList/FilterModes/React/App.js
  JSDemos/Demos/TreeList/FilterModes/visualtestrc.json
Labels: 21_2

#1320 Fix React test: Gauges-DifferentSubvalueIndicatorTypes
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypes/React/App.js
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypes/React/index.html
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypes/Vue/index.html
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypes/test-styles.css
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypes/visualtestrc.json
Labels: 21_2

#1321 Get rid of unnecessary `visualtestrc.json` files
  JSDemos/Demos/Button/Icons/visualtestrc.json
  JSDemos/Demos/Charts/PieWithResolvedLabelOverlapping/visualtestrc.json
  JSDemos/Demos/DataGrid/DeferredSelection/visualtestrc.json
  JSDemos/Demos/Gantt/ChartAppearance/visualtestrc.json
  JSDemos/Demos/Gantt/ContextMenu/visualtestrc.json
  JSDemos/Demos/Gantt/Validation/visualtestrc.json
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypes/visualtestrc.json
  JSDemos/Demos/PivotGrid/IntegratedFieldChooser/visualtestrc.json
  JSDemos/Demos/PivotGrid/Overview/visualtestrc.json
  JSDemos/Demos/ScrollView/Overview/visualtestrc.json
  JSDemos/Demos/TreeList/FilterModes/visualtestrc.json
  JSDemos/Demos/TreeList/Overview/visualtestrc.json
Labels: 21_2

#1136 Lookup Basics: rewrite
  JSDemos/Demos/Lookup/Basics/description.md
  JSDemos/Demos/SelectBox/GroupedItems/description.md
  JSDemos/menuMeta.json
Labels: 21_1

#1322 Fix single quotes error: Button-Icons
  MVCDemos/Views/Button/Icons.cshtml
  NetCoreDemos/Views/Button/Icons.cshtml
Labels: 21_2

#1241 Fix peer deps problem in renovate bot
  .npmrc
Labels: 21_2

#1325 Common-Stylingmode: make a left and right containers the same width
  JSDemos/Demos/Common/StylingMode/Angular/app/app.component.css
  JSDemos/Demos/Common/StylingMode/AngularJS/styles.css
  JSDemos/Demos/Common/StylingMode/React/styles.css
  JSDemos/Demos/Common/StylingMode/Vue/App.vue
  JSDemos/Demos/Common/StylingMode/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Common/StylingMode.css
  NetCoreDemos/wwwroot/css/DemosStyles/Common/StylingMode.css
  testing/etalons/Common-StylingMode.png
Labels: 21_2

#1326 DataGrid - ExportToPDF demo - remove unnecessary button
  JSDemos/Demos/DataGrid/ExportToPDF/jQuery/index.js
Labels: 21_2

#1323 Lookup Basics: rewrite
  JSDemos/Demos/Lookup/Basics/description.md
  JSDemos/Demos/SelectBox/GroupedItems/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 21_2

#1247 Fix scheduler demo
  JSDemos/Demos/Scheduler/Adaptability/Vue/App.vue
Labels: 21_1

#1336 DataGrid - Edit State Management: Remove CTP note
  JSDemos/Demos/DataGrid/EditStateManagement/Angular/description.md
  JSDemos/Demos/DataGrid/EditStateManagement/React/description.md
  JSDemos/Demos/DataGrid/EditStateManagement/Vue/description.md
Labels: 21_1

#1337 DataGrid - Edit State Management: Remove CTP note (#1336)
  JSDemos/Demos/DataGrid/EditStateManagement/Angular/description.md
  JSDemos/Demos/DataGrid/EditStateManagement/React/description.md
  JSDemos/Demos/DataGrid/EditStateManagement/Vue/description.md
Labels: cherry-pick, 21_2

#1222 dxScheduler - refactor grid's CSS
  testing/etalons/Scheduler-Adaptability.png
  testing/etalons/Scheduler-CellTemplates.png
  testing/etalons/Scheduler-ContextMenuIntegration.png
  testing/etalons/Scheduler-CurrentTimeIndicator.png
  testing/etalons/Scheduler-CustomDragAndDrop.png
  testing/etalons/Scheduler-CustomTemplates.png
  testing/etalons/Scheduler-CustomizeIndividualViews.png
  testing/etalons/Scheduler-Editing.png
  testing/etalons/Scheduler-GoogleCalendarIntegration.png
  testing/etalons/Scheduler-GroupByDate.png
  testing/etalons/Scheduler-GroupOrientation.png
  testing/etalons/Scheduler-IncreaseViewDuration.png
  testing/etalons/Scheduler-LimitAppointmentCountPerCell.png
  testing/etalons/Scheduler-Overview.png
  testing/etalons/Scheduler-RecurringAppointments.png
  testing/etalons/Scheduler-Resources.png
  testing/etalons/Scheduler-SimpleArray.png
  testing/etalons/Scheduler-TimeZonesSupport.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_cell_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_header_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_init.png
Labels: 21_2

#1342 CheckBox: update AngularJS demo
  JSDemos/Demos/CheckBox/Overview/AngularJS/index.html
  JSDemos/Demos/CheckBox/Overview/AngularJS/index.js
Labels: 21_2

#1343 Enable 'no-param-reassign' rule. (allow props for now)
  .eslintrc.js
  JSDemos/Demos/Charts/LoadDataOnDemand/React/App.js
  JSDemos/Demos/Charts/LoadDataOnDemand/Vue/App.vue
  JSDemos/Demos/DataGrid/CRUDOperations/AngularJS/index.js
  JSDemos/Demos/DataGrid/CRUDOperations/React/App.js
  JSDemos/Demos/DataGrid/CRUDOperations/Vue/App.vue
  JSDemos/Demos/DataGrid/CRUDOperations/jQuery/index.js
  JSDemos/Demos/DataGrid/EditStateManagement/React/utils.js
  JSDemos/Demos/DataGrid/EditStateManagement/Vue/utils.js
  JSDemos/Demos/DataGrid/EditStateManagement/jQuery/index.js
  JSDemos/Demos/Diagram/ItemSelection/React/App.js
  JSDemos/Demos/Diagram/ItemSelection/Vue/App.vue
  JSDemos/Demos/FileManager/UICustomization/React/App.js
  JSDemos/Demos/FileManager/UICustomization/Vue/App.vue
  JSDemos/Demos/FileManager/UICustomization/jQuery/index.js
  JSDemos/Demos/FilterBuilder/Customization/AngularJS/index.js
  JSDemos/Demos/FilterBuilder/Customization/React/helpers.js
  JSDemos/Demos/FilterBuilder/Customization/Vue/helpers.js
  JSDemos/Demos/FilterBuilder/Customization/jQuery/data.js
  JSDemos/Demos/FilterBuilder/Customization/jQuery/index.js
  JSDemos/Demos/Scheduler/SignalRService/signalr-session-id.js
  JSDemos/Demos/Sortable/Kanban/React/App.js
  JSDemos/Demos/VectorMap/CustomProjection/React/App.js
  JSDemos/Demos/VectorMap/CustomProjection/Vue/App.vue
Labels: 21_2

#1172 LookUp Event Handling: rewrite
  JSDemos/Demos/Lookup/EventHandling/description.md
  JSDemos/menuMeta.json
Labels: 21_1

#1349 Improve width\height calculation in size helpers
  testing/etalons/PivotGrid-ExcelJsHeaderAndFooter.png
  testing/etalons/PivotGrid-FieldPanel.png
  testing/etalons/PivotGrid-HeaderFilter.png
  testing/etalons/PivotGrid-RemoteVirtualScrolling.png
  testing/etalons/PivotGrid-StatePersistence.png
Labels: 21_2

#1354 LookUp Event Handling: rewrite (#1172)
  JSDemos/Demos/Lookup/EventHandling/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 21_2

#1355 DataGrid toolbar customization: description for non-jQuery frameworks
  JSDemos/Demos/DataGrid/ToolbarCustomization/description.md
  JSDemos/Demos/DataGrid/ToolbarCustomization/jQuery/description.md
Labels: 21_2

#1330 DataGrid - fix MultipleRecordSelectionAPI
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/jQuery/index.js
  MVCDemos/Views/DataGrid/MultipleRecordSelectionAPI.cshtml
  NetCoreDemos/Views/DataGrid/MultipleRecordSelectionAPI.cshtml
Labels: 21_2

#1362 DataGrid: Improve virtual scrolling performance by setting prerenderedRowChunkSize to 1
  testing/etalons/DataGrid-RemoteVirtualScrolling.png
Labels: 21_2

#1372 DataGrid & PivotGrid: Fix a note about export to CSV
  JSDemos/Demos/DataGrid/ExcelJSOverview/description.md
  JSDemos/Demos/PivotGrid/ExcelJSOverview/description.md
Labels: 21_1

#1373 DataGrid & PivotGrid: Fix a note about export to CSV
  JSDemos/Demos/DataGrid/ExcelJSOverview/description.md
  JSDemos/Demos/PivotGrid/ExcelJSOverview/description.md
Labels: cherry-pick, 21_2

#1376 Rewrite the 'PivotGrid - Chart Integration' demo description (#1329)
  JSDemos/Demos/PivotGrid/ChartIntegration/React/description.md
  JSDemos/Demos/PivotGrid/ChartIntegration/Vue/description.md
  JSDemos/Demos/PivotGrid/ChartIntegration/description.md
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#1385 DataGrid - MultipleRecordSelectionApi - fix MVC and NETCore
  MVCDemos/Views/DataGrid/MultipleRecordSelectionAPI.cshtml
  NetCoreDemos/Views/DataGrid/MultipleRecordSelectionAPI.cshtml
Labels: 21_2

#1384 DataGrid: Disable renovation
  JSDemos/Demos/DataGrid/SignalRService/test-code.js
Labels: 21_2

#1386 pivotgrid: fix configuration for running totals demo
  JSDemos/Demos/PivotGrid/RunningTotals/Angular/app/app.component.html
  JSDemos/Demos/PivotGrid/RunningTotals/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/RunningTotals/AngularJS/index.html
  JSDemos/Demos/PivotGrid/RunningTotals/AngularJS/index.js
  JSDemos/Demos/PivotGrid/RunningTotals/Knockout/index.html
  JSDemos/Demos/PivotGrid/RunningTotals/Knockout/index.js
  JSDemos/Demos/PivotGrid/RunningTotals/React/App.js
  JSDemos/Demos/PivotGrid/RunningTotals/Vue/App.vue
  JSDemos/Demos/PivotGrid/RunningTotals/jQuery/index.html
  JSDemos/Demos/PivotGrid/RunningTotals/jQuery/index.js
  MVCDemos/Views/PivotGrid/RunningTotals.cshtml
  NetCoreDemos/Views/PivotGrid/RunningTotals.cshtml
  testing/etalons/PivotGrid-RunningTotals.png
Labels: 21_2

#1387 pivotgrid: fix configuration for running totals demo
  JSDemos/Demos/PivotGrid/RunningTotals/Angular/app/app.component.html
  JSDemos/Demos/PivotGrid/RunningTotals/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/RunningTotals/AngularJS/index.html
  JSDemos/Demos/PivotGrid/RunningTotals/AngularJS/index.js
  JSDemos/Demos/PivotGrid/RunningTotals/Knockout/index.html
  JSDemos/Demos/PivotGrid/RunningTotals/Knockout/index.js
  JSDemos/Demos/PivotGrid/RunningTotals/React/App.js
  JSDemos/Demos/PivotGrid/RunningTotals/Vue/App.vue
  JSDemos/Demos/PivotGrid/RunningTotals/jQuery/index.html
  JSDemos/Demos/PivotGrid/RunningTotals/jQuery/index.js
  MVCDemos/Views/PivotGrid/RunningTotals.cshtml
  NetCoreDemos/Views/PivotGrid/RunningTotals.cshtml
Labels: 21_1, cherry-pick

#1388 tabpanel: fix sortable closable tabs demo for Vue v.3 (T1032472)
  JSDemos/Demos/TabPanel/SortableClosableTabs/Vue/App.vue
Labels: 21_2

#1389 tabpanel: fix sortable closable tabs demo for Vue v.3 (T1032472)
  JSDemos/Demos/TabPanel/SortableClosableTabs/Vue/App.vue
Labels: 21_1, cherry-pick

#1393 dxScheduler - Add style import to custom-DND demo
  MVCDemos/DevExtreme.MVC.Demos.csproj
Labels: 21_2

#1394 dxVectorMap - Fix React Overview demo
  JSDemos/Demos/VectorMap/Overview/React/App.js
Labels: 20_2

#1396 dxVectorMap - Fix VectorMap Tooltip demo for React
  JSDemos/Demos/VectorMap/TooltipHTMLSupport/React/App.js
Labels: 21_1
