Repository DevExpress/devextreme-demos, pull requests merged in 2021-04, with the labels that each got.

#708 Update HtmlEditor category name and badges
  JSDemos/menuMeta.json
Labels: 21_1

#709 Fix issue with null values (T986631) (cherry-pick)
  MVCDemos/Views/DropDownBox/SingleSelection.cshtml
  NetCoreDemos/Views/DropDownBox/SingleSelection.cshtml
Labels: 20_2, cherry-pick

#710 Fix issue with null values (T986631)
  MVCDemos/Views/DropDownBox/SingleSelection.cshtml
  NetCoreDemos/Views/DropDownBox/SingleSelection.cshtml
Labels: 21_1

#719 File Manager - Fix 'Documentation' links in demo description
  JSDemos/menuMeta.json
Labels: 21_1

#714 Remove CTP from Edit State Management demo name and description
  JSDemos/Demos/DataGrid/EditStateManagement/description.md
  JSDemos/menuMeta.json
Labels: 21_1

#721 Fix vdom version (1.0.2)
  package.json
Labels: 21_1

#723 File Management - Update demo badges
  JSDemos/menuMeta.json
Labels: 21_1

#724 Update navigation badges
  JSDemos/menuMeta.json
Labels: 21_1

#707 Improve pager demo
  JSDemos/Demos/DataGrid/RecordPaging/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/RecordPaging/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/RecordPaging/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/RecordPaging/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/RecordPaging/AngularJS/data.js
  JSDemos/Demos/DataGrid/RecordPaging/AngularJS/index.html
  JSDemos/Demos/DataGrid/RecordPaging/AngularJS/index.js
  JSDemos/Demos/DataGrid/RecordPaging/AngularJS/styles.css
  JSDemos/Demos/DataGrid/RecordPaging/React/App.js
  JSDemos/Demos/DataGrid/RecordPaging/React/data.js
  JSDemos/Demos/DataGrid/RecordPaging/React/index.html
  JSDemos/Demos/DataGrid/RecordPaging/React/styles.css
  JSDemos/Demos/DataGrid/RecordPaging/Vue/App.vue
  JSDemos/Demos/DataGrid/RecordPaging/Vue/data.js
  JSDemos/Demos/DataGrid/RecordPaging/Vue/index.html
  JSDemos/Demos/DataGrid/RecordPaging/Vue/styles.css
  JSDemos/Demos/DataGrid/RecordPaging/jQuery/data.js
  JSDemos/Demos/DataGrid/RecordPaging/jQuery/index.html
  JSDemos/Demos/DataGrid/RecordPaging/jQuery/index.js
  JSDemos/Demos/DataGrid/RecordPaging/jQuery/styles.css
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/DataGrid/RecordPaging.css
  MVCDemos/Views/DataGrid/RecordPaging.cshtml
  NetCoreDemos/Views/DataGrid/RecordPaging.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/RecordPaging.css
Labels: 21_1

#730 Rework the Toast demo for Angular/React/Vue (CP #706)
  JSDemos/Demos/Toast/Overview/Angular/app/app.component.css
  JSDemos/Demos/Toast/Overview/Angular/app/app.component.html
  JSDemos/Demos/Toast/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Toast/Overview/React/App.js
  JSDemos/Demos/Toast/Overview/React/ProductItem.js
  JSDemos/Demos/Toast/Overview/React/styles.css
  JSDemos/Demos/Toast/Overview/Vue/App.vue
  JSDemos/Demos/Toast/Overview/Vue/ProductItem.vue
  JSDemos/Demos/Toast/Overview/jQuery/index.js
  MVCDemos/Views/Toast/Overview.cshtml
  NetCoreDemos/Views/Toast/Overview.cshtml
Labels: 20_2, cherry-pick

#733 Remove extra styles for gauge from demo(after fix T922904)
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/Angular/app/app.component.css
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/AngularJS/styles.css
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/Knockout/styles.css
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/React/styles.css
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/Vue/App.vue
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/jQuery/styles.css
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/Angular/app/app.component.css
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/AngularJS/styles.css
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/Knockout/styles.css
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/React/styles.css
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/Vue/App.vue
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Gauges/DifferentSubvalueIndicatorTypesLinearGauge.css
  MVCDemos/Content/DemosStyles/Gauges/DifferentValueIndicatorTypesLinearGauge.css
  NetCoreDemos/wwwroot/css/DemosStyles/Gauges/DifferentSubvalueIndicatorTypesLinearGauge.css
  NetCoreDemos/wwwroot/css/DemosStyles/Gauges/DifferentValueIndicatorTypesLinearGauge.css
Labels: 20_2, cherry-pick

#734 Remove extra styles for gauge from demo(after fix T922904)
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/Angular/app/app.component.css
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/AngularJS/styles.css
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/Knockout/styles.css
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/React/styles.css
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/Vue/App.vue
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/jQuery/styles.css
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/Angular/app/app.component.css
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/AngularJS/styles.css
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/Knockout/styles.css
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/React/styles.css
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/Vue/App.vue
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Gauges/DifferentSubvalueIndicatorTypesLinearGauge.css
  MVCDemos/Content/DemosStyles/Gauges/DifferentValueIndicatorTypesLinearGauge.css
  NetCoreDemos/wwwroot/css/DemosStyles/Gauges/DifferentSubvalueIndicatorTypesLinearGauge.css
  NetCoreDemos/wwwroot/css/DemosStyles/Gauges/DifferentValueIndicatorTypesLinearGauge.css
Labels: 21_1

#726 Increase minimal version of @devextreme/vdom
  package.json
Labels: 21_1

#731 Fix design issue
  JSDemos/Demos/DataGrid/RecordPaging/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/RecordPaging/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/RecordPaging/AngularJS/index.js
  JSDemos/Demos/DataGrid/RecordPaging/React/App.js
  JSDemos/Demos/DataGrid/RecordPaging/Vue/App.vue
  JSDemos/Demos/DataGrid/RecordPaging/jQuery/index.js
  MVCDemos/Views/DataGrid/RecordPaging.cshtml
  NetCoreDemos/Views/DataGrid/RecordPaging.cshtml
Labels: 21_1

#738 Remove 'Display mode' label
  JSDemos/Demos/DataGrid/RecordPaging/AngularJS/index.html
  JSDemos/Demos/DataGrid/RecordPaging/Vue/App.vue
  JSDemos/Demos/DataGrid/RecordPaging/jQuery/index.html
  MVCDemos/Views/DataGrid/RecordPaging.cshtml
  NetCoreDemos/Views/DataGrid/RecordPaging.cshtml
Labels: 21_1

#740 Update CSS selector names in the Toast demo
  JSDemos/Demos/Toast/Overview/Angular/app/app.component.css
  JSDemos/Demos/Toast/Overview/Angular/app/app.component.html
  JSDemos/Demos/Toast/Overview/React/App.js
  JSDemos/Demos/Toast/Overview/React/styles.css
  JSDemos/Demos/Toast/Overview/jQuery/index.html
  JSDemos/Demos/Toast/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Toast/Overview.css
  MVCDemos/Views/Toast/Overview.cshtml
  NetCoreDemos/Views/Toast/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Toast/Overview.css
Labels: 21_1

#741 Update CSS selector names in the Toast demo (CP #740)
  JSDemos/Demos/Toast/Overview/Angular/app/app.component.css
  JSDemos/Demos/Toast/Overview/Angular/app/app.component.html
  JSDemos/Demos/Toast/Overview/React/App.js
  JSDemos/Demos/Toast/Overview/React/styles.css
  JSDemos/Demos/Toast/Overview/jQuery/index.html
  JSDemos/Demos/Toast/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Toast/Overview.css
  MVCDemos/Views/Toast/Overview.cshtml
  NetCoreDemos/Views/Toast/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Toast/Overview.css
Labels: 20_2, cherry-pick

#742 Virtual scrolling demo
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/HorizontalVirtualScrolling/jQuery/data.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Angular/index.html
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/React/data.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/React/index.html
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/React/index.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Vue/data.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Vue/index.html
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/Vue/index.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/description.md
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/jQuery/data.js
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/jQuery/index.html
  JSDemos/Demos/Scheduler/VerticalVirtualScrolling/jQuery/index.js
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/index.html
  JSDemos/Demos/Scheduler/VirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/VirtualScrolling/React/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/React/index.html
  JSDemos/Demos/Scheduler/VirtualScrolling/React/index.js
  JSDemos/Demos/Scheduler/VirtualScrolling/React/styles.css
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/index.html
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/index.js
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/styles.css
  JSDemos/Demos/Scheduler/VirtualScrolling/description.md
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/index.html
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/index.js
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/styles.css
  JSDemos/menuMeta.json
Labels: 21_1

#743 dxScheduler - Fix date processing in .NET demos
  MVCDemos/Views/Scheduler/CustomTemplates.cshtml
  NetCoreDemos/Views/Scheduler/CustomTemplates.cshtml
Labels: 21_1

#748 Toolbar Demo - uses private API (T989864)
  JSDemos/Demos/Toolbar/Overview/jQuery/index.js
Labels: 21_1

#753 Adds the keyExpr option to the DataGrid config of the "Columns based on a Data Source" demo
  JSDemos/Demos/DataGrid/ColumnsBasedOnADataSource/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/ColumnsBasedOnADataSource/AngularJS/index.js
  JSDemos/Demos/DataGrid/ColumnsBasedOnADataSource/Knockout/index.js
  JSDemos/Demos/DataGrid/ColumnsBasedOnADataSource/React/App.js
  JSDemos/Demos/DataGrid/ColumnsBasedOnADataSource/Vue/App.vue
  JSDemos/Demos/DataGrid/ColumnsBasedOnADataSource/jQuery/index.js
  MVCDemos/Views/DataGrid/ColumnsBasedOnADataSource.cshtml
  NetCoreDemos/Views/DataGrid/ColumnsBasedOnADataSource.cshtml
Labels: 20_2, cherry-pick

#752 Adds the keyExpr option to the DataGrid config of the "Columns based on a Data Source" demo
  JSDemos/Demos/DataGrid/ColumnsBasedOnADataSource/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/ColumnsBasedOnADataSource/AngularJS/index.js
  JSDemos/Demos/DataGrid/ColumnsBasedOnADataSource/Knockout/index.js
  JSDemos/Demos/DataGrid/ColumnsBasedOnADataSource/React/App.js
  JSDemos/Demos/DataGrid/ColumnsBasedOnADataSource/Vue/App.vue
  JSDemos/Demos/DataGrid/ColumnsBasedOnADataSource/jQuery/index.js
  MVCDemos/Views/DataGrid/ColumnsBasedOnADataSource.cshtml
  NetCoreDemos/Views/DataGrid/ColumnsBasedOnADataSource.cshtml
Labels: 21_1

#757 DataGrid: Update demo badges
  JSDemos/menuMeta.json
Labels: 21_1

#760 Fix wrong colums setting
  JSDemos/Demos/DataGrid/RecordPaging/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/RecordPaging/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/RecordPaging/AngularJS/index.js
  JSDemos/Demos/DataGrid/RecordPaging/React/App.js
  JSDemos/Demos/DataGrid/RecordPaging/Vue/App.vue
  JSDemos/Demos/DataGrid/RecordPaging/jQuery/index.js
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/DataGrid/RecordPaging.cshtml
  NetCoreDemos/Views/DataGrid/RecordPaging.cshtml
Labels: 21_1

#750 dxScheduler - Virtual scrolling demo fix for react and vue
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/VirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/VirtualScrolling/React/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/index.js
Labels: 21_1

#727 dxScheduler - cut 'priority' from resource text in Agenda
  JSDemos/Demos/Scheduler/Agenda/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Agenda/AngularJS/data.js
  JSDemos/Demos/Scheduler/Agenda/React/data.js
  JSDemos/Demos/Scheduler/Agenda/Vue/data.js
  JSDemos/Demos/Scheduler/Agenda/jQuery/data.js
Labels: 21_1

#676 Support display .Net Backend files
  JSDemos/menuMeta.json
Labels: 20_2

#751 Form - Fix Adaptivity Demo (T989863)
  JSDemos/Demos/Form/ColumnsAdaptability/Angular/app/app.component.html
  JSDemos/Demos/Form/ColumnsAdaptability/Angular/app/app.component.ts
  JSDemos/Demos/Form/ColumnsAdaptability/AngularJS/index.js
  JSDemos/Demos/Form/ColumnsAdaptability/React/App.js
  JSDemos/Demos/Form/ColumnsAdaptability/Vue/App.vue
  JSDemos/Demos/Form/ColumnsAdaptability/jQuery/index.js
  MVCDemos/Views/Form/ColumnsAdaptability.cshtml
  NetCoreDemos/Views/Form/ColumnsAdaptability.cshtml
Labels: 21_1

#779 dxScheduler - Fix typo in resources
  JSDemos/Demos/Scheduler/Resources/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Resources/AngularJS/data.js
  JSDemos/Demos/Scheduler/Resources/Knockout/data.js
  JSDemos/Demos/Scheduler/Resources/React/data.js
  JSDemos/Demos/Scheduler/Resources/Vue/data.js
  JSDemos/Demos/Scheduler/Resources/jQuery/data.js
  MVCDemos/Models/SampleData/PriorityResources.cs
  NetCoreDemos/Models/SampleData/PriorityResources.cs
Labels: 21_1

#778 dxScheduler - Improve virtual-scrolling demos
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/VirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/index.js
  MVCDemos/Content/DemosStyles/Scheduler/VirtualScrolling.css
  MVCDemos/Views/Scheduler/VirtualScrolling.cshtml
  NetCoreDemos/Views/Scheduler/VirtualScrolling.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/VirtualScrolling.css
Labels: 21_1

#747 dxScheduler - Fix context menu integration bug (T989358)
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/ContextMenuIntegration/AngularJS/index.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/React/App.js
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/App.vue
  JSDemos/Demos/Scheduler/ContextMenuIntegration/jQuery/index.js
  MVCDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  NetCoreDemos/Views/Scheduler/ContextMenuIntegration.cshtml
Labels: 21_1

#789 Update Showdown version
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/Knockout/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/index.html
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
Labels: 21_1

#790 Update Showdown version
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/Knockout/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/index.html
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
Labels: 20_2, cherry-pick

#794 Support display .Net Backend files
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#791 Update vdom package
  package.json
Labels: 21_1

#798 File Manager - Fix 'Documentation' links in demo description
  JSDemos/menuMeta.json
Labels: 20_2, cherry-pick

#804 fix branch version
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  package.json
Labels: 21_2

#805 Revert "fix branch version"
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  package.json
Labels: 21_1

#806 fix branch version
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  package.json
Labels: 21_2

#810 dxScheduler - repair dates for screenshot tests
  JSDemos/Demos/Scheduler/Adaptability/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/Adaptability/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Adaptability/AngularJS/data.js
  JSDemos/Demos/Scheduler/Adaptability/AngularJS/index.js
  JSDemos/Demos/Scheduler/Adaptability/React/App.js
  JSDemos/Demos/Scheduler/Adaptability/React/data.js
  JSDemos/Demos/Scheduler/Adaptability/Vue/App.vue
  JSDemos/Demos/Scheduler/Adaptability/Vue/data.js
  JSDemos/Demos/Scheduler/Adaptability/jQuery/data.js
  JSDemos/Demos/Scheduler/Adaptability/jQuery/index.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/AngularJS/data.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/AngularJS/index.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/React/App.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/React/data.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Vue/App.vue
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Vue/data.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/jQuery/data.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/jQuery/index.js
  JSDemos/Demos/Scheduler/SimpleArray/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/SimpleArray/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/SimpleArray/AngularJS/data.js
  JSDemos/Demos/Scheduler/SimpleArray/AngularJS/index.js
  JSDemos/Demos/Scheduler/SimpleArray/Knockout/data.js
  JSDemos/Demos/Scheduler/SimpleArray/Knockout/index.js
  JSDemos/Demos/Scheduler/SimpleArray/React/App.js
  JSDemos/Demos/Scheduler/SimpleArray/React/data.js
  JSDemos/Demos/Scheduler/SimpleArray/Vue/App.vue
  JSDemos/Demos/Scheduler/SimpleArray/Vue/data.js
  JSDemos/Demos/Scheduler/SimpleArray/jQuery/data.js
  JSDemos/Demos/Scheduler/SimpleArray/jQuery/index.js
  MVCDemos/Models/SampleData/AdaptabilityAppointments.cs
  MVCDemos/Models/SampleData/LimitAppointmentCountPerCellAppointments.cs
  MVCDemos/Models/SampleData/SimpleArrayAppointments.cs
  MVCDemos/Views/Scheduler/Adaptability.cshtml
  MVCDemos/Views/Scheduler/LimitAppointmentCountPerCell.cshtml
  MVCDemos/Views/Scheduler/SimpleArray.cshtml
  NetCoreDemos/Models/SampleData/AdaptabilityAppointments.cs
  NetCoreDemos/Models/SampleData/LimitAppointmentCountPerCellAppointments.cs
  NetCoreDemos/Models/SampleData/SimpleArrayAppointments.cs
  NetCoreDemos/Views/Scheduler/Adaptability.cshtml
  NetCoreDemos/Views/Scheduler/LimitAppointmentCountPerCell.cshtml
  NetCoreDemos/Views/Scheduler/SimpleArray.cshtml
Labels: 21_1

#811 Syncronize vdom version with devextreme
  package.json
Labels: 21_1

#813 dxScheduler - add width to css in disabled dates demo
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/CellTemplates/React/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/Vue/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Scheduler/CellTemplates.css
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/CellTemplates.css
Labels: 21_1

#814 dxScheduler - add width to css in disabled dates demo
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/CellTemplates/React/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/Vue/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Scheduler/CellTemplates.css
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/CellTemplates.css
Labels: 20_2

#817 dxScheduler - repair dates for screenshot tests
  JSDemos/Demos/Scheduler/Adaptability/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/Adaptability/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Adaptability/AngularJS/data.js
  JSDemos/Demos/Scheduler/Adaptability/AngularJS/index.js
  JSDemos/Demos/Scheduler/Adaptability/React/App.js
  JSDemos/Demos/Scheduler/Adaptability/React/data.js
  JSDemos/Demos/Scheduler/Adaptability/Vue/App.vue
  JSDemos/Demos/Scheduler/Adaptability/Vue/data.js
  JSDemos/Demos/Scheduler/Adaptability/jQuery/data.js
  JSDemos/Demos/Scheduler/Adaptability/jQuery/index.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/AngularJS/data.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/AngularJS/index.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/React/App.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/React/data.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Vue/App.vue
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Vue/data.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/jQuery/data.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/jQuery/index.js
  JSDemos/Demos/Scheduler/SimpleArray/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/SimpleArray/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/SimpleArray/AngularJS/data.js
  JSDemos/Demos/Scheduler/SimpleArray/AngularJS/index.js
  JSDemos/Demos/Scheduler/SimpleArray/Knockout/data.js
  JSDemos/Demos/Scheduler/SimpleArray/Knockout/index.js
  JSDemos/Demos/Scheduler/SimpleArray/React/App.js
  JSDemos/Demos/Scheduler/SimpleArray/React/data.js
  JSDemos/Demos/Scheduler/SimpleArray/Vue/App.vue
  JSDemos/Demos/Scheduler/SimpleArray/Vue/data.js
  JSDemos/Demos/Scheduler/SimpleArray/jQuery/data.js
  JSDemos/Demos/Scheduler/SimpleArray/jQuery/index.js
  MVCDemos/Models/SampleData/AdaptabilityAppointments.cs
  MVCDemos/Models/SampleData/LimitAppointmentCountPerCellAppointments.cs
  MVCDemos/Models/SampleData/SimpleArrayAppointments.cs
  MVCDemos/Views/Scheduler/Adaptability.cshtml
  MVCDemos/Views/Scheduler/LimitAppointmentCountPerCell.cshtml
  MVCDemos/Views/Scheduler/SimpleArray.cshtml
  NetCoreDemos/Models/SampleData/AdaptabilityAppointments.cs
  NetCoreDemos/Models/SampleData/LimitAppointmentCountPerCellAppointments.cs
  NetCoreDemos/Models/SampleData/SimpleArrayAppointments.cs
  NetCoreDemos/Views/Scheduler/Adaptability.cshtml
  NetCoreDemos/Views/Scheduler/LimitAppointmentCountPerCell.cshtml
  NetCoreDemos/Views/Scheduler/SimpleArray.cshtml
Labels: 20_2, cherry-pick

#807 dxScheduler - Change appointment generator
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/VirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/VirtualScrolling/React/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/index.js
  MVCDemos/Views/Scheduler/VirtualScrolling.cshtml
  NetCoreDemos/Views/Scheduler/VirtualScrolling.cshtml
Labels: 21_1

#829 TreeList Adaptability: rewrite
  JSDemos/Demos/TreeList/Adaptability/description.md
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#826 TreeList Form Editing: rewrite (#758)
  JSDemos/Demos/DataGrid/FormEditing/description.md
  JSDemos/Demos/TreeList/FormEditing/description.md
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick
