Repository DevExpress/devextreme-demos, pull requests merged in 2021-05, with the labels that each got.

#816 Add possibility to run demos with bundles
  .gitignore
  JSDemos/configs/Angular/config.bundle.js
  JSDemos/configs/React/config.bundle.js
  JSDemos/configs/Vue/config.bundle.js
  README.md
  gulpfile.js/index.js
  gulpfile.js/js.js
  package.json
  utils/bundle/index.js
  utils/internal/create-config.js
Labels: 21_1

#830 Add possibility to run demos with bundles (#816)
  .gitignore
  JSDemos/configs/Angular/config.bundle.js
  JSDemos/configs/React/config.bundle.js
  JSDemos/configs/Vue/config.bundle.js
  README.md
  gulpfile.js/index.js
  gulpfile.js/js.js
  package.json
  utils/bundle/index.js
  utils/internal/create-config.js
Labels: 21_2, cherry-pick

#831 dxScheduler - replace Globalize on Intl in Template demo
  JSDemos/Demos/Scheduler/CustomTemplates/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/CustomTemplates/React/Appointment.js
  JSDemos/Demos/Scheduler/CustomTemplates/React/index.html
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/AppointmentTemplate.vue
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/index.html
  JSDemos/Demos/Scheduler/CustomTemplates/jQuery/index.html
  JSDemos/Demos/Scheduler/CustomTemplates/jQuery/index.js
Labels: 21_1

#835 dxScheduler - replace Globalize on Intl in Template demo
  JSDemos/Demos/Scheduler/CustomTemplates/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/CustomTemplates/React/Appointment.js
  JSDemos/Demos/Scheduler/CustomTemplates/React/index.html
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/AppointmentTemplate.vue
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/index.html
  JSDemos/Demos/Scheduler/CustomTemplates/jQuery/index.html
  JSDemos/Demos/Scheduler/CustomTemplates/jQuery/index.js
Labels: 21_2, cherry-pick

#836 Popover Overview: fix lint warnings [vue]
  JSDemos/Demos/Toast/Overview/Vue/ProductItem.vue
Labels: 21_2

#838 Popover Overview: fix lint warnings [vue]
  JSDemos/Demos/Toast/Overview/Vue/ProductItem.vue
Labels: 20_2

#837 Popover Overview: fix lint warnings [vue]
  JSDemos/Demos/Toast/Overview/Vue/ProductItem.vue
Labels: 21_2

#839 dxScheduler - fix localize import
  JSDemos/Demos/Scheduler/CustomTemplates/React/Appointment.js
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/AppointmentTemplate.vue
Labels: 21_1

#840 dxScheduler - fix localize import
  JSDemos/Demos/Scheduler/CustomTemplates/React/Appointment.js
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/AppointmentTemplate.vue
Labels: 21_2, cherry-pick

#818 dxScheduler - repair dates for screenshot tests
  JSDemos/Demos/Scheduler/Adaptability/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/Adaptability/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Adaptability/AngularJS/data.js
  JSDemos/Demos/Scheduler/Adaptability/AngularJS/index.js
  JSDemos/Demos/Scheduler/Adaptability/React/App.js
  JSDemos/Demos/Scheduler/Adaptability/React/data.js
  JSDemos/Demos/Scheduler/Adaptability/Vue/App.vue
  JSDemos/Demos/Scheduler/Adaptability/Vue/data.js
  JSDemos/Demos/Scheduler/Adaptability/jQuery/data.js
  JSDemos/Demos/Scheduler/Adaptability/jQuery/index.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/AngularJS/data.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/AngularJS/index.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/React/App.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/React/data.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Vue/App.vue
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Vue/data.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/jQuery/data.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/jQuery/index.js
  JSDemos/Demos/Scheduler/SimpleArray/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/SimpleArray/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/SimpleArray/AngularJS/data.js
  JSDemos/Demos/Scheduler/SimpleArray/AngularJS/index.js
  JSDemos/Demos/Scheduler/SimpleArray/Knockout/data.js
  JSDemos/Demos/Scheduler/SimpleArray/Knockout/index.js
  JSDemos/Demos/Scheduler/SimpleArray/React/App.js
  JSDemos/Demos/Scheduler/SimpleArray/React/data.js
  JSDemos/Demos/Scheduler/SimpleArray/Vue/App.vue
  JSDemos/Demos/Scheduler/SimpleArray/Vue/data.js
  JSDemos/Demos/Scheduler/SimpleArray/jQuery/data.js
  JSDemos/Demos/Scheduler/SimpleArray/jQuery/index.js
  MVCDemos/Models/SampleData/AdaptabilityAppointments.cs
  MVCDemos/Models/SampleData/LimitAppointmentCountPerCellAppointments.cs
  MVCDemos/Models/SampleData/SimpleArrayAppointments.cs
  MVCDemos/Views/Scheduler/Adaptability.cshtml
  MVCDemos/Views/Scheduler/LimitAppointmentCountPerCell.cshtml
  MVCDemos/Views/Scheduler/SimpleArray.cshtml
  NetCoreDemos/Models/SampleData/AdaptabilityAppointments.cs
  NetCoreDemos/Models/SampleData/LimitAppointmentCountPerCellAppointments.cs
  NetCoreDemos/Models/SampleData/SimpleArrayAppointments.cs
  NetCoreDemos/Views/Scheduler/Adaptability.cshtml
  NetCoreDemos/Views/Scheduler/LimitAppointmentCountPerCell.cshtml
  NetCoreDemos/Views/Scheduler/SimpleArray.cshtml
Labels: 21_2, cherry-pick

#822 dxScheduler - Change appointment generator (#807)
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/VirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/VirtualScrolling/React/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/index.js
  MVCDemos/Views/Scheduler/VirtualScrolling.cshtml
  NetCoreDemos/Views/Scheduler/VirtualScrolling.cshtml
Labels: 21_2, cherry-pick

#834 dxScheduler - import styles in MVC virtual scrolling demo
  MVCDemos/DevExtreme.MVC.Demos.csproj
Labels: 21_1

#841 dxScheduler - add styles to angular virtual scrolling demo
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.css
Labels: 21_1

#842 dxScheduler - add styles to angular virtual scrolling demo
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.css
Labels: 21_2, cherry-pick

#843 Fix bundle creation issues
  utils/bundle/index.js
  utils/internal/create-config.js
Labels: 21_1

#844 Fix bundle creation issues (#843)
  utils/bundle/index.js
  utils/internal/create-config.js
Labels: 21_2, cherry-pick

#824 TreeList State Persistence: update
  JSDemos/Demos/TreeList/StatePersistence/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#825 TreeList Batch Editing: rewrite
  JSDemos/Demos/DataGrid/BatchEditing/description.md
  JSDemos/Demos/TreeList/BatchEditing/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#827 TreeList Form Editing: rewrite (#758)
  JSDemos/Demos/DataGrid/FormEditing/description.md
  JSDemos/Demos/TreeList/FormEditing/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#828 TreeList Adaptability: rewrite
  JSDemos/Demos/TreeList/Adaptability/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#846 TreeList: Update Filter Panel (#780) and Column Chooser (#788) descriptions
  JSDemos/Demos/DataGrid/RemoteGrouping/description.md
  JSDemos/Demos/TreeList/ColumnChooser/description.md
  JSDemos/Demos/TreeList/FilterPanel/description.md
  JSDemos/menuMeta.json
Labels: 21_1

#833 dxScheduler - refactor virtual scrolling demo
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/VirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/VirtualScrolling/React/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/index.js
  MVCDemos/Views/Scheduler/VirtualScrolling.cshtml
  NetCoreDemos/Views/Scheduler/VirtualScrolling.cshtml
Labels: 21_1

#848 dxScheduler - refactor virtual scrolling demo
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/VirtualScrolling/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/VirtualScrolling/React/App.js
  JSDemos/Demos/Scheduler/VirtualScrolling/React/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/data.js
  JSDemos/Demos/Scheduler/VirtualScrolling/jQuery/index.js
  MVCDemos/Views/Scheduler/VirtualScrolling.cshtml
  NetCoreDemos/Views/Scheduler/VirtualScrolling.cshtml
Labels: 21_2, cherry-pick

#849 dxScheduler - import styles in MVC virtual scrolling demo
  MVCDemos/DevExtreme.MVC.Demos.csproj
Labels: 21_2, cherry-pick

#850 Fix vue bundle usage
  JSDemos/configs/Vue/config.bundle.js
  utils/bundle/index.js
Labels: 21_1

#851 Fix vue bundle usage
  JSDemos/configs/Vue/config.bundle.js
  utils/bundle/index.js
Labels: 21_2, cherry-pick

#853 add 'cjs' subfolder to devextreme path
  utils/bundle/index.js
Labels: 21_1

#856 Revert: Tree Shaking: Fix utils imports after switch package to esm
  JSDemos/Demos/Charts/Palette/Angular/app/app.component.ts
  JSDemos/Demos/Charts/Palette/React/App.js
  JSDemos/Demos/Charts/Palette/Vue/App.vue
  JSDemos/Demos/DataGrid/CRUDOperations/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/CRUDOperations/React/App.js
  JSDemos/Demos/DataGrid/CRUDOperations/Vue/App.vue
  JSDemos/Demos/DataGrid/CellCustomization/React/DiffCell.js
  JSDemos/Demos/DataGrid/CellCustomization/Vue/DiffCell.vue
  JSDemos/Demos/DataGrid/GridSummaries/React/App.js
  JSDemos/Demos/DataGrid/GridSummaries/Vue/App.vue
  JSDemos/Demos/Localization/UsingIntl/Angular/app/app.component.ts
  JSDemos/Demos/Localization/UsingIntl/React/App.js
  JSDemos/Demos/Localization/UsingIntl/Vue/App.vue
Labels: 21_1

#857 Revert: Tree Shaking: Fix utils imports after switch package to esm
  JSDemos/Demos/Charts/Palette/Angular/app/app.component.ts
  JSDemos/Demos/Charts/Palette/React/App.js
  JSDemos/Demos/Charts/Palette/Vue/App.vue
  JSDemos/Demos/DataGrid/CRUDOperations/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/CRUDOperations/React/App.js
  JSDemos/Demos/DataGrid/CRUDOperations/Vue/App.vue
  JSDemos/Demos/DataGrid/CellCustomization/React/DiffCell.js
  JSDemos/Demos/DataGrid/CellCustomization/Vue/DiffCell.vue
  JSDemos/Demos/DataGrid/GridSummaries/React/App.js
  JSDemos/Demos/DataGrid/GridSummaries/Vue/App.vue
  JSDemos/Demos/Localization/UsingIntl/Angular/app/app.component.ts
  JSDemos/Demos/Localization/UsingIntl/React/App.js
  JSDemos/Demos/Localization/UsingIntl/Vue/App.vue
Labels: 21_2, cherry-pick

#859 Remove regular expressions for config processing (bundles)
  JSDemos/configs/Angular/config.bundle.js
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.bundle.js
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.bundle.js
  JSDemos/configs/Vue/config.js
  utils/internal/create-config.js
Labels: 21_1

#863 Remove regular expressions for config processing (bundles) (#859)
  JSDemos/configs/Angular/config.bundle.js
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.bundle.js
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.bundle.js
  JSDemos/configs/Vue/config.js
  utils/internal/create-config.js
Labels: 21_2, cherry-pick

#866 Update react version
  package.json
Labels: 21_1

#867 Update react version (#866)
  package.json
Labels: 21_2, cherry-pick

#868 dxScheduler - Change dates in demos for screenshots tests
  JSDemos/Demos/Scheduler/GroupByDate/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/GroupByDate/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/GroupByDate/AngularJS/data.js
  JSDemos/Demos/Scheduler/GroupByDate/AngularJS/index.js
  JSDemos/Demos/Scheduler/GroupByDate/React/App.js
  JSDemos/Demos/Scheduler/GroupByDate/React/data.js
  JSDemos/Demos/Scheduler/GroupByDate/Vue/App.vue
  JSDemos/Demos/Scheduler/GroupByDate/Vue/data.js
  JSDemos/Demos/Scheduler/GroupByDate/jQuery/data.js
  JSDemos/Demos/Scheduler/GroupByDate/jQuery/index.js
  MVCDemos/Models/SampleData/GroupByDateTasks.cs
  MVCDemos/Views/Scheduler/GroupByDate.cshtml
  NetCoreDemos/Models/SampleData/GroupByDateTasks.cs
  NetCoreDemos/Views/Scheduler/GroupByDate.cshtml
Labels: 21_2

#869 dxScheduler - Change dates in demos for screenshots tests
  JSDemos/Demos/Scheduler/GroupByDate/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/GroupByDate/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/GroupByDate/AngularJS/data.js
  JSDemos/Demos/Scheduler/GroupByDate/AngularJS/index.js
  JSDemos/Demos/Scheduler/GroupByDate/React/App.js
  JSDemos/Demos/Scheduler/GroupByDate/React/data.js
  JSDemos/Demos/Scheduler/GroupByDate/Vue/App.vue
  JSDemos/Demos/Scheduler/GroupByDate/Vue/data.js
  JSDemos/Demos/Scheduler/GroupByDate/jQuery/data.js
  JSDemos/Demos/Scheduler/GroupByDate/jQuery/index.js
  MVCDemos/Models/SampleData/GroupByDateTasks.cs
  MVCDemos/Views/Scheduler/GroupByDate.cshtml
  NetCoreDemos/Models/SampleData/GroupByDateTasks.cs
  NetCoreDemos/Views/Scheduler/GroupByDate.cshtml
Labels: 21_1, cherry-pick

#870 dxScheduler - Change dates in demos for screenshots tests
  JSDemos/Demos/Scheduler/GroupByDate/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/GroupByDate/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/GroupByDate/AngularJS/data.js
  JSDemos/Demos/Scheduler/GroupByDate/AngularJS/index.js
  JSDemos/Demos/Scheduler/GroupByDate/React/App.js
  JSDemos/Demos/Scheduler/GroupByDate/React/data.js
  JSDemos/Demos/Scheduler/GroupByDate/Vue/App.vue
  JSDemos/Demos/Scheduler/GroupByDate/Vue/data.js
  JSDemos/Demos/Scheduler/GroupByDate/jQuery/data.js
  JSDemos/Demos/Scheduler/GroupByDate/jQuery/index.js
  MVCDemos/Models/SampleData/GroupByDateTasks.cs
  MVCDemos/Views/Scheduler/GroupByDate.cshtml
  NetCoreDemos/Models/SampleData/GroupByDateTasks.cs
  NetCoreDemos/Views/Scheduler/GroupByDate.cshtml
Labels: 20_2, cherry-pick

#871 Update vdom package (21.1)
  package.json
Labels: 21_1

#874 dxScheduler - fix dates in Group Orientation demo
  JSDemos/Demos/Scheduler/GroupOrientation/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/GroupOrientation/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/GroupOrientation/AngularJS/data.js
  JSDemos/Demos/Scheduler/GroupOrientation/AngularJS/index.js
  JSDemos/Demos/Scheduler/GroupOrientation/React/App.js
  JSDemos/Demos/Scheduler/GroupOrientation/React/data.js
  JSDemos/Demos/Scheduler/GroupOrientation/Vue/App.vue
  JSDemos/Demos/Scheduler/GroupOrientation/Vue/data.js
  JSDemos/Demos/Scheduler/GroupOrientation/jQuery/data.js
  JSDemos/Demos/Scheduler/GroupOrientation/jQuery/index.js
  MVCDemos/Models/SampleData/Tasks.cs
  MVCDemos/Views/Scheduler/GroupOrientation.cshtml
  NetCoreDemos/Models/SampleData/Tasks.cs
  NetCoreDemos/Views/Scheduler/GroupOrientation.cshtml
Labels: 21_1

#876 dxScheduler - fix dates in Group Orientation demo
  JSDemos/Demos/Scheduler/GroupOrientation/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/GroupOrientation/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/GroupOrientation/AngularJS/data.js
  JSDemos/Demos/Scheduler/GroupOrientation/AngularJS/index.js
  JSDemos/Demos/Scheduler/GroupOrientation/React/App.js
  JSDemos/Demos/Scheduler/GroupOrientation/React/data.js
  JSDemos/Demos/Scheduler/GroupOrientation/Vue/App.vue
  JSDemos/Demos/Scheduler/GroupOrientation/Vue/data.js
  JSDemos/Demos/Scheduler/GroupOrientation/jQuery/data.js
  JSDemos/Demos/Scheduler/GroupOrientation/jQuery/index.js
  MVCDemos/Models/SampleData/Tasks.cs
  MVCDemos/Views/Scheduler/GroupOrientation.cshtml
  NetCoreDemos/Models/SampleData/Tasks.cs
  NetCoreDemos/Views/Scheduler/GroupOrientation.cshtml
Labels: 20_2, cherry-pick

#875 dxScheduler - fix dates in Group Orientation demo
  JSDemos/Demos/Scheduler/GroupOrientation/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/GroupOrientation/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/GroupOrientation/AngularJS/data.js
  JSDemos/Demos/Scheduler/GroupOrientation/AngularJS/index.js
  JSDemos/Demos/Scheduler/GroupOrientation/React/App.js
  JSDemos/Demos/Scheduler/GroupOrientation/React/data.js
  JSDemos/Demos/Scheduler/GroupOrientation/Vue/App.vue
  JSDemos/Demos/Scheduler/GroupOrientation/Vue/data.js
  JSDemos/Demos/Scheduler/GroupOrientation/jQuery/data.js
  JSDemos/Demos/Scheduler/GroupOrientation/jQuery/index.js
  MVCDemos/Models/SampleData/Tasks.cs
  MVCDemos/Views/Scheduler/GroupOrientation.cshtml
  NetCoreDemos/Models/SampleData/Tasks.cs
  NetCoreDemos/Views/Scheduler/GroupOrientation.cshtml
Labels: 21_2, cherry-pick

#815 dxScheduler - add width to css in disabled dates demo
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/CellTemplates/React/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/Vue/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Scheduler/CellTemplates.css
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/CellTemplates.css
Labels: 21_2

#812 Syncronize vdom version with devextreme
  package.json
Labels: 21_2

#884 Fix display decsription (#882)
  MVCDemos/DemoShell/DemoMenuMeta.cs
Labels: 21_2, cherry-pick

#883 dxScheduler - remove using text argument in data cell template
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CellTemplates/React/DateCell.js
  JSDemos/Demos/Scheduler/CellTemplates/Vue/DataCell.vue
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/index.js
  MVCDemos/Views/Scheduler/CellTemplates.cshtml
  NetCoreDemos/Views/Scheduler/CellTemplates.cshtml
Labels: 21_1

#885 dxScheduler - Change current dates in Editing and TimeZoneSupport demos
  JSDemos/Demos/Scheduler/TimeZonesSupport/AngularJS/index.js
  MVCDemos/Views/Scheduler/Editing.cshtml
  NetCoreDemos/Views/Scheduler/Editing.cshtml
Labels: 21_1

#886 dxScheduler - remove using text argument in data cell template
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CellTemplates/React/DateCell.js
  JSDemos/Demos/Scheduler/CellTemplates/Vue/DataCell.vue
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/index.js
  MVCDemos/Views/Scheduler/CellTemplates.cshtml
  NetCoreDemos/Views/Scheduler/CellTemplates.cshtml
Labels: 21_2, cherry-pick

#893 dxScheduler - revert dateCellTemplate and remove unused text argument from dataCellTemplate
  JSDemos/Demos/Scheduler/CellTemplates/React/DataCell.js
  JSDemos/Demos/Scheduler/CellTemplates/React/DateCell.js
  NetCoreDemos/Views/Scheduler/CellTemplates.cshtml
Labels: 21_1

#894 dxScheduler - revert dateCellTemplate and remove unused text argument from dataCellTemplate
  JSDemos/Demos/Scheduler/CellTemplates/React/DataCell.js
  JSDemos/Demos/Scheduler/CellTemplates/React/DateCell.js
  NetCoreDemos/Views/Scheduler/CellTemplates.cshtml
Labels: 21_2, cherry-pick

#901 Support dx-table styles
  MVCDemos/Content/site.css
Labels: 21_1

#902 Support dx-table style (#901)
  MVCDemos/Content/site.css
Labels: 21_2, cherry-pick

#781 TreeList Search Panel: rewrite
  JSDemos/Demos/TreeList/UsingSearchPanel/description.md
  JSDemos/menuMeta.json
Labels: 20_2

#904 TreeList Search Panel: rewrite (#781)
  JSDemos/Demos/TreeList/UsingSearchPanel/description.md
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#903 TreeList Search Panel: rewrite (#781)
  JSDemos/Demos/TreeList/UsingSearchPanel/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#898 dxScheduler - use scrollTo in current time indicator demo
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/AngularJS/index.js
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/Knockout/index.js
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/React/App.js
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/Vue/App.vue
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/jQuery/index.js
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/test-code.js
  MVCDemos/Views/Scheduler/CurrentTimeIndicator.cshtml
  NetCoreDemos/Views/Scheduler/CurrentTimeIndicator.cshtml
Labels: 21_2

#906 dxScheduler - use scrollTo in current time indicator demo
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/AngularJS/index.js
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/Knockout/index.js
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/React/App.js
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/Vue/App.vue
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/jQuery/index.js
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/test-code.js
  MVCDemos/Views/Scheduler/CurrentTimeIndicator.cshtml
  NetCoreDemos/Views/Scheduler/CurrentTimeIndicator.cshtml
Labels: 21_1, cherry-pick

#896 DataGrid - Add allowAdding/allowDeleting options to editing demos with modes
  JSDemos/Demos/DataGrid/BatchEditing/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/BatchEditing/AngularJS/index.js
  JSDemos/Demos/DataGrid/BatchEditing/React/App.js
  JSDemos/Demos/DataGrid/BatchEditing/Vue/App.vue
  JSDemos/Demos/DataGrid/BatchEditing/jQuery/index.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/AngularJS/index.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/React/App.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Vue/App.vue
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/jQuery/index.js
  JSDemos/Demos/DataGrid/FormEditing/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/FormEditing/AngularJS/index.js
  JSDemos/Demos/DataGrid/FormEditing/React/App.js
  JSDemos/Demos/DataGrid/FormEditing/Vue/App.vue
  JSDemos/Demos/DataGrid/FormEditing/jQuery/index.js
  JSDemos/Demos/DataGrid/PopupEditing/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/PopupEditing/AngularJS/index.js
  JSDemos/Demos/DataGrid/PopupEditing/React/App.js
  JSDemos/Demos/DataGrid/PopupEditing/Vue/App.vue
  JSDemos/Demos/DataGrid/PopupEditing/jQuery/index.js
  MVCDemos/Views/DataGrid/BatchEditing.cshtml
  MVCDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  MVCDemos/Views/DataGrid/FormEditing.cshtml
  MVCDemos/Views/DataGrid/PopupEditing.cshtml
  NetCoreDemos/Views/DataGrid/BatchEditing.cshtml
  NetCoreDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  NetCoreDemos/Views/DataGrid/FormEditing.cshtml
  NetCoreDemos/Views/DataGrid/PopupEditing.cshtml
Labels: 21_2, cherry-pick

#895 DataGrid - Add allowAdding/allowDeleting options to editing demos with modes
  JSDemos/Demos/DataGrid/BatchEditing/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/BatchEditing/AngularJS/index.js
  JSDemos/Demos/DataGrid/BatchEditing/React/App.js
  JSDemos/Demos/DataGrid/BatchEditing/Vue/App.vue
  JSDemos/Demos/DataGrid/BatchEditing/jQuery/index.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/AngularJS/index.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/React/App.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Vue/App.vue
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/jQuery/index.js
  JSDemos/Demos/DataGrid/FormEditing/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/FormEditing/AngularJS/index.js
  JSDemos/Demos/DataGrid/FormEditing/React/App.js
  JSDemos/Demos/DataGrid/FormEditing/Vue/App.vue
  JSDemos/Demos/DataGrid/FormEditing/jQuery/index.js
  JSDemos/Demos/DataGrid/PopupEditing/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/PopupEditing/AngularJS/index.js
  JSDemos/Demos/DataGrid/PopupEditing/React/App.js
  JSDemos/Demos/DataGrid/PopupEditing/Vue/App.vue
  JSDemos/Demos/DataGrid/PopupEditing/jQuery/index.js
  MVCDemos/Views/DataGrid/BatchEditing.cshtml
  MVCDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  MVCDemos/Views/DataGrid/FormEditing.cshtml
  MVCDemos/Views/DataGrid/PopupEditing.cshtml
  NetCoreDemos/Views/DataGrid/BatchEditing.cshtml
  NetCoreDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  NetCoreDemos/Views/DataGrid/FormEditing.cshtml
  NetCoreDemos/Views/DataGrid/PopupEditing.cshtml
Labels: 21_1

#891 DataGrid & TreeList State Storing Demo - Add a button to reset state
  JSDemos/Demos/DataGrid/StatePersistence/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/StatePersistence/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/StatePersistence/AngularJS/index.html
  JSDemos/Demos/DataGrid/StatePersistence/AngularJS/index.js
  JSDemos/Demos/DataGrid/StatePersistence/React/App.js
  JSDemos/Demos/DataGrid/StatePersistence/Vue/App.vue
  JSDemos/Demos/DataGrid/StatePersistence/jQuery/index.html
  JSDemos/Demos/DataGrid/StatePersistence/jQuery/index.js
  JSDemos/Demos/TreeList/StatePersistence/Angular/app/app.component.html
  JSDemos/Demos/TreeList/StatePersistence/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/StatePersistence/AngularJS/index.html
  JSDemos/Demos/TreeList/StatePersistence/AngularJS/index.js
  JSDemos/Demos/TreeList/StatePersistence/React/App.js
  JSDemos/Demos/TreeList/StatePersistence/Vue/App.vue
  JSDemos/Demos/TreeList/StatePersistence/jQuery/index.html
  JSDemos/Demos/TreeList/StatePersistence/jQuery/index.js
  MVCDemos/Views/DataGrid/StatePersistence.cshtml
  MVCDemos/Views/TreeList/StatePersistence.cshtml
  NetCoreDemos/Views/DataGrid/StatePersistence.cshtml
  NetCoreDemos/Views/TreeList/StatePersistence.cshtml
Labels: 21_1

#892 DataGrid & TreeList State Storing Demo - Add a button to reset state
  JSDemos/Demos/DataGrid/StatePersistence/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/StatePersistence/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/StatePersistence/AngularJS/index.html
  JSDemos/Demos/DataGrid/StatePersistence/AngularJS/index.js
  JSDemos/Demos/DataGrid/StatePersistence/React/App.js
  JSDemos/Demos/DataGrid/StatePersistence/Vue/App.vue
  JSDemos/Demos/DataGrid/StatePersistence/jQuery/index.html
  JSDemos/Demos/DataGrid/StatePersistence/jQuery/index.js
  JSDemos/Demos/TreeList/StatePersistence/Angular/app/app.component.html
  JSDemos/Demos/TreeList/StatePersistence/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/StatePersistence/AngularJS/index.html
  JSDemos/Demos/TreeList/StatePersistence/AngularJS/index.js
  JSDemos/Demos/TreeList/StatePersistence/React/App.js
  JSDemos/Demos/TreeList/StatePersistence/Vue/App.vue
  JSDemos/Demos/TreeList/StatePersistence/jQuery/index.html
  JSDemos/Demos/TreeList/StatePersistence/jQuery/index.js
  MVCDemos/Views/DataGrid/StatePersistence.cshtml
  MVCDemos/Views/TreeList/StatePersistence.cshtml
  NetCoreDemos/Views/DataGrid/StatePersistence.cshtml
  NetCoreDemos/Views/TreeList/StatePersistence.cshtml
Labels: 21_2, cherry-pick

#910 Refactoring support dx-table (#907)
  .gitignore
  MVCDemos/Content/custom.css
  MVCDemos/Content/site.css
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/Shared/_LayoutNavigation.cshtml
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  NetCoreDemos/wwwroot/css/custom.css
Labels: 21_2, cherry-pick

#909 TreeList Filter Row: rewrite (#782)
  JSDemos/Demos/TreeList/UsingFilterRow/description.md
Labels: 21_1, cherry-pick

#917 Viz - remove badges
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#918 Viz - remove badges
  JSDemos/menuMeta.json
Labels: 21_2

#920 TreeList Column Resizing: rewrite (#793)
  JSDemos/Demos/TreeList/Resizing/description.md
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#921 TreeList Column Resizing: rewrite (#793)
  JSDemos/Demos/TreeList/Resizing/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#916 TreeList Column Reordering: rewrite (#795)
  JSDemos/Demos/TreeList/Reordering/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#915 TreeList Column Reordering: rewrite (#795)
  JSDemos/Demos/TreeList/Reordering/description.md
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#925 TreeList Column Fixing: rewrite (#796)
  JSDemos/Demos/TreeList/ColumnFixing/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#924 TreeList Column Fixing: rewrite (#796)
  JSDemos/Demos/TreeList/ColumnFixing/description.md
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#923 DataGrid Column Resizing: cherry-pick from TreeList
  JSDemos/Demos/DataGrid/ColumnResizing/description.md
Labels: 21_2

#922 DataGrid Column Resizing: cherry-pick from TreeList
  JSDemos/Demos/DataGrid/ColumnResizing/description.md
Labels: 21_1

#926 Scheduler Recurring Appointments: rewrite (#802)
  JSDemos/Demos/Scheduler/RecurringAppointments/description.md
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#927 Scheduler Recurring Appointments: rewrite (#802)
  JSDemos/Demos/Scheduler/RecurringAppointments/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#929 Grids Form Editing: update
  JSDemos/Demos/DataGrid/FormEditing/description.md
  JSDemos/Demos/TreeList/FormEditing/description.md
Labels: 21_1

#930 Grids Form Editing: update (#929)
  JSDemos/Demos/DataGrid/FormEditing/description.md
  JSDemos/Demos/TreeList/FormEditing/description.md
Labels: 21_2, cherry-pick

#858 Scheduler Editing demo rewrite
  JSDemos/Demos/Scheduler/Editing/description.md
  JSDemos/menuMeta.json
Labels: 20_2

#934 Scheduler Editing demo rewrite (#858)
  JSDemos/Demos/Scheduler/Editing/description.md
  JSDemos/menuMeta.json
Labels: 21_2, cherry-pick

#911 dxScheduler - refactor resources and agenda demos
  .eslintrc.js
  JSDemos/Demos/Scheduler/Agenda/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/Agenda/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/Agenda/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Agenda/AngularJS/data.js
  JSDemos/Demos/Scheduler/Agenda/AngularJS/index.js
  JSDemos/Demos/Scheduler/Agenda/React/App.js
  JSDemos/Demos/Scheduler/Agenda/React/data.js
  JSDemos/Demos/Scheduler/Agenda/Vue/App.vue
  JSDemos/Demos/Scheduler/Agenda/Vue/data.js
  JSDemos/Demos/Scheduler/Agenda/jQuery/data.js
  JSDemos/Demos/Scheduler/Agenda/jQuery/index.js
  JSDemos/Demos/Scheduler/Resources/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/Resources/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/Resources/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Resources/AngularJS/data.js
  JSDemos/Demos/Scheduler/Resources/AngularJS/index.js
  JSDemos/Demos/Scheduler/Resources/Knockout/data.js
  JSDemos/Demos/Scheduler/Resources/Knockout/index.js
  JSDemos/Demos/Scheduler/Resources/React/App.js
  JSDemos/Demos/Scheduler/Resources/React/data.js
  JSDemos/Demos/Scheduler/Resources/Vue/App.vue
  JSDemos/Demos/Scheduler/Resources/Vue/data.js
  JSDemos/Demos/Scheduler/Resources/jQuery/data.js
  JSDemos/Demos/Scheduler/Resources/jQuery/index.js
  MVCDemos/Controllers/SchedulerController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/AppointmentWithResources.cs
  MVCDemos/Models/AssigneeResource.cs
  MVCDemos/Models/SampleData/AgendaTasks.cs
  MVCDemos/Models/SampleData/AppointmentsWithResources.cs
  MVCDemos/Models/SampleData/AssigneeResources.cs
  MVCDemos/ViewModels/SchedulerResourcesViewModel.cs
  MVCDemos/Views/Scheduler/Agenda.cshtml
  MVCDemos/Views/Scheduler/Resources.cshtml
  NetCoreDemos/Controllers/SchedulerController.cs
  NetCoreDemos/Models/AppointmentWithResources.cs
  NetCoreDemos/Models/AssigneeResource.cs
  NetCoreDemos/Models/SampleData/AgendaTasks.cs
  NetCoreDemos/Models/SampleData/AppointmentsWithResources.cs
  NetCoreDemos/Models/SampleData/AssigneeResources.cs
  NetCoreDemos/ViewModels/SchedulerResourcesViewModel.cs
  NetCoreDemos/Views/Scheduler/Agenda.cshtml
  NetCoreDemos/Views/Scheduler/Resources.cshtml
Labels: 21_1

#879 TreeList - add selectionChanged log for TreeList multiple selection demo
  JSDemos/Demos/TreeList/MultipleRowSelection/Angular/app/app.component.css
  JSDemos/Demos/TreeList/MultipleRowSelection/Angular/app/app.component.html
  JSDemos/Demos/TreeList/MultipleRowSelection/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/MultipleRowSelection/AngularJS/index.html
  JSDemos/Demos/TreeList/MultipleRowSelection/AngularJS/index.js
  JSDemos/Demos/TreeList/MultipleRowSelection/AngularJS/styles.css
  JSDemos/Demos/TreeList/MultipleRowSelection/React/App.js
  JSDemos/Demos/TreeList/MultipleRowSelection/React/styles.css
  JSDemos/Demos/TreeList/MultipleRowSelection/Vue/App.vue
  JSDemos/Demos/TreeList/MultipleRowSelection/jQuery/index.html
  JSDemos/Demos/TreeList/MultipleRowSelection/jQuery/index.js
  JSDemos/Demos/TreeList/MultipleRowSelection/jQuery/styles.css
  MVCDemos/Content/DemosStyles/TreeList/MultipleRowSelection.css
  MVCDemos/Views/TreeList/MultipleRowSelection.cshtml
  NetCoreDemos/Views/TreeList/MultipleRowSelection.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TreeList/MultipleRowSelection.css
Labels: 21_1

#880 TreeList - add selectionChanged log for TreeList multiple selection demo
  JSDemos/Demos/TreeList/MultipleRowSelection/Angular/app/app.component.css
  JSDemos/Demos/TreeList/MultipleRowSelection/Angular/app/app.component.html
  JSDemos/Demos/TreeList/MultipleRowSelection/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/MultipleRowSelection/AngularJS/index.html
  JSDemos/Demos/TreeList/MultipleRowSelection/AngularJS/index.js
  JSDemos/Demos/TreeList/MultipleRowSelection/AngularJS/styles.css
  JSDemos/Demos/TreeList/MultipleRowSelection/React/App.js
  JSDemos/Demos/TreeList/MultipleRowSelection/React/styles.css
  JSDemos/Demos/TreeList/MultipleRowSelection/Vue/App.vue
  JSDemos/Demos/TreeList/MultipleRowSelection/jQuery/index.html
  JSDemos/Demos/TreeList/MultipleRowSelection/jQuery/index.js
  JSDemos/Demos/TreeList/MultipleRowSelection/jQuery/styles.css
  MVCDemos/Content/DemosStyles/TreeList/MultipleRowSelection.css
  MVCDemos/Views/TreeList/MultipleRowSelection.cshtml
  NetCoreDemos/Views/TreeList/MultipleRowSelection.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TreeList/MultipleRowSelection.css
Labels: 21_2, cherry-pick

#931 DataGrid CellEditing Demo - fix buttons placement (21.1)
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/AngularJS/index.html
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/AngularJS/index.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/AngularJS/styles.css
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/React/App.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/React/styles.css
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Vue/App.vue
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/jQuery/index.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/jQuery/styles.css
  MVCDemos/Content/DemosStyles/DataGrid/CellEditingAndEditingAPI.css
  MVCDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  NetCoreDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/CellEditingAndEditingAPI.css
Labels: 21_1

#932 DataGrid CellEditing Demo - fix buttons placement (21.2)
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/AngularJS/index.html
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/AngularJS/index.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/AngularJS/styles.css
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/React/App.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/React/styles.css
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Vue/App.vue
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/jQuery/index.js
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/jQuery/styles.css
  MVCDemos/Content/DemosStyles/DataGrid/CellEditingAndEditingAPI.css
  MVCDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  NetCoreDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/CellEditingAndEditingAPI.css
Labels: 21_2, cherry-pick

#937 pivotgrid.export: get rid unknown symbol in description
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/description.md
Labels: 21_1, cherry-pick

#936 pivotgrid.export: get rid unknown symbol in description
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/description.md
Labels: 21_2

#938 pivotgrid.export: get rid unknown symbol in description
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/description.md
Labels: 20_2, cherry-pick

#940 Upgrade DevExtreme.AspNet.Data to version 2.8.4 (T1002466)
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Web.config
  MVCDemos/packages.config
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  package.json
Labels: 21_1

#941 Upgrade DevExtreme.AspNet.Data to version 2.8.4 (T1002466)
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Web.config
  MVCDemos/packages.config
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  package.json
Labels: 21_2, cherry-pick
