Repository DevExpress/devextreme-demos, pull requests merged in 2021-08, with the labels that each got.

#1109 Include gantt and diagram to bundle to optimize demo load time
  JSDemos/configs/Angular/config.bundle.js
  JSDemos/configs/React/config.bundle.js
  JSDemos/configs/Vue/config.bundle.js
  utils/bundle/index.js
Labels: 21_2

#1106 HtmlEditor output format demo - prevent value format change after the first edititng operation
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.service.ts
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/data.js
  JSDemos/Demos/HtmlEditor/OutputFormats/React/data.js
  JSDemos/Demos/HtmlEditor/OutputFormats/Vue/data.js
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/data.js
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
Labels: 21_1

#1113 HtmlEditor output format demo - prevent value format change after the first edititng operation
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.service.ts
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/data.js
  JSDemos/Demos/HtmlEditor/OutputFormats/React/data.js
  JSDemos/Demos/HtmlEditor/OutputFormats/Vue/data.js
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/data.js
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
Labels: 21_2, cherry-pick

#1114 Update testcafe etalons
  testing/etalons/HtmlEditor-OutputFormats.png
  testing/etalons/Scheduler-CurrentTimeIndicator.png
Labels: 21_2

#1117 Maps - remove 'center' option
  JSDemos/Demos/Map/Markers/React/App.js
  JSDemos/Demos/Map/Markers/Vue/App.vue
  JSDemos/Demos/Map/ProvidersAndTypes/React/App.js
  JSDemos/Demos/Map/Routes/React/App.js
  JSDemos/Demos/Map/Routes/Vue/App.vue
Labels: 20_2, cherry-pick

#1118 Maps - remove 'center' option
  JSDemos/Demos/Map/Markers/React/App.js
  JSDemos/Demos/Map/Markers/Vue/App.vue
  JSDemos/Demos/Map/ProvidersAndTypes/React/App.js
  JSDemos/Demos/Map/Routes/React/App.js
  JSDemos/Demos/Map/Routes/Vue/App.vue
Labels: 21_1, cherry-pick

#1112 dxScheduler - Add mock date for currentTimeIndicator demo
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/pre-test-code.js
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/test-code.js
  testing/etalons/Scheduler-CurrentTimeIndicator_mask.png
Labels: 21_2

#1126 dxScheduler - Revert CurrentTimeIndicator demo screenshot
  testing/etalons/Scheduler-CurrentTimeIndicator.png
Labels: 21_2

#1121 RadioGroup - Add valueExpr and displayExpr
  JSDemos/Demos/RadioGroup/Overview/Angular/app/app.component.html
  JSDemos/Demos/RadioGroup/Overview/Angular/app/app.component.ts
  JSDemos/Demos/RadioGroup/Overview/Angular/app/app.service.ts
  JSDemos/Demos/RadioGroup/Overview/AngularJS/data.js
  JSDemos/Demos/RadioGroup/Overview/AngularJS/index.js
  JSDemos/Demos/RadioGroup/Overview/Knockout/data.js
  JSDemos/Demos/RadioGroup/Overview/Knockout/index.js
  JSDemos/Demos/RadioGroup/Overview/React/App.js
  JSDemos/Demos/RadioGroup/Overview/React/data.js
  JSDemos/Demos/RadioGroup/Overview/Vue/App.vue
  JSDemos/Demos/RadioGroup/Overview/Vue/data.js
  JSDemos/Demos/RadioGroup/Overview/jQuery/data.js
  JSDemos/Demos/RadioGroup/Overview/jQuery/index.js
  MVCDemos/Views/RadioGroup/Overview.cshtml
  NetCoreDemos/Views/RadioGroup/Overview.cshtml
Labels: 20_2, cherry-pick

#1122 RadioGroup - Add valueExpr and displayExpr
  JSDemos/Demos/RadioGroup/Overview/Angular/app/app.component.html
  JSDemos/Demos/RadioGroup/Overview/Angular/app/app.component.ts
  JSDemos/Demos/RadioGroup/Overview/Angular/app/app.service.ts
  JSDemos/Demos/RadioGroup/Overview/AngularJS/data.js
  JSDemos/Demos/RadioGroup/Overview/AngularJS/index.js
  JSDemos/Demos/RadioGroup/Overview/Knockout/data.js
  JSDemos/Demos/RadioGroup/Overview/Knockout/index.js
  JSDemos/Demos/RadioGroup/Overview/React/App.js
  JSDemos/Demos/RadioGroup/Overview/React/data.js
  JSDemos/Demos/RadioGroup/Overview/Vue/App.vue
  JSDemos/Demos/RadioGroup/Overview/Vue/data.js
  JSDemos/Demos/RadioGroup/Overview/jQuery/data.js
  JSDemos/Demos/RadioGroup/Overview/jQuery/index.js
  MVCDemos/Views/RadioGroup/Overview.cshtml
  NetCoreDemos/Views/RadioGroup/Overview.cshtml
Labels: 21_1, cherry-pick

#1125 menu: get rid of using submenuDirection option in demo
  JSDemos/Demos/Menu/Overview/Angular/app/app.component.html
  JSDemos/Demos/Menu/Overview/AngularJS/index.html
  JSDemos/Demos/Menu/Overview/AngularJS/index.js
  JSDemos/Demos/Menu/Overview/Knockout/index.html
  JSDemos/Demos/Menu/Overview/Knockout/index.js
  JSDemos/Demos/Menu/Overview/React/App.js
  JSDemos/Demos/Menu/Overview/Vue/App.vue
  JSDemos/Demos/Menu/Overview/jQuery/index.html
  JSDemos/Demos/Menu/Overview/jQuery/index.js
  MVCDemos/Views/Menu/Overview.cshtml
  NetCoreDemos/Views/Menu/Overview.cshtml
Labels: 21_1, cherry-pick

#1101 TagBox: fix issue with Tag Count Limitation Angular Demo (T1017708)
  JSDemos/Demos/TagBox/TagCountLimitation/Angular/app/app.component.html
  JSDemos/Demos/TagBox/TagCountLimitation/Angular/app/app.component.ts
Labels: 21_2

#1120 dxScheduler - Fix dateNavigator caption button width
  testing/etalons/Scheduler-Adaptability.png
  testing/etalons/Scheduler-Agenda.png
  testing/etalons/Scheduler-BasicViews.png
  testing/etalons/Scheduler-CellTemplates.png
  testing/etalons/Scheduler-ContextMenuIntegration.png
  testing/etalons/Scheduler-CurrentTimeIndicator.png
  testing/etalons/Scheduler-CustomDragAndDrop.png
  testing/etalons/Scheduler-CustomTemplates.png
  testing/etalons/Scheduler-CustomizeIndividualViews.png
  testing/etalons/Scheduler-Editing.png
  testing/etalons/Scheduler-GoogleCalendarIntegration.png
  testing/etalons/Scheduler-GroupByDate.png
  testing/etalons/Scheduler-GroupOrientation.png
  testing/etalons/Scheduler-IncreaseViewDuration.png
  testing/etalons/Scheduler-LimitAppointmentCountPerCell.png
  testing/etalons/Scheduler-Overview.png
  testing/etalons/Scheduler-RecurringAppointments.png
  testing/etalons/Scheduler-Resources.png
  testing/etalons/Scheduler-SignalRService.png
  testing/etalons/Scheduler-SimpleArray.png
  testing/etalons/Scheduler-TimeZonesSupport.png
  testing/etalons/Scheduler-Timelines.png
  testing/etalons/Scheduler-VirtualScrolling.png
  testing/etalons/Scheduler-WebAPIService.png
  testing/widgets/ scheduler/etalons/scheduler_contextMenu_cell_click.png
  testing/widgets/ scheduler/etalons/scheduler_contextMenu_click.png
  testing/widgets/ scheduler/etalons/scheduler_contextMenu_header_click.png
  testing/widgets/ scheduler/etalons/scheduler_contextMenu_init.png
Labels: 21_2

#1096 Rename pre-test-code to client-script and add client-script for Scheduler Overview demo
  JSDemos/Demos/Gantt/StripLines/client-script.js
  JSDemos/Demos/Gantt/TaskTemplate/client-script.js
  JSDemos/Demos/Gantt/Validation/client-script.js
  JSDemos/Demos/Scheduler/Adaptability/client-script.js
  JSDemos/Demos/Scheduler/GroupByDate/client-script.js
  JSDemos/Demos/Scheduler/GroupOrientation/client-script.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/client-script.js
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/pre-test-code.js
  JSDemos/Demos/Scheduler/Overview/client-script.js
  testing/common.test.js
  testing/etalons/DateBox-Overview.png
Labels: 21_2

#1129 dxScheduler - Rename pre-test-code to client-script
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/client-script.js
Labels: 21_2

#1128 Add package-lock file and renovate bot
  .github/workflows/CI.yml
  .github/workflows/renovate_autoapprove.yml
  .github/workflows/unit_tests.yml
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
  .gitignore
  package-lock.json
  renovate.json
Labels: 21_2

#1131 File Manager - Overview - remove unnecessary script link
  JSDemos/Demos/FileManager/Overview/jQuery/index.html
Labels: 21_2

#1132 File Manager - Overview - remove unnecessary script link
  JSDemos/Demos/FileManager/Overview/jQuery/index.html
Labels: 21_1, cherry-pick

#1133 File Manager - Overview - remove unnecessary script link
  JSDemos/Demos/FileManager/Overview/jQuery/index.html
Labels: 20_2, cherry-pick

#1134 dxScheduler - Change the date setting in server-side demos
  MVCDemos/Views/Scheduler/CurrentTimeIndicator.cshtml
  NetCoreDemos/Views/Scheduler/CurrentTimeIndicator.cshtml
Labels: 21_2

#1124 menu: get rid of using submenuDirection option in demo
  JSDemos/Demos/Menu/Overview/Angular/app/app.component.html
  JSDemos/Demos/Menu/Overview/AngularJS/index.html
  JSDemos/Demos/Menu/Overview/AngularJS/index.js
  JSDemos/Demos/Menu/Overview/Knockout/index.html
  JSDemos/Demos/Menu/Overview/Knockout/index.js
  JSDemos/Demos/Menu/Overview/React/App.js
  JSDemos/Demos/Menu/Overview/Vue/App.vue
  JSDemos/Demos/Menu/Overview/jQuery/index.html
  JSDemos/Demos/Menu/Overview/jQuery/index.js
  MVCDemos/Views/Menu/Overview.cshtml
  NetCoreDemos/Views/Menu/Overview.cshtml
  testing/etalons/Menu-Overview.png
Labels: 21_2

#1137 Simplify testcafe helpers
  testing/widgets/datagrid/columns.test.js
  testing/widgets/scheduler/contextMenuIntegration.test.js
  testing/widgets/scheduler/etalons/scheduler_contextMenu_cell_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_header_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_init.png
  utils/tests/testcafe-helpers/matrix-test-helper.test.js
  utils/visual-tests/matrix-test-helper.js
Labels: 21_2

#1138 Create a simple demo-shell
  README.md
  index.html
  package-lock.json
  package.json
  utils/interactive/launch-demo.js
  utils/interactive/prompts-questions.js
  utils/shell/server.js
Labels: 21_2

#1140 dxScheduler - Revert setting date in currentTimeIndicator demo to current date
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/client-script.js
  testing/etalons/Scheduler-CurrentTimeIndicator_mask.png
Labels: 21_2

#1144 dxScheduler - remove 'updated' markers
  JSDemos/menuMeta.json
Labels: 21_2

#1142 Fix React and Vue tests: HtmlEditor-OutputFormats
  JSDemos/Demos/HtmlEditor/OutputFormats/test-code.js
  JSDemos/Demos/HtmlEditor/OutputFormats/visualtestrc.json
Labels: 21_2

#1143 Fix React and Vue tests: Charts
  JSDemos/Demos/Charts/AreaSparklines/React/styles.css
  JSDemos/Demos/Charts/AreaSparklines/Vue/App.vue
  JSDemos/Demos/Charts/AreaSparklines/visualtestrc.json
  JSDemos/Demos/Charts/BarSparklines/React/styles.css
  JSDemos/Demos/Charts/BarSparklines/Vue/App.vue
  JSDemos/Demos/Charts/BarSparklines/visualtestrc.json
  JSDemos/Demos/Charts/SimpleSparklines/React/styles.css
  JSDemos/Demos/Charts/SimpleSparklines/Vue/App.vue
  JSDemos/Demos/Charts/SimpleSparklines/visualtestrc.json
  JSDemos/Demos/Charts/WinlossSparklines/React/styles.css
  JSDemos/Demos/Charts/WinlossSparklines/Vue/App.vue
  JSDemos/Demos/Charts/WinlossSparklines/visualtestrc.json
Labels: 21_2

#1145 Shell: fix treeview expanding
  index.html
Labels: 21_2

#1148 Fix accordion demo after material upgrade
  JSDemos/Demos/Accordion/Overview/Angular/app/app.component.css
  JSDemos/Demos/Accordion/Overview/AngularJS/styles.css
  JSDemos/Demos/Accordion/Overview/Knockout/styles.css
  JSDemos/Demos/Accordion/Overview/React/styles.css
  JSDemos/Demos/Accordion/Overview/Vue/App.vue
  JSDemos/Demos/Accordion/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Accordion/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/Accordion/Overview.css
Labels: 21_2

#1149 Gauges-Value Indicator API demos fox after material upgrade
  JSDemos/Demos/Gauges/ValueIndicatorsAPI/Angular/app/app.component.css
  JSDemos/Demos/Gauges/ValueIndicatorsAPI/Knockout/styles.css
  JSDemos/Demos/Gauges/ValueIndicatorsAPI/React/styles.css
  JSDemos/Demos/Gauges/ValueIndicatorsAPI/Vue/App.vue
  JSDemos/Demos/Gauges/ValueIndicatorsAPI/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Gauges/ValueIndicatorsAPI.css
  NetCoreDemos/wwwroot/css/DemosStyles/Gauges/ValueIndicatorsAPI.css
Labels: 21_2

#1150 Fix Charts-Custom Axis Position demo after material upgrade
  JSDemos/Demos/Charts/AxisCustomPosition/Angular/app/app.component.css
  JSDemos/Demos/Charts/AxisCustomPosition/React/styles.css
  JSDemos/Demos/Charts/AxisCustomPosition/Vue/App.vue
  JSDemos/Demos/Charts/AxisCustomPosition/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Charts/AxisCustomPosition.css
  NetCoreDemos/wwwroot/css/DemosStyles/Charts/AxisCustomPosition.css
  testing/etalons/Charts-AxisCustomPosition.png
Labels: 21_2

#1152 Fix Client Side Data Processing demo after material upgrade
  JSDemos/Demos/Charts/ClientSideDataProcessing/Angular/app/app.component.css
  JSDemos/Demos/Charts/ClientSideDataProcessing/Angular/app/app.component.html
  JSDemos/Demos/Charts/ClientSideDataProcessing/AngularJS/index.html
  JSDemos/Demos/Charts/ClientSideDataProcessing/AngularJS/index.js
  JSDemos/Demos/Charts/ClientSideDataProcessing/AngularJS/styles.css
  JSDemos/Demos/Charts/ClientSideDataProcessing/Knockout/index.html
  JSDemos/Demos/Charts/ClientSideDataProcessing/Knockout/index.js
  JSDemos/Demos/Charts/ClientSideDataProcessing/Knockout/styles.css
  JSDemos/Demos/Charts/ClientSideDataProcessing/React/App.js
  JSDemos/Demos/Charts/ClientSideDataProcessing/React/styles.css
  JSDemos/Demos/Charts/ClientSideDataProcessing/Vue/App.vue
  JSDemos/Demos/Charts/ClientSideDataProcessing/jQuery/index.html
  JSDemos/Demos/Charts/ClientSideDataProcessing/jQuery/index.js
  JSDemos/Demos/Charts/ClientSideDataProcessing/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Charts/ClientSideDataProcessing.css
  MVCDemos/Views/Charts/ClientSideDataProcessing.cshtml
  NetCoreDemos/Views/Charts/ClientSideDataProcessing.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Charts/ClientSideDataProcessing.css
  testing/etalons/Charts-ClientSideDataProcessing.png
Labels: 21_2

#1151 Fix Charts-Bar Sparklines demo after material upgrade
  JSDemos/Demos/Charts/BarSparklines/Angular/app/app.component.css
  JSDemos/Demos/Charts/BarSparklines/Angular/app/app.component.html
  JSDemos/Demos/Charts/BarSparklines/AngularJS/index.html
  JSDemos/Demos/Charts/BarSparklines/AngularJS/index.js
  JSDemos/Demos/Charts/BarSparklines/AngularJS/styles.css
  JSDemos/Demos/Charts/BarSparklines/Knockout/index.html
  JSDemos/Demos/Charts/BarSparklines/Knockout/index.js
  JSDemos/Demos/Charts/BarSparklines/Knockout/styles.css
  JSDemos/Demos/Charts/BarSparklines/React/App.js
  JSDemos/Demos/Charts/BarSparklines/React/styles.css
  JSDemos/Demos/Charts/BarSparklines/Vue/App.vue
  JSDemos/Demos/Charts/BarSparklines/jQuery/index.html
  JSDemos/Demos/Charts/BarSparklines/jQuery/index.js
  JSDemos/Demos/Charts/BarSparklines/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Charts/BarSparklines.css
  MVCDemos/Views/Charts/BarSparklines.cshtml
  NetCoreDemos/Views/Charts/BarSparklines.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Charts/BarSparklines.css
  testing/etalons/Charts-BarSparklines.png
Labels: 21_2

#1153 Fix Scale Breaks demo after material upgrade
  JSDemos/Demos/Charts/ScaleBreaks/Angular/app/app.component.html
  JSDemos/Demos/Charts/ScaleBreaks/AngularJS/index.js
  JSDemos/Demos/Charts/ScaleBreaks/Knockout/index.js
  JSDemos/Demos/Charts/ScaleBreaks/React/App.js
  JSDemos/Demos/Charts/ScaleBreaks/Vue/App.vue
  JSDemos/Demos/Charts/ScaleBreaks/jQuery/index.js
  MVCDemos/Views/Charts/ScaleBreaks.cshtml
  NetCoreDemos/Views/Charts/ScaleBreaks.cshtml
  testing/etalons/Charts-ScaleBreaks.png
Labels: 21_2

#1154 Fix ServerSide Data Processing demo after material upgrade
  JSDemos/Demos/Charts/ServerSideDataProcessing/Angular/app/app.component.css
  JSDemos/Demos/Charts/ServerSideDataProcessing/Angular/app/app.component.html
  JSDemos/Demos/Charts/ServerSideDataProcessing/AngularJS/index.html
  JSDemos/Demos/Charts/ServerSideDataProcessing/AngularJS/styles.css
  JSDemos/Demos/Charts/ServerSideDataProcessing/Knockout/index.html
  JSDemos/Demos/Charts/ServerSideDataProcessing/Knockout/styles.css
  JSDemos/Demos/Charts/ServerSideDataProcessing/React/App.js
  JSDemos/Demos/Charts/ServerSideDataProcessing/React/styles.css
  JSDemos/Demos/Charts/ServerSideDataProcessing/Vue/App.vue
  JSDemos/Demos/Charts/ServerSideDataProcessing/jQuery/index.html
  JSDemos/Demos/Charts/ServerSideDataProcessing/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Charts/ServerSideDataProcessing.css
  MVCDemos/Views/Charts/ServerSideDataProcessing.cshtml
  NetCoreDemos/Views/Charts/ServerSideDataProcessing.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Charts/ServerSideDataProcessing.css
Labels: 21_2

#1155 Value Indicator API - fix MVC. AngularJS styles
  JSDemos/Demos/Gauges/ValueIndicatorsAPI/AngularJS/styles.css
  MVCDemos/Content/DemosStyles/Gauges/ValueIndicatorsAPI.css
  NetCoreDemos/wwwroot/css/DemosStyles/Gauges/ValueIndicatorsAPI.css
Labels: 21_2

#1156 FileManager-AzureClientBinding: remove jQuery from helpers
  JSDemos/Demos/FileManager/AzureClientBinding/React/App.js
  JSDemos/Demos/FileManager/AzureClientBinding/azure-file-system.js
  JSDemos/Demos/FileManager/AzureClientBinding/jQuery/index.js
  JSDemos/Demos/FileManager/AzureClientBinding/visualtestrc.json
Labels: 21_2

#1159 Fix Editors Overview demo after material upgrade
  JSDemos/Demos/Common/EditorsOverview/Angular/app/app.component.css
  JSDemos/Demos/Common/EditorsOverview/AngularJS/styles.css
  JSDemos/Demos/Common/EditorsOverview/Knockout/styles.css
  JSDemos/Demos/Common/EditorsOverview/React/App.js
  JSDemos/Demos/Common/EditorsOverview/React/styles.css
  JSDemos/Demos/Common/EditorsOverview/Vue/App.vue
  JSDemos/Demos/Common/EditorsOverview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Common/EditorsOverview.css
  NetCoreDemos/wwwroot/css/DemosStyles/Common/EditorsOverview.css
  testing/etalons/Common-EditorsOverview.png
Labels: 21_2

#1157 DataGrid: Update etalons for new scrolling mode
  testing/etalons/DataGrid-RemoteVirtualScrolling.png
Labels: 21_2

#1165 Fix DataGrid Tollbar Customization demo after material upgrade
  JSDemos/Demos/DataGrid/ToolbarCustomization/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/ToolbarCustomization/AngularJS/styles.css
  JSDemos/Demos/DataGrid/ToolbarCustomization/Knockout/styles.css
  JSDemos/Demos/DataGrid/ToolbarCustomization/React/styles.css
  JSDemos/Demos/DataGrid/ToolbarCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/ToolbarCustomization/jQuery/styles.css
  MVCDemos/Content/DemosStyles/DataGrid/ToolbarCustomization.css
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/ToolbarCustomization.css
Labels: 21_2

#1162 update dxGantt etalons
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
  testing/etalons/Gantt-ChartAppearance.png
  testing/etalons/Gantt-StripLines.png
  testing/etalons/Gantt-Validation.png
Labels: force all tests

#1167 Fix Multiple Record Selection Api demo after material upgrade
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/AngularJS/index.html
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/AngularJS/styles.css
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Knockout/index.html
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Knockout/styles.css
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/React/App.js
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/React/styles.css
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Vue/App.vue
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/jQuery/index.html
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/jQuery/styles.css
  MVCDemos/Content/DemosStyles/DataGrid/MultipleRecordSelectionAPI.css
  MVCDemos/Views/DataGrid/MultipleRecordSelectionAPI.cshtml
  NetCoreDemos/Views/DataGrid/MultipleRecordSelectionAPI.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/MultipleRecordSelectionAPI.css
  testing/etalons/DataGrid-MultipleRecordSelectionAPI.png
Labels: 21_2

#1163 Fix React and Vue tests: Charts
  JSDemos/Demos/Charts/AreaSparklines/React/App.js
  JSDemos/Demos/Charts/AreaSparklines/React/styles.css
  JSDemos/Demos/Charts/AreaSparklines/Vue/App.vue
  JSDemos/Demos/Charts/BarSparklines/React/App.js
  JSDemos/Demos/Charts/BarSparklines/React/styles.css
  JSDemos/Demos/Charts/BarSparklines/Vue/App.vue
  JSDemos/Demos/Charts/SimpleSparklines/React/App.js
  JSDemos/Demos/Charts/SimpleSparklines/React/styles.css
  JSDemos/Demos/Charts/SimpleSparklines/Vue/App.vue
  JSDemos/Demos/Charts/WinlossSparklines/React/App.js
  JSDemos/Demos/Charts/WinlossSparklines/React/styles.css
  JSDemos/Demos/Charts/WinlossSparklines/Vue/App.vue
Labels: 21_2

#1161 Fix Customize Keyboard Navigation demo after material upgrade
  JSDemos/Demos/DataGrid/CustomizeKeyboardNavigation/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/CustomizeKeyboardNavigation/AngularJS/styles.css
  JSDemos/Demos/DataGrid/CustomizeKeyboardNavigation/React/styles.css
  JSDemos/Demos/DataGrid/CustomizeKeyboardNavigation/Vue/styles.css
  JSDemos/Demos/DataGrid/CustomizeKeyboardNavigation/jQuery/styles.css
  JSDemos/Demos/TreeList/CustomizeKeyboardNavigation/Angular/app/app.component.css
  JSDemos/Demos/TreeList/CustomizeKeyboardNavigation/AngularJS/styles.css
  JSDemos/Demos/TreeList/CustomizeKeyboardNavigation/React/styles.css
  JSDemos/Demos/TreeList/CustomizeKeyboardNavigation/Vue/styles.css
  JSDemos/Demos/TreeList/CustomizeKeyboardNavigation/jQuery/styles.css
  MVCDemos/Content/DemosStyles/DataGrid/CustomizeKeyboardNavigation.css
  MVCDemos/Content/DemosStyles/TreeList/CustomizeKeyboardNavigation.css
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/CustomizeKeyboardNavigation.css
  NetCoreDemos/wwwroot/css/DemosStyles/TreeList/CustomizeKeyboardNavigation.css
  testing/etalons/DataGrid-CustomizeKeyboardNavigation.png
  testing/etalons/TreeList-CustomizeKeyboardNavigation.png
Labels: 21_2

#1173 Fix React and Vue tests: Box-Overview, RadioGroup-Overview
  JSDemos/Demos/Box/Overview/React/index.js
  JSDemos/Demos/Box/Overview/Vue/index.js
  JSDemos/Demos/Box/Overview/visualtestrc.json
  JSDemos/Demos/RadioGroup/Overview/React/index.js
  JSDemos/Demos/RadioGroup/Overview/Vue/index.js
  JSDemos/Demos/RadioGroup/Overview/visualtestrc.json
Labels: 21_2

#1170 Fix React test: DataGrid-BatchEditing
  JSDemos/Demos/DataGrid/BatchEditing/React/App.js
  JSDemos/Demos/DataGrid/BatchEditing/visualtestrc.json
Labels: 21_2

#1166 Fix Vue test: Accordion-Overview, MultiView-Overview, TabPanel-Overview
  JSDemos/Demos/Accordion/Overview/Vue/CustomItem.vue
  JSDemos/Demos/Accordion/Overview/visualtestrc.json
  JSDemos/Demos/MultiView/Overview/Vue/App.vue
  JSDemos/Demos/MultiView/Overview/visualtestrc.json
  JSDemos/Demos/TabPanel/Overview/Vue/App.vue
  JSDemos/Demos/TabPanel/Overview/visualtestrc.json
Labels: 21_2

#1164 Add search to demo-shell
  index.html
Labels: 21_2

#1174 fix typo in test-utils.js
  utils/visual-tests/inject/test-utils.js
Labels: 21_2

#1177 Fix React test: TextArea-Overview
  JSDemos/Demos/TextArea/Overview/React/App.js
  JSDemos/Demos/TextArea/Overview/visualtestrc.json
Labels: 21_2

#1178 Fix React and Vue test: LoadIndicator-Overview
  JSDemos/Demos/LoadIndicator/Overview/Angular/app/app.component.css
  JSDemos/Demos/LoadIndicator/Overview/Angular/app/app.component.html
  JSDemos/Demos/LoadIndicator/Overview/React/App.js
  JSDemos/Demos/LoadIndicator/Overview/React/styles.css
  JSDemos/Demos/LoadIndicator/Overview/Vue/App.vue
  JSDemos/Demos/LoadIndicator/Overview/jQuery/index.html
  JSDemos/Demos/LoadIndicator/Overview/jQuery/styles.css
  JSDemos/Demos/LoadIndicator/Overview/test-code.js
  JSDemos/Demos/LoadIndicator/Overview/visualtestrc.json
Labels: 21_2

#1175 Update grid pager (fix etalons)
  testing/etalons/DataGrid-AdvancedMasterDetailView.png
  testing/etalons/DataGrid-BatchUpdateRequest.png
  testing/etalons/DataGrid-CellCustomization.png
  testing/etalons/DataGrid-ColumnsBasedOnADataSource.png
  testing/etalons/DataGrid-CustomDataSource.png
  testing/etalons/DataGrid-CustomEditors.png
  testing/etalons/DataGrid-DeferredSelection.png
  testing/etalons/DataGrid-EditStateManagement.png
  testing/etalons/DataGrid-ExcelCellCustomization.png
  testing/etalons/DataGrid-ExcelJS.png
  testing/etalons/DataGrid-ExportToPDF.png
  testing/etalons/DataGrid-Filtering.png
  testing/etalons/DataGrid-FilteringAPI.png
  testing/etalons/DataGrid-FocusedRow.png
  testing/etalons/DataGrid-GridAdaptabilityOverview.png
  testing/etalons/DataGrid-GridColumnsHidingPriority.png
  testing/etalons/DataGrid-GridSummaries.png
  testing/etalons/DataGrid-GroupSummaries.png
  testing/etalons/DataGrid-KeyboardNavigation.png
  testing/etalons/DataGrid-MultipleRecordSelectionModes.png
  testing/etalons/DataGrid-Overview.png
  testing/etalons/DataGrid-RecalculateWhileEditing.png
  testing/etalons/DataGrid-RecordGrouping.png
  testing/etalons/DataGrid-RecordPaging.png
  testing/etalons/DataGrid-RightToLeftSupport.png
  testing/etalons/DataGrid-StatePersistence.png
  testing/etalons/TreeList-KeyboardNavigation.png
  testing/etalons/TreeList-Paging.png
Labels: 21_2

#1179 Fix Vue test: Common-Editors Overview
  JSDemos/Demos/Common/EditorsOverview/visualtestrc.json
Labels: 21_2

#1180 Fix Vue test: DataGrid-Multiple Record Selection API
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/visualtestrc.json
Labels: 21_2

#1184 Fix AngularJS, MVC and NetCore styles after change etalon screenshots
  JSDemos/Demos/DataGrid/BatchEditing/AngularJS/styles.css
  JSDemos/Demos/TreeList/FilterModes/AngularJS/styles.css
  MVCDemos/Content/DemosStyles/DataGrid/BatchEditing.css
  MVCDemos/Content/DemosStyles/TreeList/FilterModes.css
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/BatchEditing.css
  NetCoreDemos/wwwroot/css/DemosStyles/TreeList/FilterModes.css
Labels: 21_2

#1186 Fix AngularJS, MVC and NetCore styles after change etalon screenshots
  JSDemos/Demos/DataGrid/RealTimeUpdates/AngularJS/styles.css
  MVCDemos/Content/DemosStyles/DataGrid/RealTimeUpdates.css
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/RealTimeUpdates.css
Labels: 21_2

#1185 Drawer Demo - fix closing on outside click
  JSDemos/Demos/Drawer/TopOrBottomPosition/React/App.js
Labels: 21_2

#1199 Fix Vue test: DataGrid - Appearance
  JSDemos/Demos/DataGrid/Appearance/Vue/App.vue
  JSDemos/Demos/DataGrid/Appearance/visualtestrc.json
Labels: 21_2

#1198 Fix Vue test: Charts - PieWithResolvedLabelOverlapping
  JSDemos/Demos/Charts/PieWithResolvedLabelOverlapping/Angular/app/app.component.css
  JSDemos/Demos/Charts/PieWithResolvedLabelOverlapping/AngularJS/styles.css
  JSDemos/Demos/Charts/PieWithResolvedLabelOverlapping/React/styles.css
  JSDemos/Demos/Charts/PieWithResolvedLabelOverlapping/Vue/App.vue
  JSDemos/Demos/Charts/PieWithResolvedLabelOverlapping/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Charts/PieWithResolvedLabelOverlapping.css
  NetCoreDemos/wwwroot/css/DemosStyles/Charts/PieWithResolvedLabelOverlapping.css
  testing/etalons/Charts-PieWithResolvedLabelOverlapping.png
Labels: 21_2

#1203 Fix Vue test: TreeView-ItemSelectionAndCustomization
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Angular/app/app.component.css
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Angular/app/app.component.html
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/AngularJS/index.html
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/AngularJS/styles.css
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/React/App.js
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/React/styles.css
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Vue/App.vue
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/jQuery/index.html
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/jQuery/styles.css
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/visualtestrc.json
  MVCDemos/Content/DemosStyles/TreeView/ItemSelectionAndCustomization.css
  MVCDemos/Views/TreeView/ItemSelectionAndCustomization.cshtml
  NetCoreDemos/Views/TreeView/ItemSelectionAndCustomization.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TreeView/ItemSelectionAndCustomization.css
  testing/etalons/TreeView-ItemSelectionAndCustomization.png
Labels: 21_2

#1202 Fix Vue test: TreeList-LocalReordering
  JSDemos/Demos/TreeList/LocalReordering/Angular/app/app.component.css
  JSDemos/Demos/TreeList/LocalReordering/Angular/app/app.component.html
  JSDemos/Demos/TreeList/LocalReordering/React/App.js
  JSDemos/Demos/TreeList/LocalReordering/React/styles.css
  JSDemos/Demos/TreeList/LocalReordering/Vue/App.vue
  JSDemos/Demos/TreeList/LocalReordering/jQuery/index.html
  JSDemos/Demos/TreeList/LocalReordering/jQuery/styles.css
  JSDemos/Demos/TreeList/LocalReordering/visualtestrc.json
  MVCDemos/Content/DemosStyles/TreeList/LocalReordering.css
  MVCDemos/Views/TreeList/LocalReordering.cshtml
  NetCoreDemos/Views/TreeList/LocalReordering.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TreeList/LocalReordering.css
  testing/etalons/TreeList-LocalReordering.png
Labels: 21_2

#1204 Fix Vue test: Charts - ScaleBreaks
  JSDemos/Demos/Charts/ScaleBreaks/Angular/app/app.component.css
  JSDemos/Demos/Charts/ScaleBreaks/Angular/app/app.component.html
  JSDemos/Demos/Charts/ScaleBreaks/AngularJS/index.html
  JSDemos/Demos/Charts/ScaleBreaks/AngularJS/styles.css
  JSDemos/Demos/Charts/ScaleBreaks/React/App.js
  JSDemos/Demos/Charts/ScaleBreaks/React/styles.css
  JSDemos/Demos/Charts/ScaleBreaks/Vue/App.vue
  JSDemos/Demos/Charts/ScaleBreaks/jQuery/index.html
  JSDemos/Demos/Charts/ScaleBreaks/jQuery/styles.css
  JSDemos/Demos/Charts/ScaleBreaks/visualtestrc.json
  MVCDemos/Content/DemosStyles/Charts/ScaleBreaks.css
  MVCDemos/Views/Charts/ScaleBreaks.cshtml
  NetCoreDemos/Views/Charts/ScaleBreaks.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Charts/ScaleBreaks.css
  testing/etalons/Charts-ScaleBreaks.png
Labels: 21_2

#1207 Fix React and Vue test: DataGrid - EditStateManagement
  JSDemos/Demos/DataGrid/EditStateManagement/visualtestrc.json
Labels: 21_2

#1210 Fix React test: Scheduler Overview
  JSDemos/Demos/Scheduler/Overview/visualtestrc.json
Labels: 21_2
