Repository DevExpress/devextreme-demos, pull requests merged in 2021-12, with the labels that each got.

#1543 Form - labelMode for Overview demo
  JSDemos/Demos/Form/Overview/Angular/app/app.component.html
  JSDemos/Demos/Form/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Form/Overview/Angular/app/app.service.ts
  JSDemos/Demos/Form/Overview/AngularJS/data.js
  JSDemos/Demos/Form/Overview/AngularJS/index.html
  JSDemos/Demos/Form/Overview/AngularJS/index.js
  JSDemos/Demos/Form/Overview/React/App.js
  JSDemos/Demos/Form/Overview/React/data.js
  JSDemos/Demos/Form/Overview/Vue/App.vue
  JSDemos/Demos/Form/Overview/Vue/data.js
  JSDemos/Demos/Form/Overview/description.md
  JSDemos/Demos/Form/Overview/jQuery/data.js
  JSDemos/Demos/Form/Overview/jQuery/index.html
  JSDemos/Demos/Form/Overview/jQuery/index.js
  JSDemos/menuMeta.json
  MVCDemos/Controllers/FormController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/ActiveCompany.cs
  MVCDemos/Models/SampleData/ActiveCompanies.cs
  MVCDemos/Views/Form/Overview.cshtml
  NetCoreDemos/Controllers/FormController.cs
  NetCoreDemos/Models/ActiveCompany.cs
  NetCoreDemos/Models/SampleData/ActiveCompanies.cs
  NetCoreDemos/Views/Form/Overview.cshtml
  testing/etalons/Form-Overview.png
Labels: 21_2

#1552 Form - Fix Overview Demo
  MVCDemos/Views/Form/Overview.cshtml
  NetCoreDemos/Views/Form/Overview.cshtml
Labels: 21_2

#1551 Form - labelMode for Overview demo (#1543)
  JSDemos/Demos/Form/Overview/Angular/app/app.component.html
  JSDemos/Demos/Form/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Form/Overview/Angular/app/app.service.ts
  JSDemos/Demos/Form/Overview/AngularJS/data.js
  JSDemos/Demos/Form/Overview/AngularJS/index.html
  JSDemos/Demos/Form/Overview/AngularJS/index.js
  JSDemos/Demos/Form/Overview/React/App.js
  JSDemos/Demos/Form/Overview/React/data.js
  JSDemos/Demos/Form/Overview/Vue/App.vue
  JSDemos/Demos/Form/Overview/Vue/data.js
  JSDemos/Demos/Form/Overview/description.md
  JSDemos/Demos/Form/Overview/jQuery/data.js
  JSDemos/Demos/Form/Overview/jQuery/index.html
  JSDemos/Demos/Form/Overview/jQuery/index.js
  JSDemos/menuMeta.json
  MVCDemos/Controllers/FormController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/ActiveCompany.cs
  MVCDemos/Models/SampleData/ActiveCompanies.cs
  MVCDemos/Views/Form/Overview.cshtml
  NetCoreDemos/Controllers/FormController.cs
  NetCoreDemos/Models/ActiveCompany.cs
  NetCoreDemos/Models/SampleData/ActiveCompanies.cs
  NetCoreDemos/Views/Form/Overview.cshtml
  testing/etalons/Form-Overview.png
Labels: cherry-pick, 22_1

#1542 Update Multiple Record Selection demo according to default of selection.showCheckBoxesMode
  JSDemos/Demos/DataGrid/MultipleRecordSelectionModes/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/MultipleRecordSelectionModes/AngularJS/index.js
  JSDemos/Demos/DataGrid/MultipleRecordSelectionModes/React/App.js
  JSDemos/Demos/DataGrid/MultipleRecordSelectionModes/Vue/App.vue
  JSDemos/Demos/DataGrid/MultipleRecordSelectionModes/jQuery/index.js
  MVCDemos/Views/DataGrid/MultipleRecordSelectionModes.cshtml
  NetCoreDemos/Views/DataGrid/MultipleRecordSelectionModes.cshtml
Labels: 21_2

#1549 Update Multiple Record Selection demo according to default of selection.showCheckBoxesMode
  JSDemos/Demos/DataGrid/MultipleRecordSelectionModes/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/MultipleRecordSelectionModes/AngularJS/index.js
  JSDemos/Demos/DataGrid/MultipleRecordSelectionModes/React/App.js
  JSDemos/Demos/DataGrid/MultipleRecordSelectionModes/Vue/App.vue
  JSDemos/Demos/DataGrid/MultipleRecordSelectionModes/jQuery/index.js
  MVCDemos/Views/DataGrid/MultipleRecordSelectionModes.cshtml
  NetCoreDemos/Views/DataGrid/MultipleRecordSelectionModes.cshtml
Labels: cherry-pick, 22_1

#1553 Form - Overview demo. Use floating label mode by default
  JSDemos/Demos/Form/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Form/Overview/AngularJS/index.js
  JSDemos/Demos/Form/Overview/React/App.js
  JSDemos/Demos/Form/Overview/Vue/App.vue
  JSDemos/Demos/Form/Overview/jQuery/index.js
  JSDemos/Demos/Form/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Form/Overview.css
  MVCDemos/Views/Form/Overview.cshtml
  NetCoreDemos/Views/Form/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Form/Overview.css
  testing/etalons/Form-Overview.png
Labels: 21_2

#1554 Form - Overview demo. Use floating label mode by default (#1553)
  JSDemos/Demos/Form/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Form/Overview/AngularJS/index.js
  JSDemos/Demos/Form/Overview/React/App.js
  JSDemos/Demos/Form/Overview/Vue/App.vue
  JSDemos/Demos/Form/Overview/jQuery/index.js
  JSDemos/Demos/Form/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Form/Overview.css
  MVCDemos/Views/Form/Overview.cshtml
  NetCoreDemos/Views/Form/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Form/Overview.css
  testing/etalons/Form-Overview.png
Labels: cherry-pick, 22_1

#1556 CheckBox Overview: change demo description
  JSDemos/Demos/CheckBox/Overview/Angular/description.md
  JSDemos/Demos/CheckBox/Overview/Vue/description.md
  JSDemos/Demos/CheckBox/Overview/description.md
Labels: 21_2

#1559 CheckBox Overview: change demo description
  JSDemos/Demos/CheckBox/Overview/Angular/description.md
  JSDemos/Demos/CheckBox/Overview/Vue/description.md
  JSDemos/Demos/CheckBox/Overview/description.md
Labels: cherry-pick, 22_1

#1547 Sankey Chart: Change demo description
  JSDemos/Demos/Charts/SankeyChart/description.md
Labels: 21_2

#1560 Sankey Chart: Change demo description (#1547)
  JSDemos/Demos/Charts/SankeyChart/description.md
Labels: cherry-pick, 22_1

#1564 Autocomplete: Change demo description
  JSDemos/Demos/Autocomplete/Overview/description.md
Labels: 21_2

#1565 Autocomplete: Change demo description (#1564)
  JSDemos/Demos/Autocomplete/Overview/description.md
Labels: cherry-pick, 22_1

#1566 Charts Export and Printing API: Change demo description
  JSDemos/Demos/Charts/ExportAndPrintingAPI/description.md
Labels: 21_2

#1567 Charts Export and Printing API: Change demo description (#1566)
  JSDemos/Demos/Charts/ExportAndPrintingAPI/description.md
Labels: cherry-pick, 22_1

#1577 DataGrid: Update etalons and add mask for guid
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_1_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_2_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop_mask.png
Labels: 22_1

#1576 Update DataGrid-MultipleRecordSelectionAPI etalons
  testing/widgets/datagrid/etalons/datagrid_multiple_record_selection_and_API_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_multiple_record_selection_and_API_6_desktop.png
  testing/widgets/datagrid/etalons/datagrid_multiple_record_selection_and_API_7_desktop.png
Labels: 22_1

#1579 Update DataGrid-MultipleRecordSelectionAPI etalons
  testing/widgets/datagrid/etalons/datagrid_multiple_record_selection_and_API_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_multiple_record_selection_and_API_6_desktop.png
  testing/widgets/datagrid/etalons/datagrid_multiple_record_selection_and_API_7_desktop.png
Labels: cherry-pick, 21_2

#1581 Exclude renovation folder in update angular metadata step to fix angular build
  .github/workflows/visual_tests_frameworks.yml
Labels: 22_1

#1580 Exclude renovation folder in update angular metadata step to fix angular build
  .github/workflows/visual_tests_frameworks.yml
Labels: cherry-pick, 21_2

#1568 Update etalon of Charts-SignalRService demo
  testing/etalons/Charts-SignalRService.png
Labels: 21_2

#1569 Update etalon of Charts-SignalRService demo
  testing/etalons/Charts-SignalRService.png
Labels: cherry-pick, 22_1

#1578 dxScheduler - remove unused 'resource' property in angular approach
  JSDemos/Demos/Scheduler/TimeZonesSupport/Angular/app/app.component.html
Labels: 21_2

#1583 dxScheduler - remove unused 'resource' property in angular approach
  JSDemos/Demos/Scheduler/TimeZonesSupport/Angular/app/app.component.html
Labels: cherry-pick, 22_1

#1571 fix lint errors, regarding types in our demos
  JSDemos/Demos/Form/UpdateItemsDynamically/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/ScrollView/Overview/Angular/app/app.component.ts
Labels: 21_2

#1570 fix lint errors, regarding types in our demos
  JSDemos/Demos/Form/UpdateItemsDynamically/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/ScrollView/Overview/Angular/app/app.component.ts
Labels: 22_1

#1585 dxScheduler - remove deprecated property and replace on real property
  JSDemos/Demos/Scheduler/TimeZonesSupport/Vue/App.vue
Labels: 21_2

#1586 dxScheduler - remove deprecated property and replace on real property
  JSDemos/Demos/Scheduler/TimeZonesSupport/Vue/App.vue
Labels: cherry-pick, 22_1

#1587 Delete demo DocUrls
  JSDemos/menuMeta.json
Labels: 21_2

#1589 Delete demo DocUrls (#1587)
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1563 Enable renovate for 21_2 inside 22_1
  renovate.json
Labels: 22_1

#1592 Testcafe - add frameworks
  .gitignore
  testing/widgets/datagrid/Appearance.test.js
  testing/widgets/datagrid/BatchEditing.test.js
  testing/widgets/datagrid/BatchUpdateRequest.test.js
  testing/widgets/datagrid/CellEditingAndEditingAPI.test.js
  testing/widgets/datagrid/ColumnCustomization.test.js
  testing/widgets/datagrid/CustomNewRecordPosition.test.js
  testing/widgets/datagrid/DataValidation.test.js
  testing/widgets/datagrid/EditStateManagement.test.js
  testing/widgets/datagrid/Filtering.test.js
  testing/widgets/datagrid/FilteringAPI.test.js
  testing/widgets/datagrid/GroupSummaries.test.js
  testing/widgets/datagrid/InfiniteScrolling.test.js
  testing/widgets/datagrid/MasterDetailAPI.test.js
  testing/widgets/datagrid/MasterDetailView.test.js
  testing/widgets/datagrid/MultipleRecordSelectionAPI.test.js
  testing/widgets/datagrid/MultipleSorting.test.js
  testing/widgets/datagrid/RecordGrouping.test.js
  testing/widgets/datagrid/RecordPaging.test.js
  testing/widgets/datagrid/RemoteGrouping.test.js
  testing/widgets/datagrid/RowEditingAndEditingEvents.test.js
  testing/widgets/datagrid/RowSelection.test.js
  testing/widgets/datagrid/StatePersistence.test.js
  testing/widgets/datagrid/VirtualScrolling.test.js
  testing/widgets/scheduler/contextMenuIntegration.test.js
  testing/widgets/scheduler/templates.test.js
  utils/tests/testcafe-helpers/matrix-test-helper.test.js
  utils/visual-tests/matrix-test-helped.d.ts
  utils/visual-tests/matrix-test-helper.js
Labels: cherry-pick, 21_2

#1536 Testcafe - add frameworks
  .gitignore
  testing/widgets/datagrid/Appearance.test.js
  testing/widgets/datagrid/BatchEditing.test.js
  testing/widgets/datagrid/BatchUpdateRequest.test.js
  testing/widgets/datagrid/CellEditingAndEditingAPI.test.js
  testing/widgets/datagrid/ColumnCustomization.test.js
  testing/widgets/datagrid/CustomNewRecordPosition.test.js
  testing/widgets/datagrid/DataValidation.test.js
  testing/widgets/datagrid/EditStateManagement.test.js
  testing/widgets/datagrid/Filtering.test.js
  testing/widgets/datagrid/FilteringAPI.test.js
  testing/widgets/datagrid/GroupSummaries.test.js
  testing/widgets/datagrid/InfiniteScrolling.test.js
  testing/widgets/datagrid/MasterDetailAPI.test.js
  testing/widgets/datagrid/MasterDetailView.test.js
  testing/widgets/datagrid/MultipleRecordSelectionAPI.test.js
  testing/widgets/datagrid/MultipleSorting.test.js
  testing/widgets/datagrid/RecordGrouping.test.js
  testing/widgets/datagrid/RecordPaging.test.js
  testing/widgets/datagrid/RemoteGrouping.test.js
  testing/widgets/datagrid/RowEditingAndEditingEvents.test.js
  testing/widgets/datagrid/RowSelection.test.js
  testing/widgets/datagrid/StatePersistence.test.js
  testing/widgets/datagrid/VirtualScrolling.test.js
  testing/widgets/scheduler/contextMenuIntegration.test.js
  testing/widgets/scheduler/templates.test.js
  utils/tests/testcafe-helpers/matrix-test-helper.test.js
  utils/visual-tests/matrix-test-helped.d.ts
  utils/visual-tests/matrix-test-helper.js
Labels: 22_1

#1596 Add url for demo-shell
  index.html
Labels: 21_2

#1598 Add url for demo-shell (#1596)
  index.html
Labels: cherry-pick, 22_1

#1605 dxScheduler - replace mask in time indicator demo
  testing/etalons/Scheduler-CurrentTimeIndicator_mask.png
Labels: cherry-pick, 22_1

#1604 dxScheduler - replace mask in time indicator demo
  testing/etalons/Scheduler-CurrentTimeIndicator_mask.png
Labels: 21_2

#1602 DataGrid: Fix styles in FormEditing angular demo (T1055147)
  .github/workflows/visual_tests_frameworks.yml
  JSDemos/Demos/DataGrid/FormEditing/Angular/app/app.component.ts
Labels: 22_1

#1601 DataGrid: Fix styles in FormEditing angular demo (T1055147)
  JSDemos/Demos/DataGrid/FormEditing/Angular/app/app.component.ts
Labels: cherry-pick, 21_2

#1606 Navigation: Change RTL demo description
  JSDemos/Demos/Common/NavigationRightToLeftSupport/description.md
Labels: 21_2
