Repository DevExpress/devextreme-demos, pull requests merged in 2021-02, with the labels that each got.

#563 dxScheduler - remove 'updated' from TimeZone demo and set 'updated' to Agenda demo
  JSDemos/menuMeta.json
Labels: 21_1

#566 fix typo in deferred selection demo (t970297)
  JSDemos/Demos/DataGrid/DeferredSelection/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/DeferredSelection/AngularJS/index.html
  JSDemos/Demos/DataGrid/DeferredSelection/Knockout/index.html
  JSDemos/Demos/DataGrid/DeferredSelection/React/App.js
  JSDemos/Demos/DataGrid/DeferredSelection/Vue/App.vue
  JSDemos/Demos/DataGrid/DeferredSelection/jQuery/index.html
  MVCDemos/Views/DataGrid/DeferredSelection.cshtml
  NetCoreDemos/Views/DataGrid/DeferredSelection.cshtml
Labels: 20_2

#567 fix typo in deferred selection demo (t970297) (cherry pick)
  JSDemos/Demos/DataGrid/DeferredSelection/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/DeferredSelection/AngularJS/index.html
  JSDemos/Demos/DataGrid/DeferredSelection/Knockout/index.html
  JSDemos/Demos/DataGrid/DeferredSelection/React/App.js
  JSDemos/Demos/DataGrid/DeferredSelection/Vue/App.vue
  JSDemos/Demos/DataGrid/DeferredSelection/jQuery/index.html
  MVCDemos/Views/DataGrid/DeferredSelection.cshtml
  NetCoreDemos/Views/DataGrid/DeferredSelection.cshtml
Labels: 21_1, cherry-pick

#572 Remove popup position from the DataGrid popup editing demo
  JSDemos/Demos/DataGrid/PopupEditing/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/PopupEditing/AngularJS/index.js
  JSDemos/Demos/DataGrid/PopupEditing/Knockout/index.js
  JSDemos/Demos/DataGrid/PopupEditing/React/App.js
  JSDemos/Demos/DataGrid/PopupEditing/Vue/App.vue
  JSDemos/Demos/DataGrid/PopupEditing/jQuery/index.js
  MVCDemos/Views/DataGrid/PopupEditing.cshtml
  NetCoreDemos/Views/DataGrid/PopupEditing.cshtml
Labels: 21_1

#573 CP #572 - Remove popup position from the DataGrid popup editing demo
  JSDemos/Demos/DataGrid/PopupEditing/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/PopupEditing/AngularJS/index.js
  JSDemos/Demos/DataGrid/PopupEditing/Knockout/index.js
  JSDemos/Demos/DataGrid/PopupEditing/React/App.js
  JSDemos/Demos/DataGrid/PopupEditing/Vue/App.vue
  JSDemos/Demos/DataGrid/PopupEditing/jQuery/index.js
  MVCDemos/Views/DataGrid/PopupEditing.cshtml
  NetCoreDemos/Views/DataGrid/PopupEditing.cshtml
Labels: 20_2, cherry-pick

#575 dxScheduler - add appointmentsWorkHours.cs to metaJason
  JSDemos/menuMeta.json
Labels: 21_1, cherry-pick

#574 dxScheduler - add appointmentsWorkHours.cs to metaJason
  JSDemos/menuMeta.json
Labels: 20_2

#583 Remove popup position config from TreeList Popup Editing demo
  JSDemos/Demos/TreeList/PopupEditing/Angular/app/app.component.html
  JSDemos/Demos/TreeList/PopupEditing/AngularJS/index.js
  JSDemos/Demos/TreeList/PopupEditing/Knockout/index.js
  JSDemos/Demos/TreeList/PopupEditing/React/App.js
  JSDemos/Demos/TreeList/PopupEditing/Vue/App.vue
  JSDemos/Demos/TreeList/PopupEditing/jQuery/index.js
  MVCDemos/Views/TreeList/PopupEditing.cshtml
  NetCoreDemos/Views/TreeList/PopupEditing.cshtml
Labels: 21_1

#584 Remove popup position config from TreeList Popup Editing demo (CP #583)
  JSDemos/Demos/TreeList/PopupEditing/Angular/app/app.component.html
  JSDemos/Demos/TreeList/PopupEditing/AngularJS/index.js
  JSDemos/Demos/TreeList/PopupEditing/Knockout/index.js
  JSDemos/Demos/TreeList/PopupEditing/React/App.js
  JSDemos/Demos/TreeList/PopupEditing/Vue/App.vue
  JSDemos/Demos/TreeList/PopupEditing/jQuery/index.js
  MVCDemos/Views/TreeList/PopupEditing.cshtml
  NetCoreDemos/Views/TreeList/PopupEditing.cshtml
Labels: 20_2, cherry-pick

#577 Add a capability to close a drop down on click/selection to the DDB-S…
  JSDemos/Demos/DropDownBox/SingleSelection/Angular/app/app.component.html
  JSDemos/Demos/DropDownBox/SingleSelection/Angular/app/app.component.ts
  JSDemos/Demos/DropDownBox/SingleSelection/AngularJS/index.js
  JSDemos/Demos/DropDownBox/SingleSelection/Knockout/index.js
  JSDemos/Demos/DropDownBox/SingleSelection/React/App.js
  JSDemos/Demos/DropDownBox/SingleSelection/Vue/App.vue
  JSDemos/Demos/DropDownBox/SingleSelection/jQuery/index.js
  MVCDemos/Views/DropDownBox/SingleSelection.cshtml
  NetCoreDemos/Views/DropDownBox/SingleSelection.cshtml
Labels: 20_2

#578 Add a capability to close a drop down on click/selection to the DDB-S…
  JSDemos/Demos/DropDownBox/SingleSelection/Angular/app/app.component.html
  JSDemos/Demos/DropDownBox/SingleSelection/Angular/app/app.component.ts
  JSDemos/Demos/DropDownBox/SingleSelection/AngularJS/index.js
  JSDemos/Demos/DropDownBox/SingleSelection/Knockout/index.js
  JSDemos/Demos/DropDownBox/SingleSelection/React/App.js
  JSDemos/Demos/DropDownBox/SingleSelection/Vue/App.vue
  JSDemos/Demos/DropDownBox/SingleSelection/jQuery/index.js
  MVCDemos/Views/DropDownBox/SingleSelection.cshtml
  NetCoreDemos/Views/DropDownBox/SingleSelection.cshtml
Labels: 21_1, cherry-pick

#579 Update non optimal Razor code in ASP.NET demos
  MVCDemos/Views/DataGrid/BatchEditing.cshtml
  MVCDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  MVCDemos/Views/DataGrid/CommandColumnCustomization.cshtml
  MVCDemos/Views/DataGrid/CustomEditors.cshtml
  MVCDemos/Views/DataGrid/FilterPanel.cshtml
  MVCDemos/Views/DataGrid/InfiniteScrolling.cshtml
  MVCDemos/Views/DataGrid/MasterDetailView.cshtml
  MVCDemos/Views/DataGrid/RowEditingAndEditingEvents.cshtml
  MVCDemos/Views/DataGrid/VirtualScrolling.cshtml
  MVCDemos/Views/Scheduler/Adaptability.cshtml
  MVCDemos/Views/Scheduler/CellTemplates.cshtml
  MVCDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  MVCDemos/Views/Scheduler/CurrentTimeIndicator.cshtml
  MVCDemos/Views/Scheduler/Overview.cshtml
  NetCoreDemos/Views/DataGrid/BatchEditing.cshtml
  NetCoreDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  NetCoreDemos/Views/DataGrid/CommandColumnCustomization.cshtml
  NetCoreDemos/Views/DataGrid/CustomEditors.cshtml
  NetCoreDemos/Views/DataGrid/FilterPanel.cshtml
  NetCoreDemos/Views/DataGrid/InfiniteScrolling.cshtml
  NetCoreDemos/Views/DataGrid/MasterDetailView.cshtml
  NetCoreDemos/Views/DataGrid/RowEditingAndEditingEvents.cshtml
  NetCoreDemos/Views/DataGrid/VirtualScrolling.cshtml
  NetCoreDemos/Views/Scheduler/Adaptability.cshtml
  NetCoreDemos/Views/Scheduler/CellTemplates.cshtml
  NetCoreDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  NetCoreDemos/Views/Scheduler/CurrentTimeIndicator.cshtml
  NetCoreDemos/Views/Scheduler/Overview.cshtml
Labels: 21_1

#580 Update non optimal Razor code in ASP.NET demos (CP #579)
  MVCDemos/Views/DataGrid/BatchEditing.cshtml
  MVCDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  MVCDemos/Views/DataGrid/CommandColumnCustomization.cshtml
  MVCDemos/Views/DataGrid/CustomEditors.cshtml
  MVCDemos/Views/DataGrid/FilterPanel.cshtml
  MVCDemos/Views/DataGrid/InfiniteScrolling.cshtml
  MVCDemos/Views/DataGrid/MasterDetailView.cshtml
  MVCDemos/Views/DataGrid/RowEditingAndEditingEvents.cshtml
  MVCDemos/Views/DataGrid/VirtualScrolling.cshtml
  MVCDemos/Views/Scheduler/Adaptability.cshtml
  MVCDemos/Views/Scheduler/CellTemplates.cshtml
  MVCDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  MVCDemos/Views/Scheduler/CurrentTimeIndicator.cshtml
  MVCDemos/Views/Scheduler/Overview.cshtml
  NetCoreDemos/Views/DataGrid/BatchEditing.cshtml
  NetCoreDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  NetCoreDemos/Views/DataGrid/CommandColumnCustomization.cshtml
  NetCoreDemos/Views/DataGrid/CustomEditors.cshtml
  NetCoreDemos/Views/DataGrid/FilterPanel.cshtml
  NetCoreDemos/Views/DataGrid/InfiniteScrolling.cshtml
  NetCoreDemos/Views/DataGrid/MasterDetailView.cshtml
  NetCoreDemos/Views/DataGrid/RowEditingAndEditingEvents.cshtml
  NetCoreDemos/Views/DataGrid/VirtualScrolling.cshtml
  NetCoreDemos/Views/Scheduler/Adaptability.cshtml
  NetCoreDemos/Views/Scheduler/CellTemplates.cshtml
  NetCoreDemos/Views/Scheduler/ContextMenuIntegration.cshtml
  NetCoreDemos/Views/Scheduler/CurrentTimeIndicator.cshtml
  NetCoreDemos/Views/Scheduler/Overview.cshtml
Labels: 20_2, cherry-pick

#585 Change MVC preparation mechanism
  .eslintignore
  .gitignore
  README.md
  gulpfile.js/copy-common-asp-files.js
  gulpfile.js/copy-mercurial-asp-files.js
  gulpfile.js/index.js
  gulpfile.js/js.js
  gulpfile.js/mvc.js
  package.json
  repository.config.json
  utils/.eslintrc.js
  utils/interactive/prompts-questions.js
  utils/interactive/repos-helper.js
  utils/internal/prepare-common.js
  utils/internal/prepare-mvc.js
  utils/internal/prepare-netcore.js
  utils/shared/fs-utils.js
  utils/tests/shared/fs-utils.test.js
Labels: 21_1

#591 Remove mentions of HTML5
  MVCDemos/Content/Descr/Common/FormsAndMultiPurposeOverview.md
  MVCDemos/Views/Gantt/Toolbar.cshtml
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  MVCDemos/Views/HtmlEditor/Overview.cshtml
  MVCDemos/Views/HtmlEditor/ToolbarCustomization.cshtml
  NetCoreDemos/Views/Gantt/Toolbar.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/Overview.cshtml
  NetCoreDemos/Views/HtmlEditor/ToolbarCustomization.cshtml
Labels: 20_2

#593 Use itemTemplate instead of dxi-item #T969007
  JSDemos/Demos/TileView/ItemTemplate/Angular/app/app.component.html
Labels: 21_1

#594 Use itemTemplate instead of dxi-item #T969007 #593
  JSDemos/Demos/TileView/ItemTemplate/Angular/app/app.component.html
Labels: 20_2, cherry-pick

#597 Fix js task for not git environments (farm, mercurial)
  gulpfile.js/js.js
Labels: 21_1

#598 Fix js task for not git environments (farm, mercurial)
  gulpfile.js/js.js
Labels: 20_2

#601 Ignore BOM for DemoShell
  gulpfile.js/copy-mercurial-asp-files.js
Labels: 20_2

#602 Ignore BOM for DemoShell
  gulpfile.js/copy-mercurial-asp-files.js
Labels: 21_1, cherry-pick

#604 Fix netcore version patching
  gulpfile.js/copy-mercurial-asp-files.js
  package.json
Labels: 20_2, cherry-pick

#603 Fix netcore version patching
  gulpfile.js/copy-mercurial-asp-files.js
  package.json
Labels: 21_1

#606 Fix first Validation demo loading for netcore approach (T971142)
  NetCoreDemos/Startup.cs
Labels: 21_1

#608 Tree Shaking: Fix utils imports after switch package to esm
  JSDemos/Demos/Charts/Palette/Angular/app/app.component.ts
  JSDemos/Demos/Charts/Palette/React/App.js
  JSDemos/Demos/Charts/Palette/Vue/App.vue
  JSDemos/Demos/DataGrid/CRUDOperations/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/CRUDOperations/React/App.js
  JSDemos/Demos/DataGrid/CRUDOperations/Vue/App.vue
  JSDemos/Demos/DataGrid/CellCustomization/React/DiffCell.js
  JSDemos/Demos/DataGrid/CellCustomization/Vue/DiffCell.vue
  JSDemos/Demos/DataGrid/GridSummaries/React/App.js
  JSDemos/Demos/DataGrid/GridSummaries/Vue/App.vue
  JSDemos/Demos/Localization/UsingIntl/Angular/app/app.component.ts
  JSDemos/Demos/Localization/UsingIntl/React/App.js
  JSDemos/Demos/Localization/UsingIntl/Vue/App.vue
Labels: 21_1

#610 Fix the DataGrid's scrolling mode in the DropDownBox demos (T973993)
  JSDemos/Demos/DropDownBox/MultipleSelection/Angular/app/app.component.html
  JSDemos/Demos/DropDownBox/MultipleSelection/AngularJS/index.js
  JSDemos/Demos/DropDownBox/MultipleSelection/Knockout/index.js
  JSDemos/Demos/DropDownBox/MultipleSelection/React/App.js
  JSDemos/Demos/DropDownBox/MultipleSelection/Vue/App.vue
  JSDemos/Demos/DropDownBox/MultipleSelection/jQuery/index.js
  JSDemos/Demos/DropDownBox/SingleSelection/Angular/app/app.component.html
  JSDemos/Demos/DropDownBox/SingleSelection/AngularJS/index.js
  JSDemos/Demos/DropDownBox/SingleSelection/Knockout/index.js
  JSDemos/Demos/DropDownBox/SingleSelection/React/App.js
  JSDemos/Demos/DropDownBox/SingleSelection/Vue/App.vue
  JSDemos/Demos/DropDownBox/SingleSelection/jQuery/index.js
  MVCDemos/Views/DropDownBox/MultipleSelection.cshtml
  MVCDemos/Views/DropDownBox/SingleSelection.cshtml
  NetCoreDemos/Views/DropDownBox/MultipleSelection.cshtml
  NetCoreDemos/Views/DropDownBox/SingleSelection.cshtml
Labels: 21_1

#611 Fix the DataGrid's scrolling mode in the DropDownBox demos (T973993) #610
  JSDemos/Demos/DropDownBox/MultipleSelection/Angular/app/app.component.html
  JSDemos/Demos/DropDownBox/MultipleSelection/AngularJS/index.js
  JSDemos/Demos/DropDownBox/MultipleSelection/Knockout/index.js
  JSDemos/Demos/DropDownBox/MultipleSelection/React/App.js
  JSDemos/Demos/DropDownBox/MultipleSelection/Vue/App.vue
  JSDemos/Demos/DropDownBox/MultipleSelection/jQuery/index.js
  JSDemos/Demos/DropDownBox/SingleSelection/Angular/app/app.component.html
  JSDemos/Demos/DropDownBox/SingleSelection/AngularJS/index.js
  JSDemos/Demos/DropDownBox/SingleSelection/Knockout/index.js
  JSDemos/Demos/DropDownBox/SingleSelection/React/App.js
  JSDemos/Demos/DropDownBox/SingleSelection/Vue/App.vue
  JSDemos/Demos/DropDownBox/SingleSelection/jQuery/index.js
  MVCDemos/Views/DropDownBox/MultipleSelection.cshtml
  MVCDemos/Views/DropDownBox/SingleSelection.cshtml
  NetCoreDemos/Views/DropDownBox/MultipleSelection.cshtml
  NetCoreDemos/Views/DropDownBox/SingleSelection.cshtml
Labels: 20_2, cherry-pick

#614 Do not use symlinks
  gulpfile.js/copy-common-asp-files.js
  gulpfile.js/copy-mercurial-asp-files.js
Labels: 20_2

#615 Do not use symlinks (#614)
  gulpfile.js/copy-common-asp-files.js
  gulpfile.js/copy-mercurial-asp-files.js
Labels: 21_1, cherry-pick

#607 Fix first Validation demo loading for netcore approach (T971142)
  NetCoreDemos/Startup.cs
Labels: 20_2, cherry-pick

#618 Add minify files to the mvc projects
  gulpfile.js/copy-common-asp-files.js
  package.json
Labels: 21_1

#619 Add minify files to the mvc projects
  gulpfile.js/copy-common-asp-files.js
  package.json
Labels: 20_2, cherry-pick

#623 Filter script more carefully
  gulpfile.js/copy-common-asp-files.js
Labels: 20_2, cherry-pick

#622 Filter script more carefully
  gulpfile.js/copy-common-asp-files.js
Labels: 21_1

#624 Fix demos after inferno integration
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.js
  package.json
Labels: 21_1
