Repository DevExpress/devextreme-demos, pull requests merged in 2022-02, with the labels that each got.

#1681 DataGrid - simple array - using model instead of JS array
  MVCDemos/Controllers/DataGridController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/SampleData/SimpleArrayCustomers.cs
  MVCDemos/Views/DataGrid/SimpleArray.cshtml
  NetCoreDemos/Controllers/DataGridController.cs
  NetCoreDemos/Models/SampleData/SimpleArrayCustomers.cs
  NetCoreDemos/Views/DataGrid/SimpleArray.cshtml
Labels: 22_1

#1682 DataGrid - simple array - using model instead of JS array
  MVCDemos/Controllers/DataGridController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/SampleData/SimpleArrayCustomers.cs
  MVCDemos/Views/DataGrid/SimpleArray.cshtml
  NetCoreDemos/Controllers/DataGridController.cs
  NetCoreDemos/Models/SampleData/SimpleArrayCustomers.cs
  NetCoreDemos/Views/DataGrid/SimpleArray.cshtml
Labels: cherry-pick, 21_2

#1608 Navigation: Change RTL demo description (#1606)
  JSDemos/Demos/Common/NavigationRightToLeftSupport/description.md
Labels: cherry-pick, 22_1

#1698 Explicitly use dotnet 5.0.xxx for linting
  .github/workflows/visual_tests_frameworks.yml
Labels: 22_1

#1700 Explicitly use dotnet 5.0.xxx for linting
  .github/workflows/CI.yml
Labels: 21_1, cherry-pick

#1699 Explicitly use dotnet 5.0.xxx for linting
  .github/workflows/CI.yml
Labels: 21_2

#1696 Toolbar Overview: Change demo description
  JSDemos/Demos/Toolbar/Overview/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1702 Toolbar Overview: Change demo description (#1696)
  JSDemos/Demos/Toolbar/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1705 Compile wrappers metadata on demand
  .github/workflows/visual_tests_frameworks.yml
  JSDemos/Demos/DataGrid/MultiRowHeadersBands/visualtestrc.json
  testing/common.test.js
Labels: 22_1

#1703 fix links in demos
  JSDemos/Demos/Gantt/Sorting/description.md
Labels: 22_1

#1710 Fix link in dxGantt Sorting demo (#1703)
  JSDemos/Demos/Gantt/Sorting/description.md
Labels: cherry-pick, 21_2

#1707 Fix: run manual tests at target framework
  utils/visual-tests/matrix-test-helper.js
Labels: 22_1

#1729 Bar demo description 21_1
  JSDemos/Demos/Charts/StandardBar/description.md
Labels: 21_1, cherry-pick

#1725 Side by Side Bar Chart: update demo description (#1706)
  JSDemos/Demos/Charts/SideBySideBar/description.md
Labels: 21_1, cherry-pick

#1728 Bar demo description 21_2
  JSDemos/Demos/Charts/StandardBar/description.md
Labels: cherry-pick, 21_2

#1718 Fix: run manual tests at target framework (#1707)
  utils/visual-tests/matrix-test-helper.js
Labels: cherry-pick, 21_2

#1704 Bar Chart: update demo description
  JSDemos/Demos/Charts/StandardBar/description.md
Labels: 22_1

#1631 DataGrid - add frameworks to testcafe
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Vue/App.vue
  JSDemos/Demos/DataGrid/RecordGrouping/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/RecordGrouping/React/App.js
  JSDemos/Demos/DataGrid/RecordGrouping/Vue/App.vue
  testing/widgets/datagrid/Appearance.test.js
  testing/widgets/datagrid/BatchEditing.test.js
  testing/widgets/datagrid/BatchUpdateRequest.test.js
  testing/widgets/datagrid/CellEditingAndEditingAPI.test.js
  testing/widgets/datagrid/ColumnCustomization.test.js
  testing/widgets/datagrid/CustomNewRecordPosition.test.js
  testing/widgets/datagrid/DataValidation.test.js
  testing/widgets/datagrid/EditStateManagement.test.js
  testing/widgets/datagrid/Filtering.test.js
  testing/widgets/datagrid/FilteringAPI.test.js
  testing/widgets/datagrid/GroupSummaries.test.js
  testing/widgets/datagrid/InfiniteScrolling.test.js
  testing/widgets/datagrid/MasterDetailAPI.test.js
  testing/widgets/datagrid/MasterDetailView.test.js
  testing/widgets/datagrid/MultipleRecordSelectionAPI.test.js
  testing/widgets/datagrid/MultipleSorting.test.js
  testing/widgets/datagrid/RecordGrouping.test.js
  testing/widgets/datagrid/RecordPaging.test.js
  testing/widgets/datagrid/RemoteGrouping.test.js
  testing/widgets/datagrid/RowEditingAndEditingEvents.test.js
  testing/widgets/datagrid/RowSelection.test.js
  testing/widgets/datagrid/StatePersistence.test.js
  testing/widgets/datagrid/VirtualScrolling.test.js
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_5_desktop_mask.png
Labels: 22_1

#1734 Gantt validation demo: update description
  JSDemos/Demos/Gantt/Validation/description.md
Labels: cherry-pick, 21_2

#1733 Gantt validation demo: update description
  JSDemos/Demos/Gantt/Validation/description.md
Labels: 22_1
