Repository DevExpress/devextreme-demos, pull requests merged in 2022-04, with the labels that each got.

#1779 Resizable: add demo description
  JSDemos/Demos/Resizable/Overview/description.md
Labels: 22_1

#1785 Update grid record paging demo (21_2)
  JSDemos/Demos/DataGrid/RecordPaging/React/App.js
Labels: cherry-pick, 21_2

#1783 Change Cell Customization demo description
  JSDemos/Demos/DataGrid/PDFCellCustomization/description.md
Labels: 22_1

#1797 Fix build angular bundle
  utils/bundle/index.js
Labels: 22_1

#1798 updates devextreme-aspnet-data
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Web.config
  MVCDemos/packages.config
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  package.json
Labels: 21_2

#1799 File Manager - Temporarily change Azure demos screenshots
  testing/etalons/FileManager-AzureClientBinding.png
  testing/etalons/FileManager-AzureServerBinding.png
Labels: 22_1

#1800 File Manager - Temporarily change Azure demos screenshots
  testing/etalons/FileManager-AzureClientBinding.png
  testing/etalons/FileManager-AzureServerBinding.png
Labels: cherry-pick, 21_2

#1792 pdf export: add indent to pdf overview demo
  JSDemos/Demos/DataGrid/PDFCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFCellCustomization/React/App.js
  JSDemos/Demos/DataGrid/PDFCellCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFExportImages/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFExportImages/React/App.js
  JSDemos/Demos/DataGrid/PDFExportImages/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/React/App.js
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/React/App.js
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFOverview/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFOverview/React/App.js
  JSDemos/Demos/DataGrid/PDFOverview/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFOverview/jQuery/index.js
  MVCDemos/Views/DataGrid/PDFOverview.cshtml
  NetCoreDemos/Views/DataGrid/PDFOverview.cshtml
Labels: 22_1

#1803 Resizable: update handles' border appearance
  JSDemos/Demos/Resizable/Overview/Angular/app/app.component.css
  JSDemos/Demos/Resizable/Overview/Angular/app/app.component.html
  JSDemos/Demos/Resizable/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Resizable/Overview/React/App.js
  JSDemos/Demos/Resizable/Overview/React/styles.css
  JSDemos/Demos/Resizable/Overview/Vue/App.vue
  JSDemos/Demos/Resizable/Overview/Vue/styles.css
  JSDemos/Demos/Resizable/Overview/jQuery/index.js
  JSDemos/Demos/Resizable/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Resizable/Overview.css
  MVCDemos/Views/Resizable/Overview.cshtml
  NetCoreDemos/Views/Resizable/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Resizable/Overview.css
Labels: 22_1

#1793 File Management - Update Azure SDK packages
  MVCDemos/Controllers/ApiControllers/FileManagerAzureAccessApiController.cs
  MVCDemos/Controllers/ApiControllers/FileUploaderAzureAccessApiController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/FileManagement/AzureBlobFileProvider.cs
  MVCDemos/Scripts/utils/azure-file-system.js
  MVCDemos/Web.config
  MVCDemos/packages.config
  NetCoreDemos/Controllers/ApiControllers/FileManagerAzureAccessApiController.cs
  NetCoreDemos/Controllers/ApiControllers/FileUploaderAzureAccessApiController.cs
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  NetCoreDemos/Models/FileManagement/AzureBlobFileProvider.cs
  NetCoreDemos/wwwroot/utils/azure-file-system.js
Labels: 22_1

#1811 DataGrid - Overview - update etalons
  testing/etalons/DataGrid-Overview.png
  testing/etalons/FileManager-AzureClientBinding.png
  testing/etalons/FileManager-AzureServerBinding.png
Labels: cherry-pick, 21_2

#1810 DataGrid - Overview - update etalons
  testing/etalons/DataGrid-Overview.png
  testing/etalons/FileManager-AzureClientBinding.png
  testing/etalons/FileManager-AzureServerBinding.png
Labels: 22_1

#1806 Notify: add stack demo
  JSDemos/Demos/Toast/Stack/Angular/app/app.component.css
  JSDemos/Demos/Toast/Stack/Angular/app/app.component.html
  JSDemos/Demos/Toast/Stack/Angular/app/app.component.ts
  JSDemos/Demos/Toast/Stack/Angular/index.html
  JSDemos/Demos/Toast/Stack/React/App.js
  JSDemos/Demos/Toast/Stack/React/data.js
  JSDemos/Demos/Toast/Stack/React/index.html
  JSDemos/Demos/Toast/Stack/React/index.js
  JSDemos/Demos/Toast/Stack/React/styles.css
  JSDemos/Demos/Toast/Stack/Vue/App.vue
  JSDemos/Demos/Toast/Stack/Vue/index.html
  JSDemos/Demos/Toast/Stack/Vue/index.js
  JSDemos/Demos/Toast/Stack/description.md
  JSDemos/Demos/Toast/Stack/jQuery/data.js
  JSDemos/Demos/Toast/Stack/jQuery/index.html
  JSDemos/Demos/Toast/Stack/jQuery/index.js
  JSDemos/Demos/Toast/Stack/jQuery/style.css
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/Toast/Stack.css
  MVCDemos/Controllers/ToastController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/Toast/Stack.cshtml
  NetCoreDemos/Controllers/ToastController.cs
  NetCoreDemos/Views/Toast/Stack.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Toast/Stack.css
  testing/etalons/Toast-Stack.png
Labels: 22_1

#1717 Angular - remove deprecated `toPromise` method
  JSDemos/Demos/Charts/BarSparklines/Angular/app/app.component.ts
  JSDemos/Demos/Charts/ClientSideDataProcessing/Angular/app/app.component.ts
  JSDemos/Demos/Charts/LoadDataOnDemand/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/BatchUpdateRequest/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/CRUDOperations/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/CustomDataSource/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/DataValidation/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/EditStateManagement/Angular/app/app.service.ts
  JSDemos/Demos/DropDownBox/MultipleSelection/Angular/app/app.component.ts
  JSDemos/Demos/DropDownBox/SingleSelection/Angular/app/app.component.ts
  JSDemos/Demos/FileManager/AzureClientBinding/Angular/app/app.component.ts
  JSDemos/Demos/FileManager/AzureServerBinding/Angular/app/app.component.ts
  JSDemos/Demos/FileUploader/AzureDirectUploading/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/GoogleCalendarIntegration/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/LoadDataOnDemand/Angular/app/app.component.ts
  JSDemos/Demos/TreeView/LoadDataOnDemand/Angular/app/app.component.ts
  JSDemos/configs/Angular/config.bundle.js
  JSDemos/configs/Angular/config.js
  package-lock.json
  package.json
  utils/bundle/index.js
Labels: cherry-pick, 21_2

#1815 Export to PDF: Header and Footer description minor fix
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/description.md
Labels: 22_1

#1814 Drawer - Update 'Left or Right Position' demo description
  JSDemos/Demos/Drawer/LeftOrRightPosition/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1818 Drawer - Update 'Left or Right Position' demo description (#1814)
  JSDemos/Demos/Drawer/LeftOrRightPosition/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1819 Drawer - Update 'Top or Bottom Position' demo description
  JSDemos/Demos/Drawer/TopOrBottomPosition/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1821 File Uploader - Fix visual tests after localization update
  testing/etalons/FileUploader-AzureDirectUploading.png
  testing/etalons/FileUploader-ChunkUploading.png
  testing/etalons/FileUploader-FileUploading.png
  testing/etalons/FileUploader-Validation.png
Labels: cherry-pick, 21_2

#1820 File Uploader - Fix visual tests after localization update
  testing/etalons/FileUploader-AzureDirectUploading.png
  testing/etalons/FileUploader-ChunkUploading.png
  testing/etalons/FileUploader-FileUploading.png
  testing/etalons/FileUploader-Validation.png
Labels: 22_1

#1817 Editors & Overlays: update badges & Stack demo fixes
  JSDemos/Demos/Toast/Stack/Angular/app/app.component.css
  JSDemos/Demos/Toast/Stack/Angular/app/app.component.html
  JSDemos/Demos/Toast/Stack/React/App.js
  JSDemos/Demos/Toast/Stack/React/styles.css
  JSDemos/Demos/Toast/Stack/Vue/App.vue
  JSDemos/Demos/Toast/Stack/jQuery/index.html
  JSDemos/Demos/Toast/Stack/jQuery/index.js
  JSDemos/Demos/Toast/Stack/jQuery/style.css
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/Toast/Stack.css
  MVCDemos/Views/Toast/Stack.cshtml
  NetCoreDemos/Views/Toast/Stack.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Toast/Stack.css
  testing/etalons/Toast-Stack.png
Labels: 22_1

#1823 HtmlEditor Overview - update text in tabs selectbox
  JSDemos/Demos/HtmlEditor/Overview/Angular/app/app.service.ts
  JSDemos/Demos/HtmlEditor/Overview/AngularJS/data.js
  JSDemos/Demos/HtmlEditor/Overview/React/data.js
  JSDemos/Demos/HtmlEditor/Overview/Vue/data.js
  JSDemos/Demos/HtmlEditor/Overview/jQuery/data.js
  MVCDemos/Views/HtmlEditor/Overview.cshtml
  NetCoreDemos/Views/HtmlEditor/Overview.cshtml
Labels: 22_1

#1825 File Management - Try to fix MVC build
  MVCDemos/DevExtreme.MVC.Demos.csproj
Labels: 22_1

#1813 Tabs - Update demo description
  JSDemos/Demos/Tabs/Overview/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1826 Tabs - Update demo description (#1813)
  JSDemos/Demos/Tabs/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1827 File Management - Temporarily revert Azure changes
  MVCDemos/Controllers/ApiControllers/FileManagerAzureAccessApiController.cs
  MVCDemos/Controllers/ApiControllers/FileUploaderAzureAccessApiController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/FileManagement/AzureBlobFileProvider.cs
  MVCDemos/Scripts/utils/azure-file-system.js
  MVCDemos/Web.config
  MVCDemos/packages.config
  NetCoreDemos/Controllers/ApiControllers/FileManagerAzureAccessApiController.cs
  NetCoreDemos/Controllers/ApiControllers/FileUploaderAzureAccessApiController.cs
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  NetCoreDemos/Models/FileManagement/AzureBlobFileProvider.cs
  NetCoreDemos/wwwroot/utils/azure-file-system.js
Labels: 22_1

#1828 Toast: fix jQuery&ASP stack demo
  JSDemos/Demos/Toast/Stack/jQuery/index.html
  JSDemos/Demos/Toast/Stack/jQuery/index.js
  JSDemos/Demos/Toast/Stack/jQuery/styles.css
  MVCDemos/Views/Toast/Stack.cshtml
  NetCoreDemos/Views/Toast/Stack.cshtml
Labels: 22_1

#1830 pdf export: fix some issues
  JSDemos/Demos/DataGrid/PDFExportImages/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFExportImages/React/App.js
  JSDemos/Demos/DataGrid/PDFExportImages/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFExportImages/jQuery/index.js
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/React/App.js
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/jQuery/index.js
  MVCDemos/Content/DemosStyles/DataGrid/PDFExportImages.css
  MVCDemos/Content/DemosStyles/DataGrid/PDFExportMultipleGrids.css
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/DataGrid/PDFExportImages.cshtml
  MVCDemos/Views/DataGrid/PDFHeaderAndFooter.cshtml
  MVCDemos/Views/DataGrid/PDFOverview.cshtml
  NetCoreDemos/Views/DataGrid/PDFExportImages.cshtml
  NetCoreDemos/Views/DataGrid/PDFHeaderAndFooter.cshtml
  NetCoreDemos/Views/DataGrid/PDFOverview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/PDFExportImages.css
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/PDFExportMultipleGrids.css
Labels: 22_1

#1831 Update demo badges
  JSDemos/menuMeta.json
Labels: 22_1

#1832 pdf export: fix some remarks
  JSDemos/Demos/DataGrid/PDFExportImages/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFExportImages/React/App.js
  JSDemos/Demos/DataGrid/PDFExportImages/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFExportImages/jQuery/index.js
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/AngularJS/index.js
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/React/App.js
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/jQuery/index.js
  MVCDemos/Views/DataGrid/PDFCellCustomization.cshtml
  MVCDemos/Views/DataGrid/PDFExportImages.cshtml
  MVCDemos/Views/DataGrid/PDFExportMultipleGrids.cshtml
  MVCDemos/Views/DataGrid/PDFOverview.cshtml
  NetCoreDemos/Views/DataGrid/PDFCellCustomization.cshtml
  NetCoreDemos/Views/DataGrid/PDFExportImages.cshtml
  NetCoreDemos/Views/DataGrid/PDFExportMultipleGrids.cshtml
Labels: 22_1

#1833 update-aspnet-data 20.2.11
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/Charts/StackedBar.cshtml
  MVCDemos/Web.config
  MVCDemos/packages.config
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  NetCoreDemos/Views/Charts/StackedBar.cshtml
  NetCoreDemos/Views/DataGrid/InfiniteScrolling.cshtml
  NetCoreDemos/Views/DataGrid/VirtualScrolling.cshtml
  package.json
Labels: 20_2

#1835 Toast: rename stack direction aliases
  JSDemos/Demos/Toast/Stack/Angular/app/app.component.ts
  JSDemos/Demos/Toast/Stack/React/App.js
  JSDemos/Demos/Toast/Stack/React/data.js
  JSDemos/Demos/Toast/Stack/Vue/App.vue
  JSDemos/Demos/Toast/Stack/jQuery/data.js
  JSDemos/Demos/Toast/Stack/jQuery/index.js
  MVCDemos/Views/Toast/Stack.cshtml
  NetCoreDemos/Views/Toast/Stack.cshtml
  testing/etalons/Toast-Stack.png
Labels: 22_1
