Repository DevExpress/devextreme-demos, pull requests merged in 2022-12, with the labels that each got.

#2301 Add 'setup-dotnet' step to 'Lint code base' job
  .github/workflows/visual_tests_frameworks.yml
Labels: 22_2

#2303 DataGrid export: remove hidden demo
  JSDemos/Demos/DataGrid/ExcelJS/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/ExcelJS/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/ExcelJS/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJS/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/ExcelJS/Angular/index.html
  JSDemos/Demos/DataGrid/ExcelJS/AngularJS/data.js
  JSDemos/Demos/DataGrid/ExcelJS/AngularJS/index.html
  JSDemos/Demos/DataGrid/ExcelJS/AngularJS/index.js
  JSDemos/Demos/DataGrid/ExcelJS/AngularJS/styles.css
  JSDemos/Demos/DataGrid/ExcelJS/Knockout/data.js
  JSDemos/Demos/DataGrid/ExcelJS/Knockout/index.html
  JSDemos/Demos/DataGrid/ExcelJS/Knockout/index.js
  JSDemos/Demos/DataGrid/ExcelJS/Knockout/styles.css
  JSDemos/Demos/DataGrid/ExcelJS/React/App.js
  JSDemos/Demos/DataGrid/ExcelJS/React/data.js
  JSDemos/Demos/DataGrid/ExcelJS/React/index.html
  JSDemos/Demos/DataGrid/ExcelJS/React/index.js
  JSDemos/Demos/DataGrid/ExcelJS/React/styles.css
  JSDemos/Demos/DataGrid/ExcelJS/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJS/Vue/data.js
  JSDemos/Demos/DataGrid/ExcelJS/Vue/index.html
  JSDemos/Demos/DataGrid/ExcelJS/Vue/index.js
  JSDemos/Demos/DataGrid/ExcelJS/description.md
  JSDemos/Demos/DataGrid/ExcelJS/jQuery/data.js
  JSDemos/Demos/DataGrid/ExcelJS/jQuery/index.html
  JSDemos/Demos/DataGrid/ExcelJS/jQuery/index.js
  JSDemos/Demos/DataGrid/ExcelJS/jQuery/styles.css
  JSDemos/Demos/DataGrid/ExcelJS/test-code.js
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/DataGrid/ExcelJS.css
  MVCDemos/Controllers/DataGridController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/DataGrid/ExcelJS.cshtml
  NetCoreDemos/Controllers/DataGridController.cs
  NetCoreDemos/Views/DataGrid/ExcelJS.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/ExcelJS.css
  testing/etalons/DataGrid-ExcelJS.png
  testing/widgets/scheduler/etalons/scheduler_overview_selection.png
Labels: 22_2

#2269 Viz widgets - Add functionality tests
  JSDemos/Demos/Charts/CustomAnnotations/jQuery/index.js
  JSDemos/Demos/Charts/ZoomingOnAreaSelection/Angular/app/app.component.css
  JSDemos/Demos/Charts/ZoomingOnAreaSelection/Angular/app/app.component.html
  JSDemos/Demos/VectorMap/TooltipHTMLSupport/React/App.js
  testing/widgets/charts/Crosshair.test.js
  testing/widgets/charts/CustomAnnotationsDrag.test.js
  testing/widgets/charts/CustomLegendMarkers.test.js
  testing/widgets/charts/LoadDataOnDemand.test.js
  testing/widgets/charts/Overview.test.js
  testing/widgets/charts/PieLabelsOverlapping.test.js
  testing/widgets/charts/ZoomingAndScrollingAPI.test.js
  testing/widgets/charts/ZoomingOnAreaSelection.test.js
  testing/widgets/charts/etalons/annotations_drag.png
  testing/widgets/charts/etalons/charts_crosshair.png
  testing/widgets/charts/etalons/charts_custom_legend_marker.png
  testing/widgets/charts/etalons/charts_drag.png
  testing/widgets/charts/etalons/charts_overview_tooltip.png
  testing/widgets/charts/etalons/pie_resolve_labels_overlapping_hide.png
  testing/widgets/charts/etalons/pie_resolve_labels_overlapping_none.png
  testing/widgets/charts/etalons/range_selector_click_to_empty_place.png
  testing/widgets/charts/etalons/range_selector_slider_drag.png
  testing/widgets/charts/etalons/reset_zooming_by_selection.png
  testing/widgets/charts/etalons/zooming_by_selection.png
  testing/widgets/gauges/GaugeVariableNumberBars.test.js
  testing/widgets/gauges/etalons/bargauge_hide_bars.png
  testing/widgets/gauges/etalons/bargauge_show_bars.png
  testing/widgets/vectormap/TooltipHTMLSupport.test.js
  testing/widgets/vectormap/VectorMapZooming.test.js
  testing/widgets/vectormap/etalons/vector_map_viewport-changing.png
  testing/widgets/vectormap/etalons/vectormap_tooltip.png
  testing/widgets/vectormap/etalons/zoom_vector_map_by_control_bar.png
Labels: 22_2

#2308 Popup: Fix toolbar padding right in material
  JSDemos/Demos/Popup/Overview/Angular/app/app.component.css
  JSDemos/Demos/Popup/Overview/AngularJS/styles.css
  JSDemos/Demos/Popup/Overview/Knockout/styles.css
  JSDemos/Demos/Popup/Overview/React/styles.css
  JSDemos/Demos/Popup/Overview/Vue/App.vue
  JSDemos/Demos/Popup/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Popup/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/Popup/Overview.css
Labels: 22_2

#2305 Navigation - Right-to-Left Support demo: Add Vue and React
  JSDemos/Demos/Common/NavigationRightToLeftSupport/React/App.js
  JSDemos/Demos/Common/NavigationRightToLeftSupport/React/data.js
  JSDemos/Demos/Common/NavigationRightToLeftSupport/React/index.html
  JSDemos/Demos/Common/NavigationRightToLeftSupport/React/index.js
  JSDemos/Demos/Common/NavigationRightToLeftSupport/React/styles.css
  JSDemos/Demos/Common/NavigationRightToLeftSupport/Vue/App.vue
  JSDemos/Demos/Common/NavigationRightToLeftSupport/Vue/data.js
  JSDemos/Demos/Common/NavigationRightToLeftSupport/Vue/index.html
  JSDemos/Demos/Common/NavigationRightToLeftSupport/Vue/index.js
Labels: 22_2

#2306 Navigation - Right-to-Left Support demo: Add Vue and React
  JSDemos/Demos/Common/NavigationRightToLeftSupport/React/App.js
  JSDemos/Demos/Common/NavigationRightToLeftSupport/React/data.js
  JSDemos/Demos/Common/NavigationRightToLeftSupport/React/index.html
  JSDemos/Demos/Common/NavigationRightToLeftSupport/React/index.js
  JSDemos/Demos/Common/NavigationRightToLeftSupport/React/styles.css
  JSDemos/Demos/Common/NavigationRightToLeftSupport/Vue/App.vue
  JSDemos/Demos/Common/NavigationRightToLeftSupport/Vue/data.js
  JSDemos/Demos/Common/NavigationRightToLeftSupport/Vue/index.html
  JSDemos/Demos/Common/NavigationRightToLeftSupport/Vue/index.js
Labels: cherry-pick, 22_1

#2313 Fix FileManager-BindingToFileSystem vis test
  JSDemos/Demos/FileManager/BindingToFileSystem/test-code.js
  testing/etalons/FileManager-BindingToFileSystem.png
  testing/etalons/FileManager-BindingToFileSystem_mask.png
Labels: 22_2

#2315 scheduler - removed unused globalize imports
  JSDemos/Demos/Scheduler/CustomTemplates/React/AppointmentTooltip.js
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/AppointmentTooltipTemplate.vue
Labels: 22_2

#2319 Temporarily ignore `Scheduler/SignalRService` vis tests
  JSDemos/Demos/Scheduler/SignalRService/visualtestrc.json
Labels: force all tests, 22_2

#2323 Fix 'etalon' for `Scheduler/SignalRService`
  JSDemos/Demos/Scheduler/SignalRService/visualtestrc.json
  testing/etalons/Scheduler-SignalRService.png
Labels: force all tests, 22_1

#2325 SmartFormatter - Update etalons
  testing/etalons/Charts-Annotation.png
  testing/etalons/Charts-Area.png
  testing/etalons/Charts-AxisLabelsOverlapping.png
  testing/etalons/Charts-ChartsDrillDown.png
  testing/etalons/Charts-DiscreteAggregation.png
  testing/etalons/Charts-SignalRService.png
Labels: 22_2

#2321 scheduler - fixed date display issue and added testcafe test
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.ts
  testing/widgets/scheduler/cellTemplates.test.js
  testing/widgets/scheduler/etalons/scheduler_CellTemplates_month_view.png
Labels: 22_2

#2329 DialogsAndNotificationsOverview: fix syntax error in contentTemplate
  JSDemos/Demos/Common/DialogsAndNotificationsOverview/React/App.js
  JSDemos/Demos/Common/DialogsAndNotificationsOverview/Vue/App.vue
  JSDemos/Demos/Common/DialogsAndNotificationsOverview/jQuery/index.js
  testing/widgets/common/DialogsAndNotificationsOverview.test.js
  testing/widgets/common/etalons/common_dialogs_and_notifications_overview_popup.png
Labels: 22_2

#2331 Update the DataGrid-Overview etalon
  testing/etalons/DataGrid-Overview.png
Labels: 22_1

#2335 Fix GitHub workflows
  .github/workflows/CI.yml
  .github/workflows/renovate_autoapprove.yml
  .github/workflows/unit_tests.yml
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
Labels: 21_2

#2332 Fix FileManager-BindingToFileSystem vis test
  JSDemos/Demos/FileManager/BindingToFileSystem/test-code.js
  testing/etalons/FileManager-BindingToFileSystem.png
  testing/etalons/FileManager-BindingToFileSystem_mask.png
Labels: cherry-pick, 21_2

#2330 Update the Scheduler-SignalRService etalon
  testing/etalons/Scheduler-SignalRService.png
Labels: 21_2

#2295 DataGrid: Modify testcafe test for the Appearance demo
  testing/widgets/datagrid/Appearance.test.js
  testing/widgets/datagrid/etalons/datagrid_appearance_6_desktop.png
  testing/widgets/datagrid/etalons/datagrid_appearance_7_desktop.png
Labels: cherry-pick, 22_1

#2294 DataGrid: Modify testcafe test for the Appearance demo
  testing/widgets/datagrid/Appearance.test.js
  testing/widgets/datagrid/etalons/datagrid_appearance_6_desktop.png
  testing/widgets/datagrid/etalons/datagrid_appearance_7_desktop.png
Labels: 22_2

#2340 Update devextreme packages to new major version
  .github/workflows/unit_tests.yml
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  package-lock.json
  package.json
  renovate.json
Labels: 23_1

#2349 Revert "SmartFormatter - Update etalons"
  testing/etalons/Charts-Annotation.png
  testing/etalons/Charts-Area.png
  testing/etalons/Charts-AxisLabelsOverlapping.png
  testing/etalons/Charts-ChartsDrillDown.png
  testing/etalons/Charts-DiscreteAggregation.png
  testing/etalons/Charts-SignalRService.png
Labels: 22_2

#2344 Revert "Popup: Fix toolbar padding right (#2308)"
  JSDemos/Demos/Popup/Overview/Angular/app/app.component.css
  JSDemos/Demos/Popup/Overview/AngularJS/styles.css
  JSDemos/Demos/Popup/Overview/Knockout/styles.css
  JSDemos/Demos/Popup/Overview/React/styles.css
  JSDemos/Demos/Popup/Overview/Vue/App.vue
  JSDemos/Demos/Popup/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Popup/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/Popup/Overview.css
Labels: 22_2

#2348 Revert "Popup: Fix toolbar padding right (#2308)"
  JSDemos/Demos/Popup/Overview/Angular/app/app.component.css
  JSDemos/Demos/Popup/Overview/AngularJS/styles.css
  JSDemos/Demos/Popup/Overview/Knockout/styles.css
  JSDemos/Demos/Popup/Overview/React/styles.css
  JSDemos/Demos/Popup/Overview/Vue/App.vue
  JSDemos/Demos/Popup/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Popup/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/Popup/Overview.css
Labels: cherry-pick, 23_1

#2350 Temporarily disable system.js bundling
  .github/workflows/visual_tests_frameworks.yml
Labels: force all tests, 22_2

#2351 Temporarily disable system.js bundling (#2350)
  .github/workflows/visual_tests_frameworks.yml
Labels: cherry-pick, 23_1

#2341 Autocomplete: update demo description
  JSDemos/Demos/Autocomplete/Overview/Angular/app/app.component.html
  JSDemos/Demos/Autocomplete/Overview/AngularJS/index.html
  JSDemos/Demos/Autocomplete/Overview/Knockout/index.html
  JSDemos/Demos/Autocomplete/Overview/React/App.js
  JSDemos/Demos/Autocomplete/Overview/Vue/App.vue
  JSDemos/Demos/Autocomplete/Overview/description.md
  JSDemos/Demos/Autocomplete/Overview/jQuery/index.html
  testing/etalons/Autocomplete-Overview.png
Labels: 22_2

#2353 Autocomplete: update demo description (#2341)
  JSDemos/Demos/Autocomplete/Overview/Angular/app/app.component.html
  JSDemos/Demos/Autocomplete/Overview/AngularJS/index.html
  JSDemos/Demos/Autocomplete/Overview/Knockout/index.html
  JSDemos/Demos/Autocomplete/Overview/React/App.js
  JSDemos/Demos/Autocomplete/Overview/Vue/App.vue
  JSDemos/Demos/Autocomplete/Overview/description.md
  JSDemos/Demos/Autocomplete/Overview/jQuery/index.html
  testing/etalons/Autocomplete-Overview.png
Labels: cherry-pick, 23_1

#2356 Exclude devextreme-quill from system.js bundles
  .github/workflows/visual_tests_frameworks.yml
  JSDemos/configs/Angular/config.bundle.js
  JSDemos/configs/React/config.bundle.js
  JSDemos/configs/Vue/config.bundle.js
  utils/bundle/index.js
Labels: 22_2

#2357 Exclude devextreme-quill from system.js bundles (#2356)
  .github/workflows/visual_tests_frameworks.yml
  JSDemos/configs/Angular/config.bundle.js
  JSDemos/configs/React/config.bundle.js
  JSDemos/configs/Vue/config.bundle.js
  utils/bundle/index.js
Labels: cherry-pick, 23_1

#2352 Exclude devextreme-quill from system.js bundles
  .github/workflows/visual_tests_frameworks.yml
  JSDemos/configs/Angular/config.bundle.js
  JSDemos/configs/React/config.bundle.js
  JSDemos/configs/Vue/config.bundle.js
  utils/bundle/index.js
Labels: cherry-pick, 22_1
