Repository DevExpress/devextreme-demos, pull requests merged in 2022-05, with the labels that each got.

#1836 Toast: rename alias to predefined in Stack demo
  JSDemos/Demos/Toast/Stack/Angular/app/app.component.html
  JSDemos/Demos/Toast/Stack/Angular/app/app.component.ts
  JSDemos/Demos/Toast/Stack/React/App.js
  JSDemos/Demos/Toast/Stack/React/data.js
  JSDemos/Demos/Toast/Stack/Vue/App.vue
  JSDemos/Demos/Toast/Stack/jQuery/index.html
  JSDemos/Demos/Toast/Stack/jQuery/index.js
  MVCDemos/Views/Toast/Stack.cshtml
  NetCoreDemos/Views/Toast/Stack.cshtml
  testing/etalons/Toast-Stack.png
Labels: 22_1

#1838 Export to PDF demos: fix links
  JSDemos/Demos/DataGrid/PDFCellCustomization/description.md
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/description.md
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/description.md
  JSDemos/Demos/DataGrid/PDFOverview/description.md
Labels: 22_1

#1837 Toast: change position default value in Stack demo
  JSDemos/Demos/Toast/Stack/Angular/app/app.component.ts
  JSDemos/Demos/Toast/Stack/Vue/App.vue
Labels: 22_1

#1834 Toast Stack: add demo description
  JSDemos/Demos/Toast/Stack/description.md
Labels: 22_1

#1716 Angular - remove deprecated `toPromise` method
  JSDemos/Demos/Charts/BarSparklines/Angular/app/app.component.ts
  JSDemos/Demos/Charts/ClientSideDataProcessing/Angular/app/app.component.ts
  JSDemos/Demos/Charts/LoadDataOnDemand/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/BatchUpdateRequest/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/CRUDOperations/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/CustomDataSource/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/DataValidation/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/EditStateManagement/Angular/app/app.service.ts
  JSDemos/Demos/DropDownBox/MultipleSelection/Angular/app/app.component.ts
  JSDemos/Demos/DropDownBox/SingleSelection/Angular/app/app.component.ts
  JSDemos/Demos/FileManager/AzureClientBinding/Angular/app/app.component.ts
  JSDemos/Demos/FileManager/AzureServerBinding/Angular/app/app.component.ts
  JSDemos/Demos/FileUploader/AzureDirectUploading/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/GoogleCalendarIntegration/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/LoadDataOnDemand/Angular/app/app.component.ts
  JSDemos/Demos/TreeView/LoadDataOnDemand/Angular/app/app.component.ts
  JSDemos/configs/Angular/config.bundle.js
  JSDemos/configs/Angular/config.js
  package-lock.json
  package.json
  utils/bundle/index.js
Labels: 22_1

#1839 Toast Overview: change demo description
  JSDemos/Demos/Toast/Overview/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1840 Toast Overview: change demo description (#1839)
  JSDemos/Demos/Toast/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1841 MultiView: change demo description
  JSDemos/Demos/MultiView/Overview/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1843 MultiView: change demo description (#1841)
  JSDemos/Demos/MultiView/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1842 Box: change demo description
  JSDemos/Demos/Box/Overview/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1845 Box: change demo description (#1842)
  JSDemos/Demos/Box/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1847 Disable expandNodesRecursive based on T1087030
  JSDemos/Demos/TreeView/LoadDataOnDemand/Angular/app/app.component.html
  JSDemos/Demos/TreeView/LoadDataOnDemand/AngularJS/index.js
  JSDemos/Demos/TreeView/LoadDataOnDemand/Knockout/index.js
  JSDemos/Demos/TreeView/LoadDataOnDemand/React/App.js
  JSDemos/Demos/TreeView/LoadDataOnDemand/Vue/App.vue
  JSDemos/Demos/TreeView/LoadDataOnDemand/jQuery/index.js
  MVCDemos/Views/TreeView/LoadDataOnDemand.cshtml
  NetCoreDemos/Views/TreeView/LoadDataOnDemand.cshtml
Labels: cherry-pick, 21_2

#1846 ButtonGroup: change demo description
  JSDemos/Demos/ButtonGroup/Overview/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1848 ButtonGroup: change demo description (#1846)
  JSDemos/Demos/ButtonGroup/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1849 DataGrid - RecordPaging - showInfo
  JSDemos/Demos/DataGrid/RecordPaging/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/RecordPaging/React/App.js
  JSDemos/Demos/DataGrid/RecordPaging/Vue/App.vue
  JSDemos/Demos/DataGrid/RecordPaging/description.md
  JSDemos/Demos/DataGrid/RecordPaging/jQuery/index.js
Labels: 22_1

#1850 correct version of npm package globalize
  package-lock.json
  package.json
Labels: 22_1

#1852 FieldSet: update demo description
  JSDemos/Demos/FieldSet/Overview/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1853 FieldSet: update demo description (#1852)
  JSDemos/Demos/FieldSet/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1851 Toast: refactor react demo
  JSDemos/Demos/Toast/Stack/Angular/app/app.component.html
  JSDemos/Demos/Toast/Stack/Angular/app/app.component.ts
  JSDemos/Demos/Toast/Stack/React/App.js
  JSDemos/Demos/Toast/Stack/Vue/App.vue
  MVCDemos/Views/Toast/Stack.cshtml
  NetCoreDemos/Views/Toast/Stack.cshtml
Labels: 22_1

#1855 responsive box: simplify demo
  JSDemos/Demos/ResponsiveBox/Overview/Angular/app/app.component.html
  JSDemos/Demos/ResponsiveBox/Overview/AngularJS/index.js
  JSDemos/Demos/ResponsiveBox/Overview/Knockout/index.js
  JSDemos/Demos/ResponsiveBox/Overview/React/App.js
  JSDemos/Demos/ResponsiveBox/Overview/Vue/App.vue
  JSDemos/Demos/ResponsiveBox/Overview/jQuery/index.js
Labels: 22_1

#1854 Charts: update the 'Simple Array' demo description
  JSDemos/Demos/Charts/SimpleArray/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1856 Charts: update the 'JSON Data' demo description
  JSDemos/Demos/Charts/AjaxRequest/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1859 Charts: update the 'Simple Array' demo description (#1854)
  JSDemos/Demos/Charts/SimpleArray/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1860 Charts: update the 'JSON Data' demo description (#1856)
  JSDemos/Demos/Charts/AjaxRequest/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1857 Charts: update the 'Client-Side Data Processing' demo description
  JSDemos/Demos/Charts/ClientSideDataProcessing/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1861 Accordion - Fix animation in the Overview demo
  JSDemos/Demos/Accordion/Overview/Angular/app/app.component.css
  JSDemos/Demos/Accordion/Overview/Angular/app/app.component.html
  JSDemos/Demos/Accordion/Overview/AngularJS/index.html
  JSDemos/Demos/Accordion/Overview/AngularJS/styles.css
  JSDemos/Demos/Accordion/Overview/Knockout/index.html
  JSDemos/Demos/Accordion/Overview/Knockout/styles.css
  JSDemos/Demos/Accordion/Overview/React/App.js
  JSDemos/Demos/Accordion/Overview/React/styles.css
  JSDemos/Demos/Accordion/Overview/Vue/App.vue
  JSDemos/Demos/Accordion/Overview/jQuery/index.html
  JSDemos/Demos/Accordion/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Accordion/Overview.css
  MVCDemos/Views/Accordion/Overview.cshtml
  NetCoreDemos/Views/Accordion/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Accordion/Overview.css
  testing/etalons/Accordion-Overview.png
Labels: 21_2

#1862 Charts: update the 'Client-Side Data Processing' demo description (#1857)
  JSDemos/Demos/Charts/ClientSideDataProcessing/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1863 Accordion - Fix animation in the Overview demo
  JSDemos/Demos/Accordion/Overview/Angular/app/app.component.css
  JSDemos/Demos/Accordion/Overview/Angular/app/app.component.html
  JSDemos/Demos/Accordion/Overview/AngularJS/index.html
  JSDemos/Demos/Accordion/Overview/AngularJS/styles.css
  JSDemos/Demos/Accordion/Overview/Knockout/index.html
  JSDemos/Demos/Accordion/Overview/Knockout/styles.css
  JSDemos/Demos/Accordion/Overview/React/App.js
  JSDemos/Demos/Accordion/Overview/React/styles.css
  JSDemos/Demos/Accordion/Overview/Vue/App.vue
  JSDemos/Demos/Accordion/Overview/jQuery/index.html
  JSDemos/Demos/Accordion/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Accordion/Overview.css
  MVCDemos/Views/Accordion/Overview.cshtml
  NetCoreDemos/Views/Accordion/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Accordion/Overview.css
  testing/etalons/Accordion-Overview.png
Labels: cherry-pick, 22_1

#1864 Charts: update the 'Server-Side Data Processing' demo description (#1858)
  JSDemos/Demos/Charts/ServerSideDataProcessing/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1865 Scheduler - Add demo for the `allDayPanelMode` option
  JSDemos/Demos/Scheduler/AllDayPanelMode/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/AllDayPanelMode/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/AllDayPanelMode/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/AllDayPanelMode/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/AllDayPanelMode/Angular/index.html
  JSDemos/Demos/Scheduler/AllDayPanelMode/React/App.js
  JSDemos/Demos/Scheduler/AllDayPanelMode/React/data.js
  JSDemos/Demos/Scheduler/AllDayPanelMode/React/index.html
  JSDemos/Demos/Scheduler/AllDayPanelMode/React/index.js
  JSDemos/Demos/Scheduler/AllDayPanelMode/React/styles.css
  JSDemos/Demos/Scheduler/AllDayPanelMode/Vue/App.vue
  JSDemos/Demos/Scheduler/AllDayPanelMode/Vue/data.js
  JSDemos/Demos/Scheduler/AllDayPanelMode/Vue/index.html
  JSDemos/Demos/Scheduler/AllDayPanelMode/Vue/index.js
  JSDemos/Demos/Scheduler/AllDayPanelMode/Vue/styles.css
  JSDemos/Demos/Scheduler/AllDayPanelMode/jQuery/data.js
  JSDemos/Demos/Scheduler/AllDayPanelMode/jQuery/index.html
  JSDemos/Demos/Scheduler/AllDayPanelMode/jQuery/index.js
  JSDemos/Demos/Scheduler/AllDayPanelMode/jQuery/styles.css
  JSDemos/menuMeta.json
  testing/etalons/Scheduler-AllDayPanelMode.png
Labels: 22_1

#1866 Charts: update the 'Dynamic Series from the DataSource' demo description
  JSDemos/Demos/Charts/SeriesTemplates/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1868 Charts: update the 'Dynamic Series from the DataSource' demo description (#1866)
  JSDemos/Demos/Charts/SeriesTemplates/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1
