Repository DevExpress/devextreme-demos, pull requests merged in 2022-06, with the labels that each got.

#1869 add lint/package-lock task
  .github/workflows/lint.yml
  .github/workflows/visual_tests.yml
Labels: 22_1

#1873 File Management - Update Azure SDK packages (once again)
  MVCDemos/Controllers/ApiControllers/FileManagerAzureAccessApiController.cs
  MVCDemos/Controllers/ApiControllers/FileUploaderAzureAccessApiController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/FileManagement/AzureBlobFileProvider.cs
  MVCDemos/Scripts/utils/azure-file-system.js
  MVCDemos/Web.config
  MVCDemos/packages.config
  NetCoreDemos/Controllers/ApiControllers/FileManagerAzureAccessApiController.cs
  NetCoreDemos/Controllers/ApiControllers/FileUploaderAzureAccessApiController.cs
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  NetCoreDemos/Models/FileManagement/AzureBlobFileProvider.cs
  NetCoreDemos/wwwroot/utils/azure-file-system.js
Labels: 22_1

#1875 Update etalons due to the Chrome update
  testing/widgets/datagrid/etalons/datagrid_batch_update_request_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_7_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_API_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_3_desktop.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_cell_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_header_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_init.png
Labels: 21_2

#1877 Update etalons due to the Chrome update
  testing/etalons/DataGrid-PDFExportImages.png
  testing/etalons/Scheduler-AllDayPanelMode.png
Labels: 22_1

#1879 Types prettier not working with old ts
  package.json
Labels: 21_1

#1878 Switch: update demo description
  JSDemos/Demos/Switch/Overview/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1880 Editors: update 'RTL support' demo description
  JSDemos/Demos/Common/EditorsRightToLeftSupport/description.md
Labels: 21_2

#1882 Editors: update 'RTL support' demo description (#1880)
  JSDemos/Demos/Common/EditorsRightToLeftSupport/description.md
Labels: cherry-pick, 22_1

#1883 Switch: update demo description (#1878)
  JSDemos/Demos/Switch/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1881 RadioGroup: update demo description
  JSDemos/Demos/RadioGroup/Overview/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1886 RadioGroup: update demo description (#1881)
  JSDemos/Demos/RadioGroup/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1892 Charts: update the 'Side-by-Side Stacked Bar' demo description (#1884)
  JSDemos/Demos/Charts/SideBySideStackedBar/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1885 Charts: update the 'Drill-Down Chart' demo description
  JSDemos/Demos/Charts/DrillDown/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1891 DataGrid: Remove deprecated API in the Multiple Record Selection API demo (T1094043)
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/React/App.js
Labels: 22_1

#1890 DataGrid: Remove deprecated API in the Multiple Record Selection API demo (T1094043)
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/React/App.js
Labels: cherry-pick, 21_2

#1889 DataGrid: Remove deprecated API in the Multiple Record Selection API demo (T1094043)
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/React/App.js
Labels: 21_1, cherry-pick

#1887 Charts: update the 'Custom Bar Width' demo description
  JSDemos/Demos/Charts/CustomBarWidth/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1888 Charts: update the 'Side-by-Side Full-Stacked Bar' demo description
  JSDemos/Demos/Charts/SideBySideFullStackedBar/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1893 Charts: update the 'Drill-Down Chart' demo description (#1885)
  JSDemos/Demos/Charts/DrillDown/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1894 Charts: update the 'Custom Bar Width' demo description (#1887)
  JSDemos/Demos/Charts/CustomBarWidth/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1895 Charts: update the 'Side-by-Side Full-Stacked Bar' demo description (#1888)
  JSDemos/Demos/Charts/SideBySideFullStackedBar/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1898 DataGrid: Fix Cell Editing and Editing API demo for Vue 2 (T1090974)
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Vue/App.vue
Labels: cherry-pick, 22_1

#1897 DataGrid: Fix Cell Editing and Editing API demo for Vue 2 (T1090974)
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Vue/App.vue
Labels: 21_2

#1896 Charts: update the 'Load Data On Demand' demo description
  JSDemos/Demos/Charts/LoadDataOnDemand/description.md
Labels: 21_2

#1899 Scheduler: add the 'All Day Panel Mode' demo description
  JSDemos/Demos/Scheduler/AllDayPanelMode/description.md
Labels: 22_1

#1900 Charts: update the 'Load Data On Demand' demo description (#1896)
  JSDemos/Demos/Charts/LoadDataOnDemand/description.md
Labels: cherry-pick, 22_1

#1908 File Management - Fix azure upload bucket name
  MVCDemos/Controllers/ApiControllers/FileUploaderAzureAccessApiController.cs
  NetCoreDemos/Controllers/ApiControllers/FileUploaderAzureAccessApiController.cs
Labels: 22_1

#1904 Use latest dotnet 5.x.x SDK version & update DataGrid Overview etalon
  .github/workflows/visual_tests_frameworks.yml
  testing/etalons/DataGrid-Overview.png
Labels: 22_1

#1906 Use latest dotnet 5.x.x SDK version & update DataGrid Overview etalon
  .github/workflows/CI.yml
  testing/etalons/DataGrid-Overview.png
Labels: cherry-pick, 21_2

#1909 File Manager - Temporarily add visual test masks for Azure demos
  testing/etalons/FileManager-AzureClientBinding_mask.png
  testing/etalons/FileManager-AzureServerBinding_mask.png
Labels: 22_1

#1910 File Manager - Temporarily update visual test masks for Azure demos
  testing/etalons/FileManager-AzureClientBinding_mask.png
  testing/etalons/FileManager-AzureServerBinding_mask.png
Labels: 22_1

#1914 scheduler: add mask to the timeIndicator demo
  testing/etalons/Scheduler-CurrentTimeIndicator_mask.png
Labels: 22_2

#1913 Update versions
  .github/workflows/unit_tests.yml
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
  package-lock.json
  package.json
  renovate.json
Labels: 22_2

#1915 TabPanel: get rid of use jsx-nobind ignore comment
  JSDemos/Demos/TabPanel/SortableClosableTabs/React/App.js
Labels: cherry-pick, 22_1

#1916 TabPanel: get rid of use jsx-nobind ignore comment
  JSDemos/Demos/TabPanel/SortableClosableTabs/React/App.js
Labels: 22_2
