Repository DevExpress/devextreme-demos, pull requests merged in 2022-07, with the labels that each got.

#1919 DropDownBox: fix Grid height
  JSDemos/Demos/DropDownBox/MultipleSelection/React/App.js
  JSDemos/Demos/DropDownBox/MultipleSelection/Vue/App.vue
Labels: 22_2

#1920 Charts: update the 'Color Each Bar Differently' demo description
  JSDemos/Demos/Charts/ColorEachBar/description.md
Labels: 22_1

#1921 Charts: update the 'Color Each Bar Differently' demo description (#1920)
  JSDemos/Demos/Charts/ColorEachBar/description.md
Labels: cherry-pick, 22_2

#1925 Scheduler - Add temporary mask
  testing/etalons/Scheduler-Timelines_mask.png
Labels: 22_2

#1926 Scheduler - Add temporary mask
  testing/etalons/Scheduler-Timelines_mask.png
Labels: 22_2

#1929 Scheduler - Remove temporary mask
  testing/etalons/Scheduler-Timelines.png
  testing/etalons/Scheduler-Timelines_mask.png
Labels: 22_2

#1928 Charts: update 'Scale Breaks' demo description
  JSDemos/Demos/Charts/ScaleBreaks/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1933 Charts: update 'Scale Breaks' demo description (#1928)
  JSDemos/Demos/Charts/ScaleBreaks/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#1927 Charts: update 'Customize Points and Labels' demo description
  JSDemos/Demos/Charts/CustomizePointsAndLabels/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1934 Charts: update 'Customize Points and Labels' demo description (#1927)
  JSDemos/Demos/Charts/CustomizePointsAndLabels/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#1930 Charts: update the 'Bi-Directional Bar Chart' demo description
  JSDemos/Demos/Charts/BiDirectionalBarChart/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1936 Charts: update the 'Bi-Directional Bar Chart' demo description (#1930)
  JSDemos/Demos/Charts/BiDirectionalBarChart/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#1935 Charts: update the 'Custom Annotations' demo description
  JSDemos/Demos/Charts/CustomAnnotations/description.md
Labels: 22_1

#1937 Charts: update the 'Custom Annotations' demo description (#1935)
  JSDemos/Demos/Charts/CustomAnnotations/description.md
Labels: cherry-pick, 22_2

#1932 Charts: update the "Drill Down" demo description
  JSDemos/Demos/Charts/ChartsDrillDown/description.md
  JSDemos/Demos/Charts/DrillDown/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1938 Charts: update the "Drill Down" demo description (#1932)
  JSDemos/Demos/Charts/ChartsDrillDown/description.md
  JSDemos/Demos/Charts/DrillDown/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#1931 Scheduler - Add temporary mask
  testing/etalons/Scheduler-Timelines_mask.png
Labels: 22_1

#1939 Scheduler - Remove mask and update etalon
  testing/etalons/Scheduler-Timelines.png
Labels: 22_1

#1940 Grid filtering demo: fix typo
  JSDemos/Demos/DataGrid/FilterPanel/description.md
Labels: 22_2

#1942 TreeMap: update the 'Hierarchical Data Structure' demo description
  JSDemos/Demos/Charts/HierarchicalDataStructure/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1944 TreeMap: update the 'Hierarchical Data Structure' demo description (#1942)
  JSDemos/Demos/Charts/HierarchicalDataStructure/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#1945 TreeView: Employees data is not used in the Hierarchical Data Structure demo (T1101503) (#1943)
  JSDemos/menuMeta.json
  MVCDemos/Controllers/TreeViewController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/SampleData/TreeViewHierarchicalData.cs
  MVCDemos/Models/SampleData/TreeViewHierarchicalDataForSelection.cs
  NetCoreDemos/Controllers/TreeViewController.cs
  NetCoreDemos/Models/SampleData/TreeViewHierarchicalData.cs
  NetCoreDemos/Models/SampleData/TreeViewHierarchicalDataForSelection.cs
Labels: cherry-pick, 22_1

#1946 TreeView: fix demos
  JSDemos/menuMeta.json
  MVCDemos/Controllers/TreeViewController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/SampleData/TreeViewHierarchicalDataForContextMenu.cs
  NetCoreDemos/Controllers/TreeViewController.cs
  NetCoreDemos/Models/SampleData/TreeViewHierarchicalDataForContextMenu.cs
Labels: 22_1

#1947 TreeView: fix demos
  JSDemos/menuMeta.json
  MVCDemos/Controllers/TreeViewController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/SampleData/TreeViewHierarchicalDataForContextMenu.cs
  NetCoreDemos/Controllers/TreeViewController.cs
  NetCoreDemos/Models/SampleData/TreeViewHierarchicalDataForContextMenu.cs
Labels: 22_2

#1948 TreeMap: update the 'Plain Data Structure' demo description
  JSDemos/Demos/Charts/FlatDataStructure/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1952 Validation: show billing editors validationMessage on left
  JSDemos/Demos/Validation/Overview/Angular/app/app.component.html
  JSDemos/Demos/Validation/Overview/React/App.js
  JSDemos/Demos/Validation/Overview/Vue/App.vue
  JSDemos/Demos/Validation/Overview/jQuery/index.js
  MVCDemos/Views/Validation/Overview.cshtml
  NetCoreDemos/Views/Validation/Overview.cshtml
Labels: 22_2

#1953 DataGrid Demo - Duplicated RemoteOperations method call in Custom Editors ASP.NET Core and ASP.NET MVC demos (T1104926)
  MVCDemos/Views/DataGrid/CustomEditors.cshtml
  NetCoreDemos/Views/DataGrid/CustomEditors.cshtml
Labels: 22_2

#1954 DataGrid Demo - Duplicated RemoteOperations method call in Custom Editors ASP.NET Core and ASP.NET MVC demos (T1104926)
  MVCDemos/Views/DataGrid/CustomEditors.cshtml
  NetCoreDemos/Views/DataGrid/CustomEditors.cshtml
Labels: cherry-pick, 22_1

#1955 DataGrid Demo - Duplicated RemoteOperations method call in Custom Editors ASP.NET Core and ASP.NET MVC demos (T1104926)
  MVCDemos/Views/DataGrid/CustomEditors.cshtml
  NetCoreDemos/Views/DataGrid/CustomEditors.cshtml
Labels: 21_2
