Repository DevExpress/devextreme-demos, pull requests merged in 2022-10, with the labels that each got.

#2018 Update Autocomplete demo to use CustomStore for remote search
  JSDemos/Demos/Autocomplete/Overview/Angular/app/app.component.html
  JSDemos/Demos/Autocomplete/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Autocomplete/Overview/Angular/app/app.service.ts
  JSDemos/Demos/Autocomplete/Overview/AngularJS/data.js
  JSDemos/Demos/Autocomplete/Overview/AngularJS/index.html
  JSDemos/Demos/Autocomplete/Overview/AngularJS/index.js
  JSDemos/Demos/Autocomplete/Overview/Knockout/data.js
  JSDemos/Demos/Autocomplete/Overview/Knockout/index.html
  JSDemos/Demos/Autocomplete/Overview/Knockout/index.js
  JSDemos/Demos/Autocomplete/Overview/React/App.js
  JSDemos/Demos/Autocomplete/Overview/React/data.js
  JSDemos/Demos/Autocomplete/Overview/Vue/App.vue
  JSDemos/Demos/Autocomplete/Overview/Vue/data.js
  JSDemos/Demos/Autocomplete/Overview/jQuery/data.js
  JSDemos/Demos/Autocomplete/Overview/jQuery/index.html
  JSDemos/Demos/Autocomplete/Overview/jQuery/index.js
  JSDemos/menuMeta.json
  MVCDemos/Views/Autocomplete/Overview.cshtml
  NetCoreDemos/Views/Autocomplete/Overview.cshtml
  testing/etalons/Autocomplete-Overview.png
Labels: 22_2

#2040 Multiline Toolbar Demo: Replace data && Fix types
  JSDemos/Demos/Toolbar/Multiline/Angular/app/app.component.ts
  JSDemos/Demos/Toolbar/Multiline/Angular/app/app.service.ts
  JSDemos/Demos/Toolbar/Multiline/React/App.js
  JSDemos/Demos/Toolbar/Multiline/React/data.js
  JSDemos/Demos/Toolbar/Multiline/Vue/App.vue
  JSDemos/Demos/Toolbar/Multiline/Vue/data.js
  JSDemos/Demos/Toolbar/Multiline/jQuery/data.js
  JSDemos/Demos/Toolbar/Multiline/jQuery/index.js
  MVCDemos/Models/FontStyle.cs
  MVCDemos/Models/SampleData/ToolbarData.cs
  MVCDemos/Views/Toolbar/Multiline.cshtml
  NetCoreDemos/Models/FontStyle.cs
  NetCoreDemos/Models/SampleData/ToolbarData.cs
  NetCoreDemos/Views/Toolbar/Multiline.cshtml
Labels: 22_2

#2042 Multiline Toolbar Demo: Replace data && Fix typo
  JSDemos/Demos/Toolbar/Multiline/Angular/app/app.component.html
  JSDemos/Demos/Toolbar/Multiline/React/App.js
  JSDemos/Demos/Toolbar/Multiline/Vue/App.vue
  JSDemos/Demos/Toolbar/Multiline/jQuery/index.js
  MVCDemos/Models/FontStyle.cs
  MVCDemos/Models/SampleData/ToolbarData.cs
  MVCDemos/ViewModels/ToolbarViewModel.cs
  MVCDemos/Views/Toolbar/Multiline.cshtml
  NetCoreDemos/Models/FontStyle.cs
  NetCoreDemos/Models/SampleData/ToolbarData.cs
  NetCoreDemos/ViewModels/ToolbarViewModel.cs
  NetCoreDemos/Views/Toolbar/Multiline.cshtml
Labels: 22_2

#2044 Multiline Toolbar Demo: Remove FontStyles from controllers
  MVCDemos/Controllers/ToolbarController.cs
  NetCoreDemos/Controllers/ToolbarController.cs
Labels: 22_2

#2045 Multiline Toolbar Demo: Fix data in controllers
  NetCoreDemos/Controllers/ToolbarController.cs
Labels: 22_2

#2046 MVCDemos: upgrade NuGet references
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Web.config
  MVCDemos/packages.config
Labels: dependencies, 22_2

#2048 Popup: update demo description
  JSDemos/Demos/Popup/Overview/Angular/description.md
  JSDemos/Demos/Popup/Overview/React/description.md
  JSDemos/Demos/Popup/Overview/Vue/description.md
  JSDemos/Demos/Popup/Overview/description.md
Labels: 22_2

#2039 Popover: Update demo description
  JSDemos/Demos/Popover/Overview/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#2054 Multiline Toolbar Demo: ASP minor fixes
  JSDemos/Demos/Toolbar/Multiline/React/App.js
  JSDemos/menuMeta.json
  MVCDemos/Controllers/ToolbarController.cs
  MVCDemos/Views/Toolbar/Multiline.cshtml
  NetCoreDemos/Controllers/ToolbarController.cs
  NetCoreDemos/Views/Toolbar/Multiline.cshtml
Labels: 22_2

#2057 Fix devextreme package versions
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  package-lock.json
Labels: 22_2

#2058 LoadIndicator: Update demo description
  JSDemos/Demos/LoadIndicator/Overview/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#2051 PolarChart: update etalons Chart (T1099479)
  testing/etalons/Charts-InvertedChart.png
  testing/etalons/Charts-PolarChartZoomingAndScrollingAPI.png
Labels: cherry-pick, 22_1

#2061 LoadIndicator: Update demo description (#2058)
  JSDemos/Demos/LoadIndicator/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#2062 Multiline Toolbar Demo: fixes after review
  JSDemos/Demos/Toolbar/Multiline/Angular/app/app.component.html
  JSDemos/Demos/Toolbar/Multiline/Angular/app/app.component.ts
  JSDemos/Demos/Toolbar/Multiline/Angular/app/app.service.ts
  JSDemos/Demos/Toolbar/Multiline/React/App.js
  JSDemos/Demos/Toolbar/Multiline/React/data.js
  JSDemos/Demos/Toolbar/Multiline/Vue/App.vue
  JSDemos/Demos/Toolbar/Multiline/Vue/data.js
  JSDemos/Demos/Toolbar/Multiline/jQuery/data.js
  JSDemos/Demos/Toolbar/Multiline/jQuery/index.js
  MVCDemos/Views/Toolbar/Multiline.cshtml
  NetCoreDemos/Views/Toolbar/Multiline.cshtml
  testing/etalons/Toolbar-Multiline.png
  testing/widgets/toolbar/etalons/toolbar_multiline_mode_minimize.png
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_init.png
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_menu_open.png
Labels: 22_2

#2065 Update Readme: Windows Developer Mode #2050
  README.md
Labels: cherry-pick, 22_1

#2050 Update Readme: Windows Developer Mode
  README.md
Labels: 22_2

#2100 Sync renovate and dependabot updates from 22_1 (part 1)
  JSDemos/Demos/DataGrid/ExcelJS/AngularJS/index.html
  JSDemos/Demos/DataGrid/ExcelJS/Knockout/index.html
  JSDemos/Demos/DataGrid/ExcelJS/jQuery/index.html
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/AngularJS/index.html
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/Knockout/index.html
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/jQuery/index.html
  JSDemos/Demos/DataGrid/ExcelJSExportImages/AngularJS/index.html
  JSDemos/Demos/DataGrid/ExcelJSExportImages/Knockout/index.html
  JSDemos/Demos/DataGrid/ExcelJSExportImages/jQuery/index.html
  JSDemos/Demos/DataGrid/ExcelJSExportMultipleGrids/AngularJS/index.html
  JSDemos/Demos/DataGrid/ExcelJSExportMultipleGrids/Knockout/index.html
  JSDemos/Demos/DataGrid/ExcelJSExportMultipleGrids/jQuery/index.html
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/AngularJS/index.html
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/Knockout/index.html
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/jQuery/index.html
  JSDemos/Demos/DataGrid/ExcelJSOverview/AngularJS/index.html
  JSDemos/Demos/DataGrid/ExcelJSOverview/Knockout/index.html
  JSDemos/Demos/DataGrid/ExcelJSOverview/jQuery/index.html
  JSDemos/Demos/Gantt/ExportToPDF/jQuery/index.html
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/jQuery/index.html
  JSDemos/Demos/PivotGrid/ExcelJSOverview/jQuery/index.html
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/jQuery/index.html
  package-lock.json
  package.json
Labels: dependencies, 22_2

#2041 Update Autocomplete demo to use CustomStore for remote search
  JSDemos/Demos/Autocomplete/Overview/Angular/app/app.component.html
  JSDemos/Demos/Autocomplete/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Autocomplete/Overview/Angular/app/app.service.ts
  JSDemos/Demos/Autocomplete/Overview/AngularJS/data.js
  JSDemos/Demos/Autocomplete/Overview/AngularJS/index.html
  JSDemos/Demos/Autocomplete/Overview/AngularJS/index.js
  JSDemos/Demos/Autocomplete/Overview/Knockout/data.js
  JSDemos/Demos/Autocomplete/Overview/Knockout/index.html
  JSDemos/Demos/Autocomplete/Overview/Knockout/index.js
  JSDemos/Demos/Autocomplete/Overview/React/App.js
  JSDemos/Demos/Autocomplete/Overview/React/data.js
  JSDemos/Demos/Autocomplete/Overview/Vue/App.vue
  JSDemos/Demos/Autocomplete/Overview/Vue/data.js
  JSDemos/Demos/Autocomplete/Overview/jQuery/data.js
  JSDemos/Demos/Autocomplete/Overview/jQuery/index.html
  JSDemos/Demos/Autocomplete/Overview/jQuery/index.js
  JSDemos/menuMeta.json
  MVCDemos/Views/Autocomplete/Overview.cshtml
  NetCoreDemos/Views/Autocomplete/Overview.cshtml
  testing/etalons/Autocomplete-Overview.png
Labels: cherry-pick, 22_1

#2053 Add missing colon in MasterDetailView demo
  JSDemos/Demos/DataGrid/MasterDetailView/React/DetailTemplate.js
  JSDemos/Demos/DataGrid/MasterDetailView/Vue/DetailTemplate.vue
  testing/widgets/datagrid/MasterDetailView.test.js
  testing/widgets/datagrid/etalons/datagrid_master_detail_view_2_desktop.png
Labels: 22_2

#2059 Add missing colon in MasterDetailView demo
  JSDemos/Demos/DataGrid/MasterDetailView/React/DetailTemplate.js
  JSDemos/Demos/DataGrid/MasterDetailView/Vue/DetailTemplate.vue
  testing/widgets/datagrid/MasterDetailView.test.js
  testing/widgets/datagrid/etalons/datagrid_master_detail_view_2_desktop.png
Labels: cherry-pick, 22_1

#2113 Update testcafe to v2
  package-lock.json
  package.json
  testing/widgets/scheduler/templates.test.js
Labels: dependencies, 22_2

#2117 Update testcafe to v2
  package-lock.json
  package.json
  testing/widgets/scheduler/templates.test.js
Labels: dependencies, 22_1

#2116 Create codeql-analysis.yml (#2056)
  .github/workflows/codeql-analysis.yml
Labels: 21_2

#2114 Slider & RangeSlider: update demos
  JSDemos/Demos/RangeSlider/Overview/Angular/app/app.component.html
  JSDemos/Demos/RangeSlider/Overview/AngularJS/index.html
  JSDemos/Demos/RangeSlider/Overview/React/App.js
  JSDemos/Demos/RangeSlider/Overview/Vue/App.vue
  JSDemos/Demos/RangeSlider/Overview/jQuery/index.html
  JSDemos/Demos/Slider/Overview/Angular/app/app.component.html
  JSDemos/Demos/Slider/Overview/AngularJS/index.html
  JSDemos/Demos/Slider/Overview/React/App.js
  JSDemos/Demos/Slider/Overview/Vue/App.vue
  JSDemos/Demos/Slider/Overview/jQuery/index.html
  MVCDemos/Views/RangeSlider/Overview.cshtml
  MVCDemos/Views/Slider/Overview.cshtml
  NetCoreDemos/Views/RangeSlider/Overview.cshtml
  NetCoreDemos/Views/Slider/Overview.cshtml
  testing/etalons/RangeSlider-Overview.png
  testing/etalons/Slider-Overview.png
Labels: 22_2

#2115 Create codeql-analysis.yml (#2056)
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: 22_2

#2122 Update codeql-analysis.yml
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: cherry-pick, 22_1

#2123 Feature/codeql 21.2
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: cherry-pick, 21_2

#2124 ProgressBar: update demo description + minor code fix
  JSDemos/Demos/ProgressBar/Overview/Angular/app/app.component.ts
  JSDemos/Demos/ProgressBar/Overview/AngularJS/index.js
  JSDemos/Demos/ProgressBar/Overview/Knockout/index.js
  JSDemos/Demos/ProgressBar/Overview/React/App.js
  JSDemos/Demos/ProgressBar/Overview/Vue/App.vue
  JSDemos/Demos/ProgressBar/Overview/description.md
  JSDemos/Demos/ProgressBar/Overview/jQuery/index.js
Labels: 22_1

#2125 Upgrade ASP.NET Core demos to .NET 6
  NetCoreDemos/Controllers/ApiControllers/DataGridCustomEditorsController.cs
  NetCoreDemos/Controllers/ApiControllers/DataGridRowReorderingController.cs
  NetCoreDemos/Controllers/ApiControllers/DnDBetweenGridsController.cs
  NetCoreDemos/Controllers/ApiControllers/FileManagerAzureAccessApiController.cs
  NetCoreDemos/Controllers/ApiControllers/FileUploaderAzureAccessApiController.cs
  NetCoreDemos/Controllers/DataGridController.cs
  NetCoreDemos/Controllers/ListController.cs
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  NetCoreDemos/Startup.cs
  NetCoreDemos/web.config
Labels: 22_2

#2128 ProgressBar: update demo description + minor code fix (#2124)
  JSDemos/Demos/ProgressBar/Overview/Angular/app/app.component.ts
  JSDemos/Demos/ProgressBar/Overview/AngularJS/index.js
  JSDemos/Demos/ProgressBar/Overview/Knockout/index.js
  JSDemos/Demos/ProgressBar/Overview/React/App.js
  JSDemos/Demos/ProgressBar/Overview/Vue/App.vue
  JSDemos/Demos/ProgressBar/Overview/description.md
  JSDemos/Demos/ProgressBar/Overview/jQuery/index.js
Labels: cherry-pick, 22_2

#2138 Update standard actions to v3
  .github/workflows/lint.yml
  .github/workflows/unit_tests.yml
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
Labels: 22_1

#2130 Calendar: demonstrate weekNumberRule option
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.css
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.html
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Calendar/Overview/AngularJS/index.html
  JSDemos/Demos/Calendar/Overview/AngularJS/index.js
  JSDemos/Demos/Calendar/Overview/AngularJS/styles.css
  JSDemos/Demos/Calendar/Overview/React/App.js
  JSDemos/Demos/Calendar/Overview/React/styles.css
  JSDemos/Demos/Calendar/Overview/Vue/App.vue
  JSDemos/Demos/Calendar/Overview/jQuery/index.html
  JSDemos/Demos/Calendar/Overview/jQuery/index.js
  JSDemos/Demos/Calendar/Overview/jQuery/styles.css
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/Calendar/Overview.css
  MVCDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Calendar/Overview.css
  testing/etalons/Calendar-Overview.png
Labels: 22_2

#2129 Button: fix styles
  testing/etalons/Scheduler-Agenda.png
  testing/etalons/Scheduler-AllDayPanelMode.png
  testing/etalons/Scheduler-BasicViews.png
  testing/etalons/Scheduler-CellTemplates.png
  testing/etalons/Scheduler-ContextMenuIntegration.png
  testing/etalons/Scheduler-CurrentTimeIndicator.png
  testing/etalons/Scheduler-CustomDragAndDrop.png
  testing/etalons/Scheduler-CustomTemplates.png
  testing/etalons/Scheduler-CustomizeIndividualViews.png
  testing/etalons/Scheduler-Editing.png
  testing/etalons/Scheduler-GoogleCalendarIntegration.png
  testing/etalons/Scheduler-GroupByDate.png
  testing/etalons/Scheduler-GroupOrientation.png
  testing/etalons/Scheduler-IncreaseViewDuration.png
  testing/etalons/Scheduler-Overview.png
  testing/etalons/Scheduler-RecurringAppointments.png
  testing/etalons/Scheduler-Resources.png
  testing/etalons/Scheduler-SignalRService.png
  testing/etalons/Scheduler-SimpleArray.png
  testing/etalons/Scheduler-TimeZonesSupport.png
  testing/etalons/Scheduler-Timelines.png
  testing/etalons/Scheduler-VirtualScrolling.png
  testing/etalons/Scheduler-WebAPIService.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_cell_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_header_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_init.png
  testing/widgets/scheduler/etalons/scheduler_overview_selection.png
Labels: 22_2

#2140 Calendar: fix demo
  .eslintrc.js
  JSDemos/Demos/Calendar/Overview/AngularJS/index.html
  JSDemos/Demos/Calendar/Overview/AngularJS/index.js
  JSDemos/menuMeta.json
  MVCDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/Views/Calendar/Overview.cshtml
Labels: 22_2

#2142 Change Grid-Overview etalons
  testing/etalons/DataGrid-Overview.png
Labels: 22_2

#2143 Change the Grid-Overview etalon screenshot.
  testing/etalons/DataGrid-Overview.png
Labels: 22_1

#2136 ActionSheet: Update demo description
  JSDemos/Demos/ActionSheet/Basics/description.md
Labels: 22_1

#2146 ActionSheet: Update demo description (#2136)
  JSDemos/Demos/ActionSheet/Basics/description.md
Labels: cherry-pick, 22_2

#2135 Toolbar Multiline Mode: Update demo after review
  JSDemos/Demos/Toolbar/Adaptability/Angular/app/app.component.css
  JSDemos/Demos/Toolbar/Adaptability/Angular/app/app.component.html
  JSDemos/Demos/Toolbar/Adaptability/Angular/app/app.component.ts
  JSDemos/Demos/Toolbar/Adaptability/Angular/app/app.service.ts
  JSDemos/Demos/Toolbar/Adaptability/Angular/index.html
  JSDemos/Demos/Toolbar/Adaptability/React/App.js
  JSDemos/Demos/Toolbar/Adaptability/React/data.js
  JSDemos/Demos/Toolbar/Adaptability/React/index.html
  JSDemos/Demos/Toolbar/Adaptability/React/index.js
  JSDemos/Demos/Toolbar/Adaptability/React/styles.css
  JSDemos/Demos/Toolbar/Adaptability/Vue/App.vue
  JSDemos/Demos/Toolbar/Adaptability/Vue/data.js
  JSDemos/Demos/Toolbar/Adaptability/Vue/index.html
  JSDemos/Demos/Toolbar/Adaptability/Vue/index.js
  JSDemos/Demos/Toolbar/Adaptability/description.md
  JSDemos/Demos/Toolbar/Adaptability/jQuery/data.js
  JSDemos/Demos/Toolbar/Adaptability/jQuery/index.html
  JSDemos/Demos/Toolbar/Adaptability/jQuery/index.js
  JSDemos/Demos/Toolbar/Adaptability/jQuery/styles.css
  JSDemos/Demos/Toolbar/Multiline/Angular/app/app.component.html
  JSDemos/Demos/Toolbar/Multiline/Angular/app/app.component.ts
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/Toolbar/Adaptability.css
  MVCDemos/Controllers/ToolbarController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/SampleData/ToolbarData.cs
  MVCDemos/ViewModels/ToolbarViewModel.cs
  MVCDemos/Views/Toolbar/Adaptability.cshtml
  NetCoreDemos/Controllers/ToolbarController.cs
  NetCoreDemos/Models/SampleData/ToolbarData.cs
  NetCoreDemos/ViewModels/ToolbarViewModel.cs
  NetCoreDemos/Views/Toolbar/Adaptability.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Toolbar/Adaptability.css
  testing/etalons/Toolbar-Adaptability.png
  testing/etalons/Toolbar-Multiline.png
  testing/widgets/toolbar/Adaptability.test.js
  testing/widgets/toolbar/etalons/toolbar_multiline_mode_minimize.png
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_init.png
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_menu_open.png
Labels: 22_2

#2133 Add testcafe coverage for the Advanced Master-Detail View demo
  testing/widgets/datagrid/AdvancedMasterDetailView.test.js
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_3_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_5_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_6_desktop.png
Labels: 22_2

#2134 Add testcafe coverage for the Advanced Master-Detail View demo
  testing/widgets/datagrid/AdvancedMasterDetailView.test.js
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_3_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_5_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_6_desktop.png
Labels: cherry-pick, 22_1

#2151 DataGrid - Overview - update etalons
  testing/etalons/DataGrid-Overview.png
Labels: cherry-pick, 21_2

#2155 Update Toolbar Demo: edit notification message
  JSDemos/Demos/Toolbar/Adaptability/Angular/app/app.component.ts
  JSDemos/Demos/Toolbar/Adaptability/jQuery/index.js
  MVCDemos/Views/Toolbar/Adaptability.cshtml
  NetCoreDemos/Views/Toolbar/Adaptability.cshtml
Labels: 22_2

#2154 Calendar: update demo description
  JSDemos/Demos/Calendar/Overview/description.md
Labels: 22_2

#2156 Update Toolbar Demo: Update notification messages
  JSDemos/Demos/Toolbar/Adaptability/Angular/app/app.component.ts
  JSDemos/Demos/Toolbar/Adaptability/React/App.js
  JSDemos/Demos/Toolbar/Adaptability/Vue/App.vue
  JSDemos/Demos/Toolbar/Adaptability/jQuery/index.js
  MVCDemos/Views/Toolbar/Adaptability.cshtml
  NetCoreDemos/Views/Toolbar/Adaptability.cshtml
Labels: 22_2

#2157 ActionSheet Popover: update demo description (#2152)
  JSDemos/Demos/ActionSheet/PopoverMode/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#2153 Toolbar: update Adaptability demo description
  JSDemos/Demos/Toolbar/Adaptability/description.md
Labels: 22_2

#2158 Scheduler: fix AllDayPanelMode demo description
  JSDemos/Demos/Scheduler/AllDayPanelMode/description.md
Labels: 22_1

#2160 Scheduler: fix AllDayPanelMode demo description (#2158)
  JSDemos/Demos/Scheduler/AllDayPanelMode/description.md
Labels: cherry-pick, 22_2

#2164 PivotGrid: fix links in Header and Footer demo description
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/description.md
Labels: 22_2

#2166 Update some etalons
  testing/etalons/DataGrid-Overview.png
  testing/etalons/Form-Validation.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_6_desktop.png
Labels: 22_2

#2171 Add mask overview demo
  testing/etalons/DataGrid-Overview_mask.png
Labels: 22_2

#2172 Add mask overview demo
  testing/etalons/DataGrid-Overview_mask.png
Labels: cherry-pick, 22_1

#2175 Add mask overview demo
  testing/etalons/DataGrid-Overview_mask.png
Labels: cherry-pick, 21_2

#2161 Form: label template
  JSDemos/Demos/Form/CustomizeItem/Angular/app/app.component.css
  JSDemos/Demos/Form/CustomizeItem/Angular/app/app.component.html
  JSDemos/Demos/Form/CustomizeItem/Angular/app/app.component.ts
  JSDemos/Demos/Form/CustomizeItem/AngularJS/styles.css
  JSDemos/Demos/Form/CustomizeItem/Knockout/styles.css
  JSDemos/Demos/Form/CustomizeItem/React/App.js
  JSDemos/Demos/Form/CustomizeItem/React/LabelNotesTemplate.js
  JSDemos/Demos/Form/CustomizeItem/React/LabelTemplate.js
  JSDemos/Demos/Form/CustomizeItem/React/styles.css
  JSDemos/Demos/Form/CustomizeItem/Vue/App.vue
  JSDemos/Demos/Form/CustomizeItem/Vue/LabelNotesTemplate.vue
  JSDemos/Demos/Form/CustomizeItem/Vue/LabelTemplate.vue
  JSDemos/Demos/Form/CustomizeItem/jQuery/index.html
  JSDemos/Demos/Form/CustomizeItem/jQuery/index.js
  JSDemos/Demos/Form/CustomizeItem/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Form/CustomizeItem.css
  MVCDemos/Views/Form/CustomizeItem.cshtml
  NetCoreDemos/Views/Form/CustomizeItem.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Form/CustomizeItem.css
  testing/etalons/Form-CustomizeItem.png
  testing/widgets/form/CustomomizeItem.test.js
  testing/widgets/form/etalons/form_customize_item_label_tooltip.png
Labels: 22_2

#2178 NET demos: remove incorrect link to dxFileUploader (T1122988)
  MVCDemos/Controllers/FileUploaderController.cs
  NetCoreDemos/Controllers/FileUploaderController.cs
Labels: 22_2

#2176 Charts: update Pie demo description
  JSDemos/Demos/Charts/Pie/description.md
Labels: 22_1

#2180 Charts: update Pie demo description (#2176)
  JSDemos/Demos/Charts/Pie/description.md
Labels: cherry-pick, 22_2

#2165 LoadPanel: update demo description
  JSDemos/Demos/LoadPanel/Overview/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#2181 LoadPanel: update demo description (#2165)
  JSDemos/Demos/LoadPanel/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#2182 Form: fix customize item demo
  MVCDemos/Views/Form/CustomizeItem.cshtml
  NetCoreDemos/Views/Form/CustomizeItem.cshtml
Labels: 22_2

#2183 Form: fix customize item demo
  MVCDemos/Views/Form/CustomizeItem.cshtml
  NetCoreDemos/Views/Form/CustomizeItem.cshtml
Labels: 22_2

#2186 Navigation Components: update Overview demo description
  JSDemos/Demos/Common/NavigationOverview/Angular/description.md
  JSDemos/Demos/Common/NavigationOverview/AngularJS/description.md
  JSDemos/Demos/Common/NavigationOverview/Knockout/description.md
  JSDemos/Demos/Common/NavigationOverview/React/description.md
  JSDemos/Demos/Common/NavigationOverview/Vue/description.md
  JSDemos/Demos/Common/NavigationOverview/description.md
  JSDemos/Demos/Common/NavigationOverview/jQuery/description.md
Labels: 22_2

#2184 Doughnut PieChart: update demo description
  JSDemos/Demos/Charts/Doughnut/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#2194 Doughnut PieChart: update demo description
  JSDemos/Demos/Charts/Doughnut/description.md
Labels: 22_1

#2195 Doughnut PieChart: update demo description
  JSDemos/Demos/Charts/Doughnut/description.md
Labels: cherry-pick, 22_2

#2192 DateBox: use 'clock', 'event', 'eventall' icons instead of spins in material
  testing/etalons/DataGrid-Filtering.png
  testing/etalons/DateBox-Formatting.png
  testing/etalons/DateBox-Overview.png
  testing/widgets/datagrid/etalons/datagrid_filtering_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_3_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_5_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_6_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_7_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_7_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_8_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_3_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_focus_on_filter_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_focus_on_filter_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_focus_on_filter_3_desktop.png
  testing/widgets/form/CustomomizeItem.test.js
Labels: 22_2

#2197 Toolbar: update Adaptability demo description
  JSDemos/Demos/Toolbar/Adaptability/description.md
Labels: 22_2

#2198 DataGrid: fix imports in Angular ExportToPDF demos
  JSDemos/Demos/DataGrid/PDFCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFExportImages/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFOverview/Angular/app/app.component.ts
Labels: 22_1
