Repository DevExpress/devextreme-demos, pull requests merged in 2022-03, with the labels that each got.

#1746 Menu: add demo description
  JSDemos/Demos/Menu/Overview/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1747 Menu: add demo description (#1746)
  JSDemos/Demos/Menu/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1750 PDF - fix demos build
  MVCDemos/Views/DataGrid/PDFExportImages.cshtml
  NetCoreDemos/Views/DataGrid/PDFExportImages.cshtml
Labels: 22_1

#1753 PDF - Small fixes
  JSDemos/Demos/DataGrid/PDFCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFCellCustomization/React/App.js
  JSDemos/Demos/DataGrid/PDFCellCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/React/App.js
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/Vue/App.vue
Labels: 22_1

#1754 DataGrid.PDF - Small fixes for export to PDF demos
  JSDemos/Demos/DataGrid/PDFExportImages/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/PDFExportImages/AngularJS/index.js
  JSDemos/Demos/DataGrid/PDFExportImages/React/App.js
  JSDemos/Demos/DataGrid/PDFExportImages/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFExportImages/description.md
  JSDemos/Demos/DataGrid/PDFExportImages/jQuery/index.js
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/description.md
  testing/etalons/DataGrid-PDFExportImages.png
Labels: 22_1

#1755 PDF - update texts
  JSDemos/Demos/DataGrid/PDFCellCustomization/description.md
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/description.md
Labels: 22_1

#1756 PDF - update etalons
  testing/etalons/DataGrid-PDFOverview.png
Labels: 22_1

#1757 DataGrid.PDF - Improve Multiple Grids Demo
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/AngularJS/index.js
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/React/App.js
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/jQuery/index.js
  MVCDemos/Views/DataGrid/PDFExportImages.cshtml
  MVCDemos/Views/DataGrid/PDFExportMultipleGrids.cshtml
  NetCoreDemos/Views/DataGrid/PDFExportImages.cshtml
  NetCoreDemos/Views/DataGrid/PDFExportMultipleGrids.cshtml
Labels: 22_1

#1758 Accordion: update demo description
  JSDemos/Demos/Accordion/Overview/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1760 Accordion: update demo description (#1758)
  JSDemos/Demos/Accordion/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1759 Resizable: add new demo
  JSDemos/Demos/Resizable/Overview/Angular/app/app.component.css
  JSDemos/Demos/Resizable/Overview/Angular/app/app.component.html
  JSDemos/Demos/Resizable/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Resizable/Overview/Angular/app/app.service.ts
  JSDemos/Demos/Resizable/Overview/Angular/index.html
  JSDemos/Demos/Resizable/Overview/React/App.js
  JSDemos/Demos/Resizable/Overview/React/data.js
  JSDemos/Demos/Resizable/Overview/React/index.html
  JSDemos/Demos/Resizable/Overview/React/index.js
  JSDemos/Demos/Resizable/Overview/React/styles.css
  JSDemos/Demos/Resizable/Overview/Vue/App.vue
  JSDemos/Demos/Resizable/Overview/Vue/data.js
  JSDemos/Demos/Resizable/Overview/Vue/index.html
  JSDemos/Demos/Resizable/Overview/Vue/index.js
  JSDemos/Demos/Resizable/Overview/Vue/styles.css
  JSDemos/Demos/Resizable/Overview/description.md
  JSDemos/Demos/Resizable/Overview/jQuery/data.js
  JSDemos/Demos/Resizable/Overview/jQuery/index.html
  JSDemos/Demos/Resizable/Overview/jQuery/index.js
  JSDemos/Demos/Resizable/Overview/jQuery/styles.css
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/Resizable/Overview.css
  MVCDemos/Controllers/ResizableController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/Resizable/ResizableOverview.cshtml
  NetCoreDemos/Controllers/ResizableController.cs
  NetCoreDemos/Views/Resizable/ResizableOverview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Resizable/Overview.css
  testing/etalons/Resizable-Overview.png
Labels: 22_1

#1762 Fix resizable demo
  MVCDemos/Views/Resizable/ResizableOverview.cshtml
  NetCoreDemos/Views/Resizable/ResizableOverview.cshtml
Labels: 22_1

#1763 Update descriptions related to the pager in compact mode
  JSDemos/Demos/DataGrid/RecordPaging/description.md
  JSDemos/Demos/TreeList/Paging/description.md
Labels: 22_1

#1766 DataGrid - Overview - update etalons
  testing/etalons/DataGrid-Overview.png
Labels: 22_1

#1767 DataGrid - Overview - update etalons
  testing/etalons/DataGrid-Overview.png
Labels: cherry-pick, 21_2

#1764 Update descriptions related to the pager in compact mode
  JSDemos/Demos/DataGrid/RecordPaging/description.md
  JSDemos/Demos/TreeList/Paging/description.md
Labels: cherry-pick, 21_2

#1769 Resizable: use double quotes in mvc/core demos
  MVCDemos/Views/Resizable/ResizableOverview.cshtml
  NetCoreDemos/Views/Resizable/ResizableOverview.cshtml
Labels: 22_1

#1770 Resizable: fix mvc and core demos
  MVCDemos/Views/Resizable/ResizableOverview.cshtml
  NetCoreDemos/Views/Resizable/ResizableOverview.cshtml
Labels: 22_1

#1761 DropDownBox Single Selection: DataGrid's data source is not an array
  JSDemos/Demos/DropDownBox/SingleSelection/description.md
Labels: 21_2

#1777 Resizable: remove excess icon
  JSDemos/images/widgets/Resizable.svg
Labels: 22_1

#1776 DropDownBox Single Selection: DataGrid's data source is not an array
  JSDemos/Demos/DropDownBox/SingleSelection/description.md
Labels: cherry-pick, 22_1

#1778 Resizable: add area
  JSDemos/Demos/Resizable/Overview/Angular/app/app.component.css
  JSDemos/Demos/Resizable/Overview/Angular/app/app.component.html
  JSDemos/Demos/Resizable/Overview/React/App.js
  JSDemos/Demos/Resizable/Overview/React/styles.css
  JSDemos/Demos/Resizable/Overview/Vue/App.vue
  JSDemos/Demos/Resizable/Overview/Vue/styles.css
  JSDemos/Demos/Resizable/Overview/jQuery/index.js
  JSDemos/Demos/Resizable/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Resizable/Overview.css
  MVCDemos/Controllers/ResizableController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/Resizable/Overview.cshtml
  NetCoreDemos/Controllers/ResizableController.cs
  NetCoreDemos/Views/Resizable/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Resizable/Overview.css
  testing/etalons/Resizable-Overview.png
Labels: 22_1

#1773 Change the exportToPDF Overview demo description
  JSDemos/Demos/DataGrid/PDFOverview/description.md
Labels: 22_1

#1774 Change the exportToPDF Header And Footer demo description
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/description.md
Labels: 22_1

#1780 Resizable demo: display code only below the demo
  JSDemos/menuMeta.json
Labels: 22_1

#1781 Change the Export Multiple Grids demo description
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/description.md
Labels: 22_1

#1782 Change the Export Images demo description
  JSDemos/Demos/DataGrid/PDFExportImages/description.md
Labels: 22_1
