Repository DevExpress/devextreme-demos, pull requests merged in 2022-01, with the labels that each got.

#1607 NumberBox: Change Overview demo description
  JSDemos/Demos/NumberBox/Overview/description.md
Labels: 21_2

#1618 NumberBox: Change Overview demo description (#1607)
  JSDemos/Demos/NumberBox/Overview/description.md
Labels: cherry-pick, 22_1

#1622 TreeList: add note to the Load on Demand demo (#1619)
  JSDemos/Demos/TreeList/LoadDataOnDemand/description.md
Labels: cherry-pick, 21_2

#1621 Update notes
  JSDemos/Demos/DataGrid/RemoteGrouping/description.md
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/description.md
  JSDemos/Demos/DataGrid/SignalRService/description.md
  JSDemos/Demos/FileManager/BindingToFileSystem/description.md
  JSDemos/Demos/FileManager/Overview/description.md
  JSDemos/Demos/FileUploader/CustomDropzone/description.md
  JSDemos/Demos/FileUploader/FileSelection/description.md
  JSDemos/Demos/FileUploader/FileUploading/description.md
Labels: cherry-pick, 21_2

#1623 dxScheduler - Fix resource variables and template properties
  JSDemos/Demos/Scheduler/CustomTemplates/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CustomTemplates/AngularJS/index.html
  JSDemos/Demos/Scheduler/CustomTemplates/React/Appointment.js
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/AppointmentTemplate.vue
  JSDemos/Demos/Scheduler/CustomTemplates/jQuery/index.js
  JSDemos/Demos/Scheduler/Resources/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Resources/AngularJS/data.js
  JSDemos/Demos/Scheduler/Resources/Knockout/data.js
  JSDemos/Demos/Scheduler/Resources/React/data.js
  JSDemos/Demos/Scheduler/Resources/Vue/data.js
  JSDemos/Demos/Scheduler/Resources/jQuery/data.js
  MVCDemos/Views/Scheduler/CustomTemplates.cshtml
  NetCoreDemos/Views/Scheduler/CustomTemplates.cshtml
  testing/etalons/Scheduler-CustomTemplates.png
Labels: 22_1

#1628 dxScheduler - Fix resource variables and template properties
  JSDemos/Demos/Scheduler/CustomTemplates/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CustomTemplates/AngularJS/index.html
  JSDemos/Demos/Scheduler/CustomTemplates/React/Appointment.js
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/AppointmentTemplate.vue
  JSDemos/Demos/Scheduler/CustomTemplates/jQuery/index.js
  JSDemos/Demos/Scheduler/Resources/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/Resources/AngularJS/data.js
  JSDemos/Demos/Scheduler/Resources/Knockout/data.js
  JSDemos/Demos/Scheduler/Resources/React/data.js
  JSDemos/Demos/Scheduler/Resources/Vue/data.js
  JSDemos/Demos/Scheduler/Resources/jQuery/data.js
  MVCDemos/Views/Scheduler/CustomTemplates.cshtml
  NetCoreDemos/Views/Scheduler/CustomTemplates.cshtml
  testing/etalons/Scheduler-CustomTemplates.png
Labels: cherry-pick, 21_2

#1632 dxScheduler - mock date for time indicator demo
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/client-script.js
  testing/etalons/Scheduler-CurrentTimeIndicator.png
  testing/etalons/Scheduler-CurrentTimeIndicator_mask.png
Labels: cherry-pick, 21_2

#1630 dxScheduler - mock date for time indicator demo
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/client-script.js
  testing/etalons/Scheduler-CurrentTimeIndicator.png
  testing/etalons/Scheduler-CurrentTimeIndicator_mask.png
Labels: 22_1

#1633 DataGrid: Update etalons and add mask for guid
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_1_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_2_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop_mask.png
Labels: 21_2

#1636 Scheduler - Update test etalons due to the Chrome update
  testing/etalons/Scheduler-ContextMenuIntegration.png
  testing/etalons/Scheduler-RecurringAppointments.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_cell_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_header_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_init.png
Labels: 21_2

#1637 Scheduler - Update etalons due to the bump Chrome version
  testing/etalons/Scheduler-ContextMenuIntegration.png
  testing/etalons/Scheduler-RecurringAppointments.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_cell_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_header_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_init.png
Labels: 22_1

#1647 NumberBox Formatting: Change demo description
  JSDemos/Demos/NumberBox/Formatting/description.md
Labels: cherry-pick, 22_1

#1635 Add ts type checking
  .github/workflows/visual_tests_frameworks.yml
  JSDemos/Demos/DataGrid/CollaborativeEditing/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/CollaborativeEditing/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/DataValidation/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/EditStateManagement/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/LocalReordering/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/RealTimeUpdates/Angular/app/app.service.ts
  JSDemos/Demos/Diagram/AdvancedDataBinding/Angular/app/app.component.ts
  JSDemos/Demos/Diagram/NodesAndEdgesArrays/Angular/app/app.service.ts
  JSDemos/Demos/Diagram/OperationRestrictions/Angular/app/app.component.ts
  JSDemos/Demos/Diagram/UICustomization/Angular/app/app.component.ts
  JSDemos/Demos/FileManager/AzureClientBinding/Angular/app/app.component.ts
  JSDemos/Demos/FileManager/AzureClientBinding/azure-file-system.d.ts
  JSDemos/Demos/FileManager/AzureServerBinding/Angular/app/app.component.ts
  JSDemos/Demos/FileUploader/AzureDirectUploading/Angular/app/app.component.ts
  JSDemos/Demos/Localization/UsingGlobalize/Angular/app/cldr.d.ts
  JSDemos/Demos/Localization/UsingIntl/Angular/app/messages.d.ts
  JSDemos/Demos/ProgressBar/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/TimeZonesSupport/Angular/app/app.component.ts
  JSDemos/Demos/VectorMap/CustomAnnotations/Angular/app/app.service.ts
  JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.component.ts
  JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.service.ts
  tsconfig.json
  utils/bundle/index.js
Labels: cherry-pick, 22_1

#1480 Add ts type checking
  .github/workflows/visual_tests_frameworks.yml
  JSDemos/Demos/DataGrid/CollaborativeEditing/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/CollaborativeEditing/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/DataValidation/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/EditStateManagement/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/LocalReordering/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/RealTimeUpdates/Angular/app/app.service.ts
  JSDemos/Demos/Diagram/AdvancedDataBinding/Angular/app/app.component.ts
  JSDemos/Demos/Diagram/NodesAndEdgesArrays/Angular/app/app.service.ts
  JSDemos/Demos/Diagram/OperationRestrictions/Angular/app/app.component.ts
  JSDemos/Demos/Diagram/UICustomization/Angular/app/app.component.ts
  JSDemos/Demos/FileManager/AzureClientBinding/Angular/app/app.component.ts
  JSDemos/Demos/FileManager/AzureClientBinding/azure-file-system.d.ts
  JSDemos/Demos/FileManager/AzureServerBinding/Angular/app/app.component.ts
  JSDemos/Demos/FileUploader/AzureDirectUploading/Angular/app/app.component.ts
  JSDemos/Demos/Localization/UsingGlobalize/Angular/app/cldr.d.ts
  JSDemos/Demos/Localization/UsingIntl/Angular/app/messages.d.ts
  JSDemos/Demos/ProgressBar/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/TimeZonesSupport/Angular/app/app.component.ts
  JSDemos/Demos/VectorMap/CustomAnnotations/Angular/app/app.service.ts
  JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.component.ts
  JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.service.ts
  tsconfig.json
  utils/bundle/index.js
Labels: 21_2

#1650 Re-create package-lock.json (fixes devextreme-xxx installation)
  package-lock.json
Labels: 22_1

#1652 Scheduler - Enhance disabled dates demo (T1059315)
  JSDemos/Demos/Scheduler/CellTemplates/React/App.js
  JSDemos/Demos/Scheduler/CellTemplates/React/DataCell.js
  JSDemos/Demos/Scheduler/CellTemplates/React/DataCellMonth.js
  JSDemos/Demos/Scheduler/CellTemplates/Vue/App.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/DataCell.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/DataCellMonth.vue
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/index.js
Labels: 22_1

#1655 Scheduler - Enhance disabled dates demo (T1059315)
  JSDemos/Demos/Scheduler/CellTemplates/React/App.js
  JSDemos/Demos/Scheduler/CellTemplates/React/DataCell.js
  JSDemos/Demos/Scheduler/CellTemplates/React/DataCellMonth.js
  JSDemos/Demos/Scheduler/CellTemplates/Vue/App.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/DataCell.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/DataCellMonth.vue
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/index.js
Labels: 21_2

#1663 Fix demo tests for PR #20891
  testing/etalons/Form-Overview.png
Labels: 22_1

#1654 Fix demo tests for PR #20797
  testing/etalons/Form-Overview.png
Labels: 21_2

#1671 File Manager - Add mask to fix visual tests for BindingToFileSystem demo
  testing/etalons/FileManager-BindingToFileSystem_mask.png
Labels: 21_2

#1672 File Manager - Add mask to fix visual tests for BindingToFileSystem demo
  testing/etalons/FileManager-BindingToFileSystem_mask.png
Labels: cherry-pick, 22_1

#1666 T1059423: Change the DateBox demo description
  JSDemos/Demos/DateBox/Overview/description.md
Labels: 21_2

#1673 T1059423: Change the DateBox demo description (#1666)
  JSDemos/Demos/DateBox/Overview/description.md
Labels: cherry-pick, 22_1

#1674 TextArea Overview: Change demo description (#1665)
  JSDemos/Demos/TextArea/Overview/description.md
Labels: cherry-pick, 22_1

#1675 Delete Demo Documentation URLs
  JSDemos/menuMeta.json
Labels: 21_2

#1676 Delete Demo Documentation URLs (#1675)
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1677 SelectBox - fix bindings for angular demo
  JSDemos/Demos/SelectBox/SearchAndEditing/Angular/app/app.component.html
Labels: 22_1

#1678 SelectBox - fix bindings for angular demo
  JSDemos/Demos/SelectBox/SearchAndEditing/Angular/app/app.component.html
Labels: cherry-pick, 21_2

#1679 SelectBox - fix bindings for angular demo
  JSDemos/Demos/SelectBox/SearchAndEditing/Angular/app/app.component.html
Labels: 21_1, cherry-pick

#1680 SelectBox - fix bindings for angular demo
  JSDemos/Demos/SelectBox/SearchAndEditing/Angular/app/app.component.html
Labels: 20_2, cherry-pick

#1683 ColorBox: Change demo description
  JSDemos/Demos/ColorBox/Overview/description.md
  JSDemos/menuMeta.json
Labels: 21_2

#1684 ColorBox: Change demo description (#1683)
  JSDemos/Demos/ColorBox/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_1

#1686 HtmlEditor - use defaultValue in the React OutputFormats demo
  JSDemos/Demos/HtmlEditor/OutputFormats/React/App.js
Labels: 21_2

#1687 HtmlEditor - use defaultValue in the React OutputFormats demo
  JSDemos/Demos/HtmlEditor/OutputFormats/React/App.js
Labels: cherry-pick, 22_1

#1692 dxScheduler - Remove unnecessary assignment of "views"
  JSDemos/Demos/Scheduler/GroupByDate/React/App.js
Labels: 22_1

#1693 dxScheduler - Remove unnecessary assignment of "views"
  JSDemos/Demos/Scheduler/GroupByDate/React/App.js
Labels: 21_2

#1691 Calendar - use custom templates for the month zoom level only
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.html
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Calendar/Overview/AngularJS/index.js
  JSDemos/Demos/Calendar/Overview/React/App.js
  JSDemos/Demos/Calendar/Overview/Vue/App.vue
  JSDemos/Demos/Calendar/Overview/jQuery/index.js
  MVCDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/Views/Calendar/Overview.cshtml
Labels: cherry-pick, 21_2

#1688 Calendar - use custom templates for the month zoom level only
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.html
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Calendar/Overview/AngularJS/index.js
  JSDemos/Demos/Calendar/Overview/React/App.js
  JSDemos/Demos/Calendar/Overview/Vue/App.vue
  JSDemos/Demos/Calendar/Overview/jQuery/index.js
  MVCDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/Views/Calendar/Overview.cshtml
Labels: 22_1
