Repository DevExpress/devextreme-demos, pull requests merged in 2022-09, with the labels that each got.

#1998 Validation: update demo description
  JSDemos/Demos/Validation/Overview/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1999 PivotGrid: demonstrate capability to export field headers
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Angular/app/app.component.css
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Angular/app/app.component.html
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/React/styles.css
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/jQuery/index.html
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/jQuery/index.js
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/jQuery/styles.css
  MVCDemos/Content/DemosStyles/PivotGrid/ExcelJsHeaderAndFooter.css
  MVCDemos/Views/PivotGrid/ExcelJSHeaderAndFooter.cshtml
  NetCoreDemos/Views/PivotGrid/ExcelJsHeaderAndFooter.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/PivotGrid/ExcelJsHeaderAndFooter.css
  testing/etalons/PivotGrid-ExcelJsHeaderAndFooter.png
Labels: 22_2

#2002 Validation: update demo description (#1998)
  JSDemos/Demos/Validation/Overview/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#1996 Popup: update Overview demo description
  JSDemos/Demos/Popup/Overview/Angular/description.md
  JSDemos/Demos/Popup/Overview/React/description.md
  JSDemos/Demos/Popup/Overview/Vue/description.md
  JSDemos/Demos/Popup/Overview/description.md
Labels: 22_2

#2001 SelectBox "Overview" demo 22.2: Add a "notify" call in SelectBox's onValueChanged in the "Event Handling" section
  JSDemos/Demos/SelectBox/Overview/Angular/app/app.component.html
  JSDemos/Demos/SelectBox/Overview/Angular/app/app.component.ts
  JSDemos/Demos/SelectBox/Overview/AngularJS/index.js
  JSDemos/Demos/SelectBox/Overview/Knockout/index.js
  JSDemos/Demos/SelectBox/Overview/React/App.js
  JSDemos/Demos/SelectBox/Overview/Vue/App.vue
  JSDemos/Demos/SelectBox/Overview/jQuery/index.js
  MVCDemos/Views/SelectBox/Overview.cshtml
  NetCoreDemos/Views/SelectBox/Overview.cshtml
Labels: 22_2

#2005 SelectBox "Overview" demo 22.1: Add a "notify" call in SelectBox's onValueChanged in the "Event Handling" section
  JSDemos/Demos/SelectBox/Overview/Angular/app/app.component.html
  JSDemos/Demos/SelectBox/Overview/Angular/app/app.component.ts
  JSDemos/Demos/SelectBox/Overview/AngularJS/index.js
  JSDemos/Demos/SelectBox/Overview/Knockout/index.js
  JSDemos/Demos/SelectBox/Overview/React/App.js
  JSDemos/Demos/SelectBox/Overview/Vue/App.vue
  JSDemos/Demos/SelectBox/Overview/jQuery/index.js
  MVCDemos/Views/SelectBox/Overview.cshtml
  NetCoreDemos/Views/SelectBox/Overview.cshtml
Labels: cherry-pick, 22_1

#2008 DataGrid - Overview - update etalons
  testing/etalons/DataGrid-Overview.png
Labels: cherry-pick, 21_2

#2006 DataGrid - Overview - update etalons
  testing/etalons/DataGrid-Overview.png
Labels: 22_2

#2007 DataGrid - Overview - update etalons
  testing/etalons/DataGrid-Overview.png
Labels: cherry-pick, 22_1

#2003 PivotGrid: update the 'Header and Footer' demo description
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/description.md
Labels: 22_2

#2010 Scheduler "Customize Individual Views" demo 22.2: Declare views in HTML instead of JS in Angular
  JSDemos/Demos/Scheduler/CustomizeIndividualViews/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CustomizeIndividualViews/Angular/app/app.component.ts
Labels: 22_2

#2011 Scheduler "Customize Individual Views" demo 22.1: Declare views in HTML instead of JS in Angular
  JSDemos/Demos/Scheduler/CustomizeIndividualViews/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CustomizeIndividualViews/Angular/app/app.component.ts
Labels: cherry-pick, 22_1

#2014 Replace etalons after Chrome update to v.105.0.5195.125
  testing/etalons/ColorBox-Overview.png
  testing/etalons/NumberBox-Overview.png
  testing/etalons/SelectBox-Overview.png
  testing/etalons/TextArea-Overview.png
  testing/etalons/TextBox-Overview.png
  testing/etalons/VectorMap-DynamicViewport.png
Labels: 22_2

#2016 Toast: fix path to documentation in menuMeta
  JSDemos/menuMeta.json
  MVCDemos/Views/Toast/Stack.cshtml
  NetCoreDemos/Views/Toast/Stack.cshtml
Labels: 22_2

#2012 Calendar: add showWeekNumbers in demo
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.css
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.html
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Calendar/Overview/React/App.js
  JSDemos/Demos/Calendar/Overview/React/styles.css
  JSDemos/Demos/Calendar/Overview/Vue/App.vue
  JSDemos/Demos/Calendar/Overview/jQuery/index.html
  JSDemos/Demos/Calendar/Overview/jQuery/index.js
  JSDemos/Demos/Calendar/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Calendar/Overview.css
  MVCDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Calendar/Overview.css
  testing/etalons/Calendar-Overview.png
Labels: 22_2

#2015 Update badges for new and updated demos
  JSDemos/menuMeta.json
Labels: 22_2

#2021 Replace etalons after Chrome update to v.105.0.5195.125 (#2014)
  testing/etalons/ColorBox-Overview.png
  testing/etalons/NumberBox-Overview.png
  testing/etalons/SelectBox-Overview.png
  testing/etalons/TextArea-Overview.png
  testing/etalons/TextBox-Overview.png
  testing/etalons/VectorMap-DynamicViewport.png
Labels: cherry-pick, 22_1

#2022 Replace etalons after Chrome update to v.105.0.5195.125 (#2014)
  testing/etalons/ColorBox-Overview.png
  testing/etalons/NumberBox-Overview.png
  testing/etalons/SelectBox-Overview.png
  testing/etalons/TextArea-Overview.png
  testing/etalons/TextBox-Overview.png
  testing/etalons/VectorMap-DynamicViewport.png
Labels: cherry-pick, 21_2

#2023 DataGrid: change etalons after fix T1115916
  testing/widgets/datagrid/etalons/datagrid_filtering_3_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_5_desktop.png
Labels: 22_2

#2027 Editors: update Validation demo description
  JSDemos/Demos/Validation/Overview/description.md
Labels: 22_2

#2019 CheckBox: update demo description
  JSDemos/Demos/CheckBox/Overview/Angular/description.md
  JSDemos/Demos/CheckBox/Overview/Vue/description.md
  JSDemos/Demos/CheckBox/Overview/description.md
Labels: 22_2

#2004 Multiline toolbar demo
  JSDemos/Demos/Toolbar/Multiline/Angular/app/app.component.css
  JSDemos/Demos/Toolbar/Multiline/Angular/app/app.component.html
  JSDemos/Demos/Toolbar/Multiline/Angular/app/app.component.ts
  JSDemos/Demos/Toolbar/Multiline/Angular/app/app.service.ts
  JSDemos/Demos/Toolbar/Multiline/Angular/index.html
  JSDemos/Demos/Toolbar/Multiline/React/App.js
  JSDemos/Demos/Toolbar/Multiline/React/data.js
  JSDemos/Demos/Toolbar/Multiline/React/index.html
  JSDemos/Demos/Toolbar/Multiline/React/index.js
  JSDemos/Demos/Toolbar/Multiline/React/styles.css
  JSDemos/Demos/Toolbar/Multiline/Vue/App.vue
  JSDemos/Demos/Toolbar/Multiline/Vue/data.js
  JSDemos/Demos/Toolbar/Multiline/Vue/index.html
  JSDemos/Demos/Toolbar/Multiline/Vue/index.js
  JSDemos/Demos/Toolbar/Multiline/description.md
  JSDemos/Demos/Toolbar/Multiline/jQuery/data.js
  JSDemos/Demos/Toolbar/Multiline/jQuery/index.html
  JSDemos/Demos/Toolbar/Multiline/jQuery/index.js
  JSDemos/Demos/Toolbar/Multiline/jQuery/styles.css
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/Toolbar/Multiline.css
  MVCDemos/Controllers/ToolbarController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/FontStyle.cs
  MVCDemos/Models/ListType.cs
  MVCDemos/Models/SampleData/ToolbarData.cs
  MVCDemos/Models/TextAlign.cs
  MVCDemos/ViewModels/ToolbarViewModel.cs
  MVCDemos/Views/Toolbar/Multiline.cshtml
  NetCoreDemos/Controllers/ToolbarController.cs
  NetCoreDemos/Models/FontStyle.cs
  NetCoreDemos/Models/ListType.cs
  NetCoreDemos/Models/SampleData/ToolbarData.cs
  NetCoreDemos/Models/TextAlign.cs
  NetCoreDemos/ViewModels/ToolbarViewModel.cs
  NetCoreDemos/Views/Toolbar/Multiline.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Toolbar/Multiline.css
  testing/etalons/Toolbar-Multiline.png
  testing/widgets/toolbar/Multiline.test.js
  testing/widgets/toolbar/etalons/toolbar_multiline_mode_minimize.png
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_init.png
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_menu_open.png
Labels: 22_2

#2028 Calendar demos: Add description of the 'showWeekNumbers' property
  JSDemos/Demos/Calendar/Overview/Angular/description.md
  JSDemos/Demos/Calendar/Overview/Vue/description.md
  JSDemos/Demos/Calendar/Overview/description.md
Labels: 22_2

#2029 Multiline Toolbar mode: include CS files into context
  JSDemos/menuMeta.json
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/Toolbar/Multiline.cshtml
  NetCoreDemos/Views/Toolbar/Multiline.cshtml
Labels: 22_2

#2026 DataGrid: change etalons after fix T1115916 (#2023)
  testing/widgets/datagrid/etalons/datagrid_filtering_3_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_5_desktop.png
Labels: 21_2

#2025 DataGrid: change etalons after fix T1115916
  testing/widgets/datagrid/Filtering.test.js
  testing/widgets/datagrid/etalons/datagrid_filtering_3_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_5_desktop.png
Labels: cherry-pick, 22_1

#2032 Multiline Toolbar Demo: Fix typo && Add new model
  JSDemos/menuMeta.json
  MVCDemos/Controllers/ToolbarController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/SampleData/ToolbarData.cs
  MVCDemos/Models/ToolbarMode.cs
Labels: 22_2

#2033 Multiline Toolbar Demo: Fix types
  MVCDemos/ViewModels/ToolbarViewModel.cs
Labels: 22_2

#2024 Slider & RangeSlider: update demo to demonstrate callValueChange=onMovingComplete
  JSDemos/Demos/RangeSlider/Overview/Angular/app/app.component.html
  JSDemos/Demos/RangeSlider/Overview/Angular/app/app.component.ts
  JSDemos/Demos/RangeSlider/Overview/AngularJS/index.html
  JSDemos/Demos/RangeSlider/Overview/AngularJS/index.js
  JSDemos/Demos/RangeSlider/Overview/React/App.js
  JSDemos/Demos/RangeSlider/Overview/Vue/App.vue
  JSDemos/Demos/RangeSlider/Overview/jQuery/index.html
  JSDemos/Demos/RangeSlider/Overview/jQuery/index.js
  JSDemos/Demos/Slider/Overview/Angular/app/app.component.html
  JSDemos/Demos/Slider/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Slider/Overview/AngularJS/index.html
  JSDemos/Demos/Slider/Overview/AngularJS/index.js
  JSDemos/Demos/Slider/Overview/React/App.js
  JSDemos/Demos/Slider/Overview/Vue/App.vue
  JSDemos/Demos/Slider/Overview/jQuery/index.html
  JSDemos/Demos/Slider/Overview/jQuery/index.js
  JSDemos/menuMeta.json
  MVCDemos/Views/RangeSlider/Overview.cshtml
  MVCDemos/Views/Slider/Overview.cshtml
  NetCoreDemos/Views/RangeSlider/Overview.cshtml
  NetCoreDemos/Views/Slider/Overview.cshtml
  testing/etalons/RangeSlider-Overview.png
  testing/etalons/Slider-Overview.png
Labels: 22_2

#2034 Slider & RangeSlider demo: use SliderCallValueChange type instead of string
  MVCDemos/Views/RangeSlider/Overview.cshtml
  MVCDemos/Views/Slider/Overview.cshtml
  NetCoreDemos/Views/RangeSlider/Overview.cshtml
  NetCoreDemos/Views/Slider/Overview.cshtml
Labels: 22_2

#2035 Slider & RangeSlider demo: fix types
  MVCDemos/Views/RangeSlider/Overview.cshtml
  MVCDemos/Views/Slider/Overview.cshtml
  NetCoreDemos/Views/RangeSlider/Overview.cshtml
  NetCoreDemos/Views/Slider/Overview.cshtml
Labels: 22_2

#2036 Calendar: refactor demo
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.css
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.html
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Calendar/Overview/AngularJS/index.html
  JSDemos/Demos/Calendar/Overview/AngularJS/index.js
  JSDemos/Demos/Calendar/Overview/AngularJS/styles.css
  JSDemos/Demos/Calendar/Overview/Knockout/index.js
  JSDemos/Demos/Calendar/Overview/Knockout/styles.css
  JSDemos/Demos/Calendar/Overview/React/App.js
  JSDemos/Demos/Calendar/Overview/React/CustomCell.js
  JSDemos/Demos/Calendar/Overview/React/styles.css
  JSDemos/Demos/Calendar/Overview/Vue/App.vue
  JSDemos/Demos/Calendar/Overview/jQuery/index.html
  JSDemos/Demos/Calendar/Overview/jQuery/index.js
  JSDemos/Demos/Calendar/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Calendar/Overview.css
  MVCDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Calendar/Overview.css
Labels: 22_2

#2037 Multiline Toolbar Demo: Remove old code && Fix typos
  JSDemos/menuMeta.json
  MVCDemos/Controllers/ToolbarController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/ListType.cs
  MVCDemos/Models/SampleData/ToolbarData.cs
  MVCDemos/Models/TextAlign.cs
  MVCDemos/Models/ToolbarMode.cs
  MVCDemos/ViewModels/ToolbarViewModel.cs
  MVCDemos/Views/Toolbar/Multiline.cshtml
  NetCoreDemos/Controllers/ToolbarController.cs
  NetCoreDemos/Models/ListType.cs
  NetCoreDemos/Models/SampleData/ToolbarData.cs
  NetCoreDemos/Models/TextAlign.cs
  NetCoreDemos/ViewModels/ToolbarViewModel.cs
  NetCoreDemos/Views/Toolbar/Multiline.cshtml
Labels: 22_2

#2038 Multiline Toolbar Demo: Replace data
  MVCDemos/Views/Toolbar/Multiline.cshtml
  NetCoreDemos/Views/Toolbar/Multiline.cshtml
Labels: 22_2
