Repository DevExpress/devextreme-demos, pull requests merged in 2022-11, with the labels that each got.

#2173 DataGrid - update test for the Master-Detail API demo
  testing/widgets/datagrid/MasterDetailAPI.test.js
  testing/widgets/datagrid/etalons/datagrid_master_detail_api_2_desktop.png
Labels: 22_2

#2174 DataGrid - update test for the Master-Detail API demo
  testing/widgets/datagrid/MasterDetailAPI.test.js
  testing/widgets/datagrid/etalons/datagrid_master_detail_api_2_desktop.png
Labels: cherry-pick, 22_1

#2203 Fix set marker for Maps demo
  .gitignore
  JSDemos/Demos/Map/Markers/Angular/app/app.service.ts
  JSDemos/Demos/Map/Markers/AngularJS/index.js
  JSDemos/Demos/Map/Markers/Knockout/index.js
  JSDemos/Demos/Map/Markers/React/App.js
  JSDemos/Demos/Map/Markers/Vue/App.vue
  JSDemos/Demos/Map/Markers/jQuery/index.js
  JSDemos/images/Map/map-marker.png
  MVCDemos/Views/Map/Markers.cshtml
  NetCoreDemos/Views/Map/Markers.cshtml
Labels: 22_2

#2204 Form: fix notes after PM review
  JSDemos/Demos/Form/CustomizeItem/Angular/app/app.component.css
  JSDemos/Demos/Form/CustomizeItem/Angular/app/app.component.html
  JSDemos/Demos/Form/CustomizeItem/Angular/app/app.component.ts
  JSDemos/Demos/Form/CustomizeItem/React/App.js
  JSDemos/Demos/Form/CustomizeItem/React/LabelNotesTemplate.js
  JSDemos/Demos/Form/CustomizeItem/React/styles.css
  JSDemos/Demos/Form/CustomizeItem/Vue/App.vue
  JSDemos/Demos/Form/CustomizeItem/Vue/LabelNotesTemplate.vue
  JSDemos/Demos/Form/CustomizeItem/jQuery/index.js
  JSDemos/Demos/Form/CustomizeItem/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Form/CustomizeItem.css
  MVCDemos/Views/Form/CustomizeItem.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Form/CustomizeItem.css
  testing/widgets/form/etalons/form_customize_item_label_tooltip.png
Labels: 22_2

#2201 DataGrid: fix imports in Angular ExportToPDF demos (#2198)
  JSDemos/Demos/DataGrid/PDFCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFExportImages/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/PDFOverview/Angular/app/app.component.ts
Labels: cherry-pick, 22_2

#2205 Slider, RangeSlider: rename callValueChange with valueChangeMode
  JSDemos/Demos/RangeSlider/Overview/Angular/app/app.component.html
  JSDemos/Demos/RangeSlider/Overview/AngularJS/index.html
  JSDemos/Demos/RangeSlider/Overview/AngularJS/index.js
  JSDemos/Demos/RangeSlider/Overview/React/App.js
  JSDemos/Demos/RangeSlider/Overview/Vue/App.vue
  JSDemos/Demos/RangeSlider/Overview/jQuery/index.html
  JSDemos/Demos/RangeSlider/Overview/jQuery/index.js
  JSDemos/Demos/Slider/Overview/Angular/app/app.component.html
  JSDemos/Demos/Slider/Overview/AngularJS/index.html
  JSDemos/Demos/Slider/Overview/AngularJS/index.js
  JSDemos/Demos/Slider/Overview/React/App.js
  JSDemos/Demos/Slider/Overview/Vue/App.vue
  JSDemos/Demos/Slider/Overview/jQuery/index.html
  JSDemos/Demos/Slider/Overview/jQuery/index.js
  MVCDemos/Views/RangeSlider/Overview.cshtml
  MVCDemos/Views/Slider/Overview.cshtml
  NetCoreDemos/Views/Form/CustomizeItem.cshtml
  NetCoreDemos/Views/RangeSlider/Overview.cshtml
  NetCoreDemos/Views/Slider/Overview.cshtml
Labels: 22_2

#2202 Line Chart: update demo description
  JSDemos/Demos/Charts/Line/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#2206 Calendar & PivotGrid demos: fix notes after PM review
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.html
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Calendar/Overview/Angular/description.md
  JSDemos/Demos/Calendar/Overview/AngularJS/index.html
  JSDemos/Demos/Calendar/Overview/Knockout/index.html
  JSDemos/Demos/Calendar/Overview/React/App.js
  JSDemos/Demos/Calendar/Overview/Vue/App.vue
  JSDemos/Demos/Calendar/Overview/Vue/description.md
  JSDemos/Demos/Calendar/Overview/description.md
  JSDemos/Demos/Calendar/Overview/jQuery/index.html
  JSDemos/Demos/Calendar/Overview/jQuery/index.js
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Angular/app/app.component.css
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/React/styles.css
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/jQuery/styles.css
  MVCDemos/Content/DemosStyles/PivotGrid/ExcelJsHeaderAndFooter.css
  MVCDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/PivotGrid/ExcelJsHeaderAndFooter.css
  testing/etalons/Calendar-Overview.png
  testing/etalons/PivotGrid-ExcelJsHeaderAndFooter.png
Labels: 22_2

#2207 Slider and RangeSlider: update demo descriptions
  JSDemos/Demos/RangeSlider/Overview/Angular/description.md
  JSDemos/Demos/RangeSlider/Overview/Vue/description.md
  JSDemos/Demos/RangeSlider/Overview/description.md
  JSDemos/Demos/Slider/Overview/Angular/description.md
  JSDemos/Demos/Slider/Overview/React/description.md
  JSDemos/Demos/Slider/Overview/Vue/description.md
  JSDemos/Demos/Slider/Overview/description.md
Labels: 22_2

#2208 Line Chart: update demo description (#2202)
  JSDemos/Demos/Charts/Line/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#2209 Calendar: update demo description
  JSDemos/Demos/Calendar/Overview/Angular/description.md
  JSDemos/Demos/Calendar/Overview/Vue/description.md
  JSDemos/Demos/Calendar/Overview/description.md
Labels: 22_2

#2210 Form CustomizeItem demo & Calendar: fix notes after PM review
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.html
  JSDemos/Demos/Calendar/Overview/Angular/description.md
  JSDemos/Demos/Calendar/Overview/AngularJS/index.html
  JSDemos/Demos/Calendar/Overview/React/App.js
  JSDemos/Demos/Calendar/Overview/Vue/App.vue
  JSDemos/Demos/Calendar/Overview/Vue/description.md
  JSDemos/Demos/Calendar/Overview/description.md
  JSDemos/Demos/Calendar/Overview/jQuery/index.js
  JSDemos/Demos/Form/CustomizeItem/Angular/app/app.component.css
  JSDemos/Demos/Form/CustomizeItem/Angular/app/app.component.html
  JSDemos/Demos/Form/CustomizeItem/React/LabelNotesTemplate.js
  JSDemos/Demos/Form/CustomizeItem/React/LabelTemplate.js
  JSDemos/Demos/Form/CustomizeItem/React/styles.css
  JSDemos/Demos/Form/CustomizeItem/Vue/LabelNotesTemplate.vue
  JSDemos/Demos/Form/CustomizeItem/Vue/LabelTemplate.vue
  JSDemos/Demos/Form/CustomizeItem/jQuery/index.js
  JSDemos/Demos/Form/CustomizeItem/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Form/CustomizeItem.css
  MVCDemos/Views/Calendar/Overview.cshtml
  MVCDemos/Views/Form/CustomizeItem.cshtml
  NetCoreDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/Views/Form/CustomizeItem.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Form/CustomizeItem.css
  testing/etalons/Calendar-Overview.png
  testing/etalons/Form-CustomizeItem.png
  testing/widgets/form/etalons/form_customize_item_label_tooltip.png
Labels: 22_2

#2211 Resizable: improve handle's styling in demos
  JSDemos/Demos/Resizable/Overview/Angular/app/app.component.css
  JSDemos/Demos/Resizable/Overview/React/styles.css
  JSDemos/Demos/Resizable/Overview/Vue/styles.css
  JSDemos/Demos/Resizable/Overview/jQuery/styles.css
  JSDemos/Demos/Toolbar/Adaptability/Angular/app/app.component.css
  JSDemos/Demos/Toolbar/Adaptability/React/styles.css
  JSDemos/Demos/Toolbar/Adaptability/Vue/App.vue
  JSDemos/Demos/Toolbar/Adaptability/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Resizable/Overview.css
  MVCDemos/Content/DemosStyles/Toolbar/Adaptability.css
  NetCoreDemos/wwwroot/css/DemosStyles/Resizable/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/Toolbar/Adaptability.css
  testing/etalons/Resizable-Overview.png
  testing/etalons/Toolbar-Adaptability.png
  testing/widgets/toolbar/etalons/toolbar_multiline_mode_minimize.png
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_init.png
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_menu_open.png
Labels: 22_2

#2212 RangeBar: add minBarSize for demos
  JSDemos/Demos/Charts/RangeBar/Angular/app/app.component.html
  JSDemos/Demos/Charts/RangeBar/Angular/app/app.service.ts
  JSDemos/Demos/Charts/RangeBar/AngularJS/data.js
  JSDemos/Demos/Charts/RangeBar/AngularJS/index.js
  JSDemos/Demos/Charts/RangeBar/Knockout/data.js
  JSDemos/Demos/Charts/RangeBar/Knockout/index.js
  JSDemos/Demos/Charts/RangeBar/React/App.js
  JSDemos/Demos/Charts/RangeBar/React/data.js
  JSDemos/Demos/Charts/RangeBar/Vue/App.vue
  JSDemos/Demos/Charts/RangeBar/Vue/data.js
  JSDemos/Demos/Charts/RangeBar/jQuery/data.js
  JSDemos/Demos/Charts/RangeBar/jQuery/index.js
  MVCDemos/Views/Charts/RangeBar.cshtml
  NetCoreDemos/Views/Charts/RangeBar.cshtml
  testing/etalons/Charts-RangeBar.png
Labels: 22_2

#2214 Charts: update RangeBar demo description
  JSDemos/Demos/Charts/RangeBar/description.md
  JSDemos/menuMeta.json
Labels: 22_2

#2215 Fix tests for ChartsSignalRService demo
  JSDemos/Demos/Charts/AxisCustomPosition/test-code.js
  JSDemos/Demos/Charts/CustomLegendMarkers/test-code.js
  JSDemos/Demos/Charts/PolarChartZoomingAndScrollingAPI/test-code.js
  JSDemos/Demos/Charts/Scatter/test-code.js
  JSDemos/Demos/Charts/SignalRService/test-code.js
  JSDemos/Demos/Charts/Timeline/test-code.js
  JSDemos/Demos/DataGrid/SignalRService/test-code.js
  JSDemos/Demos/RangeSelector/LogarithmicScale/test-code.js
  utils/visual-tests/inject/test-utils.js
Labels: 22_2

#2217 Fix tests for ChartsSignalRService demo
  JSDemos/Demos/Charts/AxisCustomPosition/test-code.js
  JSDemos/Demos/Charts/CustomLegendMarkers/test-code.js
  JSDemos/Demos/Charts/PolarChartZoomingAndScrollingAPI/test-code.js
  JSDemos/Demos/Charts/Scatter/test-code.js
  JSDemos/Demos/Charts/SignalRService/test-code.js
  JSDemos/Demos/Charts/Timeline/test-code.js
  JSDemos/Demos/DataGrid/SignalRService/test-code.js
  JSDemos/Demos/RangeSelector/LogarithmicScale/test-code.js
  utils/visual-tests/inject/test-utils.js
Labels: cherry-pick, 21_2

#2216 Fix tests for ChartsSignalRService demo
  JSDemos/Demos/Charts/AxisCustomPosition/test-code.js
  JSDemos/Demos/Charts/CustomLegendMarkers/test-code.js
  JSDemos/Demos/Charts/PolarChartZoomingAndScrollingAPI/test-code.js
  JSDemos/Demos/Charts/Scatter/test-code.js
  JSDemos/Demos/Charts/SignalRService/test-code.js
  JSDemos/Demos/Charts/Timeline/test-code.js
  JSDemos/Demos/DataGrid/SignalRService/test-code.js
  JSDemos/Demos/RangeSelector/LogarithmicScale/test-code.js
  utils/visual-tests/inject/test-utils.js
Labels: cherry-pick, 22_1

#2225 Calendar: simplify styles
  testing/etalons/Calendar-Overview.png
Labels: 22_2

#2227 Toolbar Adaptability Demo: remove redundant styles
  JSDemos/Demos/Toolbar/Adaptability/Angular/app/app.component.css
  JSDemos/Demos/Toolbar/Adaptability/React/styles.css
  JSDemos/Demos/Toolbar/Adaptability/Vue/App.vue
  JSDemos/Demos/Toolbar/Adaptability/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Toolbar/Adaptability.css
  NetCoreDemos/wwwroot/css/DemosStyles/Toolbar/Adaptability.css
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_menu_open.png
Labels: 22_2

#2228 Spline Charts: update demo description
  JSDemos/Demos/Charts/Spline/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#2233 Spline Charts: update demo description (#2228)
  JSDemos/Demos/Charts/Spline/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#2234 Toolbar: styles enchancements for Vue templates specifity
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_menu_open.png
Labels: 22_2

#2236 Button: get rid of use static line-height property value
  testing/etalons/Common-CustomTextEditorButtons.png
Labels: 22_2

#2237 Toolbar: get rid of use additional class for separator
  JSDemos/Demos/Toolbar/Adaptability/Angular/app/app.component.css
  JSDemos/Demos/Toolbar/Adaptability/Angular/app/app.component.html
  JSDemos/Demos/Toolbar/Adaptability/React/App.js
  JSDemos/Demos/Toolbar/Adaptability/React/styles.css
  JSDemos/Demos/Toolbar/Adaptability/jQuery/index.js
  JSDemos/Demos/Toolbar/Adaptability/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Toolbar/Adaptability.css
  MVCDemos/Views/Toolbar/Adaptability.cshtml
  NetCoreDemos/Views/Toolbar/Adaptability.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Toolbar/Adaptability.css
Labels: 22_2

#2229 vectorMap: change demo Dynamic Viewport adding an option for control bar
  JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.component.css
  JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.component.html
  JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.component.ts
  JSDemos/Demos/VectorMap/DynamicViewport/AngularJS/index.html
  JSDemos/Demos/VectorMap/DynamicViewport/AngularJS/index.js
  JSDemos/Demos/VectorMap/DynamicViewport/AngularJS/styles.css
  JSDemos/Demos/VectorMap/DynamicViewport/Knockout/index.html
  JSDemos/Demos/VectorMap/DynamicViewport/Knockout/index.js
  JSDemos/Demos/VectorMap/DynamicViewport/Knockout/styles.css
  JSDemos/Demos/VectorMap/DynamicViewport/React/App.js
  JSDemos/Demos/VectorMap/DynamicViewport/React/styles.css
  JSDemos/Demos/VectorMap/DynamicViewport/Vue/App.vue
  JSDemos/Demos/VectorMap/DynamicViewport/jQuery/index.html
  JSDemos/Demos/VectorMap/DynamicViewport/jQuery/index.js
  JSDemos/Demos/VectorMap/DynamicViewport/jQuery/styles.css
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/VectorMap/DynamicViewport.css
  MVCDemos/Views/VectorMap/DynamicViewport.cshtml
  NetCoreDemos/Views/VectorMap/DynamicViewport.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/VectorMap/DynamicViewport.css
  testing/etalons/VectorMap-DynamicViewport.png
Labels: 22_2

#2239 Palette (Pie Chart): update demo description
  JSDemos/Demos/Charts/Palette/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#2240 Palette (Pie Chart): update demo description (#2239)
  JSDemos/Demos/Charts/Palette/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#2244 Toolbar: overflow menu list items should not have focused state
  testing/widgets/toolbar/Adaptability.test.js
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_menu_open.png
Labels: 22_2

#2245 VectorMap: update Dynamic Viewport description
  JSDemos/Demos/VectorMap/DynamicViewport/description.md
  JSDemos/menuMeta.json
Labels: 22_2

#2246 PivotGrid: Hierarchy icons overlap in fieldChooser in the IntegratedField Chooser demo (T1126747)
  testing/widgets/pivotgrid/IntegratedFieldChooser.test.js
  testing/widgets/pivotgrid/etalons/Integrated field chooser after search of hierarchy field.png
  testing/widgets/pivotgrid/etalons/Integrated field chooser.png
  testing/widgets/toolbar/Adaptability.test.js
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_menu_open.png
Labels: 22_2

#2258 T1125133 - FileManager - fix azure-file-system file
  JSDemos/Demos/FileManager/AzureClientBinding/azure-file-system.js
Labels: 22_2

#2262 Popup: Fix collision issue
  JSDemos/Demos/Popup/Overview/Angular/app/app.component.html
  JSDemos/Demos/Popup/Overview/AngularJS/index.js
  JSDemos/Demos/Popup/Overview/Knockout/index.js
  JSDemos/Demos/Popup/Overview/React/App.js
  JSDemos/Demos/Popup/Overview/Vue/App.vue
  JSDemos/Demos/Popup/Overview/jQuery/index.js
  MVCDemos/Views/Popup/Overview.cshtml
  NetCoreDemos/Views/Popup/Overview.cshtml
Labels: 22_2

#2263 Popup: Fix collision issue
  JSDemos/Demos/Popup/Overview/Angular/app/app.component.html
  JSDemos/Demos/Popup/Overview/AngularJS/index.js
  JSDemos/Demos/Popup/Overview/Knockout/index.js
  JSDemos/Demos/Popup/Overview/React/App.js
  JSDemos/Demos/Popup/Overview/Vue/App.vue
  JSDemos/Demos/Popup/Overview/jQuery/index.js
  MVCDemos/Views/Popup/Overview.cshtml
  NetCoreDemos/Views/Popup/Overview.cshtml
Labels: cherry-pick, 22_1

#2266 T1125133 - FileUploader - fix azure-file-system file
  JSDemos/Demos/FileUploader/AzureDirectUploading/azure-file-system.js
Labels: 22_2

#2267 Fix remote operations nested component
  JSDemos/Demos/DataGrid/RemoteGrouping/Vue/App.vue
  tsconfig.json
Labels: 22_2

#2268 Fix remote operations nested component 22_1
  JSDemos/Demos/DataGrid/RemoteGrouping/Vue/App.vue
  tsconfig.json
Labels: cherry-pick

#2272 Chart: update Axis Label Overlapping demo description
  JSDemos/Demos/Charts/AxisLabelsOverlapping/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#2273 Chart: update Axis Label Overlapping demo description (#2272)
  JSDemos/Demos/Charts/AxisLabelsOverlapping/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#2287 Lookup "Handle Value Change" demo 22.2: Add the options area (#2226)
  JSDemos/Demos/Lookup/EventHandling/Angular/app/app.component.css
  JSDemos/Demos/Lookup/EventHandling/Angular/app/app.component.html
  JSDemos/Demos/Lookup/EventHandling/Angular/app/app.component.ts
  JSDemos/Demos/Lookup/EventHandling/React/App.js
  JSDemos/Demos/Lookup/EventHandling/React/styles.css
  JSDemos/Demos/Lookup/EventHandling/Vue/App.vue
  JSDemos/Demos/Lookup/EventHandling/Vue/styles.css
  JSDemos/Demos/Lookup/EventHandling/jQuery/index.html
  JSDemos/Demos/Lookup/EventHandling/jQuery/index.js
  JSDemos/Demos/Lookup/EventHandling/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Lookup/EventHandling.css
  MVCDemos/Views/Lookup/EventHandling.cshtml
  NetCoreDemos/Views/Lookup/EventHandling.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Lookup/EventHandling.css
  testing/etalons/Lookup-EventHandling.png
Labels: cherry-pick, 22_2

#2252 DataGrid: Add testcafe test for the AjaxRequest, OdataService, and SimpleArray demos
  testing/widgets/datagrid/AjaxRequest.test.js
  testing/widgets/datagrid/OdataService.test.js
  testing/widgets/datagrid/SimpleArray.test.js
  testing/widgets/datagrid/etalons/datagrid_ajax_request_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_ajax_request_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_odata_service_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_odata_service_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_simple_array_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_simple_array_2_desktop.png
Labels: 22_2

#2253 DataGrid: Add testcafe test for the AjaxRequest, OdataService, and SimpleArray demos
  testing/widgets/datagrid/AjaxRequest.test.js
  testing/widgets/datagrid/OdataService.test.js
  testing/widgets/datagrid/SimpleArray.test.js
  testing/widgets/datagrid/etalons/datagrid_ajax_request_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_ajax_request_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_odata_service_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_odata_service_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_simple_array_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_simple_array_2_desktop.png
Labels: cherry-pick, 22_1

#2290 Update elatons for updated demos
  testing/etalons/Charts-Selection.png
  testing/etalons/Charts-Stock.png
  testing/etalons/Charts-Timeline.png
  testing/etalons/Charts-WindRose.png
  testing/etalons/RangeSelector-ChartOnBackgroundWithSeriesTemplate.png
Labels: 22_2

#2288 PieChart: update Pie with Custom Labels demo description
  JSDemos/Demos/Charts/PieWithCustomLabels/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#2291 PieChart: update Pie with Custom Labels demo description (#2288)
  JSDemos/Demos/Charts/PieWithCustomLabels/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#2293 Update readme file
  README.md
Labels: 22_2
