Repository DevExpress/devextreme-demos, pull requests merged in 2022-08, with the labels that each got.

#1957 Validation: replace string with enum for validationMessagePosition
  MVCDemos/Views/Validation/Overview.cshtml
  NetCoreDemos/Views/Validation/Overview.cshtml
Labels: 22_2

#1959 Scheduler - Correct condition for the disabled date cells
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/CellTemplates/React/App.js
  JSDemos/Demos/Scheduler/CellTemplates/React/DataCell.js
  JSDemos/Demos/Scheduler/CellTemplates/React/DateCell.js
  JSDemos/Demos/Scheduler/CellTemplates/React/utils.js
  JSDemos/Demos/Scheduler/CellTemplates/Vue/App.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/DateCell.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/utils.js
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/index.js
  testing/etalons/Scheduler-CellTemplates.png
Labels: cherry-pick, 22_1

#1960 Scheduler - Correct condition for the disabled date cells
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/CellTemplates/React/App.js
  JSDemos/Demos/Scheduler/CellTemplates/React/DataCell.js
  JSDemos/Demos/Scheduler/CellTemplates/React/DateCell.js
  JSDemos/Demos/Scheduler/CellTemplates/React/utils.js
  JSDemos/Demos/Scheduler/CellTemplates/Vue/App.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/DateCell.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/utils.js
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/index.js
  testing/etalons/Scheduler-CellTemplates.png
Labels: cherry-pick, 21_2

#1961 Scheduler - Correct condition for the disabled date cell template
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/CellTemplates/React/App.js
  JSDemos/Demos/Scheduler/CellTemplates/React/DataCell.js
  JSDemos/Demos/Scheduler/CellTemplates/React/DateCell.js
  JSDemos/Demos/Scheduler/CellTemplates/React/utils.js
  JSDemos/Demos/Scheduler/CellTemplates/Vue/App.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/DateCell.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/utils.js
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/index.js
  testing/etalons/Scheduler-CellTemplates.png
Labels: 22_2

#1963 Validation: fix asp validationMessagePosition
  MVCDemos/Views/Validation/Overview.cshtml
  NetCoreDemos/Views/Validation/Overview.cshtml
Labels: 22_2

#1949 TreeMap: update the 'Tiling Algorithms' demo description
  JSDemos/Demos/Charts/TilingAlgorithms/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1964 TreeMap: update the 'Tiling Algorithms' demo description (#1949)
  JSDemos/Demos/Charts/TilingAlgorithms/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#1956 HtmlEditor "Output Format" demo: add the Prettier formatting
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.component.ts
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/OutputFormats/Knockout/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/Knockout/index.js
  JSDemos/Demos/HtmlEditor/OutputFormats/React/App.js
  JSDemos/Demos/HtmlEditor/OutputFormats/Vue/App.vue
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/index.js
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.js
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
  package-lock.json
  package.json
  testing/etalons/HtmlEditor-OutputFormats.png
Labels: 22_1

#1965 CheckBox: fix demo description
  JSDemos/Demos/CheckBox/Overview/description.md
Labels: 22_1

#1950 TreeMap: update the 'Colorization' demo description
  JSDemos/Demos/Charts/Colorization/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1968 TreeMap: update the 'Colorization' demo description (#1950)
  JSDemos/Demos/Charts/Colorization/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#1974 Charts: update 'Area' demo description
  JSDemos/Demos/Charts/Area/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1976 GitHub Actions: fix concurrency params, pin Chrome version
  .github/workflows/unit_tests.yml
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
Labels: 22_1

#1977 GitHub Actions: fix concurrency params, pin Chrome version
  .github/workflows/unit_tests.yml
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
Labels: 21_2

#1978 Charts: update 'Area' demo description (#1974)
  JSDemos/Demos/Charts/Area/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#1971 DataGrid - LocalReordering demo - fix getting toIndex(T1106928)
  JSDemos/Demos/DataGrid/LocalReordering/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/LocalReordering/React/App.js
  JSDemos/Demos/DataGrid/LocalReordering/Vue/App.vue
  JSDemos/Demos/DataGrid/LocalReordering/jQuery/index.js
  MVCDemos/Views/DataGrid/LocalReordering.cshtml
  NetCoreDemos/Views/DataGrid/LocalReordering.cshtml
Labels: 22_1

#1973 DataGrid - LocalReordering demo - fix getting toIndex(T1106928)
  JSDemos/Demos/DataGrid/LocalReordering/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/LocalReordering/React/App.js
  JSDemos/Demos/DataGrid/LocalReordering/Vue/App.vue
  JSDemos/Demos/DataGrid/LocalReordering/jQuery/index.js
  MVCDemos/Views/DataGrid/LocalReordering.cshtml
  NetCoreDemos/Views/DataGrid/LocalReordering.cshtml
Labels: 21_2

#1979 HtmlEditor "Output Format" demo: add the Prettier
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.component.ts
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/index.js
  JSDemos/Demos/HtmlEditor/OutputFormats/Knockout/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/Knockout/index.js
  JSDemos/Demos/HtmlEditor/OutputFormats/React/App.js
  JSDemos/Demos/HtmlEditor/OutputFormats/Vue/App.vue
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/index.js
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.js
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
  package-lock.json
  package.json
  testing/etalons/HtmlEditor-OutputFormats.png
Labels: cherry-pick, 22_2

#1980 Charts: update Spline Area demo description
  JSDemos/Demos/Charts/SplineArea/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1981 Charts: update Step Area demo description
  JSDemos/Demos/Charts/StepArea/description.md
Labels: 22_1

#1983 Charts: update Step Area demo description (#1981)
  JSDemos/Demos/Charts/StepArea/description.md
Labels: cherry-pick, 22_2

#1982 Charts: update Spline Area demo description (#1980)
  JSDemos/Demos/Charts/SplineArea/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#1985 Charts: update Stock demo description
  JSDemos/Demos/Charts/Stock/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1987 Form and Editors Validation: `test@dx-email.com` is invalid
  JSDemos/Demos/Form/Validation/Angular/app/app.component.ts
  JSDemos/Demos/Form/Validation/AngularJS/index.js
  JSDemos/Demos/Form/Validation/Knockout/index.js
  JSDemos/Demos/Form/Validation/React/App.js
  JSDemos/Demos/Form/Validation/Vue/App.vue
  JSDemos/Demos/Form/Validation/jQuery/index.js
  JSDemos/Demos/Validation/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Validation/Overview/AngularJS/index.js
  JSDemos/Demos/Validation/Overview/Knockout/index.js
  JSDemos/Demos/Validation/Overview/React/App.js
  JSDemos/Demos/Validation/Overview/Vue/App.vue
  JSDemos/Demos/Validation/Overview/jQuery/index.js
  MVCDemos/Controllers/RemoteValidationController.cs
  NetCoreDemos/Controllers/RemoteValidationController.cs
Labels: 22_2

#1988 Form and Editors Validation: test@dx-email.com is invalid
  JSDemos/Demos/Form/Validation/Angular/app/app.component.ts
  JSDemos/Demos/Form/Validation/AngularJS/index.js
  JSDemos/Demos/Form/Validation/Knockout/index.js
  JSDemos/Demos/Form/Validation/React/App.js
  JSDemos/Demos/Form/Validation/Vue/App.vue
  JSDemos/Demos/Form/Validation/jQuery/index.js
  JSDemos/Demos/Validation/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Validation/Overview/AngularJS/index.js
  JSDemos/Demos/Validation/Overview/Knockout/index.js
  JSDemos/Demos/Validation/Overview/React/App.js
  JSDemos/Demos/Validation/Overview/Vue/App.vue
  JSDemos/Demos/Validation/Overview/jQuery/index.js
  MVCDemos/Controllers/RemoteValidationController.cs
  NetCoreDemos/Controllers/RemoteValidationController.cs
Labels: cherry-pick, 22_1

#1986 Charts: update Stock demo description (#1985)
  JSDemos/Demos/Charts/Stock/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#1984 Charts: update Step Area with Gaps demo description
  JSDemos/Demos/Charts/NullPointSupport/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1993 Charts: update Step Area with Gaps demo description (#1984)
  JSDemos/Demos/Charts/NullPointSupport/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2

#1992 Popup: add overflow menu in toolbar
  JSDemos/Demos/Popup/Overview/Angular/app/app.component.html
  JSDemos/Demos/Popup/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Popup/Overview/React/App.js
  JSDemos/Demos/Popup/Overview/Vue/App.vue
  JSDemos/Demos/Popup/Overview/jQuery/index.js
  MVCDemos/Views/Popup/Overview.cshtml
  NetCoreDemos/Views/Popup/Overview.cshtml
Labels: 22_2

#1995 Popup: add overflow menu in toolbar (AngularJS)
  JSDemos/Demos/Popup/Overview/AngularJS/index.js
Labels: 22_2

#1994 Charts: update Candlestick demo description
  JSDemos/Demos/Charts/Candlestick/description.md
  JSDemos/menuMeta.json
Labels: 22_1

#1997 Charts: update Candlestick demo description (#1994)
  JSDemos/Demos/Charts/Candlestick/description.md
  JSDemos/menuMeta.json
Labels: cherry-pick, 22_2
