Repository DevExpress/devextreme-demos, pull requests merged in 2023-06, with the labels that each got.

#2615 DateRangeBox: add the Overview demo description
  JSDemos/Demos/DateRangeBox/Overview/description.md
Labels: 23_1

#2619 DateBox formatting demo - Decipher LDML abbreviation
  JSDemos/Demos/DateBox/Formatting/Angular/app/app.component.html
  JSDemos/Demos/DateBox/Formatting/AngularJS/index.html
  JSDemos/Demos/DateBox/Formatting/React/App.js
  JSDemos/Demos/DateBox/Formatting/Vue/App.vue
  JSDemos/Demos/DateBox/Formatting/jQuery/index.html
  testing/etalons/DateBox-Formatting.png
Labels: 23_1

#2621 Move DateRangeBox demo after DateBox
  JSDemos/menuMeta.json
Labels: 23_1

#2617 DateRangeBox - Add Formatting demo
  JSDemos/Demos/DateRangeBox/Formatting/Angular/app/app.component.css
  JSDemos/Demos/DateRangeBox/Formatting/Angular/app/app.component.html
  JSDemos/Demos/DateRangeBox/Formatting/Angular/app/app.component.ts
  JSDemos/Demos/DateRangeBox/Formatting/Angular/index.html
  JSDemos/Demos/DateRangeBox/Formatting/React/App.js
  JSDemos/Demos/DateRangeBox/Formatting/React/index.html
  JSDemos/Demos/DateRangeBox/Formatting/React/index.js
  JSDemos/Demos/DateRangeBox/Formatting/React/styles.css
  JSDemos/Demos/DateRangeBox/Formatting/Vue/App.vue
  JSDemos/Demos/DateRangeBox/Formatting/Vue/index.html
  JSDemos/Demos/DateRangeBox/Formatting/Vue/index.js
  JSDemos/Demos/DateRangeBox/Formatting/jQuery/index.html
  JSDemos/Demos/DateRangeBox/Formatting/jQuery/index.js
  JSDemos/Demos/DateRangeBox/Formatting/jQuery/styles.css
  JSDemos/Demos/DateRangeBox/Formatting/test-code.js
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/DateRangeBox/Formatting.css
  MVCDemos/Controllers/DateRangeBoxController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/DateRangeBox/Formatting.cshtml
  NetCoreDemos/Controllers/DateRangeBoxController.cs
  NetCoreDemos/Views/DateRangeBox/Formatting.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/DateRangeBox/Formatting.css
  testing/etalons/DateRangeBox-Formatting.png
Labels: 23_1

#2622 DateRangeBox demo - Fix popup clipping
  JSDemos/Demos/DateRangeBox/Formatting/Angular/app/app.component.css
  JSDemos/Demos/DateRangeBox/Formatting/React/styles.css
  JSDemos/Demos/DateRangeBox/Formatting/Vue/App.vue
  JSDemos/Demos/DateRangeBox/Formatting/jQuery/styles.css
  JSDemos/Demos/DateRangeBox/Overview/Angular/app/app.component.css
  JSDemos/Demos/DateRangeBox/Overview/React/styles.css
  JSDemos/Demos/DateRangeBox/Overview/Vue/App.vue
  JSDemos/Demos/DateRangeBox/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/DateRangeBox/Formatting.css
  MVCDemos/Content/DemosStyles/DateRangeBox/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/DateRangeBox/Formatting.css
  NetCoreDemos/wwwroot/css/DemosStyles/DateRangeBox/Overview.css
Labels: 23_1

#2625 DateRangeBox Overview demo - increase height of demo container
  JSDemos/Demos/DateRangeBox/Overview/Angular/app/app.component.css
  JSDemos/Demos/DateRangeBox/Overview/React/styles.css
  JSDemos/Demos/DateRangeBox/Overview/Vue/App.vue
  JSDemos/Demos/DateRangeBox/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/DateRangeBox/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/DateRangeBox/Overview.css
Labels: 23_1

#2626 Charts: update 'Pie with Custom Fill Styles' demo description
  JSDemos/Demos/Charts/PieWithCustomStyles/description.md
Labels: 23_1

#2624 DateRangeBox: update the Overview demo description
  JSDemos/Demos/DateRangeBox/Overview/description.md
Labels: 23_1

#2623 DateRangeBox: add the Formatting demo description
  JSDemos/Demos/DateRangeBox/Formatting/description.md
Labels: 23_1

#2628 Map: add mask on unstable test
  testing/etalons/Map-ProvidersAndTypes_mask.png
Labels: 23_1

#2627 Gantt: update the Header Filter demo
  JSDemos/Demos/Gantt/HeaderFilter/description.md
Labels: 23_1

#2633 Update new demos description
  JSDemos/Demos/DataGrid/ColumnChooser/description.md
  JSDemos/Demos/DataGrid/UsingHeaderFilter/description.md
  JSDemos/Demos/DateRangeBox/Overview/description.md
Labels: 23_1

#2634 DataGrid - rename demo 'Using Header Filter' to 'Column Header Filter'
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/Angular/index.html
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/React/App.js
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/React/data.js
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/React/index.html
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/React/index.js
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/React/styles.css
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/Vue/App.vue
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/Vue/data.js
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/Vue/index.html
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/Vue/index.js
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/description.md
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/jQuery/data.js
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/jQuery/index.html
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/jQuery/index.js
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/jQuery/styles.css
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/DataGrid/ColumnHeaderFilter.css
  MVCDemos/Controllers/DataGridController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/DataGrid/ColumnHeaderFilter.cshtml
  NetCoreDemos/Controllers/DataGridController.cs
  NetCoreDemos/Views/DataGrid/ColumnHeaderFilter.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/ColumnHeaderFilter.css
  testing/etalons/DataGrid-ColumnHeaderFilter.png
Labels: 23_1

#2643 RadioGroup: The radio button's dot should be centered when the browser window is zoomed out and the compact Material theme is used (T1165339)
  testing/etalons/RadioGroup-Overview.png
  testing/etalons/Toast-Stack.png
  testing/widgets/list/etalons/List after change selectionMode to single.png
Labels: 23_1

#2644 TreeList - Form/Popup Editing: Fix an issue where new items cannot be added in ASP.NET Core/MVC
  MVCDemos/Models/TreeList/Employee.cs
  NetCoreDemos/Models/TreeList/Employee.cs
Labels: 23_1

#2646 DataRangeBox: update Overview demo
  JSDemos/Demos/DateRangeBox/Overview/description.md
Labels: 23_1

#2647 Validation demo - Demo should not use data from another demo
  JSDemos/Demos/Validation/Overview/React/App.js
  JSDemos/Demos/Validation/Overview/React/data.js
Labels: 23_1

#2651 Update etalons after Chrome update
  testing/etalons/Charts-Bubble.png
  testing/etalons/Charts-ContinuousData.png
  testing/etalons/Charts-Crosshair.png
  testing/etalons/Charts-DiscreteData.png
  testing/etalons/Charts-InvertedChart.png
  testing/etalons/Charts-PeriodicData.png
  testing/etalons/Charts-PieWithAnnotations.png
  testing/etalons/Charts-PolarChartZoomingAndScrollingAPI.png
  testing/etalons/Common-EditorsOverview.png
  testing/etalons/Diagram-Adaptability.png
  testing/etalons/Diagram-Containers.png
  testing/etalons/Diagram-CustomShapesWithIcons.png
  testing/etalons/Diagram-CustomShapesWithTemplates.png
  testing/etalons/Diagram-CustomShapesWithTemplatesWithEditing.png
  testing/etalons/Diagram-CustomShapesWithTexts.png
  testing/etalons/Diagram-ImagesInShapes.png
  testing/etalons/Diagram-ItemSelection.png
  testing/etalons/Diagram-NodesAndEdgesArrays.png
  testing/etalons/Diagram-NodesArrayHierarchicalStructure.png
  testing/etalons/Diagram-NodesArrayPlainStructure.png
  testing/etalons/Diagram-OperationRestrictions.png
  testing/etalons/Diagram-SimpleView.png
  testing/etalons/Diagram-UICustomization.png
  testing/etalons/Diagram-WebAPIService.png
  testing/etalons/Gallery-Overview.png
  testing/etalons/Gantt-ChartAppearance.png
  testing/etalons/Gantt-ContextMenu.png
  testing/etalons/Gantt-DataBinding.png
  testing/etalons/Gantt-ExportToPDF.png
  testing/etalons/Gantt-FilterRow.png
  testing/etalons/Gantt-HeaderFilter.png
  testing/etalons/Gantt-Overview.png
  testing/etalons/Gantt-Sorting.png
  testing/etalons/Gantt-StripLines.png
  testing/etalons/Gantt-TaskTemplate.png
  testing/etalons/Gantt-Toolbar.png
  testing/etalons/Gantt-Validation.png
  testing/etalons/Gauges-GaugeTitleCustomized.png
  testing/etalons/Map-Markers.png
  testing/etalons/Map-Routes.png
  testing/etalons/VectorMap-AreaWithLabelsAndTwoLegends.png
  testing/etalons/VectorMap-ColorsCustomization.png
  testing/etalons/VectorMap-CustomMapData.png
  testing/etalons/VectorMap-MultipleLayers.png
  testing/etalons/VectorMap-PieMarkers.png
  testing/etalons/VectorMap-TooltipHTMLSupport.png
  testing/widgets/charts/etalons/annotations_drag.png
  testing/widgets/charts/etalons/charts_crosshair.png
  testing/widgets/vectormap/etalons/vectormap_tooltip.png
Labels: 23_1

#2661 Update etalons after Chrome update
  testing/etalons/Charts-Bubble.png
  testing/etalons/Charts-ContinuousData.png
  testing/etalons/Charts-Crosshair.png
  testing/etalons/Charts-DiscreteData.png
  testing/etalons/Charts-InvertedChart.png
  testing/etalons/Charts-PeriodicData.png
  testing/etalons/Charts-PieWithAnnotations.png
  testing/etalons/Charts-PolarChartZoomingAndScrollingAPI.png
  testing/etalons/Common-EditorsOverview.png
  testing/etalons/Diagram-Adaptability.png
  testing/etalons/Diagram-Containers.png
  testing/etalons/Diagram-CustomShapesWithIcons.png
  testing/etalons/Diagram-CustomShapesWithTemplates.png
  testing/etalons/Diagram-CustomShapesWithTemplatesWithEditing.png
  testing/etalons/Diagram-CustomShapesWithTexts.png
  testing/etalons/Diagram-ImagesInShapes.png
  testing/etalons/Diagram-ItemSelection.png
  testing/etalons/Diagram-NodesAndEdgesArrays.png
  testing/etalons/Diagram-NodesArrayHierarchicalStructure.png
  testing/etalons/Diagram-NodesArrayPlainStructure.png
  testing/etalons/Diagram-OperationRestrictions.png
  testing/etalons/Diagram-SimpleView.png
  testing/etalons/Diagram-UICustomization.png
  testing/etalons/Diagram-WebAPIService.png
  testing/etalons/Gallery-Overview.png
  testing/etalons/Gantt-ChartAppearance.png
  testing/etalons/Gantt-ContextMenu.png
  testing/etalons/Gantt-DataBinding.png
  testing/etalons/Gantt-ExportToPDF.png
  testing/etalons/Gantt-FilterRow.png
  testing/etalons/Gantt-HeaderFilter.png
  testing/etalons/Gantt-Overview.png
  testing/etalons/Gantt-Sorting.png
  testing/etalons/Gantt-StripLines.png
  testing/etalons/Gantt-TaskTemplate.png
  testing/etalons/Gantt-Toolbar.png
  testing/etalons/Gantt-Validation.png
  testing/etalons/Gauges-GaugeTitleCustomized.png
  testing/etalons/Map-Markers.png
  testing/etalons/Map-Routes.png
  testing/etalons/VectorMap-AreaWithLabelsAndTwoLegends.png
  testing/etalons/VectorMap-ColorsCustomization.png
  testing/etalons/VectorMap-CustomMapData.png
  testing/etalons/VectorMap-MultipleLayers.png
  testing/etalons/VectorMap-PieMarkers.png
  testing/etalons/VectorMap-TooltipHTMLSupport.png
  testing/widgets/charts/etalons/annotations_drag.png
  testing/widgets/charts/etalons/charts_crosshair.png
  testing/widgets/vectormap/etalons/vectormap_tooltip.png
Labels: cherry-pick, 23_2

#2668 CI: Clone wrappers from 23.1 on branch 23_1
  .github/workflows/visual_tests_frameworks.yml
Labels: 23_1

#2657 chore: update devextreme* packages to 23.1.3
  package-lock.json
Labels: 23_1

#2671 CI: fix frameworks workflow after updating wrapper repos
  .github/workflows/visual_tests_frameworks.yml
Labels: 23_2

#2669 Editor Appearance demo: rework to show new DateRangeBox component
  JSDemos/Demos/Common/EditorAppearanceVariants/Angular/app/app.component.css
  JSDemos/Demos/Common/EditorAppearanceVariants/Angular/app/app.component.html
  JSDemos/Demos/Common/EditorAppearanceVariants/Angular/app/app.component.ts
  JSDemos/Demos/Common/EditorAppearanceVariants/Angular/app/app.service.ts
  JSDemos/Demos/Common/EditorAppearanceVariants/React/App.js
  JSDemos/Demos/Common/EditorAppearanceVariants/React/data.js
  JSDemos/Demos/Common/EditorAppearanceVariants/React/styles.css
  JSDemos/Demos/Common/EditorAppearanceVariants/Vue/App.vue
  JSDemos/Demos/Common/EditorAppearanceVariants/Vue/data.js
  JSDemos/Demos/Common/EditorAppearanceVariants/jQuery/data.js
  JSDemos/Demos/Common/EditorAppearanceVariants/jQuery/index.html
  JSDemos/Demos/Common/EditorAppearanceVariants/jQuery/index.js
  JSDemos/Demos/Common/EditorAppearanceVariants/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Common/EditorAppearanceVariants.css
  MVCDemos/Views/Common/EditorAppearanceVariants.cshtml
  NetCoreDemos/Views/Common/EditorAppearanceVariants.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Common/EditorAppearanceVariants.css
  testing/etalons/Common-EditorAppearanceVariants.png
  testing/widgets/common/EditorAppearanceVariants.test.js
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_floating_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_floating_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_hidden_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_hidden_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_static_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_static_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_floating_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_floating_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_hidden_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_hidden_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_static_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_static_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_floating_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_floating_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_hidden_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_hidden_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_static_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_static_desktop_mask.png
Labels: cherry-pick, 23_2

#2673 CI: Fix frameworks workflow after updating wrapper repos
  .github/workflows/visual_tests_frameworks.yml
Labels: cherry-pick, 23_1

#2637 Accessibility tests: Show warnings instead of errors
  .github/workflows/visual_tests.yml
  package-lock.json
  package.json
  testing/common.test.js
  utils/axe-reporter/reporter.js
  utils/visual-tests/testcafe-runner.mjs
Labels: force all tests, 23_1

#2667 TreeList - rename demo 'Using Header Filter' to 'Column Header Filter'
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Angular/app/app.component.css
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Angular/app/app.component.html
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Angular/app/app.service.ts
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Angular/index.html
  JSDemos/Demos/TreeList/ColumnHeaderFilter/AngularJS/data.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/AngularJS/index.html
  JSDemos/Demos/TreeList/ColumnHeaderFilter/AngularJS/index.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/AngularJS/styles.css
  JSDemos/Demos/TreeList/ColumnHeaderFilter/React/App.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/React/data.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/React/index.html
  JSDemos/Demos/TreeList/ColumnHeaderFilter/React/index.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/React/styles.css
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Vue/App.vue
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Vue/data.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Vue/index.html
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Vue/index.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/description.md
  JSDemos/Demos/TreeList/ColumnHeaderFilter/jQuery/data.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/jQuery/index.html
  JSDemos/Demos/TreeList/ColumnHeaderFilter/jQuery/index.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/jQuery/styles.css
  JSDemos/menuMeta.json
  JSDemos/redirects.json
  MVCDemos/Content/DemosStyles/TreeList/ColumnHeaderFilter.css
  MVCDemos/Controllers/TreeListController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/TreeList/ColumnHeaderFilter.cshtml
  NetCoreDemos/Controllers/TreeListController.cs
  NetCoreDemos/Views/TreeList/ColumnHeaderFilter.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TreeList/ColumnHeaderFilter.css
  testing/etalons/TreeList-ColumnHeaderFilter.png
Labels: cherry-pick, 23_2

#2666 TreeList - rename demo 'Using Header Filter' to 'Column Header Filter'
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Angular/app/app.component.css
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Angular/app/app.component.html
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Angular/app/app.component.ts
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Angular/app/app.service.ts
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Angular/index.html
  JSDemos/Demos/TreeList/ColumnHeaderFilter/AngularJS/data.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/AngularJS/index.html
  JSDemos/Demos/TreeList/ColumnHeaderFilter/AngularJS/index.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/AngularJS/styles.css
  JSDemos/Demos/TreeList/ColumnHeaderFilter/React/App.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/React/data.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/React/index.html
  JSDemos/Demos/TreeList/ColumnHeaderFilter/React/index.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/React/styles.css
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Vue/App.vue
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Vue/data.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Vue/index.html
  JSDemos/Demos/TreeList/ColumnHeaderFilter/Vue/index.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/description.md
  JSDemos/Demos/TreeList/ColumnHeaderFilter/jQuery/data.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/jQuery/index.html
  JSDemos/Demos/TreeList/ColumnHeaderFilter/jQuery/index.js
  JSDemos/Demos/TreeList/ColumnHeaderFilter/jQuery/styles.css
  JSDemos/menuMeta.json
  JSDemos/redirects.json
  MVCDemos/Content/DemosStyles/TreeList/ColumnHeaderFilter.css
  MVCDemos/Controllers/TreeListController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/TreeList/ColumnHeaderFilter.cshtml
  NetCoreDemos/Controllers/TreeListController.cs
  NetCoreDemos/Views/TreeList/ColumnHeaderFilter.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TreeList/ColumnHeaderFilter.css
  testing/etalons/TreeList-ColumnHeaderFilter.png
Labels: 23_1

#2672 DateRangeBox: update spaces and links to docs
  JSDemos/Demos/DateRangeBox/Overview/description.md
Labels: 23_1

#2677 Ignore azure.file.system.js Everywhere
  .gitignore
  JSDemos/shared/azure.file.system.js
Labels: 23_1

#2679 DataGrid: update the Cell Customization demo (T1175367)
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/description.md
Labels: 23_1

#2678 Ignore azure.file.system.js Everywhere
  .gitignore
  JSDemos/shared/azure.file.system.js
Labels: cherry-pick, 23_2
