Repository DevExpress/devextreme-demos, pull requests merged in 2023-07, with the labels that each got.

#2682 Renovate bot - update settings
  renovate.json
Labels: 23_2

#2658 TagBox Overview Demo: Add tagTemplate and Popover
  JSDemos/Demos/TagBox/Overview/Angular/app/app.component.css
  JSDemos/Demos/TagBox/Overview/Angular/app/app.component.html
  JSDemos/Demos/TagBox/Overview/Angular/app/app.component.ts
  JSDemos/Demos/TagBox/Overview/React/App.js
  JSDemos/Demos/TagBox/Overview/React/Tag.js
  JSDemos/Demos/TagBox/Overview/React/data.js
  JSDemos/Demos/TagBox/Overview/React/styles.css
  JSDemos/Demos/TagBox/Overview/Vue/App.vue
  JSDemos/Demos/TagBox/Overview/Vue/Tag.vue
  JSDemos/Demos/TagBox/Overview/Vue/data.js
  JSDemos/Demos/TagBox/Overview/jQuery/index.html
  JSDemos/Demos/TagBox/Overview/jQuery/index.js
  JSDemos/Demos/TagBox/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/TagBox/Overview.css
  MVCDemos/Views/TagBox/Overview.cshtml
  NetCoreDemos/Views/TagBox/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TagBox/Overview.css
  testing/etalons/TagBox-Overview.png
Labels: 23_1

#2685 TagBox Overview Demo: Add tagTemplate and Popover (#2658)
  JSDemos/Demos/TagBox/Overview/Angular/app/app.component.css
  JSDemos/Demos/TagBox/Overview/Angular/app/app.component.html
  JSDemos/Demos/TagBox/Overview/Angular/app/app.component.ts
  JSDemos/Demos/TagBox/Overview/React/App.js
  JSDemos/Demos/TagBox/Overview/React/Tag.js
  JSDemos/Demos/TagBox/Overview/React/data.js
  JSDemos/Demos/TagBox/Overview/React/styles.css
  JSDemos/Demos/TagBox/Overview/Vue/App.vue
  JSDemos/Demos/TagBox/Overview/Vue/Tag.vue
  JSDemos/Demos/TagBox/Overview/Vue/data.js
  JSDemos/Demos/TagBox/Overview/jQuery/index.html
  JSDemos/Demos/TagBox/Overview/jQuery/index.js
  JSDemos/Demos/TagBox/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/TagBox/Overview.css
  MVCDemos/Views/TagBox/Overview.cshtml
  NetCoreDemos/Views/TagBox/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TagBox/Overview.css
  testing/etalons/TagBox-Overview.png
Labels: cherry-pick, 23_2

#2688 DataGrid - Filter Panel - Fix warnings in frameworks
  JSDemos/Demos/DataGrid/FilterPanel/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/FilterPanel/React/App.js
  JSDemos/Demos/DataGrid/FilterPanel/Vue/App.vue
Labels: 23_2

#2696 Add SelectBoxEditingController for SelectBox demo to SearchAndEditing
  JSDemos/menuMeta.json
Labels: 23_1

#2703 CI: Fix workflows after devextreme has been converted to monorepo
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
Labels: 23_2

#2698 Add SelectBoxEditingController for SelectBox demo to SearchAndEditing
  JSDemos/menuMeta.json
Labels: cherry-pick, 23_2

#2708 Menu: delimiter beetween root menu item and submenu should be positioned correctly (T1174356)
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_1_desktop.png
Labels: cherry-pick, 23_1

#2710 Menu: delimiter beetween root menu item and submenu should be positioned correctly (T1174356)
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_3_desktop.png
Labels: 23_2

#2707 Menu: delimiter beetween root menu item and submenu should be positioned correctly (T1174356)
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_3_desktop.png
Labels: 22_2

#2717 Menu: delimiter beetween root menu item and submenu should be positioned correctly (T1174356)
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_1_desktop.png
Labels: force all tests, 23_2

#2715 CI: Fix angular building
  .github/workflows/visual_tests_frameworks.yml
Labels: 23_2

#2720 HtmlEditor: fix `getModule` naming (#2719)
  JSDemos/Demos/HtmlEditor/Tables/description.md
Labels: cherry-pick, 23_2

#2721 CI: Use stable 18.16.1 node version
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
Labels: force all tests, 23_2

#2694 Remove all badges
  JSDemos/menuMeta.json
Labels: 23_2

#2725 HtmlEditor: add tabindex to scrollable div in Output Formats demo
  JSDemos/Demos/HtmlEditor/OutputFormats/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/OutputFormats/React/App.js
  JSDemos/Demos/HtmlEditor/OutputFormats/Vue/App.vue
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/index.html
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
Labels: 23_2

#2726 HtmlEditor: add tabindex to message cards in Mentions demo
  JSDemos/Demos/HtmlEditor/Mentions/Angular/app/app.component.html
  JSDemos/Demos/HtmlEditor/Mentions/React/App.js
  JSDemos/Demos/HtmlEditor/Mentions/Vue/App.vue
  JSDemos/Demos/HtmlEditor/Mentions/jQuery/index.html
  MVCDemos/Views/HtmlEditor/Mentions.cshtml
  NetCoreDemos/Views/HtmlEditor/Mentions.cshtml
Labels: 23_2

#2732 Button: update etalons with disabled state
  testing/etalons/Button-Icons.png
  testing/etalons/Gantt-ExportToPDF.png
  testing/etalons/Gantt-Overview.png
  testing/etalons/Gantt-Toolbar.png
Labels: 23_2

#2737 DataGrid - Update etalons for failing tests: batch editing, filtering by range
  testing/widgets/datagrid/etalons/datagrid_batch_editing_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_1_desktop.png
Labels: 23_2

#2734 Revert "CI: Fix angular building (#2715)"
  .github/workflows/visual_tests_frameworks.yml
Labels: 23_2
