Repository DevExpress/devextreme-demos, pull requests merged in 2023-08, with the labels that each got.

#2740 Tabs/TabPanel: Fix tab styling && Update etalon
  JSDemos/Demos/TabPanel/SortableClosableTabs/Angular/app/app.component.css
  JSDemos/Demos/TabPanel/SortableClosableTabs/React/styles.css
  JSDemos/Demos/TabPanel/SortableClosableTabs/Vue/App.vue
  JSDemos/Demos/TabPanel/SortableClosableTabs/jQuery/styles.css
  MVCDemos/Content/DemosStyles/TabPanel/SortableClosableTabs.css
  NetCoreDemos/wwwroot/css/DemosStyles/TabPanel/SortableClosableTabs.css
  testing/etalons/Tabs-Overview.png
Labels: 23_2

#2742 Fix "subscribe" Deprecate
  JSDemos/Demos/Diagram/Adaptability/Angular/app/app.component.ts
  JSDemos/Demos/Diagram/Containers/Angular/app/app.component.ts
  JSDemos/Demos/Diagram/CustomShapesWithIcons/Angular/app/app.component.ts
  JSDemos/Demos/Diagram/CustomShapesWithTexts/Angular/app/app.component.ts
  JSDemos/Demos/Diagram/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Diagram/ReadOnly/Angular/app/app.component.ts
  JSDemos/Demos/Diagram/UICustomization/Angular/app/app.component.ts
Labels: 23_2

#2723 Typescript to Javascript demos conversion tool
  .eslintrc.js
  .github/workflows/lint.yml
  JSDemos/configs/React/config.js
  package-lock.json
  package.json
  testing/common.test.js
  tsconfig.json
  utils/ts-to-js-converter/cli.ts
  utils/ts-to-js-converter/converter.ts
  utils/ts-to-js-converter/types.ts
Labels: 23_2

#2745 DropDownButton: fix action button paddings
  testing/etalons/DataGrid-ExcelJSOverview.png
  testing/etalons/DataGrid-PDFOverview.png
  testing/etalons/DropDownButton-Overview.png
  testing/etalons/Toolbar-Adaptability.png
  testing/widgets/toolbar/etalons/toolbar_multiline_mode_minimize.png
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_menu_open.png
Labels: force all tests, 23_2

#2749 Delete React links from descriptions
  JSDemos/Demos/Charts/Overview/React/description.md
  JSDemos/Demos/Common/ActionAndListsOverview/React/description.md
  JSDemos/Demos/Common/DialogsAndNotificationsOverview/React/description.md
  JSDemos/Demos/Common/EditorsOverview/React/description.md
  JSDemos/Demos/Common/EditorsRightToLeftSupport/React/description.md
  JSDemos/Demos/Common/FormsAndMultiPurposeOverview/React/description.md
  JSDemos/Demos/DataGrid/EditStateManagement/React/description.md
  JSDemos/Demos/DataGrid/Overview/React/description.md
  JSDemos/Demos/Gauges/Overview/React/description.md
  JSDemos/Demos/PivotGrid/Overview/React/description.md
  JSDemos/Demos/Scheduler/Overview/React/description.md
  JSDemos/Demos/TreeList/Overview/React/description.md
  JSDemos/Demos/VectorMap/Overview/React/description.md
Labels: 23_2

#2744 Accessibility: DataGrid - Fix non-contrasting column headers
  testing/etalons/DataGrid-Column3RdPartyEngineTemplate.png
  testing/etalons/DataGrid-ColumnTemplate.png
  testing/etalons/DataGrid-ExcelJSExportImages.png
  testing/etalons/DataGrid-FilterPanel.png
  testing/etalons/DataGrid-GridAdaptabilityOverview.png
  testing/etalons/DataGrid-PDFExportImages.png
  testing/etalons/DataGrid-RealTimeUpdates.png
  testing/etalons/DataGrid-RowSelection.png
  testing/etalons/DataGrid-RowTemplate.png
  testing/etalons/TreeList-ColumnHeaderFilter.png
  testing/etalons/TreeList-FilterPanel.png
  testing/widgets/datagrid/etalons/datagrid_batch_update_request_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_1_desktop.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_3_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_5_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_3_desktop.png
  testing/widgets/datagrid/etalons/datagrid_filtering_by_range_4_desktop.png
Labels: 23_2

#2751 Tabs, TabPanel: Update etalons
  testing/etalons/Common-NavigationOverview.png
  testing/etalons/DataGrid-ExcelJSExportMultipleGrids.png
  testing/etalons/DataGrid-PDFExportMultipleGrids.png
  testing/etalons/Form-GroupedFields.png
  testing/etalons/TabPanel-Overview.png
  testing/etalons/TabPanel-SortableClosableTabs.png
  testing/etalons/Tabs-Overview.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_3_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_5_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_6_desktop.png
Labels: 23_2

#2753 CI: Use stable 18.16.1 node version (#2721)
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
Labels: cherry-pick, 23_1

#2756 Gantt Overview: add getting started link (#2752)
  JSDemos/Demos/Gantt/Overview/description.md
Labels: cherry-pick, 23_2

#2759 Tab/TabPanel, Map: Replace etalons && Add mask
  testing/etalons/DataGrid-ExcelJSExportMultipleGrids.png
  testing/etalons/DataGrid-PDFExportMultipleGrids.png
  testing/etalons/Form-GroupedFields.png
  testing/etalons/Map-Markers_mask.png
  testing/etalons/Map-Routes_mask.png
  testing/etalons/Tabs-Overview.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_3_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_5_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_6_desktop.png
Labels: 23_2

#2724 DataGrid/PivotGrid - Export demos: Remove e.cancel in the onExporting function
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/jQuery/index.js
  JSDemos/Demos/DataGrid/ExcelJSExportImages/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSExportImages/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSExportImages/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSExportImages/jQuery/index.js
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/jQuery/index.js
  JSDemos/Demos/DataGrid/ExcelJSOverview/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSOverview/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSOverview/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSOverview/jQuery/index.js
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/jQuery/index.js
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJSOverview/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJSOverview/jQuery/index.js
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/jQuery/index.js
  MVCDemos/Views/DataGrid/ExcelJSCellCustomization.cshtml
  MVCDemos/Views/DataGrid/ExcelJSExportImages.cshtml
  MVCDemos/Views/DataGrid/ExcelJSHeaderAndFooter.cshtml
  MVCDemos/Views/DataGrid/ExcelJSOverview.cshtml
  MVCDemos/Views/PivotGrid/ExcelJSCellCustomization.cshtml
  MVCDemos/Views/PivotGrid/ExcelJSHeaderAndFooter.cshtml
  MVCDemos/Views/PivotGrid/ExcelJSOverview.cshtml
  NetCoreDemos/Views/DataGrid/ExcelJSCellCustomization.cshtml
  NetCoreDemos/Views/DataGrid/ExcelJSExportImages.cshtml
  NetCoreDemos/Views/DataGrid/ExcelJSHeaderAndFooter.cshtml
  NetCoreDemos/Views/DataGrid/ExcelJSOverview.cshtml
  NetCoreDemos/Views/PivotGrid/ExcelJSCellCustomization.cshtml
  NetCoreDemos/Views/PivotGrid/ExcelJSOverview.cshtml
  NetCoreDemos/Views/PivotGrid/ExcelJsHeaderAndFooter.cshtml
Labels: 23_1

#2762 Convert react gauges demos to functionality
  JSDemos/Demos/Gauges/AnglesCustomization/React/App.js
  JSDemos/Demos/Gauges/BaseValueForRangeBar/React/App.js
  JSDemos/Demos/Gauges/CustomLayout/React/App.js
  JSDemos/Demos/Gauges/CustomLayoutLinearGauge/React/App.js
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypes/React/App.js
  JSDemos/Demos/Gauges/DifferentSubvalueIndicatorTypesLinearGauge/React/App.js
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypes/React/App.js
  JSDemos/Demos/Gauges/DifferentValueIndicatorTypesLinearGauge/React/App.js
  JSDemos/Demos/Gauges/GaugeTitleCustomized/React/App.js
  JSDemos/Demos/Gauges/GaugeTooltip/React/App.js
  JSDemos/Demos/Gauges/LabelsCustomization/React/App.js
  JSDemos/Demos/Gauges/Overview/React/App.js
  JSDemos/Demos/Gauges/Palette/React/App.js
  JSDemos/Demos/Gauges/PaletteForRanges/React/App.js
  JSDemos/Demos/Gauges/ScaleCustomTickInterval/React/App.js
  JSDemos/Demos/Gauges/ScaleCustomTickValues/React/App.js
  JSDemos/Demos/Gauges/ScaleLabelFormatting/React/App.js
  JSDemos/Demos/Gauges/ScaleMinorTicks/React/App.js
  JSDemos/Demos/Gauges/SubvalueIndicatorTextFormatting/React/App.js
  JSDemos/Demos/Gauges/Tooltip/React/App.js
  JSDemos/Demos/Gauges/UpdateBarGaugeDataAtRuntime/React/App.js
  JSDemos/Demos/Gauges/UpdateCircularGaugeDataAtRuntime/React/App.js
  JSDemos/Demos/Gauges/UpdateLinearGaugeDataAtRuntime/React/App.js
  JSDemos/Demos/Gauges/ValueIndicatorsAPI/React/App.js
  JSDemos/Demos/Gauges/VariableNumberOfBars/React/App.js
  JSDemos/Demos/Gauges/VariableNumberOfSubvalueIndicators/React/App.js
Labels: 23_2

#2763 DataGrid/PivotGrid - Export demos: Remove e.cancel in the onExporting function
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/jQuery/index.js
  JSDemos/Demos/DataGrid/ExcelJSExportImages/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSExportImages/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSExportImages/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSExportImages/jQuery/index.js
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/jQuery/index.js
  JSDemos/Demos/DataGrid/ExcelJSOverview/Angular/app/app.component.ts
  JSDemos/Demos/DataGrid/ExcelJSOverview/React/App.js
  JSDemos/Demos/DataGrid/ExcelJSOverview/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSOverview/jQuery/index.js
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/jQuery/index.js
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJSOverview/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJSOverview/jQuery/index.js
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/jQuery/index.js
  MVCDemos/Views/DataGrid/ExcelJSCellCustomization.cshtml
  MVCDemos/Views/DataGrid/ExcelJSExportImages.cshtml
  MVCDemos/Views/DataGrid/ExcelJSHeaderAndFooter.cshtml
  MVCDemos/Views/DataGrid/ExcelJSOverview.cshtml
  MVCDemos/Views/PivotGrid/ExcelJSCellCustomization.cshtml
  MVCDemos/Views/PivotGrid/ExcelJSHeaderAndFooter.cshtml
  MVCDemos/Views/PivotGrid/ExcelJSOverview.cshtml
  NetCoreDemos/Views/DataGrid/ExcelJSCellCustomization.cshtml
  NetCoreDemos/Views/DataGrid/ExcelJSExportImages.cshtml
  NetCoreDemos/Views/DataGrid/ExcelJSHeaderAndFooter.cshtml
  NetCoreDemos/Views/DataGrid/ExcelJSOverview.cshtml
  NetCoreDemos/Views/PivotGrid/ExcelJSCellCustomization.cshtml
  NetCoreDemos/Views/PivotGrid/ExcelJSOverview.cshtml
  NetCoreDemos/Views/PivotGrid/ExcelJsHeaderAndFooter.cshtml
Labels: cherry-pick, 23_2

#2764 Skip test: Charts-PieWithCustomStyles
  JSDemos/Demos/Charts/PieWithCustomStyles/visualtestrc.json
Labels: force all tests, 23_2

#2754 Accessibility: DataGrid - Fix non-contrasting pager info
  testing/widgets/datagrid/etalons/datagrid_record_paging_2_desktop.png
Labels: 23_2

#2760 Sync changes from hg
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Web.config
  MVCDemos/packages.config
  NetCoreDemos/bundleconfig.json
Labels: 23_2

#2766 Scheduler(T1180373): Add R1 templates test for all platforms.
  testing/widgets/scheduler/cellTemplates.test.js
  testing/widgets/scheduler/etalons/scheduler_CellTemplates_view_dates_changed.png
Labels: 23_2

#2773 Scheduler(T1180373): Add R1 templates test for all platforms. (#2766)
  testing/widgets/scheduler/cellTemplates.test.js
  testing/widgets/scheduler/etalons/scheduler_CellTemplates_view_dates_changed.png
Labels: cherry-pick, 23_1

#2774 ButtonGroup: redesign contained mode
  testing/etalons/ButtonGroup-Overview.png
  testing/etalons/DropDownButton-Overview.png
  testing/etalons/HtmlEditor-OutputFormats.png
  testing/etalons/Scheduler-Adaptability.png
  testing/etalons/Scheduler-Agenda.png
  testing/etalons/Scheduler-AllDayPanelMode.png
  testing/etalons/Scheduler-BasicViews.png
  testing/etalons/Scheduler-CellTemplates.png
  testing/etalons/Scheduler-ContextMenuIntegration.png
  testing/etalons/Scheduler-CurrentTimeIndicator.png
  testing/etalons/Scheduler-CustomDragAndDrop.png
  testing/etalons/Scheduler-CustomTemplates.png
  testing/etalons/Scheduler-CustomizeIndividualViews.png
  testing/etalons/Scheduler-Editing.png
  testing/etalons/Scheduler-GoogleCalendarIntegration.png
  testing/etalons/Scheduler-GroupByDate.png
  testing/etalons/Scheduler-GroupOrientation.png
  testing/etalons/Scheduler-IncreaseViewDuration.png
  testing/etalons/Scheduler-LimitAppointmentCountPerCell.png
  testing/etalons/Scheduler-Overview.png
  testing/etalons/Scheduler-RecurringAppointments.png
  testing/etalons/Scheduler-Resources.png
  testing/etalons/Scheduler-SignalRService.png
  testing/etalons/Scheduler-SimpleArray.png
  testing/etalons/Scheduler-TimeZonesSupport.png
  testing/etalons/Scheduler-Timelines.png
  testing/etalons/Scheduler-VirtualScrolling.png
  testing/etalons/Scheduler-WebAPIService.png
  testing/etalons/Toolbar-Adaptability.png
  testing/widgets/scheduler/etalons/scheduler_CellTemplates_month_view.png
  testing/widgets/scheduler/etalons/scheduler_CellTemplates_view_dates_changed.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_cell_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_header_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_init.png
  testing/widgets/scheduler/etalons/scheduler_overview_selection.png
  testing/widgets/toolbar/etalons/toolbar_multiline_mode_minimize.png
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_init.png
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_menu_open.png
Labels: 23_2

#2777 Accessibility: TreeList - Update etalon to fix a contrast issue
  testing/etalons/TreeList-Overview.png
Labels: force all tests, 23_2

#2781 Lookup: unify styles for placeholder
  JSDemos/Demos/Lookup/Templates/Angular/app/app.component.css
  JSDemos/Demos/Lookup/Templates/AngularJS/styles.css
  JSDemos/Demos/Lookup/Templates/React/styles.css
  JSDemos/Demos/Lookup/Templates/Vue/App.vue
  JSDemos/Demos/Lookup/Templates/Vue/FieldItem.vue
  JSDemos/Demos/Lookup/Templates/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Lookup/Templates.css
  NetCoreDemos/wwwroot/css/DemosStyles/Lookup/Templates.css
  testing/etalons/Lookup-Templates.png
Labels: force all tests, 23_2

#2783 Disable bundle minification in Core demos
  NetCoreDemos/bundleconfig.json
Labels: 23_1

#2784 Disable bundle minification in Core demos
  NetCoreDemos/bundleconfig.json
Labels: 22_2

#2778 New etalons (T1181477)
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop_mask.png
Labels: 23_2

#2790 CI: Do not build generators
  .github/workflows/visual_tests_frameworks.yml
Labels: 23_2

#2750 CRLF -> LF
  .github/workflows/lint.yml
  MVCDemos/Models/MedalAnnotationInfo.cs
  MVCDemos/Models/SampleData/IceHockeyGoldMedalistsData.cs
  MVCDemos/Models/SampleData/MedalAnnotations.cs
  MVCDemos/Views/Charts/PieWithAnnotations.cshtml
  MVCDemos/Views/Diagram/OperationRestrictions.cshtml
  MVCDemos/Views/Diagram/WebAPIService.cshtml
  NetCoreDemos/Controllers/ApiControllers/DiagramEmployeesController.cs
  NetCoreDemos/Models/MedalAnnotationInfo.cs
  NetCoreDemos/Models/SampleData/IceHockeyGoldMedalistsData.cs
  NetCoreDemos/Models/SampleData/MedalAnnotations.cs
  NetCoreDemos/Views/Charts/PieWithAnnotations.cshtml
  NetCoreDemos/Views/Diagram/OperationRestrictions.cshtml
  NetCoreDemos/Views/Diagram/WebAPIService.cshtml
  NetCoreDemos/wwwroot/Descr/Diagram/CustomShapesWithTemplatesWithEditing.md
  NetCoreDemos/wwwroot/css/DemosStyles/Charts/PieWithAnnotations.css
Labels: 23_2

#2794 Restore cache into npm cache directory
  .github/actions/restore-npm-cache/action.yml
  .github/workflows/visual_tests_frameworks.yml
Labels: 22_2

#2796 CI: Pin chrome version
  .github/actions/pin-browsers/action.yml
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
Labels: 22_2

#2789 New etalons (T1181477)
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop_mask.png
Labels: cherry-pick, 22_2

#2787 New etalons (T1181477)
  testing/widgets/datagrid/etalons/datagrid_batch_editing_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop_mask.png
Labels: cherry-pick, 23_1

#2797 Ts to Js lang switcher
  index.html
Labels: 23_2

#2795 dxScheduler - fix header and footer margin
  testing/etalons/Scheduler-Adaptability.png
  testing/etalons/Scheduler-AllDayPanelMode.png
  testing/etalons/Scheduler-CellTemplates.png
  testing/etalons/Scheduler-ContextMenuIntegration.png
  testing/etalons/Scheduler-CurrentTimeIndicator.png
  testing/etalons/Scheduler-CustomDragAndDrop.png
  testing/etalons/Scheduler-CustomTemplates.png
  testing/etalons/Scheduler-CustomizeIndividualViews.png
  testing/etalons/Scheduler-Editing.png
  testing/etalons/Scheduler-GoogleCalendarIntegration.png
  testing/etalons/Scheduler-GroupByDate.png
  testing/etalons/Scheduler-GroupOrientation.png
  testing/etalons/Scheduler-IncreaseViewDuration.png
  testing/etalons/Scheduler-LimitAppointmentCountPerCell.png
  testing/etalons/Scheduler-Overview.png
  testing/etalons/Scheduler-RecurringAppointments.png
  testing/etalons/Scheduler-Resources.png
  testing/etalons/Scheduler-SimpleArray.png
  testing/etalons/Scheduler-TimeZonesSupport.png
  testing/etalons/Scheduler-Timelines.png
  testing/etalons/Scheduler-VirtualScrolling.png
  testing/widgets/scheduler/etalons/scheduler_CellTemplates_view_dates_changed.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_cell_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_header_click.png
  testing/widgets/scheduler/etalons/scheduler_contextMenu_init.png
  testing/widgets/scheduler/etalons/scheduler_overview_selection.png
Labels: 23_2

#2803 Menu: screenshots updated
  testing/etalons/FileManager-AzureClientBinding.png
  testing/etalons/FileManager-AzureServerBinding.png
  testing/etalons/FileManager-BindingToEF.png
  testing/etalons/FileManager-BindingToFileSystem.png
  testing/etalons/FileManager-BindingToHierarchicalStructure.png
  testing/etalons/FileManager-CustomThumbnails.png
  testing/etalons/FileManager-Overview.png
  testing/etalons/FileManager-UICustomization.png
Labels: cherry-pick, 23_1

#2801 Fix visual tests failures due to build timeout
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
Labels: 23_2

#2807 Button: delete 'back' type from Predefined Types demo description
  JSDemos/Demos/Button/PredefinedTypes/description.md
Labels: 23_2

#2809 Using local devextreme dist for running aspnet demos
  README.md
  gulpfile.js/aspnet.js
  gulpfile.js/copy-common-asp-files.js
Labels: 23_2
