Repository DevExpress/devextreme-demos, pull requests merged in 2023-11, with the labels that each got.

#2954 Map: update mask to cover whole map
  testing/etalons/Map-Markers_mask.png
Labels: 23_2

#2962 DEMOS: showBorders set to true in 'SingleSelection' demo and padding for label changed in 'Menu overview' demo
  JSDemos/Demos/DropDownBox/SingleSelection/Angular/app/app.component.html
  JSDemos/Demos/DropDownBox/SingleSelection/React/App.tsx
  JSDemos/Demos/DropDownBox/SingleSelection/ReactJs/App.js
  JSDemos/Demos/DropDownBox/SingleSelection/Vue/App.vue
  JSDemos/Demos/DropDownBox/SingleSelection/jQuery/index.js
  JSDemos/Demos/Menu/Overview/Angular/app/app.component.css
  JSDemos/Demos/Menu/Overview/React/styles.css
  JSDemos/Demos/Menu/Overview/Vue/App.vue
  JSDemos/Demos/Menu/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Menu/Overview.css
  MVCDemos/Views/DropDownBox/SingleSelection.cshtml
  NetCoreDemos/Views/DropDownBox/SingleSelection.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Menu/Overview.css
  testing/etalons/Menu-Overview.png
Labels: 23_2

#2964 DRB Demo: add disableOutOfRangeSelection property demonstration
  JSDemos/Demos/DateRangeBox/Overview/Angular/app/app.component.html
  JSDemos/Demos/DateRangeBox/Overview/React/App.tsx
  JSDemos/Demos/DateRangeBox/Overview/ReactJs/App.js
  JSDemos/Demos/DateRangeBox/Overview/Vue/App.vue
  JSDemos/Demos/DateRangeBox/Overview/jQuery/index.html
  JSDemos/Demos/DateRangeBox/Overview/jQuery/index.js
  MVCDemos/Views/DateRangeBox/Overview.cshtml
  NetCoreDemos/Views/DateRangeBox/Overview.cshtml
  testing/etalons/DateRangeBox-Overview.png
Labels: 23_2

#2963 CI: Run lint tasks on changed files
  .github/workflows/visual_tests_frameworks.yml
  utils/eslint-runner.ts
Labels: 23_2

#2949 🎨 Fluent: Redesign FilterBuilder Demo group
  JSDemos/Demos/FilterBuilder/Customization/Angular/app/app.component.css
  JSDemos/Demos/FilterBuilder/Customization/React/styles.css
  JSDemos/Demos/FilterBuilder/Customization/Vue/App.vue
  JSDemos/Demos/FilterBuilder/Customization/jQuery/styles.css
  JSDemos/Demos/FilterBuilder/WithDataGrid/Angular/app/app.component.css
  JSDemos/Demos/FilterBuilder/WithDataGrid/React/styles.css
  JSDemos/Demos/FilterBuilder/WithDataGrid/Vue/App.vue
  JSDemos/Demos/FilterBuilder/WithDataGrid/jQuery/styles.css
  JSDemos/Demos/FilterBuilder/WithList/Angular/app/app.component.css
  JSDemos/Demos/FilterBuilder/WithList/React/styles.css
  JSDemos/Demos/FilterBuilder/WithList/Vue/App.vue
  JSDemos/Demos/FilterBuilder/WithList/jQuery/styles.css
  MVCDemos/Content/DemosStyles/FilterBuilder/Customization.css
  MVCDemos/Content/DemosStyles/FilterBuilder/WithDataGrid.css
  MVCDemos/Content/DemosStyles/FilterBuilder/WithList.css
  NetCoreDemos/wwwroot/css/DemosStyles/FilterBuilder/Customization.css
  NetCoreDemos/wwwroot/css/DemosStyles/FilterBuilder/WithDataGrid.css
  NetCoreDemos/wwwroot/css/DemosStyles/FilterBuilder/WithList.css
  testing/etalons/FilterBuilder-Customization.png
  testing/etalons/FilterBuilder-WithDataGrid.png
  testing/etalons/FilterBuilder-WithList.png
Labels: 23_2

#2958 Form GroupedFields: update header styles
  JSDemos/Demos/Form/GroupedFields/Angular/app/app.component.css
  JSDemos/Demos/Form/GroupedFields/React/styles.css
  JSDemos/Demos/Form/GroupedFields/Vue/App.vue
  JSDemos/Demos/Form/GroupedFields/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Form/GroupedFields.css
  NetCoreDemos/wwwroot/css/DemosStyles/Form/GroupedFields.css
  testing/etalons/Form-GroupedFields.png
Labels: 23_2

#2968 ProgressBar: update padding
  JSDemos/Demos/ProgressBar/Overview/Angular/app/app.component.css
  JSDemos/Demos/ProgressBar/Overview/React/styles.css
  JSDemos/Demos/ProgressBar/Overview/Vue/App.vue
  JSDemos/Demos/ProgressBar/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/ProgressBar/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/ProgressBar/Overview.css
  testing/etalons/ProgressBar-Overview.png
Labels: 23_2

#2974 CI: Lint all files if changed config or workflow
  utils/eslint-runner.ts
Labels: 23_2

#2831 Add workflow for build aspnet demos
  .github/workflows/build-aspnet.yml
Labels: 23_2

#2966 Make check for known license warnings less strict
  testing/known-warnings.json
Labels: 23_2

#2976 CI: Add vue to eslint patterns and enable logging
  .github/workflows/visual_tests_frameworks.yml
  utils/eslint-runner.ts
Labels: 23_2

#2950 PivotGrid - Vue - add ts
  JSDemos/Demos/PivotGrid/ChartIntegration/Vue/App.vue
  JSDemos/Demos/PivotGrid/ChartIntegration/Vue/data.ts
  JSDemos/Demos/PivotGrid/DrillDown/Vue/App.vue
  JSDemos/Demos/PivotGrid/DrillDown/Vue/data.ts
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/Vue/data.ts
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJSOverview/Vue/data.ts
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Vue/App.vue
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Vue/data.ts
  JSDemos/Demos/PivotGrid/FieldPanel/Vue/App.vue
  JSDemos/Demos/PivotGrid/FieldPanel/Vue/data.ts
  JSDemos/Demos/PivotGrid/Overview/Vue/App.vue
  JSDemos/Demos/PivotGrid/Overview/Vue/data.ts
  JSDemos/Demos/PivotGrid/RunningTotals/Vue/App.vue
  JSDemos/Demos/PivotGrid/RunningTotals/Vue/data.ts
  JSDemos/Demos/PivotGrid/SimpleArray/Vue/App.vue
  JSDemos/Demos/PivotGrid/SimpleArray/Vue/data.ts
  JSDemos/Demos/PivotGrid/StandaloneFieldChooser/Vue/App.vue
  JSDemos/Demos/PivotGrid/StandaloneFieldChooser/Vue/data.ts
  JSDemos/Demos/PivotGrid/StatePersistence/Vue/App.vue
  JSDemos/Demos/PivotGrid/StatePersistence/Vue/data.ts
  JSDemos/Demos/PivotGrid/SummaryDisplayModes/Vue/App.vue
  JSDemos/Demos/PivotGrid/SummaryDisplayModes/Vue/data.ts
  JSDemos/Demos/PivotGrid/VirtualScrolling/Vue/App.vue
  JSDemos/Demos/PivotGrid/VirtualScrolling/Vue/data.ts
  JSDemos/Demos/PivotGrid/WebAPIService/Vue/App.vue
Labels: 23_2

#2959 TreeView: Fix left padding content in List
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Angular/app/app.component.css
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/AngularJS/styles.css
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/React/styles.css
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Vue/App.vue
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/jQuery/index.js
  JSDemos/Demos/TreeView/ItemSelectionAndCustomization/jQuery/styles.css
  MVCDemos/Content/DemosStyles/TreeView/ItemSelectionAndCustomization.css
  NetCoreDemos/wwwroot/css/DemosStyles/TreeView/ItemSelectionAndCustomization.css
  testing/widgets/treeview/ItemSelectionAndCustomization.test.js
  testing/widgets/treeview/etalons/treeview_selection_field_is_open.png
Labels: 23_2

#2955 TextArea: Add text area paddings
  JSDemos/Demos/TextArea/Overview/Angular/app/app.component.css
  JSDemos/Demos/TextArea/Overview/Angular/app/app.component.html
  JSDemos/Demos/TextArea/Overview/React/App.tsx
  JSDemos/Demos/TextArea/Overview/React/styles.css
  JSDemos/Demos/TextArea/Overview/ReactJs/App.js
  JSDemos/Demos/TextArea/Overview/ReactJs/styles.css
  JSDemos/Demos/TextArea/Overview/Vue/App.vue
  JSDemos/Demos/TextArea/Overview/jQuery/index.html
  JSDemos/Demos/TextArea/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/TextArea/Overview.css
  MVCDemos/Views/TextArea/Overview.cshtml
  NetCoreDemos/Views/TextArea/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TextArea/Overview.css
  testing/etalons/TextArea-Overview.png
Labels: 23_2

#2969 TextEditor: 'outside' label should be aligned when before buttons used and input should be focused after label click
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_floating_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_floating_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_hidden_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_hidden_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_outside_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_outside_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_static_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_static_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_floating_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_floating_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_hidden_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_hidden_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_outside_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_outside_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_static_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_static_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_floating_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_floating_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_hidden_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_hidden_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_outside_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_outside_desktop_mask.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_static_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_static_desktop_mask.png
Labels: 23_2

#2967 Lookup Templates: make both editors have the same height
  JSDemos/Demos/Lookup/Templates/Angular/app/app.component.css
  JSDemos/Demos/Lookup/Templates/React/styles.css
  JSDemos/Demos/Lookup/Templates/Vue/App.vue
  JSDemos/Demos/Lookup/Templates/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Lookup/Templates.css
  NetCoreDemos/wwwroot/css/DemosStyles/Lookup/Templates.css
Labels: 23_2

#2952 Editors: use eye icon and delete png eye
  JSDemos/Demos/Common/CustomTextEditorButtons/Angular/app/app.component.ts
  JSDemos/Demos/Common/CustomTextEditorButtons/AngularJS/index.html
  JSDemos/Demos/Common/CustomTextEditorButtons/React/App.tsx
  JSDemos/Demos/Common/CustomTextEditorButtons/ReactJs/App.js
  JSDemos/Demos/Common/CustomTextEditorButtons/Vue/App.vue
  JSDemos/Demos/Common/CustomTextEditorButtons/jQuery/index.js
  JSDemos/Demos/Form/Validation/AngularJS/index.js
  JSDemos/Demos/Validation/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Validation/Overview/AngularJS/index.js
  JSDemos/Demos/Validation/Overview/React/App.tsx
  JSDemos/Demos/Validation/Overview/ReactJs/App.js
  JSDemos/Demos/Validation/Overview/Vue/App.vue
  JSDemos/Demos/Validation/Overview/jQuery/index.js
  JSDemos/images/icons/eye.png
  MVCDemos/Content/images/icons/eye.png
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/Common/CustomTextEditorButtons.cshtml
  MVCDemos/Views/Validation/Overview.cshtml
  NetCoreDemos/Views/Common/CustomTextEditorButtons.cshtml
  NetCoreDemos/Views/Validation/Overview.cshtml
  NetCoreDemos/wwwroot/images/icons/eye.png
  testing/etalons/Common-CustomTextEditorButtons.png
  testing/etalons/Map-Routes_mask.png
  testing/etalons/Validation-Overview.png
Labels: 23_2

#2980 Editor Appearance Variants - show validation message on the left of states SelectBox
  JSDemos/Demos/Common/EditorAppearanceVariants/Angular/app/app.component.html
  JSDemos/Demos/Common/EditorAppearanceVariants/React/App.tsx
  JSDemos/Demos/Common/EditorAppearanceVariants/ReactJs/App.js
  JSDemos/Demos/Common/EditorAppearanceVariants/Vue/App.vue
  JSDemos/Demos/Common/EditorAppearanceVariants/jQuery/index.js
  MVCDemos/Views/Common/EditorAppearanceVariants.cshtml
  NetCoreDemos/Views/Common/EditorAppearanceVariants.cshtml
Labels: 23_2

#2961 Scheduler Vue: add types
  JSDemos/Demos/Scheduler/Adaptability/Vue/App.vue
  JSDemos/Demos/Scheduler/Adaptability/Vue/data.ts
  JSDemos/Demos/Scheduler/Agenda/Vue/App.vue
  JSDemos/Demos/Scheduler/Agenda/Vue/data.ts
  JSDemos/Demos/Scheduler/AllDayPanelMode/Vue/App.vue
  JSDemos/Demos/Scheduler/AllDayPanelMode/Vue/data.ts
  JSDemos/Demos/Scheduler/BasicViews/Vue/App.vue
  JSDemos/Demos/Scheduler/BasicViews/Vue/data.ts
  JSDemos/Demos/Scheduler/CellTemplates/Vue/App.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/DataCell.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/DateCell.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/TimeCell.vue
  JSDemos/Demos/Scheduler/CellTemplates/Vue/data.ts
  JSDemos/Demos/Scheduler/CellTemplates/Vue/utils.ts
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/App.vue
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Vue/data.ts
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/Vue/App.vue
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/Vue/AppointmentTemplate.vue
  JSDemos/Demos/Scheduler/CurrentTimeIndicator/Vue/data.ts
  JSDemos/Demos/Scheduler/CustomDragAndDrop/Vue/App.vue
  JSDemos/Demos/Scheduler/CustomDragAndDrop/Vue/data.ts
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/App.vue
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/AppointmentTemplate.vue
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/AppointmentTooltipTemplate.vue
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/data.ts
  JSDemos/Demos/Scheduler/CustomizeIndividualViews/Vue/App.vue
  JSDemos/Demos/Scheduler/CustomizeIndividualViews/Vue/data.ts
  JSDemos/Demos/Scheduler/Editing/Vue/App.vue
  JSDemos/Demos/Scheduler/Editing/Vue/data.ts
  JSDemos/Demos/Scheduler/GroupByDate/Vue/App.vue
  JSDemos/Demos/Scheduler/GroupByDate/Vue/data.ts
  JSDemos/Demos/Scheduler/GroupOrientation/Vue/App.vue
  JSDemos/Demos/Scheduler/GroupOrientation/Vue/data.ts
  JSDemos/Demos/Scheduler/IncreaseViewDuration/Vue/App.vue
  JSDemos/Demos/Scheduler/IncreaseViewDuration/Vue/data.ts
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Vue/App.vue
  JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Vue/data.ts
  JSDemos/Demos/Scheduler/Overview/Vue/App.vue
  JSDemos/Demos/Scheduler/Overview/Vue/data.ts
  JSDemos/Demos/Scheduler/RecurringAppointments/Vue/App.vue
  JSDemos/Demos/Scheduler/RecurringAppointments/Vue/data.ts
  JSDemos/Demos/Scheduler/Resources/Vue/App.vue
  JSDemos/Demos/Scheduler/Resources/Vue/data.ts
  JSDemos/Demos/Scheduler/SimpleArray/Vue/App.vue
  JSDemos/Demos/Scheduler/SimpleArray/Vue/data.ts
  JSDemos/Demos/Scheduler/TimeZonesSupport/Vue/App.vue
  JSDemos/Demos/Scheduler/TimeZonesSupport/Vue/data.ts
  JSDemos/Demos/Scheduler/Timelines/Vue/App.vue
  JSDemos/Demos/Scheduler/Timelines/Vue/data.ts
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/App.vue
  JSDemos/Demos/Scheduler/VirtualScrolling/Vue/data.ts
  JSDemos/Demos/Scheduler/WebAPIService/Vue/App.vue
Labels: 23_2

#2981 DataGrid - fix column width
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/React/App.js
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/React/App.tsx
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/ReactJs/App.js
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/Vue/App.vue
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/jQuery/index.js
  MVCDemos/Views/DataGrid/RemoteVirtualScrolling.cshtml
  NetCoreDemos/Views/DataGrid/RemoteVirtualScrolling.cshtml
  testing/etalons/DataGrid-RemoteVirtualScrolling.png
Labels: cherry-pick, 23_2

#2972 Context Menu Demo: custom item template alignment and icons size styles changed
  JSDemos/Demos/ContextMenu/Templates/Angular/app/app.component.css
  JSDemos/Demos/ContextMenu/Templates/Angular/app/app.component.html
  JSDemos/Demos/ContextMenu/Templates/React/App.js
  JSDemos/Demos/ContextMenu/Templates/React/styles.css
  JSDemos/Demos/ContextMenu/Templates/Vue/App.vue
  JSDemos/Demos/ContextMenu/Templates/jQuery/index.js
  JSDemos/Demos/ContextMenu/Templates/jQuery/styles.css
  MVCDemos/Content/DemosStyles/ContextMenu/Templates.css
  MVCDemos/Views/ContextMenu/Templates.cshtml
  NetCoreDemos/Views/ContextMenu/Templates.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/ContextMenu/Templates.css
  testing/widgets/contextmenu/ContextMenu.test.js
  testing/widgets/contextmenu/etalons/ccontext_menu_templates_custom_appearance.png
Labels: 23_2

#2979 Grouped list - Fix arrow vertical alignment
  testing/etalons/Common-ActionAndListsOverview.png
  testing/etalons/List-GroupedList.png
  testing/etalons/List-WebAPI.png
Labels: force all tests, 23_2

#2992 Drawer - change list background color and add shadow on toolbar
  JSDemos/Demos/Drawer/LeftOrRightPosition/Angular/app/app.component.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/Angular/app/app.component.html
  JSDemos/Demos/Drawer/LeftOrRightPosition/React/NavigationList.js
  JSDemos/Demos/Drawer/LeftOrRightPosition/React/styles.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/Vue/App.vue
  JSDemos/Demos/Drawer/LeftOrRightPosition/Vue/NavigationList.vue
  JSDemos/Demos/Drawer/LeftOrRightPosition/jQuery/index.js
  JSDemos/Demos/Drawer/LeftOrRightPosition/jQuery/styles.css
  JSDemos/Demos/Drawer/TopOrBottomPosition/Angular/app/app.component.css
  JSDemos/Demos/Drawer/TopOrBottomPosition/Angular/app/app.component.html
  JSDemos/Demos/Drawer/TopOrBottomPosition/React/NavigationList.js
  JSDemos/Demos/Drawer/TopOrBottomPosition/React/styles.css
  JSDemos/Demos/Drawer/TopOrBottomPosition/Vue/App.vue
  JSDemos/Demos/Drawer/TopOrBottomPosition/Vue/NavigationList.vue
  JSDemos/Demos/Drawer/TopOrBottomPosition/jQuery/index.js
  JSDemos/Demos/Drawer/TopOrBottomPosition/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Drawer/LeftOrRightPosition.css
  MVCDemos/Content/DemosStyles/Drawer/TopOrBottomPosition.css
  MVCDemos/Views/Drawer/LeftOrRightPosition.cshtml
  MVCDemos/Views/Drawer/TopOrBottomPosition.cshtml
  NetCoreDemos/Views/Drawer/LeftOrRightPosition.cshtml
  NetCoreDemos/Views/Drawer/TopOrBottomPosition.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Drawer/LeftOrRightPosition.css
  NetCoreDemos/wwwroot/css/DemosStyles/Drawer/TopOrBottomPosition.css
  testing/etalons/Drawer-LeftOrRightPosition.png
  testing/etalons/Drawer-TopOrBottomPosition.png
Labels: 23_2

#2995 DataGrid - Fix the background color of invalid cells in the Material theme (T1197268)
  testing/etalons/DataGrid-FocusedRow.png
  testing/etalons/TreeList-FocusedRow.png
Labels: 23_2

#2997 DataGrid: update Row Selection description
  JSDemos/Demos/DataGrid/RowSelection/description.md
Labels: 23_2

#2998 Skip linting MD files in demo root
  utils/eslint-runner.ts
Labels: 23_2

#2988 dxScheduler - add Work Shift demo
  JSDemos/Demos/Scheduler/WorkShifts/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/WorkShifts/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/WorkShifts/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/WorkShifts/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/WorkShifts/Angular/index.html
  JSDemos/Demos/Scheduler/WorkShifts/React/App.tsx
  JSDemos/Demos/Scheduler/WorkShifts/React/data.ts
  JSDemos/Demos/Scheduler/WorkShifts/React/index.html
  JSDemos/Demos/Scheduler/WorkShifts/React/index.tsx
  JSDemos/Demos/Scheduler/WorkShifts/React/styles.css
  JSDemos/Demos/Scheduler/WorkShifts/ReactJs/App.js
  JSDemos/Demos/Scheduler/WorkShifts/ReactJs/converter.tsconfig.json
  JSDemos/Demos/Scheduler/WorkShifts/ReactJs/data.js
  JSDemos/Demos/Scheduler/WorkShifts/ReactJs/index.html
  JSDemos/Demos/Scheduler/WorkShifts/ReactJs/index.js
  JSDemos/Demos/Scheduler/WorkShifts/ReactJs/styles.css
  JSDemos/Demos/Scheduler/WorkShifts/Vue/App.vue
  JSDemos/Demos/Scheduler/WorkShifts/Vue/data.ts
  JSDemos/Demos/Scheduler/WorkShifts/Vue/index.html
  JSDemos/Demos/Scheduler/WorkShifts/Vue/index.js
  JSDemos/Demos/Scheduler/WorkShifts/description.md
  JSDemos/Demos/Scheduler/WorkShifts/jQuery/data.js
  JSDemos/Demos/Scheduler/WorkShifts/jQuery/index.html
  JSDemos/Demos/Scheduler/WorkShifts/jQuery/index.js
  JSDemos/Demos/Scheduler/WorkShifts/jQuery/styles.css
  JSDemos/menuMeta.json
  testing/etalons/Scheduler-WorkShifts.png
Labels: 23_2

#2970 Add DateRangeBox to Validation demo
  JSDemos/Demos/Validation/Overview/Angular/app/app.component.html
  JSDemos/Demos/Validation/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Validation/Overview/React/App.tsx
  JSDemos/Demos/Validation/Overview/ReactJs/App.js
  JSDemos/Demos/Validation/Overview/Vue/App.vue
  JSDemos/Demos/Validation/Overview/jQuery/index.html
  JSDemos/Demos/Validation/Overview/jQuery/index.js
  MVCDemos/Controllers/ValidationController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/ViewModels/EditorsViewModel.cs
  MVCDemos/ViewModels/VerifyDateRange.cs
  MVCDemos/Views/Form/Validation.cshtml
  MVCDemos/Views/Validation/Overview.cshtml
  NetCoreDemos/Controllers/ValidationController.cs
  NetCoreDemos/ViewModels/EditorsViewModel.cs
  NetCoreDemos/ViewModels/VerifyDateRange.cs
  NetCoreDemos/ViewModels/VerifyDateRangeSelection.cs
  NetCoreDemos/Views/Validation/Overview.cshtml
  testing/etalons/Validation-Overview.png
Labels: 23_2

#3002 Update Node.js to v20
  .github/workflows/lint.yml
  .github/workflows/publish-demos.yml
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
Labels: 23_2

#3001 Form Group Fields: add caption in left column to make columns symmetric
  JSDemos/Demos/Form/GroupedFields/Angular/app/app.component.html
  JSDemos/Demos/Form/GroupedFields/React/App.tsx
  JSDemos/Demos/Form/GroupedFields/ReactJs/App.js
  JSDemos/Demos/Form/GroupedFields/Vue/App.vue
  JSDemos/Demos/Form/GroupedFields/jQuery/index.js
  MVCDemos/Views/Form/GroupedFields.cshtml
  NetCoreDemos/Views/Form/GroupedFields.cshtml
  testing/etalons/Form-GroupedFields.png
Labels: 23_2

#3006 Fix NetCore build errors
  NetCoreDemos/ViewModels/EditorsViewModel.cs
  NetCoreDemos/ViewModels/VerifyDateRange.cs
  NetCoreDemos/ViewModels/VerifyDateRangeSelection.cs
Labels: 23_2

#3004 Log DevExtreme top commit
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
Labels: 23_2

#3007 Form Validation Demo: fix button alignment in one column mode
  JSDemos/Demos/Form/Validation/Angular/app/app.component.css
  JSDemos/Demos/Form/Validation/React/styles.css
  JSDemos/Demos/Form/Validation/ReactJs/styles.css
  JSDemos/Demos/Form/Validation/Vue/App.vue
  JSDemos/Demos/Form/Validation/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Form/Validation.css
  NetCoreDemos/wwwroot/css/DemosStyles/Form/Validation.css
  testing/etalons/Form-Validation.png
  testing/widgets/form/etalons/form_validation_after_reset.png
  testing/widgets/form/etalons/form_validation_before_reset.png
  testing/widgets/form/etalons/form_validation_summary.png
Labels: 23_2

#3009 Add release config for prepare-aspnet script
  .eslintrc.js
  gulpfile.js/aspnet.js
  gulpfile.js/copy-asp-files.js
  package.json
Labels: 23_2

#3008 Gallery - Update etalons after fix focus state
  testing/etalons/Gallery-Item3RdPartyEngineTemplate.png
  testing/etalons/Gallery-ItemTemplate.png
Labels: 23_2

#2973 Tabs/TabPanel: Add demo-container and fix sizes
  JSDemos/Demos/TabPanel/Overview/Angular/app/app.component.css
  JSDemos/Demos/TabPanel/Overview/Angular/app/app.component.html
  JSDemos/Demos/TabPanel/Overview/Angular/app/app.component.ts
  JSDemos/Demos/TabPanel/Overview/React/styles.css
  JSDemos/Demos/TabPanel/Overview/ReactJs/styles.css
  JSDemos/Demos/TabPanel/Overview/Vue/App.vue
  JSDemos/Demos/TabPanel/Overview/Vue/TaskItem.vue
  JSDemos/Demos/TabPanel/Overview/jQuery/index.html
  JSDemos/Demos/TabPanel/Overview/jQuery/styles.css
  JSDemos/Demos/Tabs/Overview/Angular/app/app.component.css
  JSDemos/Demos/Tabs/Overview/Angular/app/app.component.html
  JSDemos/Demos/Tabs/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Tabs/Overview/React/App.tsx
  JSDemos/Demos/Tabs/Overview/React/styles.css
  JSDemos/Demos/Tabs/Overview/ReactJs/App.js
  JSDemos/Demos/Tabs/Overview/ReactJs/styles.css
  JSDemos/Demos/Tabs/Overview/Vue/App.vue
  JSDemos/Demos/Tabs/Overview/jQuery/index.html
  JSDemos/Demos/Tabs/Overview/jQuery/index.js
  JSDemos/Demos/Tabs/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/TabPanel/Overview.css
  MVCDemos/Content/DemosStyles/Tabs/Overview.css
  MVCDemos/Views/Tabs/Overview.cshtml
  NetCoreDemos/Views/Tabs/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TabPanel/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/Tabs/Overview.css
  testing/etalons/TabPanel-Overview.png
  testing/etalons/Tabs-Overview.png
  testing/widgets/tabpanel/etalons/tabpanel_iconposition_start.png
  testing/widgets/tabpanel/etalons/tabpanel_shownavbuttons_false.png
  testing/widgets/tabpanel/etalons/tabpanel_stylingmode_primary.png
  testing/widgets/tabpanel/etalons/tabpanel_tabsposition_top.png
  testing/widgets/tabs/etalons/tabs_shownavbuttons_true.png
Labels: 23_2

#3016 dxScheduler - enable offset property
  JSDemos/Demos/Scheduler/WorkShifts/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/WorkShifts/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/WorkShifts/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/WorkShifts/React/App.tsx
  JSDemos/Demos/Scheduler/WorkShifts/React/data.ts
  JSDemos/Demos/Scheduler/WorkShifts/ReactJs/App.js
  JSDemos/Demos/Scheduler/WorkShifts/ReactJs/converter.tsconfig.json
  JSDemos/Demos/Scheduler/WorkShifts/ReactJs/data.js
  JSDemos/Demos/Scheduler/WorkShifts/Vue/App.vue
  JSDemos/Demos/Scheduler/WorkShifts/Vue/data.ts
  JSDemos/Demos/Scheduler/WorkShifts/jQuery/data.js
  JSDemos/Demos/Scheduler/WorkShifts/jQuery/index.js
  testing/etalons/Scheduler-WorkShifts.png
Labels: 23_2

#3014 Drawer: update demo appearance
  JSDemos/Demos/Drawer/LeftOrRightPosition/Angular/app/app.component.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/Angular/app/app.component.html
  JSDemos/Demos/Drawer/LeftOrRightPosition/Angular/app/app.component.ts
  JSDemos/Demos/Drawer/LeftOrRightPosition/React/App.tsx
  JSDemos/Demos/Drawer/LeftOrRightPosition/React/NavigationList.tsx
  JSDemos/Demos/Drawer/LeftOrRightPosition/React/styles.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/ReactJs/App.js
  JSDemos/Demos/Drawer/LeftOrRightPosition/ReactJs/NavigationList.js
  JSDemos/Demos/Drawer/LeftOrRightPosition/ReactJs/styles.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/Vue/App.vue
  JSDemos/Demos/Drawer/LeftOrRightPosition/Vue/NavigationList.vue
  JSDemos/Demos/Drawer/LeftOrRightPosition/jQuery/index.html
  JSDemos/Demos/Drawer/LeftOrRightPosition/jQuery/index.js
  JSDemos/Demos/Drawer/LeftOrRightPosition/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Drawer/LeftOrRightPosition.css
  MVCDemos/Views/Drawer/LeftOrRightPosition.cshtml
  NetCoreDemos/Views/Drawer/LeftOrRightPosition.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Drawer/LeftOrRightPosition.css
  testing/etalons/Drawer-LeftOrRightPosition.png
Labels: 23_2

#3017 Make check for known devextreme warnings less strict
  testing/known-warnings.json
Labels: 23_2

#3024 Drawer - update appearance
  JSDemos/Demos/Drawer/LeftOrRightPosition/Angular/app/app.component.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/Angular/app/app.component.ts
  JSDemos/Demos/Drawer/LeftOrRightPosition/React/App.tsx
  JSDemos/Demos/Drawer/LeftOrRightPosition/React/styles.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/ReactJs/App.js
  JSDemos/Demos/Drawer/LeftOrRightPosition/ReactJs/styles.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/Vue/App.vue
  JSDemos/Demos/Drawer/LeftOrRightPosition/jQuery/index.js
  JSDemos/Demos/Drawer/LeftOrRightPosition/jQuery/styles.css
  JSDemos/Demos/Drawer/TopOrBottomPosition/Angular/app/app.component.css
  JSDemos/Demos/Drawer/TopOrBottomPosition/Angular/app/app.component.html
  JSDemos/Demos/Drawer/TopOrBottomPosition/Angular/app/app.component.ts
  JSDemos/Demos/Drawer/TopOrBottomPosition/React/App.tsx
  JSDemos/Demos/Drawer/TopOrBottomPosition/React/NavigationList.tsx
  JSDemos/Demos/Drawer/TopOrBottomPosition/React/styles.css
  JSDemos/Demos/Drawer/TopOrBottomPosition/ReactJs/App.js
  JSDemos/Demos/Drawer/TopOrBottomPosition/ReactJs/NavigationList.js
  JSDemos/Demos/Drawer/TopOrBottomPosition/ReactJs/styles.css
  JSDemos/Demos/Drawer/TopOrBottomPosition/Vue/App.vue
  JSDemos/Demos/Drawer/TopOrBottomPosition/Vue/NavigationList.vue
  JSDemos/Demos/Drawer/TopOrBottomPosition/jQuery/index.html
  JSDemos/Demos/Drawer/TopOrBottomPosition/jQuery/index.js
  JSDemos/Demos/Drawer/TopOrBottomPosition/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Drawer/LeftOrRightPosition.css
  MVCDemos/Content/DemosStyles/Drawer/TopOrBottomPosition.css
  MVCDemos/Views/Drawer/LeftOrRightPosition.cshtml
  MVCDemos/Views/Drawer/TopOrBottomPosition.cshtml
  NetCoreDemos/Views/Drawer/LeftOrRightPosition.cshtml
  NetCoreDemos/Views/Drawer/TopOrBottomPosition.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Drawer/LeftOrRightPosition.css
  NetCoreDemos/wwwroot/css/DemosStyles/Drawer/TopOrBottomPosition.css
  testing/etalons/Drawer-LeftOrRightPosition.png
  testing/etalons/Drawer-TopOrBottomPosition.png
Labels: 23_2

#3023 Scheduler: add 'Work Shifts' demo description
  JSDemos/Demos/Scheduler/WorkShifts/description.md
Labels: 23_2

#3025 Drawer - delete custom border-top for list items
  JSDemos/Demos/Drawer/LeftOrRightPosition/Angular/app/app.component.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/React/styles.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/ReactJs/styles.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/Vue/App.vue
  JSDemos/Demos/Drawer/LeftOrRightPosition/jQuery/styles.css
  JSDemos/Demos/Drawer/TopOrBottomPosition/Angular/app/app.component.css
  JSDemos/Demos/Drawer/TopOrBottomPosition/React/styles.css
  JSDemos/Demos/Drawer/TopOrBottomPosition/ReactJs/styles.css
  JSDemos/Demos/Drawer/TopOrBottomPosition/Vue/App.vue
  JSDemos/Demos/Drawer/TopOrBottomPosition/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Drawer/LeftOrRightPosition.css
  MVCDemos/Content/DemosStyles/Drawer/TopOrBottomPosition.css
  NetCoreDemos/wwwroot/css/DemosStyles/Drawer/LeftOrRightPosition.css
  NetCoreDemos/wwwroot/css/DemosStyles/Drawer/TopOrBottomPosition.css
  testing/etalons/Drawer-LeftOrRightPosition.png
Labels: 23_2

#3020 TreeView: add box-sizing style for items in drag demos
  JSDemos/Demos/TreeView/DragAndDropHierarchicalDataStructure/Angular/app/app.component.css
  JSDemos/Demos/TreeView/DragAndDropHierarchicalDataStructure/React/styles.css
  JSDemos/Demos/TreeView/DragAndDropHierarchicalDataStructure/ReactJs/styles.css
  JSDemos/Demos/TreeView/DragAndDropHierarchicalDataStructure/Vue/App.vue
  JSDemos/Demos/TreeView/DragAndDropHierarchicalDataStructure/jQuery/styles.css
  JSDemos/Demos/TreeView/DragAndDropPlainDataStructure/Angular/app/app.component.css
  JSDemos/Demos/TreeView/DragAndDropPlainDataStructure/React/styles.css
  JSDemos/Demos/TreeView/DragAndDropPlainDataStructure/ReactJs/styles.css
  JSDemos/Demos/TreeView/DragAndDropPlainDataStructure/Vue/App.vue
  JSDemos/Demos/TreeView/DragAndDropPlainDataStructure/jQuery/styles.css
  MVCDemos/Content/DemosStyles/TreeView/DragAndDropHierarchicalDataStructure.css
  MVCDemos/Content/DemosStyles/TreeView/DragAndDropPlainDataStructure.css
  NetCoreDemos/wwwroot/css/DemosStyles/TreeView/DragAndDropHierarchicalDataStructure.css
  NetCoreDemos/wwwroot/css/DemosStyles/TreeView/DragAndDropPlainDataStructure.css
Labels: 23_2

#2978 Turn off accessibility tests for not accessible components and skip rest errors
  .github/workflows/visual_tests.yml
  JSDemos/Demos/Localization/UsingGlobalize/jQuery/index.html
  testing/.eslintrc.js
  testing/common.test.js
Labels: force all tests, 23_2

#3022 Scheduler day length: Change reduced appointment icon.
  testing/etalons/Scheduler-AllDayPanelMode.png
Labels: 23_2

#3031 SelectBox Customize Drop-Down Button - fix button template size
  JSDemos/Demos/SelectBox/CustomizeDropDownButton/Angular/app/app.component.css
  JSDemos/Demos/SelectBox/CustomizeDropDownButton/React/styles.css
  JSDemos/Demos/SelectBox/CustomizeDropDownButton/ReactJs/styles.css
  JSDemos/Demos/SelectBox/CustomizeDropDownButton/Vue/App.vue
  JSDemos/Demos/SelectBox/CustomizeDropDownButton/jQuery/styles.css
  MVCDemos/Content/DemosStyles/SelectBox/CustomizeDropDownButton.css
  NetCoreDemos/wwwroot/css/DemosStyles/SelectBox/CustomizeDropDownButton.css
Labels: 23_2

#3034 AspNet: Install DevExtreme.AspNet.Core package from file in release configuration
  gulpfile.js/copy-asp-files.js
Labels: 23_2

#3032 dxScheduler - create new day shift demo(.net mvc)
  MVCDemos/Content/DemosStyles/Scheduler/WorkShifts.css
  MVCDemos/Controllers/SchedulerController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/SampleData/WorkShiftsAppointmentData.cs
  MVCDemos/Models/SampleData/WorkShiftsOffsetData.cs
  MVCDemos/Models/WorkShift.cs
  MVCDemos/ViewModels/WorkShiftsViewModel.cs
  MVCDemos/Views/Scheduler/WorkShifts.cshtml
Labels: 23_2

#3027 Vue: use re-exported types from platform package
  JSDemos/Demos/DataGrid/AdvancedMasterDetailView/Vue/AddressTab.vue
  JSDemos/Demos/DataGrid/BatchUpdateRequest/Vue/App.vue
  JSDemos/Demos/DataGrid/CascadingLookups/Vue/App.vue
  JSDemos/Demos/DataGrid/CellCustomization/Vue/DiffCell.vue
  JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Vue/App.vue
  JSDemos/Demos/DataGrid/CollaborativeEditing/Vue/Grid.vue
  JSDemos/Demos/DataGrid/ColumnChooser/Vue/App.vue
  JSDemos/Demos/DataGrid/ColumnHeaderFilter/Vue/App.vue
  JSDemos/Demos/DataGrid/CommandColumnCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/CustomEditors/Vue/App.vue
  JSDemos/Demos/DataGrid/CustomEditors/Vue/EmployeeDropDownBoxComponent.vue
  JSDemos/Demos/DataGrid/CustomEditors/Vue/EmployeeTagBoxComponent.vue
  JSDemos/Demos/DataGrid/CustomNewRecordPosition/Vue/App.vue
  JSDemos/Demos/DataGrid/CustomSummaries/Vue/App.vue
  JSDemos/Demos/DataGrid/CustomizeKeyboardNavigation/Vue/App.vue
  JSDemos/Demos/DataGrid/DeferredSelection/Vue/App.vue
  JSDemos/Demos/DataGrid/DnDBetweenGrids/Vue/Grid.vue
  JSDemos/Demos/DataGrid/EditStateManagement/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSCellCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSExportImages/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSHeaderAndFooter/Vue/App.vue
  JSDemos/Demos/DataGrid/ExcelJSOverview/Vue/App.vue
  JSDemos/Demos/DataGrid/FilterPanel/Vue/App.vue
  JSDemos/Demos/DataGrid/Filtering/Vue/App.vue
  JSDemos/Demos/DataGrid/FilteringAPI/Vue/App.vue
  JSDemos/Demos/DataGrid/FocusedRow/Vue/App.vue
  JSDemos/Demos/DataGrid/GridSummaries/Vue/App.vue
  JSDemos/Demos/DataGrid/InfiniteScrolling/Vue/App.vue
  JSDemos/Demos/DataGrid/LocalReordering/Vue/App.vue
  JSDemos/Demos/DataGrid/MasterDetailAPI/Vue/App.vue
  JSDemos/Demos/DataGrid/MasterDetailView/Vue/DetailTemplate.vue
  JSDemos/Demos/DataGrid/MultipleRecordSelectionAPI/Vue/App.vue
  JSDemos/Demos/DataGrid/Overview/Vue/App.vue
  JSDemos/Demos/DataGrid/Overview/Vue/DiscountCell.vue
  JSDemos/Demos/DataGrid/PDFCellCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFExportImages/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFHeaderAndFooter/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFOverview/Vue/App.vue
  JSDemos/Demos/DataGrid/RecordPaging/Vue/App.vue
  JSDemos/Demos/DataGrid/RemoteReordering/Vue/App.vue
  JSDemos/Demos/DataGrid/RightToLeftSupport/Vue/App.vue
  JSDemos/Demos/DataGrid/RowSelection/Vue/App.vue
  JSDemos/Demos/DataGrid/SignalRService/Vue/ChangeCell.vue
  JSDemos/Demos/DataGrid/SignalRService/Vue/PriceCell.vue
  JSDemos/Demos/DataGrid/ToolbarCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/VirtualScrolling/Vue/App.vue
Labels: 23_2

#3035 dxScheduler - create new day shift demo(.net core)
  NetCoreDemos/Controllers/SchedulerController.cs
  NetCoreDemos/Models/SampleData/WorkShiftsAppointmentData.cs
  NetCoreDemos/Models/SampleData/WorkShiftsOffsetData.cs
  NetCoreDemos/Models/WorkShift.cs
  NetCoreDemos/ViewModels/WorkShiftsViewModel.cs
  NetCoreDemos/Views/Scheduler/WorkShifts.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/WorkShifts.css
Labels: 23_2

#3038 dxScheduler - update work shift demo: change week to workWeek
  JSDemos/Demos/Scheduler/WorkShifts/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/WorkShifts/React/App.tsx
  JSDemos/Demos/Scheduler/WorkShifts/ReactJs/App.js
  JSDemos/Demos/Scheduler/WorkShifts/Vue/App.vue
  JSDemos/Demos/Scheduler/WorkShifts/jQuery/index.js
  MVCDemos/Views/Scheduler/WorkShifts.cshtml
  NetCoreDemos/Views/Scheduler/WorkShifts.cshtml
  testing/etalons/Scheduler-WorkShifts.png
Labels: 23_2

#3036 Drawer,List demos - Remove absolute positioned container
  JSDemos/Demos/Drawer/LeftOrRightPosition/Angular/app/app.component.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/React/styles.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/ReactJs/styles.css
  JSDemos/Demos/Drawer/LeftOrRightPosition/Vue/App.vue
  JSDemos/Demos/Drawer/LeftOrRightPosition/jQuery/styles.css
  JSDemos/Demos/List/ItemTemplate/Angular/app/app.component.css
  JSDemos/Demos/List/ItemTemplate/React/styles.css
  JSDemos/Demos/List/ItemTemplate/ReactJs/styles.css
  JSDemos/Demos/List/ItemTemplate/Vue/App.vue
  JSDemos/Demos/List/ItemTemplate/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Drawer/LeftOrRightPosition.css
  MVCDemos/Content/DemosStyles/List/ItemTemplate.css
  NetCoreDemos/wwwroot/css/DemosStyles/Drawer/LeftOrRightPosition.css
  NetCoreDemos/wwwroot/css/DemosStyles/List/ItemTemplate.css
  testing/etalons/List-ItemTemplate.png
Labels: 23_2

#3039 Numberbox overview demo: get rid of deprecated api
  JSDemos/Demos/NumberBox/Overview/Angular/app/app.component.ts
  JSDemos/Demos/NumberBox/Overview/AngularJS/index.js
  JSDemos/Demos/NumberBox/Overview/React/App.tsx
  JSDemos/Demos/NumberBox/Overview/ReactJs/App.js
  JSDemos/Demos/NumberBox/Overview/Vue/App.vue
  JSDemos/Demos/NumberBox/Overview/jQuery/index.js
  MVCDemos/Views/NumberBox/Overview.cshtml
  NetCoreDemos/Views/NumberBox/Overview.cshtml
Labels: 23_2

#3045 Calendar - fix cellComponent props in React demo
  JSDemos/Demos/Calendar/Overview/React/CustomCell.tsx
  JSDemos/Demos/Calendar/Overview/ReactJs/CustomCell.js
Labels: 23_2

#3041 popup scrolling demo: remove custom color style
  JSDemos/Demos/Popup/Scrolling/Angular/app/app.component.css
  JSDemos/Demos/Popup/Scrolling/React/styles.css
  JSDemos/Demos/Popup/Scrolling/ReactJs/styles.css
  JSDemos/Demos/Popup/Scrolling/Vue/App.vue
  JSDemos/Demos/Popup/Scrolling/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Popup/Scrolling.css
  NetCoreDemos/wwwroot/css/DemosStyles/Popup/Scrolling.css
  testing/etalons/Popup-Scrolling.png
Labels: 23_2

#3043 TabPanel: Fix text contrast && Remove nav checkbox
  JSDemos/Demos/TabPanel/Overview/Angular/app/app.component.css
  JSDemos/Demos/TabPanel/Overview/Angular/app/app.component.html
  JSDemos/Demos/TabPanel/Overview/Angular/app/app.component.ts
  JSDemos/Demos/TabPanel/Overview/React/App.tsx
  JSDemos/Demos/TabPanel/Overview/React/data.ts
  JSDemos/Demos/TabPanel/Overview/React/styles.css
  JSDemos/Demos/TabPanel/Overview/ReactJs/App.js
  JSDemos/Demos/TabPanel/Overview/ReactJs/data.js
  JSDemos/Demos/TabPanel/Overview/ReactJs/styles.css
  JSDemos/Demos/TabPanel/Overview/Vue/App.vue
  JSDemos/Demos/TabPanel/Overview/Vue/TaskItem.vue
  JSDemos/Demos/TabPanel/Overview/Vue/data.js
  JSDemos/Demos/TabPanel/Overview/jQuery/data.js
  JSDemos/Demos/TabPanel/Overview/jQuery/index.html
  JSDemos/Demos/TabPanel/Overview/jQuery/index.js
  JSDemos/Demos/TabPanel/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/TabPanel/Overview.css
  MVCDemos/Views/TabPanel/Overview.cshtml
  NetCoreDemos/Views/TabPanel/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TabPanel/Overview.css
  testing/etalons/TabPanel-Overview.png
  testing/etalons/Tabs-Overview.png
  testing/widgets/tabpanel/Overview.test.js
  testing/widgets/tabpanel/etalons/tabpanel_iconposition_start.png
  testing/widgets/tabpanel/etalons/tabpanel_shownavbuttons_false.png
  testing/widgets/tabpanel/etalons/tabpanel_stylingmode_primary.png
  testing/widgets/tabpanel/etalons/tabpanel_tabsposition_top.png
  testing/widgets/tabs/etalons/tabs_orientation_vertical.png
  testing/widgets/tabs/etalons/tabs_stylingmode_secondary.png
Labels: force all tests, 23_2

#3050 DataGrid: Fix the Popup Editing demo
  JSDemos/Demos/DataGrid/PopupEditing/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/PopupEditing/React/styles.css
  JSDemos/Demos/DataGrid/PopupEditing/ReactJs/styles.css
  JSDemos/Demos/DataGrid/PopupEditing/Vue/App.vue
  JSDemos/Demos/DataGrid/PopupEditing/jQuery/styles.css
  MVCDemos/Content/DemosStyles/DataGrid/PopupEditing.css
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/PopupEditing.css
Labels: 23_2

#3055 Web API Service: add/update marketing note
  JSDemos/Demos/Charts/ServerSideDataProcessing/description.md
  JSDemos/Demos/DataGrid/CustomDataSource/description.md
  JSDemos/Demos/DataGrid/OdataService/description.md
  JSDemos/Demos/DataGrid/WebAPIService/description.md
  JSDemos/Demos/Diagram/WebAPIService/description.md
  JSDemos/Demos/List/WebAPI/description.md
  JSDemos/Demos/PivotGrid/WebAPIService/description.md
  JSDemos/Demos/Scheduler/WebAPIService/description.md
  JSDemos/Demos/TreeList/WebAPIService/description.md
Labels: 23_2

#3053 dxScheduler- update appointment layout in demo(day shift)
  JSDemos/Demos/Scheduler/WorkShifts/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/WorkShifts/Angular/app/app.service.ts
  JSDemos/Demos/Scheduler/WorkShifts/React/App.tsx
  JSDemos/Demos/Scheduler/WorkShifts/React/data.ts
  JSDemos/Demos/Scheduler/WorkShifts/ReactJs/App.js
  JSDemos/Demos/Scheduler/WorkShifts/ReactJs/data.js
  JSDemos/Demos/Scheduler/WorkShifts/Vue/App.vue
  JSDemos/Demos/Scheduler/WorkShifts/Vue/data.ts
  JSDemos/Demos/Scheduler/WorkShifts/jQuery/data.js
  JSDemos/Demos/Scheduler/WorkShifts/jQuery/index.html
  MVCDemos/Models/SampleData/WorkShiftsAppointmentData.cs
  MVCDemos/Views/Scheduler/WorkShifts.cshtml
  NetCoreDemos/Models/SampleData/WorkShiftsAppointmentData.cs
  NetCoreDemos/Views/Scheduler/WorkShifts.cshtml
Labels: 23_2

#3056 Reporting/Dashboard: add marketing notes
  JSDemos/Demos/Charts/ExportAndPrintingAPI/description.md
  JSDemos/Demos/Charts/FunnelChart/description.md
  JSDemos/Demos/Charts/Overview/Angular/description.md
  JSDemos/Demos/Charts/Overview/React/description.md
  JSDemos/Demos/Charts/Overview/ReactJs/description.md
  JSDemos/Demos/Charts/Overview/Vue/description.md
  JSDemos/Demos/Charts/Overview/jQuery/description.md
  JSDemos/Demos/Charts/Pie/description.md
  JSDemos/Demos/Charts/SimpleBullets/description.md
  JSDemos/Demos/DataGrid/ExcelJSOverview/description.md
  JSDemos/Demos/DataGrid/PDFOverview/description.md
  JSDemos/Demos/Gauges/Overview/Angular/description.md
  JSDemos/Demos/Gauges/Overview/React/description.md
  JSDemos/Demos/Gauges/Overview/ReactJs/description.md
  JSDemos/Demos/Gauges/Overview/Vue/description.md
  JSDemos/Demos/Gauges/Overview/jQuery/description.md
  JSDemos/Demos/PivotGrid/Overview/Angular/description.md
  JSDemos/Demos/PivotGrid/Overview/React/description.md
  JSDemos/Demos/PivotGrid/Overview/ReactJs/description.md
  JSDemos/Demos/PivotGrid/Overview/Vue/description.md
  JSDemos/Demos/PivotGrid/Overview/jQuery/description.md
  JSDemos/Demos/VectorMap/Overview/Angular/description.md
  JSDemos/Demos/VectorMap/Overview/React/description.md
  JSDemos/Demos/VectorMap/Overview/ReactJs/description.md
  JSDemos/Demos/VectorMap/Overview/Vue/description.md
  JSDemos/Demos/VectorMap/Overview/jQuery/description.md
Labels: 23_2

#3060 Temporary skip broken map tests
  testing/common.test.js
Labels: 23_2
