Repository DevExpress/devextreme-demos, pull requests merged in 2023-01, with the labels that each got.

#2347 Rename map -> maps img parent folder
  JSDemos/images/Maps/map-marker.png
Labels: 22_2

#2343 DataGrid - Fix demos
  MVCDemos/Controllers/ApiControllers/DataGridRowReorderingController.cs
  MVCDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  MVCDemos/Views/DataGrid/FormEditing.cshtml
  MVCDemos/Views/DataGrid/PopupEditing.cshtml
Labels: 22_2

#2355 Button: Remove redundant styles for .dx-theme-ios7 and .dx-theme-android5
  JSDemos/Demos/Button/Icons/Angular/app/app.component.css
  JSDemos/Demos/Button/Icons/AngularJS/styles.css
  JSDemos/Demos/Button/Icons/Knockout/styles.css
  JSDemos/Demos/Button/Icons/React/styles.css
  JSDemos/Demos/Button/Icons/Vue/App.vue
  JSDemos/Demos/Button/Icons/jQuery/styles.css
  JSDemos/Demos/Lookup/EventHandling/Angular/app/app.component.css
  JSDemos/Demos/Lookup/EventHandling/AngularJS/styles.css
  JSDemos/Demos/Lookup/EventHandling/Knockout/styles.css
  JSDemos/Demos/Lookup/EventHandling/React/styles.css
  JSDemos/Demos/Lookup/EventHandling/Vue/styles.css
  JSDemos/Demos/Lookup/EventHandling/jQuery/styles.css
  JSDemos/Demos/Lookup/Templates/Angular/app/app.component.css
  JSDemos/Demos/Lookup/Templates/AngularJS/styles.css
  JSDemos/Demos/Lookup/Templates/Knockout/styles.css
  JSDemos/Demos/Lookup/Templates/React/styles.css
  JSDemos/Demos/Lookup/Templates/Vue/App.vue
  JSDemos/Demos/Lookup/Templates/jQuery/styles.css
  JSDemos/Demos/SelectBox/CustomizeDropDownButton/Angular/app/app.component.css
  JSDemos/Demos/SelectBox/CustomizeDropDownButton/AngularJS/styles.css
  JSDemos/Demos/SelectBox/CustomizeDropDownButton/Knockout/styles.css
  JSDemos/Demos/SelectBox/CustomizeDropDownButton/React/styles.css
  JSDemos/Demos/SelectBox/CustomizeDropDownButton/Vue/App.vue
  JSDemos/Demos/SelectBox/CustomizeDropDownButton/jQuery/styles.css
  JSDemos/Demos/Toast/Overview/Knockout/styles.css
  MVCDemos/Content/DemosStyles/Button/Icons.css
  MVCDemos/Content/DemosStyles/Lookup/EventHandling.css
  MVCDemos/Content/DemosStyles/Lookup/Templates.css
  NetCoreDemos/wwwroot/css/DemosStyles/Button/Icons.css
  NetCoreDemos/wwwroot/css/DemosStyles/Lookup/EventHandling.css
  NetCoreDemos/wwwroot/css/DemosStyles/Lookup/Templates.css
Labels: 23_1

#2361 Rename map -> maps img parent folder
  JSDemos/images/Maps/map-marker.png
Labels: cherry-pick, 23_1

#2363 DataGrid - Fix demos
  MVCDemos/Controllers/ApiControllers/DataGridRowReorderingController.cs
  MVCDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  MVCDemos/Views/DataGrid/FormEditing.cshtml
  MVCDemos/Views/DataGrid/PopupEditing.cshtml
Labels: cherry-pick, 23_1

#2368 Exclude devextreme-quill from system.js bundles
  JSDemos/configs/Angular/config.bundle.js
  JSDemos/configs/React/config.bundle.js
  JSDemos/configs/Vue/config.bundle.js
  package-lock.json
  package.json
  utils/bundle/index.js
Labels: cherry-pick, 21_2

#2373 Restore HtmlEditor visual tests
  JSDemos/Demos/HtmlEditor/Mentions/visualtestrc.json
  JSDemos/Demos/HtmlEditor/OutputFormats/visualtestrc.json
  JSDemos/Demos/HtmlEditor/Overview/visualtestrc.json
  JSDemos/Demos/HtmlEditor/Tables/visualtestrc.json
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/visualtestrc.json
Labels: force all tests, 22_2

#2371 Charts: replace deprecated callValueChanged option with new valueChangeMode option
  JSDemos/Demos/Charts/DiscreteAxisZoomingAndScrolling/Angular/app/app.component.html
  JSDemos/Demos/Charts/DiscreteAxisZoomingAndScrolling/AngularJS/index.js
  JSDemos/Demos/Charts/DiscreteAxisZoomingAndScrolling/Knockout/index.js
  JSDemos/Demos/Charts/DiscreteAxisZoomingAndScrolling/React/App.js
  JSDemos/Demos/Charts/DiscreteAxisZoomingAndScrolling/Vue/App.vue
  JSDemos/Demos/Charts/DiscreteAxisZoomingAndScrolling/jQuery/index.js
  JSDemos/Demos/Charts/PointsAggregation/Knockout/index.js
  JSDemos/Demos/Charts/PointsAggregationFinancialChart/Angular/app/app.component.html
  JSDemos/Demos/Charts/PointsAggregationFinancialChart/AngularJS/index.js
  JSDemos/Demos/Charts/PointsAggregationFinancialChart/Knockout/index.js
  JSDemos/Demos/Charts/PointsAggregationFinancialChart/React/App.js
  JSDemos/Demos/Charts/PointsAggregationFinancialChart/Vue/App.vue
  JSDemos/Demos/Charts/PointsAggregationFinancialChart/jQuery/index.js
  JSDemos/Demos/Charts/PolarChartZoomingAndScrollingAPI/Angular/app/app.component.html
  JSDemos/Demos/Charts/PolarChartZoomingAndScrollingAPI/React/App.js
  JSDemos/Demos/Charts/PolarChartZoomingAndScrollingAPI/Vue/App.vue
  JSDemos/Demos/Charts/PolarChartZoomingAndScrollingAPI/jQuery/index.js
  JSDemos/Demos/Charts/ZoomingAndScrollingAPI/Angular/app/app.component.html
  JSDemos/Demos/Charts/ZoomingAndScrollingAPI/AngularJS/index.js
  JSDemos/Demos/Charts/ZoomingAndScrollingAPI/Knockout/index.js
  JSDemos/Demos/Charts/ZoomingAndScrollingAPI/React/App.js
  JSDemos/Demos/Charts/ZoomingAndScrollingAPI/Vue/App.vue
  JSDemos/Demos/Charts/ZoomingAndScrollingAPI/jQuery/index.js
  JSDemos/Demos/RangeSelector/LogarithmicScale/Angular/app/app.component.html
  JSDemos/Demos/RangeSelector/LogarithmicScale/AngularJS/index.js
  JSDemos/Demos/RangeSelector/LogarithmicScale/Knockout/index.js
  JSDemos/Demos/RangeSelector/LogarithmicScale/React/App.js
  JSDemos/Demos/RangeSelector/LogarithmicScale/Vue/App.vue
  JSDemos/Demos/RangeSelector/LogarithmicScale/jQuery/index.js
  JSDemos/Demos/RangeSelector/UseRangeSelectionForCalculation/Angular/app/app.component.html
  JSDemos/Demos/RangeSelector/UseRangeSelectionForCalculation/Angular/app/app.component.ts
  JSDemos/Demos/RangeSelector/UseRangeSelectionForCalculation/AngularJS/index.js
  JSDemos/Demos/RangeSelector/UseRangeSelectionForCalculation/Knockout/index.js
  JSDemos/Demos/RangeSelector/UseRangeSelectionForCalculation/React/App.js
  JSDemos/Demos/RangeSelector/UseRangeSelectionForCalculation/Vue/App.vue
  JSDemos/Demos/RangeSelector/UseRangeSelectionForCalculation/jQuery/index.js
  JSDemos/Demos/RangeSelector/UseRangeSelectionForFiltering/Angular/app/app.component.html
  JSDemos/Demos/RangeSelector/UseRangeSelectionForFiltering/AngularJS/index.js
  JSDemos/Demos/RangeSelector/UseRangeSelectionForFiltering/Knockout/index.js
  JSDemos/Demos/RangeSelector/UseRangeSelectionForFiltering/React/App.js
  JSDemos/Demos/RangeSelector/UseRangeSelectionForFiltering/Vue/App.vue
  JSDemos/Demos/RangeSelector/UseRangeSelectionForFiltering/jQuery/index.js
  MVCDemos/Views/Charts/DiscreteAxisZoomingAndScrolling.cshtml
  MVCDemos/Views/Charts/PointsAggregationFinancialChart.cshtml
  MVCDemos/Views/Charts/PolarChartZoomingAndScrollingAPI.cshtml
  MVCDemos/Views/Charts/ZoomingAndScrollingAPI.cshtml
  MVCDemos/Views/RangeSelector/LogarithmicScale.cshtml
  MVCDemos/Views/RangeSelector/UseRangeSelectionForCalculation.cshtml
  MVCDemos/Views/RangeSelector/UseRangeSelectionForFiltering.cshtml
  NetCoreDemos/Views/Charts/DiscreteAxisZoomingAndScrolling.cshtml
  NetCoreDemos/Views/Charts/PointsAggregationFinancialChart.cshtml
  NetCoreDemos/Views/Charts/PolarChartZoomingAndScrollingAPI.cshtml
  NetCoreDemos/Views/Charts/ZoomingAndScrollingAPI.cshtml
  NetCoreDemos/Views/RangeSelector/LogarithmicScale.cshtml
  NetCoreDemos/Views/RangeSelector/UseRangeSelectionForCalculation.cshtml
  NetCoreDemos/Views/RangeSelector/UseRangeSelectionForFiltering.cshtml
  testing/etalons/RangeSelector-UseRangeSelectionForCalculation.png
Labels: 23_1

#2374 Restore HtmlEditor visual tests
  JSDemos/Demos/HtmlEditor/Mentions/visualtestrc.json
  JSDemos/Demos/HtmlEditor/OutputFormats/visualtestrc.json
  JSDemos/Demos/HtmlEditor/Overview/visualtestrc.json
  JSDemos/Demos/HtmlEditor/Tables/visualtestrc.json
  JSDemos/Demos/HtmlEditor/ToolbarCustomization/visualtestrc.json
Labels: cherry-pick, force all tests, 23_1

#2372 Use showEvent hideEvent instead of binding to visible
  JSDemos/Demos/Popover/Overview/Angular/app/app.component.html
  JSDemos/Demos/Popover/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Popover/Overview/React/App.js
  JSDemos/Demos/Popover/Overview/Vue/App.vue
  JSDemos/Demos/Tooltip/Overview/Angular/app/app.component.html
  JSDemos/Demos/Tooltip/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Tooltip/Overview/React/App.js
  JSDemos/Demos/Tooltip/Overview/Vue/App.vue
Labels: 23_1

#2376 Tooltip popover - showEvent hideEvent instead of binding to visible
  JSDemos/Demos/Popover/Overview/Angular/app/app.component.html
  JSDemos/Demos/Popover/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Popover/Overview/React/App.js
  JSDemos/Demos/Popover/Overview/Vue/App.vue
  JSDemos/Demos/Tooltip/Overview/Angular/app/app.component.html
  JSDemos/Demos/Tooltip/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Tooltip/Overview/React/App.js
  JSDemos/Demos/Tooltip/Overview/Vue/App.vue
Labels: cherry-pick, 22_2

#2333 SelectBox grouped Items demo: Update pregrouped dataSource
  JSDemos/Demos/SelectBox/GroupedItems/Angular/app/app.component.html
  JSDemos/Demos/SelectBox/GroupedItems/Angular/app/app.component.ts
  JSDemos/Demos/SelectBox/GroupedItems/React/App.js
  JSDemos/Demos/SelectBox/GroupedItems/Vue/App.vue
  JSDemos/Demos/SelectBox/GroupedItems/jQuery/index.js
  MVCDemos/Views/SelectBox/GroupedItems.cshtml
  NetCoreDemos/Views/SelectBox/GroupedItems.cshtml
  testing/etalons/SelectBox-GroupedItems.png
Labels: 22_2

#2362 23.1 - SelectBox grouped Items demo: Update pregrouped dataSource
  JSDemos/Demos/SelectBox/GroupedItems/Angular/app/app.component.html
  JSDemos/Demos/SelectBox/GroupedItems/Angular/app/app.component.ts
  JSDemos/Demos/SelectBox/GroupedItems/React/App.js
  JSDemos/Demos/SelectBox/GroupedItems/Vue/App.vue
  JSDemos/Demos/SelectBox/GroupedItems/jQuery/index.js
  MVCDemos/Views/SelectBox/GroupedItems.cshtml
  NetCoreDemos/Views/SelectBox/GroupedItems.cshtml
  testing/etalons/SelectBox-GroupedItems.png
Labels: cherry-pick, 23_1

#2381 TextArea demo: Update "on blur" to "on change"
  JSDemos/Demos/TextArea/Overview/Angular/app/app.component.ts
  JSDemos/Demos/TextArea/Overview/React/data.js
  JSDemos/Demos/TextArea/Overview/Vue/data.js
  JSDemos/Demos/TextArea/Overview/jQuery/index.js
  MVCDemos/Views/TextArea/Overview.cshtml
  NetCoreDemos/Views/TextArea/Overview.cshtml
  testing/etalons/TextArea-Overview.png
Labels: 23_1

#2337 TileView: Add ASP.NET demos (Basics)
  MVCDemos/Content/DemosStyles/TileView/Basics.css
  MVCDemos/Content/images/Gallery/12.jpg
  MVCDemos/Content/images/Gallery/14.jpg
  MVCDemos/Content/images/Gallery/17.jpg
  MVCDemos/Content/images/Gallery/20.jpg
  MVCDemos/Content/images/Gallery/21.jpg
  MVCDemos/Content/images/Gallery/22.jpg
  MVCDemos/Content/images/Gallery/23.jpg
  MVCDemos/Controllers/TileViewController.cs
  MVCDemos/Models/SampleData/TileViewItems.cs
  MVCDemos/Models/TileViewItem.cs
  MVCDemos/Views/TileView/Basics.cshtml
  NetCoreDemos/Controllers/TileViewController.cs
  NetCoreDemos/Models/SampleData/TileViewItems.cs
  NetCoreDemos/Models/TileViewItem.cs
  NetCoreDemos/Views/TileView/Basics.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TileView/Basics.css
  NetCoreDemos/wwwroot/images/Gallery/12.jpg
  NetCoreDemos/wwwroot/images/Gallery/14.jpg
  NetCoreDemos/wwwroot/images/Gallery/17.jpg
  NetCoreDemos/wwwroot/images/Gallery/20.jpg
  NetCoreDemos/wwwroot/images/Gallery/21.jpg
  NetCoreDemos/wwwroot/images/Gallery/22.jpg
  NetCoreDemos/wwwroot/images/Gallery/23.jpg
Labels: 23_1

#2338 TileView: Add ASP.NET demos (Basics)
  MVCDemos/Content/DemosStyles/TileView/Basics.css
  MVCDemos/Content/images/Gallery/12.jpg
  MVCDemos/Content/images/Gallery/14.jpg
  MVCDemos/Content/images/Gallery/17.jpg
  MVCDemos/Content/images/Gallery/20.jpg
  MVCDemos/Content/images/Gallery/21.jpg
  MVCDemos/Content/images/Gallery/22.jpg
  MVCDemos/Content/images/Gallery/23.jpg
  MVCDemos/Controllers/TileViewController.cs
  MVCDemos/Models/SampleData/TileViewItems.cs
  MVCDemos/Models/TileViewItem.cs
  MVCDemos/Views/TileView/Basics.cshtml
  NetCoreDemos/Controllers/TileViewController.cs
  NetCoreDemos/Models/SampleData/TileViewItems.cs
  NetCoreDemos/Models/TileViewItem.cs
  NetCoreDemos/Views/TileView/Basics.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TileView/Basics.css
  NetCoreDemos/wwwroot/images/Gallery/12.jpg
  NetCoreDemos/wwwroot/images/Gallery/14.jpg
  NetCoreDemos/wwwroot/images/Gallery/17.jpg
  NetCoreDemos/wwwroot/images/Gallery/20.jpg
  NetCoreDemos/wwwroot/images/Gallery/21.jpg
  NetCoreDemos/wwwroot/images/Gallery/22.jpg
  NetCoreDemos/wwwroot/images/Gallery/23.jpg
Labels: cherry-pick, 22_2

#2388 Tooltip: update demo description
  JSDemos/Demos/Tooltip/Overview/description.md
  JSDemos/Demos/Tooltip/Overview/jQuery/description.md
Labels: 22_2

#2389 Tooltip: update demo description (#2388)
  JSDemos/Demos/Tooltip/Overview/description.md
  JSDemos/Demos/Tooltip/Overview/jQuery/description.md
Labels: cherry-pick, 23_1

#2393 Pin html-react-parser version
  package-lock.json
  package.json
Labels: 21_2, force all tests

#2391 TileView: Add ASP.NET demos (Directions)
  MVCDemos/Content/DemosStyles/TileView/Directions.css
  MVCDemos/Controllers/TileViewController.cs
  MVCDemos/Views/TileView/Directions.cshtml
  NetCoreDemos/Controllers/TileViewController.cs
  NetCoreDemos/Views/TileView/Directions.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TileView/Directions.css
Labels: 23_1

#2392 TileView: Add ASP.NET demos (Directions)
  MVCDemos/Content/DemosStyles/TileView/Directions.css
  MVCDemos/Controllers/TileViewController.cs
  MVCDemos/Views/TileView/Directions.cshtml
  NetCoreDemos/Controllers/TileViewController.cs
  NetCoreDemos/Views/TileView/Directions.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TileView/Directions.css
Labels: cherry-pick, 22_2

#2394 TileView: Add ASP.NET demos (Item Template)
  MVCDemos/Content/DemosStyles/TileView/ItemTemplate.css
  MVCDemos/Controllers/TileViewController.cs
  MVCDemos/Views/TileView/ItemTemplate.cshtml
  NetCoreDemos/Controllers/TileViewController.cs
  NetCoreDemos/Views/TileView/ItemTemplate.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TileView/ItemTemplate.css
Labels: 23_1

#2395 TileView: Add ASP.NET demos (Item Template)
  MVCDemos/Content/DemosStyles/TileView/ItemTemplate.css
  MVCDemos/Controllers/TileViewController.cs
  MVCDemos/Views/TileView/ItemTemplate.cshtml
  NetCoreDemos/Controllers/TileViewController.cs
  NetCoreDemos/Views/TileView/ItemTemplate.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TileView/ItemTemplate.css
Labels: cherry-pick, 22_2

#2396 Copy shared file without rebuild Mvc
  gulpfile.js/index.js
  gulpfile.js/shared.js
  package.json
Labels: 22_2

#2404 DropDownBox: Fix selection issue in the Single Selection demo
  JSDemos/Demos/DropDownBox/SingleSelection/jQuery/index.js
Labels: cherry-pick, 22_2

#2397 Bubble Chart: Update etalon
  testing/etalons/Charts-Bubble.png
Labels: 22_2

#2400 Bubble Chart: Update etalon
  testing/etalons/Charts-Bubble.png
Labels: cherry-pick, 21_2

#2405 TreeList LoadDataOnDemand Demo: Load data from Sources publish subfoder
  NetCoreDemos/Controllers/ApiControllers/TreeListDataController.cs
Labels: 23_1

#2406 TreeList LoadDataOnDemand Demo: Load data from Sources publish subfoder
  NetCoreDemos/Controllers/ApiControllers/TreeListDataController.cs
Labels: cherry-pick, 22_2

#2408 Extract Selection to a separate object
  JSDemos/Demos/DataGrid/RowSelection/Vue/App.vue
Labels: cherry-pick, 23_1

#2407 Extract Selection to a separate object
  JSDemos/Demos/DataGrid/RowSelection/Vue/App.vue
Labels: 22_2

#2409 SelectBox GroupedItems demo: use Newtonsoft.Json to support MVC
  MVCDemos/Views/SelectBox/GroupedItems.cshtml
  NetCoreDemos/Views/SelectBox/GroupedItems.cshtml
Labels: cherry-pick, 22_2

#2414 TileView demos: include MVC files to csproj
  MVCDemos/DevExtreme.MVC.Demos.csproj
Labels: 23_1

#2413 TileView demos: include MVC files to csproj
  MVCDemos/DevExtreme.MVC.Demos.csproj
Labels: cherry-pick, 22_2

#2417 TileView ASP demos: update csproj and menuMeta
  JSDemos/menuMeta.json
  MVCDemos/DevExtreme.MVC.Demos.csproj
Labels: 22_2

#2418 TileView ASP demos: update csproj and menuMeta
  JSDemos/menuMeta.json
  MVCDemos/DevExtreme.MVC.Demos.csproj
Labels: cherry-pick, 23_1

#2419 ReadMe: update paragraph about ASP.NET demos
  README.md
Labels: 23_1

#2420 DataGrid: update incorrect syntax in Vue demos
  JSDemos/Demos/DataGrid/CascadingLookups/Vue/App.vue
  JSDemos/Demos/DataGrid/CustomEditors/Vue/App.vue
Labels: 22_2

#2422 Popup: remove unused button from markup in 'Scrolling' demo
  JSDemos/Demos/Popup/Scrolling/jQuery/index.html
Labels: 23_1

#2425 DataGrid: update incorrect syntax in Vue demos (#2420)
  JSDemos/Demos/DataGrid/CascadingLookups/Vue/App.vue
  JSDemos/Demos/DataGrid/CustomEditors/Vue/App.vue
Labels: cherry-pick, 23_1

#2424 Popup: remove unused button from markup in 'Scrolling' demo
  JSDemos/Demos/Popup/Scrolling/jQuery/index.html
Labels: cherry-pick, 22_2
