Repository DevExpress/devextreme-demos, pull requests merged in 2023-03, with the labels that each got.

#2477 CI: Setup dotnet 5, update actions to v3
  .github/workflows/CI.yml
  .github/workflows/unit_tests.yml
Labels: 21_1

#2478 CI: Setup dotnet 5, update actions to v3
  .github/workflows/CI.yml
  .github/workflows/unit_tests.yml
Labels: 20_2

#2458 The Column type is added
  JSDemos/Demos/DataGrid/CascadingLookups/Angular/app/app.component.ts
Labels: 22_2

#2472 Update FileUploader security for NetCore/Mvc
  JSDemos/menuMeta.json
  MVCDemos/Controllers/FileUploaderController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/FileUploader/ChunkMetadata.cs
  NetCoreDemos/Controllers/FileUploaderController.cs
  NetCoreDemos/Models/FileUploader/ChunkMetadata.cs
Labels: 20_2, cherry-pick

#2471 Update FileUploader security for NetCore/Mvc
  JSDemos/menuMeta.json
  MVCDemos/Controllers/FileUploaderController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/FileUploader/ChunkMetadata.cs
  NetCoreDemos/Controllers/FileUploaderController.cs
  NetCoreDemos/Models/FileUploader/ChunkMetadata.cs
Labels: 21_1, cherry-pick

#2474 Gauges: update Overview demo with centerTemplate
  JSDemos/Demos/Gauges/Overview/Angular/app/app.component.css
  JSDemos/Demos/Gauges/Overview/Angular/app/app.component.html
  JSDemos/Demos/Gauges/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Gauges/Overview/AngularJS/index.html
  JSDemos/Demos/Gauges/Overview/AngularJS/index.js
  JSDemos/Demos/Gauges/Overview/AngularJS/styles.css
  JSDemos/Demos/Gauges/Overview/Knockout/index.html
  JSDemos/Demos/Gauges/Overview/Knockout/index.js
  JSDemos/Demos/Gauges/Overview/Knockout/styles.css
  JSDemos/Demos/Gauges/Overview/React/App.js
  JSDemos/Demos/Gauges/Overview/React/styles.css
  JSDemos/Demos/Gauges/Overview/Vue/App.vue
  JSDemos/Demos/Gauges/Overview/Vue/styles.css
  JSDemos/Demos/Gauges/Overview/jQuery/index.html
  JSDemos/Demos/Gauges/Overview/jQuery/index.js
  JSDemos/Demos/Gauges/Overview/jQuery/styles.css
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/Gauges/Overview.css
  MVCDemos/Views/Gauges/Overview.cshtml
  NetCoreDemos/Views/Gauges/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Gauges/Overview.css
  testing/etalons/Gauges-Overview.png
Labels: 23_1

#2479 Gauges: update title demo with centerTemplate option
  JSDemos/Demos/Gauges/GaugeTitleCustomized/Angular/app/app.component.css
  JSDemos/Demos/Gauges/GaugeTitleCustomized/Angular/app/app.component.html
  JSDemos/Demos/Gauges/GaugeTitleCustomized/React/App.js
  JSDemos/Demos/Gauges/GaugeTitleCustomized/React/styles.css
  JSDemos/Demos/Gauges/GaugeTitleCustomized/Vue/App.vue
  JSDemos/Demos/Gauges/GaugeTitleCustomized/jQuery/index.js
  JSDemos/Demos/Gauges/GaugeTitleCustomized/jQuery/styles.css
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/Gauges/GaugeTitleCustomized.css
  MVCDemos/Views/Gauges/GaugeTitleCustomized.cshtml
  NetCoreDemos/Views/Gauges/GaugeTitleCustomized.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Gauges/GaugeTitleCustomized.css
  testing/etalons/Gauges-GaugeTitleCustomized.png
Labels: 23_1

#2485 List: removes repaintChangesOnly props from the demo
  JSDemos/Demos/List/ItemDragging/Angular/app/app.component.html
  JSDemos/Demos/List/ItemDragging/React/App.js
  JSDemos/Demos/List/ItemDragging/Vue/App.vue
  JSDemos/Demos/List/ItemDragging/jQuery/index.js
  JSDemos/Demos/SelectBox/GroupedItems/Vue/App.vue
Labels: 23_1

#2483 Change the icon path in Angular demo
  JSDemos/Demos/Common/CustomTextEditorButtons/Angular/app/app.component.ts
Labels: 22_2

#2484 Change the icon path in Angular demo
  JSDemos/Demos/Common/CustomTextEditorButtons/Angular/app/app.component.ts
Labels: cherry-pick, 23_1

#2487 HtmlEditor: Replace the data in the htmlEditor demo with the actual data
  JSDemos/Demos/HtmlEditor/Overview/Angular/app/app.service.ts
  JSDemos/Demos/HtmlEditor/Overview/AngularJS/data.js
  JSDemos/Demos/HtmlEditor/Overview/React/data.js
  JSDemos/Demos/HtmlEditor/Overview/Vue/data.js
  JSDemos/Demos/HtmlEditor/Overview/jQuery/data.js
  MVCDemos/Views/HtmlEditor/Overview.cshtml
  NetCoreDemos/Views/HtmlEditor/Overview.cshtml
  testing/etalons/HtmlEditor-Overview.png
Labels: 23_1

#2488 Gauge: fix demo with center template
  JSDemos/Demos/Gauges/GaugeTitleCustomized/Angular/app/app.component.html
  JSDemos/Demos/Gauges/GaugeTitleCustomized/React/App.js
  JSDemos/Demos/Gauges/GaugeTitleCustomized/Vue/App.vue
  JSDemos/Demos/Gauges/GaugeTitleCustomized/jQuery/index.js
  MVCDemos/Views/Gauges/GaugeTitleCustomized.cshtml
  NetCoreDemos/Views/Gauges/GaugeTitleCustomized.cshtml
  testing/etalons/Gauges-GaugeTitleCustomized.png
Labels: 23_1

#2491 List: removes repaintChangesOnly props from the demo (#2485)
  JSDemos/Demos/List/ItemDragging/Angular/app/app.component.html
  JSDemos/Demos/List/ItemDragging/React/App.js
  JSDemos/Demos/List/ItemDragging/Vue/App.vue
  JSDemos/Demos/List/ItemDragging/jQuery/index.js
  JSDemos/Demos/SelectBox/GroupedItems/Vue/App.vue
Labels: cherry-pick, 22_2

#2492 HtmlEditor: Replace the data in the htmlEditor demo with the actual data (#2487)
  JSDemos/Demos/HtmlEditor/Overview/Angular/app/app.service.ts
  JSDemos/Demos/HtmlEditor/Overview/AngularJS/data.js
  JSDemos/Demos/HtmlEditor/Overview/React/data.js
  JSDemos/Demos/HtmlEditor/Overview/Vue/data.js
  JSDemos/Demos/HtmlEditor/Overview/jQuery/data.js
  MVCDemos/Views/HtmlEditor/Overview.cshtml
  NetCoreDemos/Views/HtmlEditor/Overview.cshtml
  testing/etalons/HtmlEditor-Overview.png
Labels: cherry-pick, 22_2

#2486 Popup: update scrolling demo
  JSDemos/Demos/Popup/Scrolling/Angular/app/app.component.css
  JSDemos/Demos/Popup/Scrolling/Angular/app/app.component.html
  JSDemos/Demos/Popup/Scrolling/Angular/app/app.component.ts
  JSDemos/Demos/Popup/Scrolling/React/App.js
  JSDemos/Demos/Popup/Scrolling/React/styles.css
  JSDemos/Demos/Popup/Scrolling/Vue/App.vue
  JSDemos/Demos/Popup/Scrolling/jQuery/data.js
  JSDemos/Demos/Popup/Scrolling/jQuery/index.html
  JSDemos/Demos/Popup/Scrolling/jQuery/index.js
  JSDemos/Demos/Popup/Scrolling/jQuery/styles.css
  JSDemos/images/Popup-Scrolling-Image.jpg
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/Popup/Scrolling.css
  MVCDemos/Content/images/Popup-Scrolling-Image.jpg
  MVCDemos/Views/Popup/Scrolling.cshtml
  NetCoreDemos/Views/Popup/Scrolling.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Popup/Scrolling.css
  NetCoreDemos/wwwroot/images/Popup-Scrolling-Image.jpg
  testing/etalons/Popup-Scrolling.png
  testing/widgets/popup/Scrolling.test.js
  testing/widgets/popup/etalons/popup with scrollable container.png
  testing/widgets/popup/etalons/popup with scrollview.png
Labels: 23_1

#2494 Chart & Dialogs: get rid of testcafe warnings in visual tests
  JSDemos/Demos/List/ListSelection/Angular/app/app.component.html
  JSDemos/Demos/List/ListSelection/Angular/app/app.component.ts
  testing/widgets/charts/Crosshair.test.js
  testing/widgets/charts/etalons/charts_crosshair.png
  testing/widgets/common/DialogsAndNotificationsOverview.test.js
Labels: 23_1

#2489 Modifying the Form - Validation demo
  JSDemos/Demos/Form/Validation/Angular/app/app.component.html
  JSDemos/Demos/Form/Validation/Angular/app/app.component.ts
  JSDemos/Demos/Form/Validation/AngularJS/index.js
  JSDemos/Demos/Form/Validation/React/App.js
  JSDemos/Demos/Form/Validation/Vue/App.vue
  JSDemos/Demos/Form/Validation/jQuery/index.js
  MVCDemos/Views/Form/Validation.cshtml
  NetCoreDemos/Views/Form/Validation.cshtml
  testing/etalons/Form-Validation.png
Labels: 22_2

#2495 Popup demo: revert images
  JSDemos/images/Popup-Scrolling-Image.jpg
  MVCDemos/Content/images/Popup-Scrolling-Image.jpg
  NetCoreDemos/wwwroot/images/Popup-Scrolling-Image.jpg
Labels: 23_1

#2496 Popup scrolling: fix remarks after designer review
  JSDemos/Demos/Popup/Scrolling/Angular/app/app.component.html
  JSDemos/Demos/Popup/Scrolling/Angular/app/app.component.ts
  JSDemos/Demos/Popup/Scrolling/React/App.js
  JSDemos/Demos/Popup/Scrolling/Vue/App.vue
  JSDemos/Demos/Popup/Scrolling/jQuery/index.js
  MVCDemos/Views/Popup/Scrolling.cshtml
  NetCoreDemos/Views/Popup/Scrolling.cshtml
Labels: 23_1

#2498 Popup: update 'Scrolling' demo description
  JSDemos/Demos/Popup/Scrolling/description.md
  JSDemos/menuMeta.json
Labels: 23_1

#2501 TileView: improve CSP style-src directive 'unsafe-inline' in demos (#2497)
  JSDemos/Demos/TileView/Basics/AngularJS/index.js
  JSDemos/Demos/TileView/Basics/Knockout/index.js
  JSDemos/Demos/TileView/Basics/jQuery/index.js
  JSDemos/Demos/TileView/Directions/AngularJS/index.js
  JSDemos/Demos/TileView/Directions/Knockout/index.js
  JSDemos/Demos/TileView/Directions/jQuery/index.js
  JSDemos/Demos/TileView/ItemTemplate/jQuery/index.js
Labels: cherry-pick, 22_2

#2500 Circular Gauge: update 'Title And Center Label Customized' demo descr…
  JSDemos/Demos/Gauges/GaugeTitleCustomized/React/description.md
  JSDemos/Demos/Gauges/GaugeTitleCustomized/description.md
  JSDemos/Demos/Gauges/Overview/Angular/description.md
  JSDemos/Demos/Gauges/Overview/React/description.md
  JSDemos/Demos/Gauges/Overview/Vue/description.md
  JSDemos/Demos/Gauges/Overview/jQuery/description.md
  JSDemos/menuMeta.json
Labels: 23_1

#2503 Editor Appearance Variants: Apply styling mode to options section editors
  JSDemos/Demos/Common/EditorAppearanceVariants/Angular/app/app.component.html
  JSDemos/Demos/Common/EditorAppearanceVariants/React/App.js
  JSDemos/Demos/Common/EditorAppearanceVariants/Vue/App.vue
Labels: cherry-pick, 22_2

#2473 PieChart: add demo with custom styles (patterns, gradients)
  JSDemos/Demos/Charts/CustomLegendMarkers/Angular/app/app.component.ts
  JSDemos/Demos/Charts/PieWithCustomStyles/Angular/app/app.component.css
  JSDemos/Demos/Charts/PieWithCustomStyles/Angular/app/app.component.html
  JSDemos/Demos/Charts/PieWithCustomStyles/Angular/app/app.component.ts
  JSDemos/Demos/Charts/PieWithCustomStyles/Angular/app/app.service.ts
  JSDemos/Demos/Charts/PieWithCustomStyles/Angular/index.html
  JSDemos/Demos/Charts/PieWithCustomStyles/React/App.js
  JSDemos/Demos/Charts/PieWithCustomStyles/React/data.js
  JSDemos/Demos/Charts/PieWithCustomStyles/React/index.html
  JSDemos/Demos/Charts/PieWithCustomStyles/React/index.js
  JSDemos/Demos/Charts/PieWithCustomStyles/React/styles.css
  JSDemos/Demos/Charts/PieWithCustomStyles/Vue/App.vue
  JSDemos/Demos/Charts/PieWithCustomStyles/Vue/data.js
  JSDemos/Demos/Charts/PieWithCustomStyles/Vue/index.html
  JSDemos/Demos/Charts/PieWithCustomStyles/Vue/index.js
  JSDemos/Demos/Charts/PieWithCustomStyles/description.md
  JSDemos/Demos/Charts/PieWithCustomStyles/jQuery/data.js
  JSDemos/Demos/Charts/PieWithCustomStyles/jQuery/index.html
  JSDemos/Demos/Charts/PieWithCustomStyles/jQuery/index.js
  JSDemos/Demos/Charts/PieWithCustomStyles/jQuery/styles.css
  JSDemos/images/Charts/PieWithCustomStyles/diamond.svg
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/Charts/PieWithCustomStyles.css
  MVCDemos/Content/images/Charts/PieWithCustomStyles/diamond.svg
  MVCDemos/Controllers/ChartsController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/Charts/PieWithCustomStyles.cshtml
  NetCoreDemos/Controllers/ChartsController.cs
  NetCoreDemos/Views/Charts/PieWithCustomStyles.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Charts/PieWithCustomStyles.css
  NetCoreDemos/wwwroot/images/Charts/PieWithCustomStyles/diamond.svg
  testing/etalons/Charts-PieWithCustomStyles.png
  utils/bundle/index.js
Labels: 23_1

#2506 Chart: remove aggregateByCategory from demo
  JSDemos/Demos/Charts/DiscreteAggregation/Angular/app/app.component.html
  JSDemos/Demos/Charts/DiscreteAggregation/React/App.js
  JSDemos/Demos/Charts/DiscreteAggregation/Vue/App.vue
  JSDemos/Demos/Charts/DiscreteAggregation/jQuery/index.js
  MVCDemos/Views/Charts/DiscreteAggregation.cshtml
  NetCoreDemos/Views/Charts/DiscreteAggregation.cshtml
Labels: 23_1

#2509 Chart: change texts in custom style demo
  JSDemos/Demos/Charts/PieWithCustomStyles/Angular/app/app.component.ts
  JSDemos/Demos/Charts/PieWithCustomStyles/Angular/app/app.service.ts
  JSDemos/Demos/Charts/PieWithCustomStyles/React/App.js
  JSDemos/Demos/Charts/PieWithCustomStyles/React/data.js
  JSDemos/Demos/Charts/PieWithCustomStyles/Vue/App.vue
  JSDemos/Demos/Charts/PieWithCustomStyles/Vue/data.js
  JSDemos/Demos/Charts/PieWithCustomStyles/jQuery/data.js
  JSDemos/Demos/Charts/PieWithCustomStyles/jQuery/index.js
  JSDemos/menuMeta.json
  MVCDemos/Views/Charts/PieWithCustomStyles.cshtml
  NetCoreDemos/Views/Charts/PieWithCustomStyles.cshtml
  testing/etalons/Charts-PieWithCustomStyles.png
Labels: 23_1

#2510 Gauge: change texts for demo with center template
  JSDemos/Demos/Gauges/GaugeTitleCustomized/Angular/app/app.component.html
  JSDemos/Demos/Gauges/GaugeTitleCustomized/React/App.js
  JSDemos/Demos/Gauges/GaugeTitleCustomized/Vue/App.vue
  JSDemos/Demos/Gauges/GaugeTitleCustomized/jQuery/index.js
  JSDemos/menuMeta.json
  MVCDemos/Views/Gauges/GaugeTitleCustomized.cshtml
  NetCoreDemos/Views/Gauges/GaugeTitleCustomized.cshtml
  testing/etalons/Gauges-GaugeTitleCustomized.png
Labels: 23_1
