Repository DevExpress/devextreme-demos, pull requests merged in 2023-02, with the labels that each got.

#2430 Shared azure.file.system.js source file across file manager and upload demos
  .eslintignore
  .gitignore
  JSDemos/Demos/FileManager/AzureClientBinding/Angular/app/app.component.ts
  JSDemos/Demos/FileManager/AzureClientBinding/Angular/index.html
  JSDemos/Demos/FileManager/AzureClientBinding/React/App.js
  JSDemos/Demos/FileManager/AzureClientBinding/React/index.html
  JSDemos/Demos/FileManager/AzureClientBinding/Vue/App.vue
  JSDemos/Demos/FileManager/AzureClientBinding/Vue/index.html
  JSDemos/Demos/FileManager/AzureClientBinding/azure-file-system.d.ts
  JSDemos/Demos/FileManager/AzureClientBinding/azure-file-system.js
  JSDemos/Demos/FileManager/AzureClientBinding/description.md
  JSDemos/Demos/FileManager/AzureClientBinding/jQuery/index.html
  JSDemos/Demos/FileManager/AzureClientBinding/jQuery/index.js
  JSDemos/Demos/FileUploader/AzureDirectUploading/Angular/app/app.component.ts
  JSDemos/Demos/FileUploader/AzureDirectUploading/Angular/index.html
  JSDemos/Demos/FileUploader/AzureDirectUploading/React/App.js
  JSDemos/Demos/FileUploader/AzureDirectUploading/React/index.html
  JSDemos/Demos/FileUploader/AzureDirectUploading/Vue/App.vue
  JSDemos/Demos/FileUploader/AzureDirectUploading/Vue/index.html
  JSDemos/Demos/FileUploader/AzureDirectUploading/azure-file-system.js
  JSDemos/Demos/FileUploader/AzureDirectUploading/description.md
  JSDemos/Demos/FileUploader/AzureDirectUploading/jQuery/index.html
  JSDemos/Demos/FileUploader/AzureDirectUploading/jQuery/index.js
  JSDemos/menuMeta.json
  JSDemos/shared/azure.file.system.ts
  JSDemos/shared/tsconfig.json
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Scripts/utils/azure-file-system.js
  MVCDemos/Views/FileManager/AzureClientBinding.cshtml
  MVCDemos/Views/FileUploader/AzureDirectUploading.cshtml
  NetCoreDemos/Views/FileManager/AzureClientBinding.cshtml
  NetCoreDemos/Views/FileUploader/AzureDirectUploading.cshtml
  NetCoreDemos/wwwroot/Descr/FileManager/AzureClientBinding.md
  NetCoreDemos/wwwroot/utils/azure-file-system.js
  gulpfile.js/index.js
  gulpfile.js/js.js
  gulpfile.js/mvc.js
  gulpfile.js/shared.js
  package.json
  utils/copy-shared-resources/copy.js
  utils/copy-shared-resources/files-js.json
  utils/copy-shared-resources/files-mvc.json
Labels: cherry-pick, 23_1

#2429 v23.1 Added integer format for NumberBox - Formatting demo
  JSDemos/Demos/NumberBox/Formatting/Angular/app/app.component.html
  JSDemos/Demos/NumberBox/Formatting/React/App.js
  JSDemos/Demos/NumberBox/Formatting/Vue/App.vue
  JSDemos/Demos/NumberBox/Formatting/jQuery/index.html
  JSDemos/Demos/NumberBox/Formatting/jQuery/index.js
  MVCDemos/Views/NumberBox/Formatting.cshtml
  NetCoreDemos/Views/NumberBox/Formatting.cshtml
  testing/etalons/NumberBox-Formatting.png
Labels: 23_1

#2431 v22.2 Added integer format for NumberBox - Formatting demo
  JSDemos/Demos/NumberBox/Formatting/Angular/app/app.component.html
  JSDemos/Demos/NumberBox/Formatting/React/App.js
  JSDemos/Demos/NumberBox/Formatting/Vue/App.vue
  JSDemos/Demos/NumberBox/Formatting/jQuery/index.html
  JSDemos/Demos/NumberBox/Formatting/jQuery/index.js
  MVCDemos/Views/NumberBox/Formatting.cshtml
  NetCoreDemos/Views/NumberBox/Formatting.cshtml
  testing/etalons/NumberBox-Formatting.png
Labels: cherry-pick, 22_2

#2432 Toolbar: Update margin right
  JSDemos/Demos/Toolbar/Adaptability/Angular/app/app.component.css
  JSDemos/Demos/Toolbar/Adaptability/React/styles.css
  JSDemos/Demos/Toolbar/Adaptability/Vue/App.vue
  JSDemos/Demos/Toolbar/Adaptability/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Toolbar/Adaptability.css
  NetCoreDemos/wwwroot/css/DemosStyles/Toolbar/Adaptability.css
  testing/etalons/Toolbar-Adaptability.png
Labels: 23_1

#2435 NumberBox: update Formatting demo description
  JSDemos/Demos/NumberBox/Formatting/description.md
Labels: 22_2

#2436 NumberBox: update Formatting demo description (#2435)
  JSDemos/Demos/NumberBox/Formatting/description.md
Labels: cherry-pick, 23_1

#2441 Exclude dx.all.debug bundle from MVC.Demos.csproj
  MVCDemos/DevExtreme.MVC.Demos.csproj
Labels: 22_2

#2401 TreeList: Transform the response data in the Load Data on Demand demo
  JSDemos/Demos/TreeList/LoadDataOnDemand/jQuery/index.js
  MVCDemos/Views/TreeList/LoadDataOnDemand.cshtml
  NetCoreDemos/Views/TreeList/LoadDataOnDemand.cshtml
Labels: 23_1

#2402 TreeList: Transform the response data in the Load Data on Demand demo
  JSDemos/Demos/TreeList/LoadDataOnDemand/jQuery/index.js
  MVCDemos/Views/TreeList/LoadDataOnDemand.cshtml
  NetCoreDemos/Views/TreeList/LoadDataOnDemand.cshtml
Labels: cherry-pick, 22_2

#2446 CI: update vue workflow
  .github/workflows/visual_tests_frameworks.yml
Labels: force all tests, 23_1

#2448 Fix Slider and RangeSlider MVC/NetCore demos
  MVCDemos/Views/RangeSlider/Overview.cshtml
  MVCDemos/Views/Slider/Overview.cshtml
  NetCoreDemos/Views/RangeSlider/Overview.cshtml
  NetCoreDemos/Views/Slider/Overview.cshtml
Labels: 23_1

#2451 Update README.md
  README.md
Labels: 23_1

#2453 dxScheduler - replace deprecated type in angular approach
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.ts
Labels: 23_1

#2454 dxScheduler - replace deprecated type in angular approach
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.ts
Labels: cherry-pick, 22_2

#2456 CI: fix dependencies
  .github/workflows/visual_tests_frameworks.yml
Labels: 22_2

#2457 Update README.md
  README.md
Labels: cherry-pick, 22_2

#2463 CI: fix Vue build
  .github/workflows/visual_tests_frameworks.yml
Labels: 23_1

#2464 CI: fix Vue build
  .github/workflows/visual_tests_frameworks.yml
Labels: cherry-pick, 22_2

#2449 Update FileUploader security for NetCore/Mvc
  JSDemos/menuMeta.json
  MVCDemos/Controllers/FileUploaderController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/FileUploader/ChunkMetadata.cs
  NetCoreDemos/Controllers/FileUploaderController.cs
  NetCoreDemos/Models/FileUploader/ChunkMetadata.cs
Labels: 22_2

#2465 Update FileUploader security for NetCore/Mvc (#2449)
  JSDemos/menuMeta.json
  MVCDemos/Controllers/FileUploaderController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/FileUploader/ChunkMetadata.cs
  NetCoreDemos/Controllers/FileUploaderController.cs
  NetCoreDemos/Models/FileUploader/ChunkMetadata.cs
Labels: cherry-pick, 23_1

#2469 Update FileUploader security for NetCore/Mvc
  JSDemos/menuMeta.json
  MVCDemos/Controllers/FileUploaderController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/FileUploader/ChunkMetadata.cs
  NetCoreDemos/Controllers/FileUploaderController.cs
  NetCoreDemos/Models/FileUploader/ChunkMetadata.cs
Labels: cherry-pick, 22_1

#2461 TagBox - Overview: Prevent users from entering duplicate custom values
  JSDemos/Demos/TagBox/Overview/Angular/app/app.component.ts
  JSDemos/Demos/TagBox/Overview/React/App.js
  JSDemos/Demos/TagBox/Overview/Vue/App.vue
  JSDemos/Demos/TagBox/Overview/jQuery/index.js
  MVCDemos/Views/TagBox/Overview.cshtml
  NetCoreDemos/Views/TagBox/Overview.cshtml
Labels: 23_1

#2462 TagBox - Overview: Prevent users from entering duplicate custom values
  JSDemos/Demos/TagBox/Overview/Angular/app/app.component.ts
  JSDemos/Demos/TagBox/Overview/React/App.js
  JSDemos/Demos/TagBox/Overview/Vue/App.vue
  JSDemos/Demos/TagBox/Overview/jQuery/index.js
  MVCDemos/Views/TagBox/Overview.cshtml
  NetCoreDemos/Views/TagBox/Overview.cshtml
Labels: cherry-pick, 22_2
