Repository DevExpress/devextreme-demos, pull requests merged in 2023-12, with the labels that each got.

#2956 DataGrid - remove height warning from known list
  JSDemos/Demos/TreeList/Adaptability/Angular/app/app.component.css
  JSDemos/Demos/TreeList/Adaptability/React/styles.css
  JSDemos/Demos/TreeList/Adaptability/ReactJs/styles.css
  JSDemos/Demos/TreeList/Adaptability/Vue/App.vue
  JSDemos/Demos/TreeList/Adaptability/jQuery/styles.css
  JSDemos/Demos/TreeList/CustomizeKeyboardNavigation/Angular/app/app.component.css
  JSDemos/Demos/TreeList/CustomizeKeyboardNavigation/React/styles.css
  JSDemos/Demos/TreeList/CustomizeKeyboardNavigation/ReactJs/styles.css
  JSDemos/Demos/TreeList/CustomizeKeyboardNavigation/Vue/styles.css
  JSDemos/Demos/TreeList/CustomizeKeyboardNavigation/jQuery/index.html
  JSDemos/Demos/TreeList/CustomizeKeyboardNavigation/jQuery/styles.css
  JSDemos/Demos/TreeList/FormEditing/Angular/app/app.component.css
  JSDemos/Demos/TreeList/FormEditing/React/App.tsx
  JSDemos/Demos/TreeList/FormEditing/React/styles.css
  JSDemos/Demos/TreeList/FormEditing/ReactJs/App.js
  JSDemos/Demos/TreeList/FormEditing/ReactJs/styles.css
  JSDemos/Demos/TreeList/FormEditing/Vue/App.vue
  JSDemos/Demos/TreeList/FormEditing/jQuery/styles.css
  JSDemos/Demos/TreeList/PopupEditing/React/App.tsx
  JSDemos/Demos/TreeList/PopupEditing/ReactJs/App.js
  JSDemos/Demos/TreeList/SingleRowSelection/React/App.tsx
  JSDemos/Demos/TreeList/SingleRowSelection/ReactJs/App.js
  MVCDemos/Content/DemosStyles/TreeList/Adaptability.css
  MVCDemos/Content/DemosStyles/TreeList/CustomizeKeyboardNavigation.css
  MVCDemos/Content/DemosStyles/TreeList/FormEditing.css
  NetCoreDemos/wwwroot/css/DemosStyles/TreeList/Adaptability.css
  NetCoreDemos/wwwroot/css/DemosStyles/TreeList/CustomizeKeyboardNavigation.css
  NetCoreDemos/wwwroot/css/DemosStyles/TreeList/FormEditing.css
  testing/known-warnings.json
Labels: 23_2

#3061 Temporary skip broken map tests
  testing/common.test.js
Labels: 23_1

#3065 Fix strange SystemJs behaviour when it loads module with empty export
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.js
Labels: cherry-pick, force all tests, 22_2

#3063 Chart - Remove rounding values on translation for line/area series(T1195064)
  testing/etalons/Charts-Annotation.png
  testing/etalons/Charts-Area.png
  testing/etalons/Charts-AreaSparklines.png
  testing/etalons/Charts-AxisCustomPosition.png
  testing/etalons/Charts-AxisLabelsOverlapping.png
  testing/etalons/Charts-Bubble.png
  testing/etalons/Charts-Crosshair.png
  testing/etalons/Charts-CustomLegendMarkers.png
  testing/etalons/Charts-ErrorBars.png
  testing/etalons/Charts-HoverMode.png
  testing/etalons/Charts-Line.png
  testing/etalons/Charts-LoadDataOnDemand.png
  testing/etalons/Charts-LogarithmicVsLinearAxes.png
  testing/etalons/Charts-MultipleAxes.png
  testing/etalons/Charts-MultiplePanes.png
  testing/etalons/Charts-MultipleSeriesSelection.png
  testing/etalons/Charts-NullPointSupport.png
  testing/etalons/Charts-Overview.png
  testing/etalons/Charts-ParetoChart.png
  testing/etalons/Charts-PointImage.png
  testing/etalons/Charts-PointsAggregation.png
  testing/etalons/Charts-PointsAggregationFinancialChart.png
  testing/etalons/Charts-RangeArea.png
  testing/etalons/Charts-Scatter.png
  testing/etalons/Charts-SeriesTemplates.png
  testing/etalons/Charts-ServerSideDataProcessing.png
  testing/etalons/Charts-SimpleSparklines.png
  testing/etalons/Charts-Spline.png
  testing/etalons/Charts-SplineArea.png
  testing/etalons/Charts-StepArea.png
  testing/etalons/Charts-StepLine.png
  testing/etalons/Charts-Strips.png
  testing/etalons/Charts-ZoomingAndScrolling.png
  testing/etalons/Charts-ZoomingAndScrollingAPI.png
  testing/etalons/Charts-ZoomingOnAreaSelection.png
  testing/etalons/DataGrid-CellCustomization.png
  testing/etalons/RangeSelector-ChartOnBackgroundWithSeriesTemplate.png
  testing/etalons/RangeSelector-CustomizedChartOnBackground.png
  testing/etalons/RangeSelector-DateTimeScale.png
  testing/etalons/RangeSelector-LogarithmicScale.png
  testing/etalons/RangeSelector-NumericScale.png
  testing/widgets/charts/etalons/charts_crosshair.png
  testing/widgets/charts/etalons/charts_drag.png
  testing/widgets/charts/etalons/charts_overview_tooltip.png
  testing/widgets/charts/etalons/range_selector_click_to_empty_place.png
  testing/widgets/charts/etalons/range_selector_slider_drag.png
  testing/widgets/charts/etalons/reset_zooming_by_selection.png
  testing/widgets/charts/etalons/zooming_by_selection.png
Labels: cherry-pick, 23_1

#3057 dxScheduler - made height of icons to one view
  testing/etalons/Scheduler-AllDayPanelMode.png
Labels: 23_2

#3068 Readme.md - Added a description of how to launch demos on Mac OS
  README.md
Labels: 23_2

#3066 Revert adding "check generated demos" workflow
  .github/workflows/visual_tests_frameworks.yml
  package-lock.json
  package.json
  testing/common.test.js
  utils/ts-to-js-converter/cli.ts
  utils/ts-to-js-converter/converter.ts
  utils/ts-to-js-converter/types.ts
Labels: 23_1

#3069 Popup Overview Angular Demo: use arrow functions to drop the 'that' reference
  JSDemos/Demos/Popup/Overview/Angular/app/app.component.ts
Labels: 23_2

#3070 Chart ZoomingAndScrollingAPI demo: fix range is not updated onHandleMove
  JSDemos/Demos/Charts/ZoomingAndScrollingAPI/React/App.tsx
  JSDemos/Demos/Charts/ZoomingAndScrollingAPI/ReactJs/App.js
Labels: 23_2

#3072 Calendar: fix appearance on mobile devices
  JSDemos/Demos/Calendar/MultipleSelection/Angular/app/app.component.css
  JSDemos/Demos/Calendar/MultipleSelection/Angular/app/app.component.html
  JSDemos/Demos/Calendar/MultipleSelection/React/App.tsx
  JSDemos/Demos/Calendar/MultipleSelection/React/styles.css
  JSDemos/Demos/Calendar/MultipleSelection/ReactJs/App.js
  JSDemos/Demos/Calendar/MultipleSelection/ReactJs/styles.css
  JSDemos/Demos/Calendar/MultipleSelection/Vue/App.vue
  JSDemos/Demos/Calendar/MultipleSelection/jQuery/index.html
  JSDemos/Demos/Calendar/MultipleSelection/jQuery/styles.css
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.css
  JSDemos/Demos/Calendar/Overview/Angular/app/app.component.html
  JSDemos/Demos/Calendar/Overview/React/App.tsx
  JSDemos/Demos/Calendar/Overview/React/styles.css
  JSDemos/Demos/Calendar/Overview/ReactJs/App.js
  JSDemos/Demos/Calendar/Overview/ReactJs/styles.css
  JSDemos/Demos/Calendar/Overview/Vue/App.vue
  JSDemos/Demos/Calendar/Overview/jQuery/index.html
  JSDemos/Demos/Calendar/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Calendar/MultipleSelection.css
  MVCDemos/Content/DemosStyles/Calendar/Overview.css
  MVCDemos/Views/Calendar/MultipleSelection.cshtml
  MVCDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/Views/Calendar/MultipleSelection.cshtml
  NetCoreDemos/Views/Calendar/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Calendar/MultipleSelection.css
  NetCoreDemos/wwwroot/css/DemosStyles/Calendar/Overview.css
Labels: 23_2

#3071 TreeView: Remove skipping a11y tests
  testing/common.test.js
Labels: force all tests, 23_2

#3079 FileManagement - remove demo visual test for cloud demos
  testing/etalons/FileManager-AzureClientBinding.png
  testing/etalons/FileManager-AzureClientBinding_mask.png
  testing/etalons/FileManager-AzureServerBinding.png
  testing/etalons/FileManager-AzureServerBinding_mask.png
  testing/etalons/FileUploader-AzureDirectUploading.png
Labels: 23_2

#3084 Update etalons after Chrome update to version 120
  testing/etalons/Diagram-Adaptability.png
  testing/etalons/Diagram-CustomShapesWithTemplates.png
  testing/etalons/Diagram-CustomShapesWithTemplatesWithEditing.png
  testing/etalons/Diagram-ItemSelection.png
  testing/etalons/Diagram-NodesAndEdgesArrays.png
  testing/etalons/Diagram-NodesArrayHierarchicalStructure.png
  testing/etalons/Diagram-NodesArrayPlainStructure.png
  testing/etalons/Diagram-OperationRestrictions.png
  testing/etalons/Diagram-SimpleView.png
  testing/etalons/Diagram-WebAPIService.png
Labels: force all tests, 23_1

#3085 Update etalons after Chrome update to version 120
  testing/etalons/Diagram-Adaptability.png
  testing/etalons/Diagram-CustomShapesWithTemplatesWithEditing.png
  testing/etalons/Diagram-NodesAndEdgesArrays.png
  testing/etalons/Diagram-NodesArrayHierarchicalStructure.png
  testing/etalons/Diagram-NodesArrayPlainStructure.png
  testing/etalons/Diagram-OperationRestrictions.png
  testing/etalons/Diagram-WebAPIService.png
Labels: force all tests, 22_2

#3086 Update etalons after Chrome update to version 120
  testing/etalons/Charts-Bubble.png
  testing/etalons/Charts-ContinuousData.png
  testing/etalons/Charts-Crosshair.png
  testing/etalons/Charts-DiscreteData.png
  testing/etalons/Charts-InvertedChart.png
  testing/etalons/Charts-PeriodicData.png
  testing/etalons/Charts-PieWithAnnotations.png
  testing/etalons/Charts-PolarChartZoomingAndScrollingAPI.png
  testing/etalons/Charts-WindRose.png
  testing/etalons/Common-EditorsOverview.png
  testing/etalons/Diagram-Adaptability.png
  testing/etalons/Diagram-Containers.png
  testing/etalons/Diagram-CustomShapesWithIcons.png
  testing/etalons/Diagram-CustomShapesWithTemplates.png
  testing/etalons/Diagram-CustomShapesWithTemplatesWithEditing.png
  testing/etalons/Diagram-CustomShapesWithTexts.png
  testing/etalons/Diagram-ImagesInShapes.png
  testing/etalons/Diagram-ItemSelection.png
  testing/etalons/Diagram-NodesAndEdgesArrays.png
  testing/etalons/Diagram-NodesArrayHierarchicalStructure.png
  testing/etalons/Diagram-NodesArrayPlainStructure.png
  testing/etalons/Diagram-OperationRestrictions.png
  testing/etalons/Diagram-SimpleView.png
  testing/etalons/Diagram-UICustomization.png
  testing/etalons/Diagram-WebAPIService.png
  testing/etalons/Gallery-Overview.png
  testing/etalons/Gantt-ChartAppearance.png
  testing/etalons/Gantt-ContextMenu.png
  testing/etalons/Gantt-DataBinding.png
  testing/etalons/Gantt-ExportToPDF.png
  testing/etalons/Gantt-FilterRow.png
  testing/etalons/Gantt-HeaderFilter.png
  testing/etalons/Gantt-Overview.png
  testing/etalons/Gantt-Sorting.png
  testing/etalons/Gantt-StripLines.png
  testing/etalons/Gantt-TaskTemplate.png
  testing/etalons/Gantt-Toolbar.png
  testing/etalons/Gantt-Validation.png
  testing/etalons/Gauges-GaugeTitleCustomized.png
  testing/etalons/VectorMap-AreaWithLabelsAndTwoLegends.png
  testing/etalons/VectorMap-ColorsCustomization.png
  testing/etalons/VectorMap-CustomMapData.png
  testing/etalons/VectorMap-MultipleLayers.png
  testing/etalons/VectorMap-PieMarkers.png
  testing/etalons/VectorMap-TooltipHTMLSupport.png
  testing/widgets/datagrid/etalons/datagrid_batch_editing_2_desktop.png
Labels: force all tests, 22_1

#3088 FileManagement - Remove missed azure globals
  .eslintrc.js
Labels: 23_2

#3091 Update devextreme and devexpress deps in the lockfile
  package-lock.json
Labels: 23_2

#3093 CI: Branch 24_1
  JSDemos/menuMeta.json
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  package-lock.json
  package.json
Labels: 24_1
