Repository DevExpress/devextreme-demos, pull requests merged in 2023-05, with the labels that each got.

#2574 List 'Item Drag and Drop' Demo: Add the reorder event handler (#2551)
  JSDemos/Demos/List/ItemDragging/Angular/app/app.component.html
  JSDemos/Demos/List/ItemDragging/Angular/app/app.component.ts
  JSDemos/Demos/List/ItemDragging/Vue/App.vue
  JSDemos/Demos/List/ItemDragging/jQuery/index.js
  testing/widgets/list/ItemDragging.test.js
Labels: cherry-pick, 22_2

#2573 Calendar: use flex for navigation buttons container
  testing/etalons/Calendar-Overview.png
Labels: 23_1

#2576 Toolbar Demo: use icon 'back' instead of deprecated type 'back' for button
  JSDemos/Demos/Toolbar/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Toolbar/Overview/React/App.js
  JSDemos/Demos/Toolbar/Overview/Vue/App.vue
  JSDemos/Demos/Toolbar/Overview/jQuery/index.js
  MVCDemos/Views/Toolbar/Overview.cshtml
  NetCoreDemos/Views/Toolbar/Overview.cshtml
Labels: 23_1

#2578 Calendar: update etalon
  testing/etalons/Calendar-Overview.png
Labels: 23_1

#2579 Lookup "Handle Value Change": Fix datasource (#2522)
  MVCDemos/Views/Lookup/EventHandling.cshtml
  NetCoreDemos/Views/Lookup/EventHandling.cshtml
Labels: cherry-pick, 22_2

#2568 PivotGrid: update a demo related to headerFilter
  JSDemos/Demos/PivotGrid/HeaderFilter/description.md
Labels: 23_1

#2571 TreeList: update Column Chooser and Header Filter demos
  JSDemos/Demos/TreeList/ColumnChooser/description.md
  JSDemos/Demos/TreeList/UsingHeaderFilter/description.md
Labels: 23_1

#2582 Calendar: change range selection styles according to new design
  testing/etalons/Calendar-Overview.png
  testing/etalons/Map-ProvidersAndTypes_mask.png
Labels: 23_1

#2572 DataGrid: add Column Chooser and Header Filter demos
  JSDemos/Demos/DataGrid/ColumnChooser/description.md
  JSDemos/Demos/DataGrid/UsingHeaderFilter/description.md
Labels: 23_1

#2577 Toolbar demo: add accessibility attr for selectBox
  JSDemos/Demos/Toolbar/Adaptability/Angular/app/app.component.html
  JSDemos/Demos/Toolbar/Adaptability/React/App.js
  JSDemos/Demos/Toolbar/Adaptability/React/data.js
  JSDemos/Demos/Toolbar/Adaptability/Vue/App.vue
  JSDemos/Demos/Toolbar/Adaptability/jQuery/index.js
  JSDemos/Demos/Toolbar/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Toolbar/Overview/React/App.js
  JSDemos/Demos/Toolbar/Overview/Vue/App.vue
  JSDemos/Demos/Toolbar/Overview/jQuery/index.js
  MVCDemos/Views/Toolbar/Adaptability.cshtml
  MVCDemos/Views/Toolbar/Overview.cshtml
  NetCoreDemos/Views/Toolbar/Adaptability.cshtml
  NetCoreDemos/Views/Toolbar/Overview.cshtml
Labels: 23_1

#2587 List: update demo to demonstrate new selectByClick prop
  JSDemos/Demos/List/ListSelection/Angular/app/app.component.html
  JSDemos/Demos/List/ListSelection/Angular/app/app.component.ts
  JSDemos/Demos/List/ListSelection/React/App.js
  JSDemos/Demos/List/ListSelection/Vue/App.vue
  JSDemos/Demos/List/ListSelection/jQuery/index.html
  JSDemos/Demos/List/ListSelection/jQuery/index.js
  MVCDemos/Views/List/ListSelection.cshtml
  NetCoreDemos/Views/List/ListSelection.cshtml
  testing/etalons/List-ListSelection.png
  testing/widgets/list/ListSelection.test.js
  testing/widgets/list/etalons/List after change selectionMode to multiple.png
  testing/widgets/list/etalons/List after change selectionMode to none.png
  testing/widgets/list/etalons/List after change selectionMode to single.png
  testing/widgets/list/etalons/List after click on item, selectionMode=all.png
Labels: 23_1

#2590 File uploading demos "typo": should be type, not size (#2191)
  JSDemos/Demos/FileUploader/FileUploading/React/App.js
  JSDemos/Demos/FileUploader/FileUploading/Vue/App.vue
Labels: cherry-pick

#2591 Calendar: change selection color
  testing/etalons/Calendar-Overview.png
Labels: 23_1

#2595 DataGrid(T1163515): Update etalons after group panel border fix. (#2585)
  testing/etalons/DataGrid-ExcelJSExportMultipleGrids.png
  testing/etalons/DataGrid-Overview.png
  testing/etalons/DataGrid-PDFExportMultipleGrids.png
  testing/etalons/DataGrid-Row3RdPartyEngineTemplate.png
  testing/widgets/datagrid/etalons/datagrid_appearance_3_desktop.png
Labels: cherry-pick, 22_2

#2554 Store generated code in devextreme-vue repo
  .github/workflows/visual_tests_frameworks.yml
  .gitignore
Labels: force all tests

#2597 Adding controllers to the Drill-Down Chart demo (cherry pick (#2596))
  JSDemos/menuMeta.json
Labels: cherry-pick

#2599 DataGrid/TreeList - Update the "Using Header Filter" demo
  JSDemos/Demos/DataGrid/UsingHeaderFilter/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/UsingHeaderFilter/React/App.js
  JSDemos/Demos/DataGrid/UsingHeaderFilter/Vue/App.vue
  JSDemos/Demos/DataGrid/UsingHeaderFilter/jQuery/index.js
  JSDemos/Demos/TreeList/UsingHeaderFilter/Angular/app/app.component.html
  JSDemos/Demos/TreeList/UsingHeaderFilter/React/App.js
  JSDemos/Demos/TreeList/UsingHeaderFilter/Vue/App.vue
  JSDemos/Demos/TreeList/UsingHeaderFilter/jQuery/index.js
  MVCDemos/Views/DataGrid/UsingHeaderFilter.cshtml
  MVCDemos/Views/TreeList/UsingHeaderFilter.cshtml
  NetCoreDemos/Views/DataGrid/UsingHeaderFilter.cshtml
  NetCoreDemos/Views/TreeList/UsingHeaderFilter.cshtml
  testing/etalons/DataGrid-UsingHeaderFilter.png
  testing/etalons/TreeList-UsingHeaderFilter.png
Labels: 23_1

#2603 CI: use devextreme-dist package
  gulpfile.js/copy-common-asp-files.js
  index.html
  utils/templates/AngularJS/index.html
  utils/templates/jQuery/index.html
Labels: 23_1

#2602 PieChart: add utils file in demo with custom styles
  JSDemos/Demos/Charts/PieWithCustomStyles/React/App.js
  JSDemos/Demos/Charts/PieWithCustomStyles/React/utils.js
  JSDemos/Demos/Charts/PieWithCustomStyles/Vue/App.vue
  JSDemos/Demos/Charts/PieWithCustomStyles/Vue/utils.js
Labels: 23_1

#2601 Form - Overview: Remove in-line arrays in Vue
  JSDemos/Demos/Form/Overview/Vue/App.vue
Labels: 23_1

#2604 Form - Overview: Remove in-line arrays in Vue (#2601)
  JSDemos/Demos/Form/Overview/Vue/App.vue
Labels: cherry-pick, 22_2

#2589 CI: Fix 'get changed files' step
  .github/actions/get-changed-files/action.yml
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
Labels: 23_1

#2481 Linter - add `eslint-plugin-deprecation`
  .eslintrc.js
  .github/workflows/visual_tests_frameworks.yml
  JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.ts
  JSDemos/shared/azure.file.system.ts
  package-lock.json
  package.json
Labels: 23_1

#2607 Map: Update mask
  testing/etalons/Map-ProvidersAndTypes_mask.png
Labels: 23_1

#2584 Accessibility tests
  .eslintrc.js
  .github/workflows/visual_tests.yml
  .gitignore
  package-lock.json
  package.json
  testing/.eslintrc.js
  testing/common.test.js
  utils/axe-reporter/reporter.js
  utils/axe-reporter/template.md
  utils/visual-tests/matrix-test-helper.js
Labels: 23_1

#2611 Add DateRangeBox Overview demo
  JSDemos/Demos/DateRangeBox/Overview/Angular/app/app.component.css
  JSDemos/Demos/DateRangeBox/Overview/Angular/app/app.component.html
  JSDemos/Demos/DateRangeBox/Overview/Angular/app/app.component.ts
  JSDemos/Demos/DateRangeBox/Overview/Angular/index.html
  JSDemos/Demos/DateRangeBox/Overview/React/App.js
  JSDemos/Demos/DateRangeBox/Overview/React/index.html
  JSDemos/Demos/DateRangeBox/Overview/React/index.js
  JSDemos/Demos/DateRangeBox/Overview/React/styles.css
  JSDemos/Demos/DateRangeBox/Overview/Vue/App.vue
  JSDemos/Demos/DateRangeBox/Overview/Vue/index.html
  JSDemos/Demos/DateRangeBox/Overview/Vue/index.js
  JSDemos/Demos/DateRangeBox/Overview/jQuery/index.html
  JSDemos/Demos/DateRangeBox/Overview/jQuery/index.js
  JSDemos/Demos/DateRangeBox/Overview/jQuery/styles.css
  JSDemos/Demos/DateRangeBox/Overview/test-code.js
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/DateRangeBox/Overview.css
  MVCDemos/Controllers/DateRangeBoxController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/DateRangeBox/Overview.cshtml
  NetCoreDemos/Controllers/DateRangeBoxController.cs
  NetCoreDemos/Views/DateRangeBox/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/DateRangeBox/Overview.css
  testing/etalons/DateRangeBox-Overview.png
Labels: 23_1

#2614 FileUploader - Async Upload: Fix parameter issue
  NetCoreDemos/Controllers/FileUploaderController.cs
Labels: 23_1

#2616 FileUploader - Async Upload: Fix parameter issue
  NetCoreDemos/Controllers/FileUploaderController.cs
Labels: cherry-pick, 22_2
