Repository DevExpress/devextreme-demos, pull requests merged in 2023-04, with the labels that each got.

#2512 DataGrid Overview: Update set data for request
  JSDemos/Demos/DataGrid/Overview/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/Overview/AngularJS/index.js
  JSDemos/Demos/DataGrid/Overview/React/App.js
  JSDemos/Demos/DataGrid/Overview/Vue/App.vue
  JSDemos/Demos/DataGrid/Overview/jQuery/index.js
  MVCDemos/Views/DataGrid/Overview.cshtml
  NetCoreDemos/Views/DataGrid/Overview.cshtml
Labels: 23_1

#2513 Include Scheduler demos files in MVC project
  MVCDemos/DevExtreme.MVC.Demos.csproj
Labels: 23_1

#2514 DataGrid Overview: Update set data for request
  JSDemos/Demos/DataGrid/Overview/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/Overview/AngularJS/index.js
  JSDemos/Demos/DataGrid/Overview/React/App.js
  JSDemos/Demos/DataGrid/Overview/Vue/App.vue
  JSDemos/Demos/DataGrid/Overview/jQuery/index.js
  MVCDemos/Views/DataGrid/Overview.cshtml
  NetCoreDemos/Views/DataGrid/Overview.cshtml
Labels: cherry-pick, 22_2

#2515 Include Scheduler demos files in MVC project
  MVCDemos/DevExtreme.MVC.Demos.csproj
Labels: cherry-pick, 22_2

#2507 PieChart: describe Pie with Custom Styles demo
  JSDemos/Demos/Charts/PieWithCustomStyles/description.md
Labels: 23_1

#2511 Charts: update 'Discrete Aggregation' demo description
  JSDemos/Demos/Charts/DiscreteAggregation/description.md
Labels: 23_1

#2523 Fix FileUploader controller for .Net Core
  NetCoreDemos/Controllers/FileUploaderController.cs
Labels: cherry-pick, 22_2

#2516 DataGrid Overview: Update set data for request
  JSDemos/Demos/DataGrid/Overview/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/Overview/AngularJS/index.js
  JSDemos/Demos/DataGrid/Overview/React/App.js
  JSDemos/Demos/DataGrid/Overview/Vue/App.vue
  JSDemos/Demos/DataGrid/Overview/jQuery/index.js
  MVCDemos/Views/DataGrid/Overview.cshtml
  NetCoreDemos/Views/DataGrid/Overview.cshtml
  package-lock.json
  package.json
  testing/etalons/DataGrid-RowTemplate_mask.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_2_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_3_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_5_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_6_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_master_detail_api_2_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_master_detail_view_2_desktop_mask.png
Labels: cherry-pick, 22_1

#2519 List Selection demo: avoid looping after change selectionMode to 'none' in React
  JSDemos/Demos/List/ListSelection/Angular/app/app.component.html
  JSDemos/Demos/List/ListSelection/AngularJS/index.html
  JSDemos/Demos/List/ListSelection/Knockout/index.html
  JSDemos/Demos/List/ListSelection/React/App.js
  JSDemos/Demos/List/ListSelection/Vue/App.vue
  JSDemos/Demos/List/ListSelection/jQuery/index.html
  JSDemos/Demos/List/ListSelection/jQuery/index.js
  MVCDemos/Views/List/ListSelection.cshtml
  NetCoreDemos/Views/List/ListSelection.cshtml
  testing/widgets/list/ListSelection.test.js
  testing/widgets/list/etalons/List after change selectionMode to multiple.png
  testing/widgets/list/etalons/List after change selectionMode to none.png
  testing/widgets/list/etalons/List after change selectionMode to single.png
  testing/widgets/list/etalons/List after click on item, selectionMode=all.png
Labels: 23_1

#2526 List Selection demo: avoid looping after change selectionMode to 'none' in React (#2519)
  JSDemos/Demos/List/ListSelection/Angular/app/app.component.html
  JSDemos/Demos/List/ListSelection/AngularJS/index.html
  JSDemos/Demos/List/ListSelection/Knockout/index.html
  JSDemos/Demos/List/ListSelection/React/App.js
  JSDemos/Demos/List/ListSelection/Vue/App.vue
  JSDemos/Demos/List/ListSelection/jQuery/index.html
  JSDemos/Demos/List/ListSelection/jQuery/index.js
  MVCDemos/Views/List/ListSelection.cshtml
  NetCoreDemos/Views/List/ListSelection.cshtml
  testing/widgets/list/ListSelection.test.js
  testing/widgets/list/etalons/List after change selectionMode to multiple.png
  testing/widgets/list/etalons/List after change selectionMode to none.png
  testing/widgets/list/etalons/List after change selectionMode to single.png
  testing/widgets/list/etalons/List after click on item, selectionMode=all.png
Labels: cherry-pick, 22_2

#2528 Server-side demos: add note about Web API Service
  JSDemos/Demos/Charts/ServerSideDataProcessing/description.md
  JSDemos/Demos/DataGrid/CustomDataSource/description.md
  JSDemos/Demos/DataGrid/OdataService/description.md
  JSDemos/Demos/DataGrid/WebAPIService/description.md
Labels: 22_2

#2529 Server-side demos: add note about Web API Service (#2528)
  JSDemos/Demos/Charts/ServerSideDataProcessing/description.md
  JSDemos/Demos/DataGrid/CustomDataSource/description.md
  JSDemos/Demos/DataGrid/OdataService/description.md
  JSDemos/Demos/DataGrid/WebAPIService/description.md
Labels: cherry-pick, 23_1

#2502 Changing the Editors - Validation demo
  JSDemos/Demos/Validation/Overview/Angular/app/app.component.html
  JSDemos/Demos/Validation/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Validation/Overview/AngularJS/index.html
  JSDemos/Demos/Validation/Overview/AngularJS/index.js
  JSDemos/Demos/Validation/Overview/React/App.js
  JSDemos/Demos/Validation/Overview/Vue/App.vue
  JSDemos/Demos/Validation/Overview/jQuery/index.js
  MVCDemos/Views/Validation/Overview.cshtml
  NetCoreDemos/Views/Validation/Overview.cshtml
  testing/etalons/Validation-Overview.png
Labels: 22_2

#2527 Changing the Editors - Validation demo v23_1
  JSDemos/Demos/Validation/Overview/Angular/app/app.component.html
  JSDemos/Demos/Validation/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Validation/Overview/AngularJS/index.html
  JSDemos/Demos/Validation/Overview/AngularJS/index.js
  JSDemos/Demos/Validation/Overview/React/App.js
  JSDemos/Demos/Validation/Overview/Vue/App.vue
  JSDemos/Demos/Validation/Overview/jQuery/index.js
  MVCDemos/Views/Validation/Overview.cshtml
  NetCoreDemos/Views/Validation/Overview.cshtml
  testing/etalons/Validation-Overview.png
Labels: cherry-pick, 23_1

#2504 Map: remove Bing credentials from provider
  JSDemos/Demos/Map/Markers/Angular/app/app.component.html
  JSDemos/Demos/Map/Markers/Angular/app/app.component.ts
  JSDemos/Demos/Map/Markers/Angular/app/app.service.ts
  JSDemos/Demos/Map/Markers/AngularJS/index.js
  JSDemos/Demos/Map/Markers/React/App.js
  JSDemos/Demos/Map/Markers/Vue/App.vue
  JSDemos/Demos/Map/Markers/jQuery/index.js
  JSDemos/Demos/Map/ProvidersAndTypes/Angular/app/app.component.html
  JSDemos/Demos/Map/ProvidersAndTypes/Angular/app/app.component.ts
  JSDemos/Demos/Map/ProvidersAndTypes/Angular/app/app.service.ts
  JSDemos/Demos/Map/ProvidersAndTypes/AngularJS/index.js
  JSDemos/Demos/Map/ProvidersAndTypes/React/App.js
  JSDemos/Demos/Map/ProvidersAndTypes/Vue/App.vue
  JSDemos/Demos/Map/ProvidersAndTypes/jQuery/index.js
  JSDemos/Demos/Map/Routes/Angular/app/app.component.html
  JSDemos/Demos/Map/Routes/Angular/app/app.component.ts
  JSDemos/Demos/Map/Routes/Angular/app/app.service.ts
  JSDemos/Demos/Map/Routes/AngularJS/index.js
  JSDemos/Demos/Map/Routes/React/App.js
  JSDemos/Demos/Map/Routes/Vue/App.vue
  JSDemos/Demos/Map/Routes/jQuery/index.js
  MVCDemos/Views/Map/Markers.cshtml
  MVCDemos/Views/Map/ProvidersAndTypes.cshtml
  MVCDemos/Views/Map/Routes.cshtml
  NetCoreDemos/Views/Map/Markers.cshtml
  NetCoreDemos/Views/Map/ProvidersAndTypes.cshtml
  NetCoreDemos/Views/Map/Routes.cshtml
  testing/etalons/Map-Markers.png
  testing/etalons/Map-Markers_mask.png
  testing/etalons/Map-ProvidersAndTypes.png
  testing/etalons/Map-ProvidersAndTypes_mask.png
  testing/etalons/Map-Routes.png
  testing/etalons/Map-Routes_mask.png
Labels: 23_1

#2517 Editor Appearance Variants: Add visual test and asyncForEach helper
  testing/widgets/common/EditorAppearanceVariants.test.js
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_floating_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_hidden_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_filled_static_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_floating_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_hidden_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_static_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_floating_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_hidden_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_underlined_static_desktop.png
  utils/visual-tests/helpers/async-for-each.js
Labels: 23_1

#2532 DataGrid: Temporary update masks for some etalons.
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_2_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_update_row_1_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_update_row_2_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_update_row_4_desktop_mask.png
Labels: 23_1

#2533 DataGrid: Temporary update masks for some etalons. (#2532)
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_2_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_update_row_1_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_update_row_2_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_update_row_4_desktop_mask.png
Labels: cherry-pick, 22_2

#2534 DataGrid: Temporary update masks for some etalons. (#2532)
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_2_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_insert_row_4_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_update_row_1_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_update_row_2_desktop_mask.png
  testing/widgets/datagrid/etalons/datagrid_edit_state_management_update_row_4_desktop_mask.png
Labels: cherry-pick, 22_1

#2536 DataGrid Overview: Update set data for request
  JSDemos/Demos/DataGrid/Overview/Angular/app/app.service.ts
  JSDemos/Demos/DataGrid/Overview/AngularJS/index.js
  JSDemos/Demos/DataGrid/Overview/React/App.js
  JSDemos/Demos/DataGrid/Overview/Vue/App.vue
  JSDemos/Demos/DataGrid/Overview/jQuery/index.js
  MVCDemos/Views/DataGrid/Overview.cshtml
  NetCoreDemos/Views/DataGrid/Overview.cshtml
Labels: cherry-pick, 21_2

#2540 DataGrid / TreeList Demos missing crud configuration settings
  JSDemos/menuMeta.json
  MVCDemos/Controllers/TreeListController.cs
  MVCDemos/Views/DataGrid/KeyboardNavigation.cshtml
  MVCDemos/Views/TreeList/CustomizeKeyboardNavigation.cshtml
  MVCDemos/Views/TreeList/KeyboardNavigation.cshtml
  NetCoreDemos/Controllers/TreeListController.cs
  NetCoreDemos/Views/DataGrid/CellEditingAndEditingAPI.cshtml
  NetCoreDemos/Views/DataGrid/FormEditing.cshtml
  NetCoreDemos/Views/DataGrid/KeyboardNavigation.cshtml
  NetCoreDemos/Views/DataGrid/PopupEditing.cshtml
  NetCoreDemos/Views/TreeList/CustomizeKeyboardNavigation.cshtml
Labels: cherry-pick, 22_2

#2543 Tabs and Map: Update etalon and mask
  testing/etalons/Map-ProvidersAndTypes_mask.png
  testing/etalons/Tabs-Overview.png
Labels: 23_1

#2542 DropDownBox Multiple Selection: Add visual test
  testing/widgets/dropdownbox/MultipleSelection.test.js
  testing/widgets/dropdownbox/etalons/dropdownbox_multiple_selection_gridbox.png
  testing/widgets/dropdownbox/etalons/dropdownbox_multiple_selection_treebox.png
Labels: 23_1

#2553 Map: Update mask
  testing/etalons/Map-ProvidersAndTypes_mask.png
Labels: 23_1

#2552 DropDownBox Multiple Selection: Add visual test (#2542)
  testing/widgets/dropdownbox/MultipleSelection.test.js
  testing/widgets/dropdownbox/etalons/dropdownbox_multiple_selection_gridbox.png
  testing/widgets/dropdownbox/etalons/dropdownbox_multiple_selection_treebox.png
Labels: cherry-pick, 22_2

#2539 DataGrid - Header Filter Customization Feature - Remove usage of deprecated options
  JSDemos/Demos/DataGrid/Filtering/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/Filtering/React/App.js
  JSDemos/Demos/DataGrid/Filtering/Vue/App.vue
  JSDemos/Demos/DataGrid/Filtering/jQuery/index.js
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/React/App.js
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/Vue/App.vue
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/jQuery/index.js
  JSDemos/Demos/PivotGrid/HeaderFilter/Angular/app/app.component.html
  JSDemos/Demos/PivotGrid/HeaderFilter/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/HeaderFilter/React/App.js
  JSDemos/Demos/PivotGrid/HeaderFilter/Vue/App.vue
  JSDemos/Demos/PivotGrid/HeaderFilter/jQuery/index.js
  JSDemos/Demos/PivotGrid/IntegratedFieldChooser/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/IntegratedFieldChooser/React/App.js
  JSDemos/Demos/PivotGrid/IntegratedFieldChooser/Vue/App.vue
  JSDemos/Demos/PivotGrid/IntegratedFieldChooser/jQuery/index.js
  JSDemos/Demos/PivotGrid/OLAPDataSource/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/OLAPDataSource/React/App.js
  JSDemos/Demos/PivotGrid/OLAPDataSource/Vue/App.vue
  JSDemos/Demos/PivotGrid/OLAPDataSource/jQuery/index.js
  JSDemos/Demos/PivotGrid/RemoteVirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/PivotGrid/RemoteVirtualScrolling/React/App.js
  JSDemos/Demos/PivotGrid/RemoteVirtualScrolling/Vue/App.vue
  JSDemos/Demos/PivotGrid/RemoteVirtualScrolling/jQuery/index.js
  JSDemos/Demos/PivotGrid/StandaloneFieldChooser/Angular/app/app.component.ts
  JSDemos/Demos/PivotGrid/StandaloneFieldChooser/React/App.js
  JSDemos/Demos/PivotGrid/StandaloneFieldChooser/Vue/App.vue
  JSDemos/Demos/PivotGrid/StandaloneFieldChooser/jQuery/index.js
  JSDemos/shared/azure.file.system.js
  MVCDemos/Views/DataGrid/Filtering.cshtml
  MVCDemos/Views/DataGrid/RemoteVirtualScrolling.cshtml
  MVCDemos/Views/PivotGrid/HeaderFilter.cshtml
  MVCDemos/Views/PivotGrid/IntegratedFieldChooser.cshtml
  MVCDemos/Views/PivotGrid/OLAPDataSource.cshtml
  MVCDemos/Views/PivotGrid/RemoteVirtualScrolling.cshtml
  MVCDemos/Views/PivotGrid/StandaloneFieldChooser.cshtml
  NetCoreDemos/Views/DataGrid/Filtering.cshtml
  NetCoreDemos/Views/DataGrid/RemoteVirtualScrolling.cshtml
  NetCoreDemos/Views/PivotGrid/HeaderFilter.cshtml
  NetCoreDemos/Views/PivotGrid/IntegratedFieldChooser.cshtml
  NetCoreDemos/Views/PivotGrid/OLAPDataSource.cshtml
  NetCoreDemos/Views/PivotGrid/RemoteVirtualScrolling.cshtml
  NetCoreDemos/Views/PivotGrid/StandaloneFieldChooser.cshtml
Labels: 23_1

#2562 3rd-Party Template Engines: update demo descriptions
  JSDemos/Demos/DataGrid/Column3RdPartyEngineTemplate/description.md
  JSDemos/Demos/DataGrid/Row3RdPartyEngineTemplate/description.md
  JSDemos/Demos/Gallery/Item3RdPartyEngineTemplate/description.md
  JSDemos/Demos/List/Item3RdPartyEngineTemplate/description.md
  JSDemos/Demos/TileView/Item3RdPartyEngineTemplate/description.md
Labels: 23_1

#2561 Sortable(T1161852): Demo React Kanban - a cloned list appears when drag-and-dropping a list to another area
  JSDemos/Demos/Sortable/Kanban/React/App.js
  testing/widgets/sortable/etalons/kanban_card_drag-n-drop_different-column.png
  testing/widgets/sortable/etalons/kanban_card_drag-n-drop_same-column.png
  testing/widgets/sortable/etalons/kanban_list_drag-n-drop.png
  testing/widgets/sortable/kanban.test.js
Labels: 23_1

#2564 Sortable(T1161852): Demo React Kanban - a cloned list appears when drag-and-dropping a list to another area (#2561)
  JSDemos/Demos/Sortable/Kanban/React/App.js
  testing/widgets/sortable/etalons/kanban_card_drag-n-drop_different-column.png
  testing/widgets/sortable/etalons/kanban_card_drag-n-drop_same-column.png
  testing/widgets/sortable/etalons/kanban_list_drag-n-drop.png
  testing/widgets/sortable/kanban.test.js
Labels: cherry-pick, 22_1

#2551 List 'Item Drag and Drop' Demo: Add the reorder event handler
  JSDemos/Demos/List/ItemDragging/Angular/app/app.component.html
  JSDemos/Demos/List/ItemDragging/Angular/app/app.component.ts
  JSDemos/Demos/List/ItemDragging/Vue/App.vue
  JSDemos/Demos/List/ItemDragging/jQuery/index.js
  testing/widgets/list/ItemDragging.test.js
Labels: 23_1

#2566 OData Service: add title to the note
  JSDemos/Demos/Charts/ServerSideDataProcessing/description.md
  JSDemos/Demos/DataGrid/CustomDataSource/description.md
  JSDemos/Demos/DataGrid/OdataService/description.md
  JSDemos/Demos/DataGrid/WebAPIService/description.md
Labels: 22_2

#2567 OData Service: add title to the note (#2566)
  JSDemos/Demos/Charts/ServerSideDataProcessing/description.md
  JSDemos/Demos/DataGrid/CustomDataSource/description.md
  JSDemos/Demos/DataGrid/OdataService/description.md
  JSDemos/Demos/DataGrid/WebAPIService/description.md
Labels: cherry-pick, 23_1
