Repository DevExpress/devextreme-demos, pull requests merged in 2023-10, with the labels that each got.

#2867 FormsAndMultiPurposeOverview: get rid of custom background
  JSDemos/Demos/Common/FormsAndMultiPurposeOverview/Angular/app/app.component.css
  JSDemos/Demos/Common/FormsAndMultiPurposeOverview/Angular/app/app.component.html
  JSDemos/Demos/Common/FormsAndMultiPurposeOverview/AngularJS/index.js
  JSDemos/Demos/Common/FormsAndMultiPurposeOverview/AngularJS/styles.css
  JSDemos/Demos/Common/FormsAndMultiPurposeOverview/React/App.js
  JSDemos/Demos/Common/FormsAndMultiPurposeOverview/React/styles.css
  JSDemos/Demos/Common/FormsAndMultiPurposeOverview/Vue/App.vue
  JSDemos/Demos/Common/FormsAndMultiPurposeOverview/jQuery/index.js
  JSDemos/Demos/Common/FormsAndMultiPurposeOverview/jQuery/styles.css
Labels: 23_2

#2878 Rename Calendar Builder Values to Value
  MVCDemos/Views/Calendar/MultipleSelection.cshtml
  NetCoreDemos/Views/Calendar/MultipleSelection.cshtml
Labels: 23_2

#2819 Resolve svg path as node src attr
  JSDemos/Demos/SelectBox/CustomizeDropDownButton/Vue/App.vue
Labels: 23_2

#2874 Fluent: Scheduler - CSS fixes (part 3)
  JSDemos/Demos/Scheduler/GroupByDate/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/GroupByDate/React/App.js
  JSDemos/Demos/Scheduler/GroupByDate/Vue/App.vue
  JSDemos/Demos/Scheduler/GroupByDate/jQuery/index.js
  JSDemos/Demos/Scheduler/Overview/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/Overview/React/styles.css
  JSDemos/Demos/Scheduler/Overview/Vue/DataCell.vue
  JSDemos/Demos/Scheduler/Overview/Vue/ResourceCell.vue
  JSDemos/Demos/Scheduler/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Scheduler/Overview.css
  MVCDemos/Views/Scheduler/GroupByDate.cshtml
  NetCoreDemos/Views/Scheduler/GroupByDate.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/Overview.css
Labels: 23_2

#2881 DataGrid: update ColumnChooser demo description
  JSDemos/Demos/DataGrid/ColumnChooser/description.md
Labels: 23_1

#2883 Form Validation Demo: add validation rules for dateRangebox
  JSDemos/Demos/Form/Validation/Angular/app/app.component.css
  JSDemos/Demos/Form/Validation/Angular/app/app.component.html
  JSDemos/Demos/Form/Validation/Angular/app/app.component.ts
  JSDemos/Demos/Form/Validation/React/App.js
  JSDemos/Demos/Form/Validation/React/styles.css
  JSDemos/Demos/Form/Validation/Vue/App.vue
  JSDemos/Demos/Form/Validation/jQuery/index.js
  JSDemos/Demos/Form/Validation/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Form/Validation.css
  MVCDemos/Views/Form/Validation.cshtml
  NetCoreDemos/Views/Form/Validation.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Form/Validation.css
Labels: 23_2

#2882 DataGrid: update ColumnChooser demo description (#2881)
  JSDemos/Demos/DataGrid/ColumnChooser/description.md
Labels: cherry-pick, 23_2

#2886 DataGrid - fix column width
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/React/App.js
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/Vue/App.vue
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/jQuery/index.js
  MVCDemos/Views/DataGrid/RemoteVirtualScrolling.cshtml
  NetCoreDemos/Views/DataGrid/RemoteVirtualScrolling.cshtml
  testing/etalons/DataGrid-RemoteVirtualScrolling.png
Labels: 23_1

#2887 feature: license check. Add known warning.
  testing/known-warnings.json
Labels: 23_2

#2889 Calendar: update demo descriptions
  JSDemos/Demos/Calendar/MultipleSelection/Angular/description.md
  JSDemos/Demos/Calendar/MultipleSelection/Vue/description.md
  JSDemos/Demos/Calendar/MultipleSelection/description.md
  JSDemos/Demos/Calendar/Overview/description.md
Labels: 23_2

#2890 Form validation demo: drb validation changed
  JSDemos/Demos/Form/Validation/Angular/app/app.component.html
  JSDemos/Demos/Form/Validation/Angular/app/app.component.ts
  JSDemos/Demos/Form/Validation/React/App.js
  JSDemos/Demos/Form/Validation/Vue/App.vue
  JSDemos/Demos/Form/Validation/jQuery/index.js
  MVCDemos/Views/Form/Validation.cshtml
  NetCoreDemos/Views/Form/Validation.cshtml
Labels: 23_2

#2897 Fix frameworks workflow after reverting changes in devextreme-vue repo
  .github/workflows/visual_tests_frameworks.yml
Labels: 23_1

#2895 Resolve svg path as node src attr (fails in WG)
  JSDemos/Demos/SelectBox/CustomizeDropDownButton/Vue/App.vue
Labels: cherry-pick, 23_1

#2892 🎨 Fluent: Redesign Field Chooser
  testing/etalons/PivotGrid-StandaloneFieldChooser.png
  testing/widgets/pivotgrid/etalons/Integrated field chooser after search of hierarchy field.png
  testing/widgets/pivotgrid/etalons/Integrated field chooser.png
Labels: 23_2

#2900 🎨 Fluent: Redesign custom toolbar demo
  JSDemos/Demos/DataGrid/ToolbarCustomization/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/ToolbarCustomization/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/ToolbarCustomization/React/App.js
  JSDemos/Demos/DataGrid/ToolbarCustomization/React/styles.css
  JSDemos/Demos/DataGrid/ToolbarCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/ToolbarCustomization/jQuery/index.js
  JSDemos/Demos/DataGrid/ToolbarCustomization/jQuery/styles.css
  MVCDemos/Content/DemosStyles/DataGrid/ToolbarCustomization.css
  MVCDemos/Views/DataGrid/ToolbarCustomization.cshtml
  NetCoreDemos/Views/DataGrid/ToolbarCustomization.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/ToolbarCustomization.css
  testing/etalons/DataGrid-ToolbarCustomization.png
Labels: 23_2

#2879 CI: Stabilize frameworks tests
  .github/workflows/visual_tests.yml
  .github/workflows/visual_tests_frameworks.yml
  gulpfile.js/js.js
  package.json
  utils/bundle/index.js
  utils/visual-tests/testcafe-runner.mjs
Labels: 23_2

#2907 Form, Editors: change gap between label & editor in 'outside' label mode in Generic & Material
  testing/etalons/Form-ColumnsAdaptability.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_2_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_3_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_4_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_5_desktop.png
  testing/widgets/datagrid/etalons/datagrid_advanced_master_detail_view_6_desktop.png
Labels: force all tests, 23_2

#2911 Remove unnecessary packages in MVC demos
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Web.config
  MVCDemos/packages.config
Labels: 22_2

#2912 Remove unnecessary packages in MVC demos
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Web.config
  MVCDemos/packages.config
Labels: 23_1

#2851 Support generate demos bundles for publish
  .eslintignore
  .github/workflows/publish-demos.yml
  .gitignore
  .prettierignore
  .stylelintignore
  .vscode/settings.json
  JSDemos/Demos/DataGrid/CellCustomization/React/DiffCell.js
  JSDemos/Demos/Diagram/UICustomization/React/App.js
  JSDemos/Demos/Diagram/UICustomization/Vue/App.vue
  JSDemos/Demos/Scheduler/CustomTemplates/React/Appointment.js
  JSDemos/Demos/Scheduler/CustomTemplates/Vue/AppointmentTemplate.vue
  JSDemos/Demos/Scheduler/TimeZonesSupport/Angular/app/app.component.ts
  JSDemos/Demos/Scheduler/TimeZonesSupport/React/App.js
  JSDemos/Demos/Scheduler/TimeZonesSupport/Vue/App.vue
  JSDemos/Demos/TreeList/KeyboardNavigation/React/index.js
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.js
  package-lock.json
  package.json
  tsconfig.json
  utils/bundle/index.js
  utils/create-bundles/React/bundler.ts
  utils/create-bundles/React/template.html
  utils/create-bundles/Vue/bundler.ts
  utils/create-bundles/Vue/template.html
  utils/create-bundles/helper/bundler.ts
  utils/create-bundles/helper/index.ts
  utils/create-bundles/helper/metadata/scripts/init-theme.js
  utils/create-bundles/helper/types.ts
  utils/create-bundles/index.ts
  utils/create-bundles/plugins/ignore-missing-css.ts
Labels: 23_2

#2914 Fix preparing JS bundles script
  gulpfile.js/js.js
  package.json
Labels: 23_2

#2876 Fix Export Custom Markup demo
  JSDemos/Demos/Charts/ExportCustomMarkup/React/Form.js
Labels: 23_2

#2921 Fix PieChart with custom styles demo
  JSDemos/Demos/Charts/PieWithCustomStyles/visualtestrc.json
Labels: 23_2

#2779 TagBox: update Overview demo description
  JSDemos/Demos/TagBox/Overview/description.md
Labels: 23_2

#2920 Fix PieChart with custom styles demo
  utils/bundle/index.js
Labels: 23_1

#2923 Cherry-pick: tagbox update (#2779)
  JSDemos/Demos/TagBox/Overview/description.md
Labels: cherry-pick, 23_1

#2924 Tabs: add demo descriptions
  JSDemos/Demos/Tabs/Overview/description.md
  JSDemos/Demos/Tabs/Selection/description.md
Labels: 23_2

#2927 dxScheduler - support material/fluent UI style in disable date demo
  JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.css
  JSDemos/Demos/Scheduler/CellTemplates/React/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/Vue/styles.css
  JSDemos/Demos/Scheduler/CellTemplates/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Scheduler/CellTemplates.css
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/CellTemplates.css
Labels: 23_2

#2925 TabPanel: update demo descriptions
  JSDemos/Demos/TabPanel/Overview/description.md
  JSDemos/Demos/TabPanel/Templates/React/description.md
  JSDemos/Demos/TabPanel/Templates/description.md
Labels: 23_2

#2932 Ignore pre-release version warning
  testing/known-warnings.json
Labels: 23_2

#2930 Popup: update toolbar buttons stylingMode
  JSDemos/Demos/Popup/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Popup/Overview/React/App.js
  JSDemos/Demos/Popup/Overview/Vue/App.vue
  JSDemos/Demos/Popup/Overview/jQuery/index.js
  MVCDemos/Views/Popup/Overview.cshtml
  NetCoreDemos/Views/Popup/Overview.cshtml
Labels: 23_2

#2928 Tabs/TabPanel: Add Full width, remove tab-item width, update text content
  JSDemos/Demos/TabPanel/Overview/Angular/app/app.component.html
  JSDemos/Demos/TabPanel/Overview/React/App.js
  JSDemos/Demos/TabPanel/Overview/React/data.js
  JSDemos/Demos/TabPanel/Overview/Vue/App.vue
  JSDemos/Demos/TabPanel/Overview/Vue/data.js
  JSDemos/Demos/TabPanel/Overview/jQuery/data.js
  JSDemos/Demos/TabPanel/Overview/jQuery/index.html
  JSDemos/Demos/TabPanel/Templates/Angular/app/app.component.html
  JSDemos/Demos/TabPanel/Templates/React/CompanyItem.js
  JSDemos/Demos/TabPanel/Templates/Vue/App.vue
  JSDemos/Demos/TabPanel/Templates/jQuery/index.html
  JSDemos/Demos/Tabs/Overview/Angular/app/app.component.css
  JSDemos/Demos/Tabs/Overview/Angular/app/app.component.html
  JSDemos/Demos/Tabs/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Tabs/Overview/React/App.js
  JSDemos/Demos/Tabs/Overview/React/data.js
  JSDemos/Demos/Tabs/Overview/React/styles.css
  JSDemos/Demos/Tabs/Overview/Vue/App.vue
  JSDemos/Demos/Tabs/Overview/Vue/data.js
  JSDemos/Demos/Tabs/Overview/jQuery/data.js
  JSDemos/Demos/Tabs/Overview/jQuery/index.html
  JSDemos/Demos/Tabs/Overview/jQuery/index.js
  JSDemos/Demos/Tabs/Overview/jQuery/styles.css
  JSDemos/Demos/Tabs/Selection/Angular/app/app.component.html
  JSDemos/Demos/Tabs/Selection/React/App.js
  JSDemos/Demos/Tabs/Selection/Vue/App.vue
  JSDemos/Demos/Tabs/Selection/jQuery/index.html
  MVCDemos/Content/DemosStyles/Tabs/Overview.css
  MVCDemos/Views/TabPanel/Overview.cshtml
  MVCDemos/Views/TabPanel/Templates.cshtml
  MVCDemos/Views/Tabs/Overview.cshtml
  MVCDemos/Views/Tabs/Selection.cshtml
  NetCoreDemos/Views/TabPanel/Overview.cshtml
  NetCoreDemos/Views/TabPanel/Templates.cshtml
  NetCoreDemos/Views/Tabs/Overview.cshtml
  NetCoreDemos/Views/Tabs/Selection.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Tabs/Overview.css
  testing/etalons/TabPanel-Overview.png
  testing/etalons/TabPanel-Templates.png
  testing/etalons/Tabs-Overview.png
  testing/etalons/Tabs-Selection.png
  testing/widgets/tabpanel/etalons/tabpanel_iconposition_start.png
  testing/widgets/tabpanel/etalons/tabpanel_shownavbuttons_false.png
  testing/widgets/tabpanel/etalons/tabpanel_stylingmode_primary.png
  testing/widgets/tabpanel/etalons/tabpanel_tabsposition_top.png
  testing/widgets/tabs/etalons/tabs_iconposition_end.png
  testing/widgets/tabs/etalons/tabs_orientation_vertical.png
  testing/widgets/tabs/etalons/tabs_second_item_selection.png
  testing/widgets/tabs/etalons/tabs_shownavbuttons_true.png
  testing/widgets/tabs/etalons/tabs_stylingmode_secondary.png
  testing/widgets/tabs/etalons/tabs_third_item_selection.png
Labels: 23_2

#2935 Editors Appearance Variants: update demo description
  JSDemos/Demos/Common/EditorAppearanceVariants/description.md
Labels: 23_2

#2926 Decrease lint task duration in frameworks tests
  .github/workflows/visual_tests_frameworks.yml
  package-lock.json
  package.json
  utils/eslint-runner.ts
Labels: 23_2

#2937 TabPanel: fix titles in Overview demo description
  JSDemos/Demos/TabPanel/Overview/description.md
Labels: 23_2

#2939 Button group demo - Fix item selection in React
  JSDemos/Demos/ButtonGroup/Overview/React/App.js
Labels: 23_1

#2940 Decrease lint task duration in frameworks tests (#2926)
  .github/workflows/visual_tests_frameworks.yml
  package-lock.json
  package.json
  utils/eslint-runner.ts
Labels: 23_1

#2945 dxScheduler - remove unused property in demos(WebAPIService and SignalRService)
  JSDemos/Demos/Scheduler/WebAPIService/Angular/app/app.component.html
  JSDemos/Demos/Scheduler/WebAPIService/AngularJS/index.js
  JSDemos/Demos/Scheduler/WebAPIService/React/App.tsx
  JSDemos/Demos/Scheduler/WebAPIService/Vue/App.vue
  JSDemos/Demos/Scheduler/WebAPIService/jQuery/index.js
  NetCoreDemos/Views/Scheduler/SignalRService.cshtml
  NetCoreDemos/Views/Scheduler/WebAPIService.cshtml
Labels: 23_2

#2948 Update demo descriptions after review
  JSDemos/Demos/Calendar/Overview/description.md
  JSDemos/Demos/Form/Validation/description.md
  JSDemos/Demos/TabPanel/Overview/description.md
Labels: 23_2

#2942 Tabs: Align the content at the beginning of the block in vertical orientation
  JSDemos/Demos/Tabs/Overview/Angular/app/app.component.css
  JSDemos/Demos/Tabs/Overview/Angular/app/app.component.html
  JSDemos/Demos/Tabs/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Tabs/Overview/React/App.js
  JSDemos/Demos/Tabs/Overview/React/data.js
  JSDemos/Demos/Tabs/Overview/React/styles.css
  JSDemos/Demos/Tabs/Overview/Vue/App.vue
  JSDemos/Demos/Tabs/Overview/jQuery/index.html
  JSDemos/Demos/Tabs/Overview/jQuery/index.js
  JSDemos/Demos/Tabs/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Tabs/Overview.css
  MVCDemos/Views/Tabs/Overview.cshtml
  NetCoreDemos/Views/Tabs/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Tabs/Overview.css
  testing/etalons/Tabs-Overview.png
  testing/widgets/tabs/Overview.test.js
  testing/widgets/tabs/etalons/tabs_iconposition_end.png
  testing/widgets/tabs/etalons/tabs_orientation_vertical.png
  testing/widgets/tabs/etalons/tabs_rtlenabled_true.png
  testing/widgets/tabs/etalons/tabs_shownavbuttons_true.png
  testing/widgets/tabs/etalons/tabs_stylingmode_secondary.png
Labels: 23_2

#2946 Calendar Overview: use cellComponent instead of cellRender in React
  JSDemos/Demos/Calendar/Overview/React/App.tsx
  JSDemos/Demos/Calendar/Overview/ReactJs/App.js
Labels: 23_2

#2929 Demos with treeview: add baseline screenshots
  testing/etalons/Common-NavigationOverview.png
  testing/etalons/Common-NavigationRightToLeftSupport.png
  testing/etalons/FileManager-AzureClientBinding.png
  testing/etalons/FileManager-AzureServerBinding.png
  testing/etalons/FileManager-BindingToEF.png
  testing/etalons/FileManager-BindingToFileSystem.png
  testing/etalons/FileManager-BindingToHierarchicalStructure.png
  testing/etalons/FileManager-CustomThumbnails.png
  testing/etalons/FileManager-Overview.png
  testing/etalons/FileManager-UICustomization.png
  testing/etalons/PivotGrid-StandaloneFieldChooser.png
  testing/etalons/TreeView-ContextMenuIntegration.png
  testing/etalons/TreeView-DragAndDropHierarchicalDataStructure.png
  testing/etalons/TreeView-DragAndDropPlainDataStructure.png
  testing/etalons/TreeView-FlatDataStructure.png
  testing/etalons/TreeView-HierarchicalDataStructure.png
  testing/etalons/TreeView-ItemSelectionAndCustomization.png
  testing/etalons/TreeView-LoadDataOnDemand.png
  testing/etalons/TreeView-TreeViewWithSearchBar.png
  testing/etalons/TreeView-VirtualMode.png
  testing/widgets/datagrid/etalons/datagrid_column_customization_2.png
  testing/widgets/datagrid/etalons/datagrid_column_customization_3.png
  testing/widgets/dropdownbox/etalons/dropdownbox_multiple_selection_treebox.png
  testing/widgets/pivotgrid/etalons/Integrated field chooser after search of hierarchy field.png
  testing/widgets/pivotgrid/etalons/Integrated field chooser.png
Labels: 23_2

#2951 Form validation demo: set openOnClick to true for dateBox
  JSDemos/Demos/Form/Validation/Angular/app/app.component.ts
  JSDemos/Demos/Form/Validation/React/App.js
  JSDemos/Demos/Form/Validation/Vue/App.vue
  JSDemos/Demos/Form/Validation/jQuery/index.js
  MVCDemos/Views/Form/Validation.cshtml
  NetCoreDemos/Views/Form/Validation.cshtml
Labels: 23_2

#2931 Components: get rid of h1 tag in demos
  JSDemos/Demos/Accordion/Overview/Angular/app/app.component.css
  JSDemos/Demos/Accordion/Overview/Angular/app/app.component.html
  JSDemos/Demos/Accordion/Overview/React/CustomTitle.js
  JSDemos/Demos/Accordion/Overview/React/styles.css
  JSDemos/Demos/Accordion/Overview/Vue/App.vue
  JSDemos/Demos/Accordion/Overview/Vue/CustomTitle.vue
  JSDemos/Demos/Accordion/Overview/jQuery/index.html
  JSDemos/Demos/Accordion/Overview/jQuery/styles.css
  JSDemos/Demos/LoadPanel/Overview/Angular/app/app.component.css
  JSDemos/Demos/LoadPanel/Overview/Angular/app/app.component.html
  JSDemos/Demos/LoadPanel/Overview/React/App.js
  JSDemos/Demos/LoadPanel/Overview/React/styles.css
  JSDemos/Demos/LoadPanel/Overview/Vue/App.vue
  JSDemos/Demos/LoadPanel/Overview/jQuery/index.html
  JSDemos/Demos/LoadPanel/Overview/jQuery/styles.css
  JSDemos/Demos/MultiView/Overview/Angular/app/app.component.css
  JSDemos/Demos/MultiView/Overview/Angular/app/app.component.html
  JSDemos/Demos/MultiView/Overview/React/CompanyItem.js
  JSDemos/Demos/MultiView/Overview/React/styles.css
  JSDemos/Demos/MultiView/Overview/Vue/App.vue
  JSDemos/Demos/MultiView/Overview/jQuery/index.html
  JSDemos/Demos/MultiView/Overview/jQuery/styles.css
  JSDemos/Demos/Popup/Overview/Angular/app/app.component.css
  JSDemos/Demos/Popup/Overview/Angular/app/app.component.html
  JSDemos/Demos/Popup/Overview/React/App.js
  JSDemos/Demos/Popup/Overview/React/styles.css
  JSDemos/Demos/Popup/Overview/Vue/App.vue
  JSDemos/Demos/Popup/Overview/jQuery/index.html
  JSDemos/Demos/Popup/Overview/jQuery/styles.css
  JSDemos/Demos/Toast/Overview/Angular/app/app.component.css
  JSDemos/Demos/Toast/Overview/Angular/app/app.component.html
  JSDemos/Demos/Toast/Overview/React/App.js
  JSDemos/Demos/Toast/Overview/React/styles.css
  JSDemos/Demos/Toast/Overview/Vue/App.vue
  JSDemos/Demos/Toast/Overview/jQuery/index.html
  JSDemos/Demos/Toast/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Accordion/Overview.css
  MVCDemos/Content/DemosStyles/LoadPanel/Overview.css
  MVCDemos/Content/DemosStyles/MultiView/Overview.css
  MVCDemos/Content/DemosStyles/Popup/Overview.css
  MVCDemos/Content/DemosStyles/Toast/Overview.css
  MVCDemos/Views/Accordion/Overview.cshtml
  MVCDemos/Views/LoadPanel/Overview.cshtml
  MVCDemos/Views/MultiView/Overview.cshtml
  MVCDemos/Views/Popup/Overview.cshtml
  MVCDemos/Views/Toast/Overview.cshtml
  NetCoreDemos/Views/Accordion/Overview.cshtml
  NetCoreDemos/Views/LoadPanel/Overview.cshtml
  NetCoreDemos/Views/MultiView/Overview.cshtml
  NetCoreDemos/Views/Popup/Overview.cshtml
  NetCoreDemos/Views/Toast/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Accordion/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/LoadPanel/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/MultiView/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/Popup/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/Toast/Overview.css
  testing/etalons/Popup-Overview.png
  testing/etalons/Toast-Overview.png
Labels: 23_2
