Repository DevExpress/devextreme-demos, pull requests merged in 2023-09, with the labels that each got.

#2804 dxFileUploader - fix upload operation in azure demo provider (T1185682)
  JSDemos/shared/azure.file.system.ts
Labels: 23_2

#2805 dxFileUploader - fix upload operation in azure demo provider (T1185682)
  JSDemos/shared/azure.file.system.ts
Labels: cherry-pick, 23_1

#2806 dxFileUploader - fix upload operation in azure demo provider (T1185682)
  JSDemos/shared/azure.file.system.ts
Labels: cherry-pick, 22_2

#2810 Editors: height standardization in material default & compact themes
  testing/etalons/Common-EditorAppearanceVariants.png
  testing/etalons/Form-Overview.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_floating_desktop.png
  testing/widgets/common/etalons/common_editor_appearance_variants_outlined_static_desktop.png
Labels: force all tests, 23_2

#2802 Form validation: 'reset form' button added
  JSDemos/Demos/Form/Validation/Angular/app/app.component.css
  JSDemos/Demos/Form/Validation/Angular/app/app.component.html
  JSDemos/Demos/Form/Validation/Angular/app/app.component.ts
  JSDemos/Demos/Form/Validation/Angular/app/app.service.ts
  JSDemos/Demos/Form/Validation/React/App.js
  JSDemos/Demos/Form/Validation/React/data.js
  JSDemos/Demos/Form/Validation/React/styles.css
  JSDemos/Demos/Form/Validation/Vue/App.vue
  JSDemos/Demos/Form/Validation/Vue/data.js
  JSDemos/Demos/Form/Validation/jQuery/data.js
  JSDemos/Demos/Form/Validation/jQuery/index.js
  JSDemos/Demos/Form/Validation/jQuery/styles.css
  testing/etalons/Form-Validation.png
Labels: 23_2

#2813 Form validation Demo: 'reset form' button added for mvc and netcore
  JSDemos/Demos/Form/Validation/Angular/app/app.component.html
  JSDemos/Demos/Form/Validation/Angular/app/app.component.ts
  MVCDemos/Content/DemosStyles/Form/Validation.css
  MVCDemos/ViewModels/EditorsViewModel.cs
  MVCDemos/Views/Form/Validation.cshtml
  NetCoreDemos/ViewModels/EditorsViewModel.cs
  NetCoreDemos/Views/Form/Validation.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Form/Validation.css
Labels: 23_2

#2818 T1186741: Add test cases for scheduler custom dnd demo.
  testing/widgets/scheduler/customDragAndDrop.test.js
  testing/widgets/scheduler/etalons/scheduler_custom-dnd_all-day-panel_list.png
  testing/widgets/scheduler/etalons/scheduler_custom-dnd_date-table_list.png
  testing/widgets/scheduler/etalons/scheduler_custom-dnd_list_all-day-panel.png
  testing/widgets/scheduler/etalons/scheduler_custom-dnd_list_date-table.png
Labels: 23_2

#2816 form validation demo: test for buttons
  JSDemos/Demos/Form/Validation/Angular/app/app.component.html
  MVCDemos/Views/Form/Validation.cshtml
  NetCoreDemos/Views/Form/Validation.cshtml
  testing/widgets/form/Validation.test.js
  testing/widgets/form/etalons/form_validation_after_reset.png
  testing/widgets/form/etalons/form_validation_before_reset.png
  testing/widgets/form/etalons/form_validation_summary.png
Labels: 23_2

#2826 Form validation demo: updated badge added
  JSDemos/menuMeta.json
Labels: 23_2

#2815 Popup - Actualize focus state
  testing/widgets/common/etalons/common_dialogs_and_notifications_overview_popup.png
  testing/widgets/datagrid/etalons/datagrid_column_customization_2.png
  testing/widgets/pivotgrid/etalons/Integrated field chooser.png
  testing/widgets/popup/etalons/popup with scrollable container.png
  testing/widgets/popup/etalons/popup with scrollview.png
  testing/widgets/toolbar/etalons/toolbar_singleline_mode_menu_open.png
Labels: 23_2

#2836 Update internal tools scripts usages
  .github/workflows/visual_tests_frameworks.yml
Labels: 23_2

#2833 PivotGrid - Review react to functional approach
  JSDemos/Demos/PivotGrid/ChartIntegration/React/App.js
  JSDemos/Demos/PivotGrid/DrillDown/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSCellCustomization/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJSOverview/React/App.js
  JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/React/App.js
  JSDemos/Demos/PivotGrid/FieldPanel/React/App.js
  JSDemos/Demos/PivotGrid/HeaderFilter/React/App.js
  JSDemos/Demos/PivotGrid/IntegratedFieldChooser/React/App.js
  JSDemos/Demos/PivotGrid/LayoutCustomization/React/App.js
  JSDemos/Demos/PivotGrid/OLAPDataSource/React/App.js
  JSDemos/Demos/PivotGrid/Overview/React/App.js
  JSDemos/Demos/PivotGrid/RemoteVirtualScrolling/React/App.js
  JSDemos/Demos/PivotGrid/RunningTotals/React/App.js
  JSDemos/Demos/PivotGrid/SimpleArray/React/App.js
  JSDemos/Demos/PivotGrid/StandaloneFieldChooser/React/App.js
  JSDemos/Demos/PivotGrid/StatePersistence/React/App.js
  JSDemos/Demos/PivotGrid/SummaryDisplayModes/React/App.js
  JSDemos/Demos/PivotGrid/VirtualScrolling/React/App.js
  JSDemos/Demos/PivotGrid/WebAPIService/React/App.js
Labels: 23_2

#2843 MVCDemos - Disable script bundle transforms / min
  MVCDemos/App_Start/BundleConfig.cs
Labels: 23_2

#2821 T1186741: Add test cases for scheduler custom dnd demo. (#2818)
  testing/widgets/scheduler/customDragAndDrop.test.js
  testing/widgets/scheduler/etalons/scheduler_custom-dnd_all-day-panel_list.png
  testing/widgets/scheduler/etalons/scheduler_custom-dnd_date-table_list.png
  testing/widgets/scheduler/etalons/scheduler_custom-dnd_list_all-day-panel.png
  testing/widgets/scheduler/etalons/scheduler_custom-dnd_list_date-table.png
Labels: cherry-pick, 23_1

#2844 TabPanel: Move Overview demo to Templates
  JSDemos/Demos/TabPanel/Templates/Angular/app/app.component.css
  JSDemos/Demos/TabPanel/Templates/Angular/app/app.component.html
  JSDemos/Demos/TabPanel/Templates/Angular/app/app.component.ts
  JSDemos/Demos/TabPanel/Templates/Angular/app/app.service.ts
  JSDemos/Demos/TabPanel/Templates/Angular/index.html
  JSDemos/Demos/TabPanel/Templates/React/App.js
  JSDemos/Demos/TabPanel/Templates/React/CompanyItem.js
  JSDemos/Demos/TabPanel/Templates/React/data.js
  JSDemos/Demos/TabPanel/Templates/React/index.html
  JSDemos/Demos/TabPanel/Templates/React/index.js
  JSDemos/Demos/TabPanel/Templates/React/styles.css
  JSDemos/Demos/TabPanel/Templates/Vue/App.vue
  JSDemos/Demos/TabPanel/Templates/Vue/data.js
  JSDemos/Demos/TabPanel/Templates/Vue/index.html
  JSDemos/Demos/TabPanel/Templates/Vue/index.js
  JSDemos/Demos/TabPanel/Templates/jQuery/data.js
  JSDemos/Demos/TabPanel/Templates/jQuery/index.html
  JSDemos/Demos/TabPanel/Templates/jQuery/index.js
  JSDemos/Demos/TabPanel/Templates/jQuery/styles.css
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/TabPanel/Templates.css
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/TabPanel/Templates.cshtml
  NetCoreDemos/Views/TabPanel/Templates.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TabPanel/Templates.css
  testing/etalons/TabPanel-Templates.png
Labels: 23_2

#2848 Form: update Validation demo description
  JSDemos/Demos/Form/Validation/description.md
Labels: 23_2

#2855 TabPanel: Update Overview demo
  JSDemos/Demos/TabPanel/Overview/Angular/app/app.component.css
  JSDemos/Demos/TabPanel/Overview/Angular/app/app.component.html
  JSDemos/Demos/TabPanel/Overview/Angular/app/app.component.ts
  JSDemos/Demos/TabPanel/Overview/Angular/app/app.service.ts
  JSDemos/Demos/TabPanel/Overview/React/App.js
  JSDemos/Demos/TabPanel/Overview/React/TaskItem.js
  JSDemos/Demos/TabPanel/Overview/React/data.js
  JSDemos/Demos/TabPanel/Overview/React/styles.css
  JSDemos/Demos/TabPanel/Overview/Vue/App.vue
  JSDemos/Demos/TabPanel/Overview/Vue/TaskItem.vue
  JSDemos/Demos/TabPanel/Overview/Vue/data.js
  JSDemos/Demos/TabPanel/Overview/jQuery/data.js
  JSDemos/Demos/TabPanel/Overview/jQuery/index.js
  JSDemos/Demos/TabPanel/Overview/jQuery/styles.css
  MVCDemos/Content/DemosStyles/TabPanel/Overview.css
  MVCDemos/Models/SampleData/TabpanelData.cs
  MVCDemos/Views/TabPanel/Overview.cshtml
  NetCoreDemos/Models/SampleData/TabPanelData.cs
  NetCoreDemos/Views/TabPanel/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/TabPanel/Overview.css
  testing/etalons/TabPanel-Overview.png
  testing/widgets/tabpanel/etalons/tabpanel_iconposition_start.png
  testing/widgets/tabpanel/etalons/tabpanel_shownavbuttons_false.png
  testing/widgets/tabpanel/etalons/tabpanel_stylingmode_primary.png
  testing/widgets/tabpanel/etalons/tabpanel_tabsposition_top.png
Labels: force all tests, 23_2

#2857 Scheduler: add React description to Custom Templates demo
  JSDemos/Demos/Scheduler/CustomTemplates/React/description.md
Labels: 23_2

#2856 Grid summary - column width fix
  JSDemos/Demos/DataGrid/CustomSummaries/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/CustomSummaries/AngularJS/index.js
  JSDemos/Demos/DataGrid/CustomSummaries/React/App.js
  JSDemos/Demos/DataGrid/CustomSummaries/Vue/App.vue
  JSDemos/Demos/DataGrid/CustomSummaries/jQuery/index.js
  JSDemos/Demos/DataGrid/GridSummaries/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/GridSummaries/AngularJS/index.js
  JSDemos/Demos/DataGrid/GridSummaries/React/App.js
  JSDemos/Demos/DataGrid/GridSummaries/Vue/App.vue
  JSDemos/Demos/DataGrid/GridSummaries/jQuery/index.js
  JSDemos/Demos/DataGrid/GroupSummaries/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/GroupSummaries/AngularJS/index.js
  JSDemos/Demos/DataGrid/GroupSummaries/React/App.js
  JSDemos/Demos/DataGrid/GroupSummaries/Vue/App.vue
  JSDemos/Demos/DataGrid/GroupSummaries/jQuery/index.js
  JSDemos/Demos/DataGrid/RecalculateWhileEditing/Angular/app/app.component.html
  JSDemos/Demos/DataGrid/RecalculateWhileEditing/AngularJS/index.js
  JSDemos/Demos/DataGrid/RecalculateWhileEditing/React/App.js
  JSDemos/Demos/DataGrid/RecalculateWhileEditing/Vue/App.vue
  JSDemos/Demos/DataGrid/RecalculateWhileEditing/jQuery/index.js
  MVCDemos/Views/DataGrid/CustomSummaries.cshtml
  MVCDemos/Views/DataGrid/GridSummaries.cshtml
  MVCDemos/Views/DataGrid/GroupSummaries.cshtml
  MVCDemos/Views/DataGrid/RecalculateWhileEditing.cshtml
  NetCoreDemos/Views/DataGrid/CustomSummaries.cshtml
  NetCoreDemos/Views/DataGrid/GridSummaries.cshtml
  NetCoreDemos/Views/DataGrid/GroupSummaries.cshtml
  NetCoreDemos/Views/DataGrid/RecalculateWhileEditing.cshtml
  testing/etalons/DataGrid-CustomSummaries.png
  testing/etalons/DataGrid-GridSummaries.png
  testing/etalons/DataGrid-GroupSummaries.png
  testing/etalons/DataGrid-RecalculateWhileEditing.png
  testing/widgets/datagrid/etalons/datagrid_group_summaries_2_desktop.png
Labels: 23_2

#2861 DataGrid Editing Form: add mention of Customize Edit Form topic
  JSDemos/Demos/DataGrid/FormEditing/description.md
Labels: 23_1

#2837 Tabs: new tabs demo added and 'Overview' moved to 'Selection'
  JSDemos/Demos/Tabs/Overview/Angular/app/app.component.css
  JSDemos/Demos/Tabs/Overview/Angular/app/app.component.html
  JSDemos/Demos/Tabs/Overview/Angular/app/app.component.ts
  JSDemos/Demos/Tabs/Overview/Angular/app/app.service.ts
  JSDemos/Demos/Tabs/Overview/AngularJS/index.js
  JSDemos/Demos/Tabs/Overview/React/App.js
  JSDemos/Demos/Tabs/Overview/React/data.js
  JSDemos/Demos/Tabs/Overview/React/styles.css
  JSDemos/Demos/Tabs/Overview/Vue/App.vue
  JSDemos/Demos/Tabs/Overview/Vue/data.js
  JSDemos/Demos/Tabs/Overview/jQuery/data.js
  JSDemos/Demos/Tabs/Overview/jQuery/index.html
  JSDemos/Demos/Tabs/Overview/jQuery/index.js
  JSDemos/Demos/Tabs/Overview/jQuery/styles.css
  JSDemos/Demos/Tabs/Selection/Angular/app/app.component.css
  JSDemos/Demos/Tabs/Selection/Angular/app/app.component.html
  JSDemos/Demos/Tabs/Selection/Angular/app/app.component.ts
  JSDemos/Demos/Tabs/Selection/Angular/app/app.service.ts
  JSDemos/Demos/Tabs/Selection/Angular/index.html
  JSDemos/Demos/Tabs/Selection/React/App.js
  JSDemos/Demos/Tabs/Selection/React/data.js
  JSDemos/Demos/Tabs/Selection/React/index.html
  JSDemos/Demos/Tabs/Selection/React/index.js
  JSDemos/Demos/Tabs/Selection/React/styles.css
  JSDemos/Demos/Tabs/Selection/Vue/App.vue
  JSDemos/Demos/Tabs/Selection/Vue/data.js
  JSDemos/Demos/Tabs/Selection/Vue/index.html
  JSDemos/Demos/Tabs/Selection/Vue/index.js
  JSDemos/Demos/Tabs/Selection/jQuery/data.js
  JSDemos/Demos/Tabs/Selection/jQuery/index.html
  JSDemos/Demos/Tabs/Selection/jQuery/index.js
  JSDemos/Demos/Tabs/Selection/jQuery/styles.css
  JSDemos/menuMeta.json
  MVCDemos/Content/DemosStyles/Tabs/Overview.css
  MVCDemos/Content/DemosStyles/Tabs/Selection.css
  MVCDemos/Controllers/TabsController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/Tabs/Overview.cshtml
  MVCDemos/Views/Tabs/Selection.cshtml
  NetCoreDemos/Controllers/TabsController.cs
  NetCoreDemos/Views/Tabs/Overview.cshtml
  NetCoreDemos/Views/Tabs/Selection.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Tabs/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/Tabs/Selection.css
  testing/etalons/Tabs-Overview.png
  testing/etalons/Tabs-Selection.png
  testing/widgets/tabs/Overview.test.js
  testing/widgets/tabs/etalons/tabs_iconposition_end.png
  testing/widgets/tabs/etalons/tabs_orientation_vertical.png
  testing/widgets/tabs/etalons/tabs_shownavbuttons_true.png
  testing/widgets/tabs/etalons/tabs_stylingmode_secondary.png
Labels: 23_2

#2866 Bump DevExtreme.AspNet.Data (nuget, npm) dep version to latest v3.0.0
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Web.config
  MVCDemos/packages.config
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  package-lock.json
  package.json
Labels: dependencies, 23_2

#2824 Form validation demo: editor width changed to adjust validation msg width
  JSDemos/Demos/Form/Validation/Angular/app/app.component.html
  JSDemos/Demos/Form/Validation/React/App.js
  JSDemos/Demos/Form/Validation/Vue/App.vue
  JSDemos/Demos/Form/Validation/jQuery/index.js
  MVCDemos/Views/Form/Validation.cshtml
  NetCoreDemos/Views/Form/Validation.cshtml
Labels: 23_2

#2852 Tabs: new selection demo added
  JSDemos/Demos/Tabs/Selection/Angular/app/app.component.css
  JSDemos/Demos/Tabs/Selection/Angular/app/app.component.html
  JSDemos/Demos/Tabs/Selection/Angular/app/app.component.ts
  JSDemos/Demos/Tabs/Selection/Angular/app/app.service.ts
  JSDemos/Demos/Tabs/Selection/React/App.js
  JSDemos/Demos/Tabs/Selection/React/data.js
  JSDemos/Demos/Tabs/Selection/React/styles.css
  JSDemos/Demos/Tabs/Selection/Vue/App.vue
  JSDemos/Demos/Tabs/Selection/Vue/data.js
  JSDemos/Demos/Tabs/Selection/jQuery/data.js
  JSDemos/Demos/Tabs/Selection/jQuery/index.html
  JSDemos/Demos/Tabs/Selection/jQuery/index.js
  JSDemos/Demos/Tabs/Selection/jQuery/styles.css
  MVCDemos/Content/DemosStyles/Tabs/Selection.css
  MVCDemos/Views/Tabs/Selection.cshtml
  NetCoreDemos/Views/Tabs/Selection.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Tabs/Selection.css
  testing/etalons/Tabs-Selection.png
  testing/widgets/tabs/Selection.test.js
  testing/widgets/tabs/etalons/tabs_second_item_selection.png
  testing/widgets/tabs/etalons/tabs_third_item_selection.png
Labels: 23_2

#2869 Fix error when SystemJs loads module with empty export
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.js
  JSDemos/configs/Vue/config.js
Labels: cherry-pick, 23_1

#2870 Form Validation Demo: update editors' settings to make `reset` button behavior more intuitive
  JSDemos/Demos/Form/Validation/Angular/app/app.component.html
  JSDemos/Demos/Form/Validation/Angular/app/app.component.ts
  JSDemos/Demos/Form/Validation/React/App.js
  JSDemos/Demos/Form/Validation/Vue/App.vue
  JSDemos/Demos/Form/Validation/jQuery/index.js
  MVCDemos/Views/Form/Validation.cshtml
  NetCoreDemos/Views/Form/Validation.cshtml
Labels: 23_2
