Repository DevExpress/devextreme-demos, pull requests merged in 2024-01, with the labels that each got.

#3097 Re-fix types in Vue demos (#3078)
  JSDemos/Demos/DataGrid/BatchUpdateRequest/Vue/App.vue
  JSDemos/Demos/DataGrid/CustomEditors/Vue/EmployeeDropDownBoxComponent.vue
  JSDemos/Demos/DataGrid/CustomEditors/Vue/EmployeeTagBoxComponent.vue
  JSDemos/Demos/DataGrid/DeferredSelection/Vue/App.vue
  JSDemos/Demos/DataGrid/FilterPanel/Vue/App.vue
  JSDemos/Demos/DataGrid/PDFExportMultipleGrids/Vue/App.vue
  JSDemos/Demos/TreeList/KeyboardNavigation/Vue/App.vue
Labels: cherry-pick

#3098 DropDownBox: update Single Selection description
  JSDemos/Demos/DropDownBox/SingleSelection/description.md
Labels: 23_2

#3099 DropDownBox: update Single Selection description (#3098)
  JSDemos/Demos/DropDownBox/SingleSelection/description.md
Labels: cherry-pick, 24_1

#3100 Remove App.js from React folder for site to work Grid - Remote virtual scrolling
  JSDemos/Demos/DataGrid/RemoteVirtualScrolling/React/App.js
Labels: cherry-pick, 24_1

#3104 Fix - Vue form updateItems dynamically
  JSDemos/Demos/Form/UpdateItemsDynamically/Vue/App.vue
Labels: cherry-pick, 23_2

#3105 Fix - Vue form updateItems dynamically (#3104)
  JSDemos/Demos/Form/UpdateItemsDynamically/Vue/App.vue
Labels: cherry-pick, 24_1

#3107 (fix) - Scheduler - Custom Templates codesandbox
  JSDemos/Demos/Scheduler/CustomTemplates/React/Appointment.tsx
  JSDemos/Demos/Scheduler/CustomTemplates/ReactJs/Appointment.js
Labels: 23_2

#3109 TabPanel: Fix ASP Template demos
  MVCDemos/Controllers/TabPanelController.cs
  MVCDemos/Models/SampleData/TabpanelData.cs
  MVCDemos/Views/TabPanel/Overview.cshtml
  NetCoreDemos/Controllers/TabPanelController.cs
  NetCoreDemos/Models/SampleData/TabPanelData.cs
  NetCoreDemos/Views/TabPanel/Overview.cshtml
Labels: cherry-pick, 23_2

#3110 TabPanel: Fix ASP Template demos
  MVCDemos/Controllers/TabPanelController.cs
  MVCDemos/Models/SampleData/TabpanelData.cs
  MVCDemos/Views/TabPanel/Overview.cshtml
  NetCoreDemos/Controllers/TabPanelController.cs
  NetCoreDemos/Models/SampleData/TabPanelData.cs
  NetCoreDemos/Views/TabPanel/Overview.cshtml
Labels: 24_1

#3112 TabPanel: Fix typo in ASP Templates demos
  MVCDemos/Views/TabPanel/Templates.cshtml
  NetCoreDemos/Views/TabPanel/Templates.cshtml
Labels: cherry-pick, 23_2

#3111 TabPanel: Fix typo in ASP Templates demos
  MVCDemos/Views/TabPanel/Templates.cshtml
  NetCoreDemos/Views/TabPanel/Templates.cshtml
Labels: 24_1

#3113 fix the Sortable > Customization demo
  JSDemos/Demos/Sortable/Customization/React/App.tsx
  JSDemos/Demos/Sortable/Customization/ReactJs/App.js
Labels: 23_2

#3114 fix the Sortable > Customization demo
  JSDemos/Demos/Sortable/Customization/React/App.tsx
  JSDemos/Demos/Sortable/Customization/ReactJs/App.js
Labels: 24_1

#3116 FileUploader: Add aria-label into the file uploader input
  JSDemos/Demos/FileUploader/FileSelection/Angular/app/app.component.html
  JSDemos/Demos/FileUploader/FileSelection/React/App.tsx
  JSDemos/Demos/FileUploader/FileSelection/ReactJs/App.js
  JSDemos/Demos/FileUploader/FileSelection/Vue/App.vue
  JSDemos/Demos/FileUploader/FileSelection/jQuery/index.js
  MVCDemos/Views/FileUploader/FileSelection.cshtml
  NetCoreDemos/Views/FileUploader/FileSelection.cshtml
Labels: 24_1

#3115 DataGrid - Toolbar Customization: Fix toolbar items being misaligned in a generic compact theme (T1207099)
  JSDemos/Demos/DataGrid/ToolbarCustomization/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/ToolbarCustomization/React/styles.css
  JSDemos/Demos/DataGrid/ToolbarCustomization/ReactJs/styles.css
  JSDemos/Demos/DataGrid/ToolbarCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/ToolbarCustomization/jQuery/styles.css
  MVCDemos/Content/DemosStyles/DataGrid/ToolbarCustomization.css
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/ToolbarCustomization.css
  testing/etalons/DataGrid-ToolbarCustomization.png
Labels: 24_1

#3117 Gallery: Add img alt into the data source
  JSDemos/Demos/Gallery/Overview/Angular/app/app.service.ts
  JSDemos/Demos/Gallery/Overview/React/data.ts
  JSDemos/Demos/Gallery/Overview/ReactJs/data.js
  JSDemos/Demos/Gallery/Overview/Vue/data.ts
  JSDemos/Demos/Gallery/Overview/jQuery/data.js
  MVCDemos/Controllers/GalleryController.cs
  MVCDemos/ViewModels/GalleryViewModel.cs
  NetCoreDemos/Controllers/GalleryController.cs
  NetCoreDemos/ViewModels/GalleryViewModel.cs
Labels: 24_1

#3118 DataGrid - Toolbar Customization: Fix toolbar items being misaligned in a generic compact theme (T1207099)
  JSDemos/Demos/DataGrid/ToolbarCustomization/Angular/app/app.component.css
  JSDemos/Demos/DataGrid/ToolbarCustomization/React/styles.css
  JSDemos/Demos/DataGrid/ToolbarCustomization/ReactJs/styles.css
  JSDemos/Demos/DataGrid/ToolbarCustomization/Vue/App.vue
  JSDemos/Demos/DataGrid/ToolbarCustomization/jQuery/styles.css
  MVCDemos/Content/DemosStyles/DataGrid/ToolbarCustomization.css
  NetCoreDemos/wwwroot/css/DemosStyles/DataGrid/ToolbarCustomization.css
  testing/etalons/DataGrid-ToolbarCustomization.png
Labels: cherry-pick, 23_2

#3119 Autocomplete: Add aria-label into disabled input
  JSDemos/Demos/Autocomplete/Overview/Angular/app/app.component.html
  JSDemos/Demos/Autocomplete/Overview/React/App.tsx
  JSDemos/Demos/Autocomplete/Overview/ReactJs/App.js
  JSDemos/Demos/Autocomplete/Overview/Vue/App.vue
  JSDemos/Demos/Autocomplete/Overview/jQuery/index.js
  MVCDemos/Views/Autocomplete/Overview.cshtml
  NetCoreDemos/Views/Autocomplete/Overview.cshtml
Labels: 24_1

#3120 Accessibility: Get rid of Autocomplete, Gallery and FileUploader demos from exceptions
  testing/common.test.js
Labels: force all tests, 24_1

#3122 NETCore.Demos - Explicit bump transitive package references / dependencies
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
Labels: dependencies, 23_2

#3123 NETCore.Demos - Explicit bump transitive package references / dependencies
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
Labels: cherry-pick, dependencies, 23_1

#3124 CI: restore DevExtreme.AspNet.Core from local folder, even if the version is not stable
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  gulpfile.js/copy-asp-files.js
Labels: 23_2

#3126 NETCore.Demos - Explicit bump transitive package references / dependencies
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
Labels: cherry-pick, dependencies, 24_1

#3127 CI: restore DevExtreme.AspNet.Core from local folder, even if the version is not stable
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  gulpfile.js/copy-asp-files.js
Labels: cherry-pick, 24_1
