Repository DevExpress/devextreme-demos, pull requests merged in 2024-03, with the labels that each got.

#3155 CI: Read path to menuMeta.json from repository.config
  gulpfile.js/copy-common-asp-files.js
  package-lock.json
  package.json
  utils/shared/config-helper.js
  utils/shared/create-repository-config.js
Labels: 24_1

#3157 Strips Demo : Update Strips Text (MVC & NetCore)
  MVCDemos/Views/Charts/Strips.cshtml
  NetCoreDemos/Views/Charts/Strips.cshtml
Labels: cherry-pick, 24_1

#3156 Diagram & FileManager : Rework With Public API (MVC & Netcore)
  MVCDemos/Views/Diagram/ItemSelection.cshtml
  MVCDemos/Views/Diagram/NodesAndEdgesArrays.cshtml
  MVCDemos/Views/FileManager/UICustomization.cshtml
  NetCoreDemos/Views/Diagram/ItemSelection.cshtml
  NetCoreDemos/Views/Diagram/NodesAndEdgesArrays.cshtml
  NetCoreDemos/Views/FileManager/UICustomization.cshtml
Labels: cherry-pick, 24_1

#3159 NETCore.Demos - Bump EntityFrameworkCore, remove explicit transitive package Microsoft.Data.SqlClient bump
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
Labels: cherry-pick, dependencies, 24_1

#3158 Fix Build aspnet demos workflow
  .github/workflows/build-aspnet.yml
  gulpfile.js/copy-common-asp-files.js
Labels: 24_1

#3160 form: Remove double T from CustomizeItem demo
  NetCoreDemos/Views/Form/CustomizeItem.cshtml
Labels: 24_1

#3161 form: Remove double T from CustomizeItem demo
  NetCoreDemos/Views/Form/CustomizeItem.cshtml
Labels: cherry-pick, 23_2

#3163 Styles: add CSS variables for use in demos and UI template gallery
  MVCDemos/Content/DemosStyles/Drawer/LeftOrRightPosition.css
  MVCDemos/Content/DemosStyles/Drawer/TopOrBottomPosition.css
  MVCDemos/Content/DemosStyles/FileUploader/ChunkUploading.css
  MVCDemos/Content/DemosStyles/FileUploader/CustomDropzone.css
  MVCDemos/Content/DemosStyles/HtmlEditor/Mentions.css
  MVCDemos/Content/DemosStyles/Scheduler/CustomDragAndDrop.css
  MVCDemos/Content/DemosStyles/Sortable/Customization.css
  MVCDemos/Content/DemosStyles/Sortable/Kanban.css
  MVCDemos/Content/DemosStyles/TabPanel/Overview.css
  MVCDemos/Content/DemosStyles/Tabs/Selection.css
  MVCDemos/Views/Drawer/LeftOrRightPosition.cshtml
  MVCDemos/Views/Drawer/TopOrBottomPosition.cshtml
  MVCDemos/Views/DropDownButton/Overview.cshtml
  MVCDemos/Views/FileUploader/ChunkUploading.cshtml
  MVCDemos/Views/FileUploader/CustomDropzone.cshtml
  MVCDemos/Views/HtmlEditor/Mentions.cshtml
  MVCDemos/Views/Scheduler/CustomDragAndDrop.cshtml
  MVCDemos/Views/Sortable/Customization.cshtml
  MVCDemos/Views/Sortable/_Kanban.cshtml
  MVCDemos/Views/TabPanel/Overview.cshtml
  NetCoreDemos/Views/Drawer/LeftOrRightPosition.cshtml
  NetCoreDemos/Views/Drawer/TopOrBottomPosition.cshtml
  NetCoreDemos/Views/DropDownButton/Overview.cshtml
  NetCoreDemos/Views/FileUploader/ChunkUploading.cshtml
  NetCoreDemos/Views/FileUploader/CustomDropzone.cshtml
  NetCoreDemos/Views/HtmlEditor/Mentions.cshtml
  NetCoreDemos/Views/Scheduler/CustomDragAndDrop.cshtml
  NetCoreDemos/Views/Sortable/Customization.cshtml
  NetCoreDemos/Views/Sortable/_Kanban.cshtml
  NetCoreDemos/Views/TabPanel/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Drawer/LeftOrRightPosition.css
  NetCoreDemos/wwwroot/css/DemosStyles/Drawer/TopOrBottomPosition.css
  NetCoreDemos/wwwroot/css/DemosStyles/FileUploader/ChunkUploading.css
  NetCoreDemos/wwwroot/css/DemosStyles/FileUploader/CustomDropzone.css
  NetCoreDemos/wwwroot/css/DemosStyles/HtmlEditor/Mentions.css
  NetCoreDemos/wwwroot/css/DemosStyles/Scheduler/CustomDragAndDrop.css
  NetCoreDemos/wwwroot/css/DemosStyles/Sortable/Customization.css
  NetCoreDemos/wwwroot/css/DemosStyles/Sortable/Kanban.css
  NetCoreDemos/wwwroot/css/DemosStyles/TabPanel/Overview.css
  NetCoreDemos/wwwroot/css/DemosStyles/Tabs/Selection.css
Labels: 24_1

#3146 Use Remote attr with AdditionalFields instead of custom async rule
  MVCDemos/Controllers/RemoteValidationController.cs
  MVCDemos/Models/DataGrid/EmployeeValidation.cs
  MVCDemos/Views/DataGrid/DataValidation.cshtml
  NetCoreDemos/Controllers/RemoteValidationController.cs
  NetCoreDemos/Models/DataGrid/EmployeeValidation.cs
  NetCoreDemos/Views/DataGrid/DataValidation.cshtml
Labels: 24_1

#3171 Drawer/TopOrBottomPosition: Fix drawer not taking full width in MVC demos
  MVCDemos/Views/Drawer/TopOrBottomPosition.cshtml
Labels: 24_1

#3172 Fix missing code tabs in ASP.NET MVC/Core demos
  JSDemos/menuMeta.json
Labels: 23_2

#3174 MVC Demos: Fix path to json data in code tabs of Diagram Overview demo
  JSDemos/menuMeta.json
Labels: 23_2

#3176 Scheduler - fix custom drag and drop - Object.asssign error
  JSDemos/Demos/Scheduler/CustomDragAndDrop/Angular/app/app.component.ts
Labels: 23_2

#3178 MVC Demos: Fix path to demo source files
  MVCDemos/DemoShell/DemoMenuMeta.cs
Labels: 24_1

#3177 FileUploader: Fix Custom Drop Zone Multiple Files and Incorrect File Extension Handling
  MVCDemos/Views/FileUploader/CustomDropzone.cshtml
  NetCoreDemos/Views/FileUploader/CustomDropzone.cshtml
Labels: 24_1

#3179 Vue DataGrid - Cascading Lookups fix
  JSDemos/Demos/DataGrid/CascadingLookups/Vue/App.vue
Labels: 23_2

#3181 Form/GroupFields: add caption template in both mvc and .net demos
  MVCDemos/Content/DemosStyles/Form/GroupedFields.css
  MVCDemos/Views/Form/GroupedFields.cshtml
  NetCoreDemos/Views/Form/GroupedFields.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Form/GroupedFields.css
Labels: 24_1

#3180 DropDownButton Demo: Set Button Template for DropDownButton
  MVCDemos/Content/DemosStyles/DropDownButton/Overview.css
  MVCDemos/Content/images/employees/51.png
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/DropDownButton/Overview.cshtml
  NetCoreDemos/Views/DropDownButton/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/DropDownButton/Overview.css
  NetCoreDemos/wwwroot/images/employees/51.png
Labels: 24_1
