Repository DevExpress/devextreme-demos, pull requests merged in 2024-05, with the labels that each got.

#3203 ContextMenu: Add scrolling demo for .Net MVC and Core
  MVCDemos/Content/DemosStyles/ContextMenu/Scrolling.css
  MVCDemos/Controllers/ContextMenuController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Models/ContextMenuScrollingItem.cs
  MVCDemos/Models/SampleData/ContextMenuData.cs
  MVCDemos/Views/ContextMenu/Scrolling.cshtml
  NetCoreDemos/Controllers/ContextMenuController.cs
  NetCoreDemos/Models/ContextMenuScrollingItem.cs
  NetCoreDemos/Models/SampleData/ContextMenuData.cs
  NetCoreDemos/Views/ContextMenu/Scrolling.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/ContextMenu/Scrolling.css
Labels: 24_1

#3208 Export Custom Markup: Rework prepareMarkup function for .NET Frameworks
  MVCDemos/Views/Charts/ExportCustomMarkup.cshtml
  NetCoreDemos/Views/Charts/ExportCustomMarkup.cshtml
Labels: 24_1

#3206 Splitter: update focusable element in MVC and .Net Demo
  MVCDemos/Content/DemosStyles/Splitter/Overview.css
  MVCDemos/Views/Splitter/Overview.cshtml
  NetCoreDemos/Views/Splitter/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Splitter/Overview.css
Labels: 24_1

#3207 ContextMenu: Update target area sizes for .NET Frameworks
  MVCDemos/Content/DemosStyles/ContextMenu/Scrolling.css
  NetCoreDemos/wwwroot/css/DemosStyles/ContextMenu/Scrolling.css
Labels: 24_1

#3209 Splitter: add collapsedSize option on Central Pane on MVC and .Net demos
  MVCDemos/Views/Splitter/Overview.cshtml
  NetCoreDemos/Views/Splitter/Overview.cshtml
Labels: 24_1

#3210 Arrange jQuery / Microsoft.AspNet.SignalR.JS nuget packages after #3198
  .gitignore
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Scripts/jquery.signalR-2.2.2.js
  MVCDemos/Scripts/jquery.signalR-2.2.2.min.js
  MVCDemos/Views/Charts/SignalRService.cshtml
  MVCDemos/Views/DataGrid/CollaborativeEditing.cshtml
  MVCDemos/Views/DataGrid/SignalRService.cshtml
  MVCDemos/Views/Scheduler/SignalRService.cshtml
  MVCDemos/packages.config
Labels: dependencies, 24_1

#3211 ContextMenu / Menu: Apply New Data set in Context Menu and Menu component in both MVC and .Net Demos
  MVCDemos/Models/SampleData/ContextMenuData.cs
  MVCDemos/Models/SampleData/MenuScrollingData.cs
  NetCoreDemos/Models/SampleData/ContextMenuData.cs
  NetCoreDemos/Models/SampleData/MenuScrollingData.cs
Labels: 24_1

#3212 BarGauge / Palette: Scale down data units
  MVCDemos/Views/Gauges/Palette.cshtml
  NetCoreDemos/Views/Gauges/Palette.cshtml
Labels: 24_1

#3213 TagBox: Add alt on image in custom template example
  MVCDemos/Views/TagBox/Overview.cshtml
  NetCoreDemos/Views/TagBox/Overview.cshtml
Labels: 24_1

#3215 Diagram: arrange "commands" props types (T1227506)
  JSDemos/Demos/Diagram/CustomShapesWithTemplatesWithEditing/React/App.tsx
  JSDemos/Demos/Diagram/CustomShapesWithTemplatesWithEditing/ReactJs/App.js
  JSDemos/Demos/Diagram/UICustomization/React/App.tsx
  JSDemos/Demos/Diagram/UICustomization/ReactJs/App.js
Labels: cherry-pick, 23_2

#3216 Context Menu / Menu: additional changes in data and typo's
  MVCDemos/Models/SampleData/ContextMenuData.cs
  MVCDemos/Models/SampleData/MenuScrollingData.cs
  MVCDemos/Views/ContextMenu/Scrolling.cshtml
  MVCDemos/Views/Menu/Scrolling.cshtml
  NetCoreDemos/Models/SampleData/ContextMenuData.cs
  NetCoreDemos/Models/SampleData/MenuScrollingData.cs
  NetCoreDemos/Views/ContextMenu/Scrolling.cshtml
  NetCoreDemos/Views/Menu/Scrolling.cshtml
Labels: 24_1
