Repository DevExpress/devextreme-demos, pull requests merged in 2024-06, with the labels that each got.

#3219 CI: Clone correct devextreme-aspnet branch in aspnet demo tests
  .github/workflows/build-aspnet.yml
Labels: 23_2

#3218 NETCore.Demos - Explicit bump transitive package references / dependencies
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
Labels: cherry-pick, dependencies, 23_2

#3220 Fix demo tests
  testing/etalons/FileManager-BindingToFileSystem.png
Labels: force all tests, 23_2
