Repository DevExpress/devextreme-demos, pull requests merged in 2024-02, with the labels that each got.

#3136 Replace moved /Common/Object_Structures/ links
  JSDemos/Demos/Charts/CustomLegendMarkers/description.md
  JSDemos/Demos/Scheduler/AllDayPanelMode/description.md
  JSDemos/Demos/Scheduler/RecurringAppointments/description.md
  JSDemos/Demos/Scheduler/SimpleArray/description.md
  JSDemos/Demos/Scheduler/TimeZonesSupport/description.md
Labels: 23_2

#3137 Replace moved /Common/Object_Structures/ links
  JSDemos/Demos/Charts/CustomLegendMarkers/description.md
  JSDemos/Demos/Scheduler/AllDayPanelMode/description.md
  JSDemos/Demos/Scheduler/RecurringAppointments/description.md
  JSDemos/Demos/Scheduler/SimpleArray/description.md
  JSDemos/Demos/Scheduler/TimeZonesSupport/description.md
Labels: cherry-pick, 24_1

#3140 NETCore.Demos - Bump EntityFrameworkCore, remove explicit transitive package Microsoft.Data.SqlClient bump
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
Labels: dependencies, 23_2

#3141 NETCore.Demos - Bump EntityFrameworkCore, remove explicit transitive package Microsoft.Data.SqlClient bump
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
Labels: cherry-pick, dependencies, 23_1

#3144 Fix ASP links in JS demo descriptions
  JSDemos/Demos/DataGrid/RemoteReordering/description.md
  JSDemos/Demos/DataGrid/SignalRService/description.md
  JSDemos/Demos/DataGrid/WebAPIService/description.md
  JSDemos/Demos/List/WebAPI/description.md
  JSDemos/Demos/Scheduler/SignalRService/description.md
  JSDemos/Demos/Scheduler/WebAPIService/description.md
  JSDemos/Demos/TreeList/LoadDataOnDemand/description.md
  JSDemos/Demos/TreeList/WebAPIService/description.md
Labels: 23_2

#3148 Toast Overview Demo - Unified Display Time For Vue & Angular
  JSDemos/Demos/Toast/Overview/Angular/app/app.component.html
  JSDemos/Demos/Toast/Overview/Vue/App.vue
Labels: cherry-pick, 23_1

#3147 Strips Demo : Updated Chart Title and Labels
  JSDemos/Demos/Charts/Strips/Angular/app/app.component.html
  JSDemos/Demos/Charts/Strips/React/App.tsx
  JSDemos/Demos/Charts/Strips/ReactJs/App.js
  JSDemos/Demos/Charts/Strips/Vue/App.vue
  JSDemos/Demos/Charts/Strips/jQuery/index.js
  MVCDemos/Views/Charts/Strips.cshtml
  NetCoreDemos/Views/Charts/Strips.cshtml
  testing/etalons/Charts-Strips.png
Labels: 23_2

#3149 Drawer: fix overlap, bottom, expand configurations in React
  testing/widgets/drawer/TopOrBottomPosition.test.js
  testing/widgets/drawer/etalons/drawer(overlap, bottom, expand).png
  testing/widgets/drawer/etalons/drawer_after_resize(overlap, bottom, expand).png
  testing/widgets/drawer/etalons/drawer_closed(overlap, bottom, expand).png
  testing/widgets/drawer/etalons/drawer_opened(overlap, bottom, expand).png
Labels: cherry-pick, force all tests, 23_2

#3150 Drawer: fix overlap, bottom, expand configurations in React
  testing/widgets/drawer/TopOrBottomPosition.test.js
  testing/widgets/drawer/etalons/drawer(overlap, bottom, expand).png
  testing/widgets/drawer/etalons/drawer_after_resize(overlap, bottom, expand).png
  testing/widgets/drawer/etalons/drawer_closed(overlap, bottom, expand).png
  testing/widgets/drawer/etalons/drawer_opened(overlap, bottom, expand).png
Labels: cherry-pick, force all tests, 23_1

#3154 CI: remove missing postinstall script
  package-lock.json
  package.json
Labels: 24_1
