Repository DevExpress/devextreme-demos, pull requests merged in 2024-04, with the labels that each got.

#3182 Splitter Demo: create Splitter demo
  MVCDemos/Content/DemosStyles/Splitter/Overview.css
  MVCDemos/Controllers/SplitterController.cs
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Views/Splitter/Overview.cshtml
  NetCoreDemos/Controllers/SplitterController.cs
  NetCoreDemos/Views/Splitter/Overview.cshtml
  NetCoreDemos/wwwroot/css/DemosStyles/Splitter/Overview.css
Labels: 24_1

#3185 MVC & NetCore add missing padding to iframe styles
  MVCDemos/Content/demo-template.css
  NetCoreDemos/wwwroot/css/demo-template.css
Labels: 23_2

#3187 HtmlEditor: use showdown package instead of devextreme-showdown (T1223917)
  JSDemos/Demos/HtmlEditor/OutputFormats/AngularJS/index.html
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/description.md
  JSDemos/Demos/HtmlEditor/OutputFormats/jQuery/index.html
  JSDemos/configs/Angular/config.js
  JSDemos/configs/React/config.js
  JSDemos/configs/ReactJs/config.js
  JSDemos/configs/Vue/config.js
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
Labels: 23_2

#3189 HtmlEditor: use showdown package instead of devextreme-showdown (T1223917)
  MVCDemos/Views/HtmlEditor/OutputFormats.cshtml
  NetCoreDemos/Views/HtmlEditor/OutputFormats.cshtml
Labels: 24_1

#3193 Angular - Accordion - fix demo in WG
  JSDemos/Demos/Accordion/Overview/Angular/app/app.component.ts
Labels: 23_2

#3195 ASP.NET Core DataGrid: update Validation demo description
  MVCDemos/Content/Descr/DataGrid/DataValidation.md
Labels: 24_1

#3198 Bump DevExtreme.AspNet.Data (nuget, npm) dep version to v4.0.0-beta.2
  MVCDemos/DevExtreme.MVC.Demos.csproj
  MVCDemos/Web.config
  MVCDemos/packages.config
  NetCoreDemos/DevExtreme.NETCore.Demos.csproj
  package-lock.json
  package.json
Labels: dependencies, 24_1

#3200 Scheduler(T1225772): update demos etalon
  testing/etalons/Scheduler-CustomTemplates.png
Labels: cherry-pick, 23_2

#3201 Scheduler(T1225772): update demos etalon
  testing/etalons/Scheduler-CustomTemplates.png
Labels: cherry-pick, 23_1

#3204 Menu scrolling: get rid of flex-shrink: 0 for options
  MVCDemos/Content/DemosStyles/Menu/Scrolling.css
  NetCoreDemos/wwwroot/css/DemosStyles/Menu/Scrolling.css
Labels: 24_1
